Repository CMSgov/design-system, pull requests merged in 2019-04, with the labels that each got.

#406 Use variable for button border width
  packages/core/src/components/Button/Button.scss
  packages/support/src/settings/_variables.forms.scss
Labels: Engineering

#403 Minor text updates to README
  README.md
Labels: Documentation, Ready for review

#405 Pattern lifecycle documentation updates
  .github/ISSUE_TEMPLATE/propose-a-new-item-for-the-cms-design-system.md
  .github/images/CMS-Design-System-component-decision-workflow.jpg
  .github/images/pattern-decision-tree.png
  .github/images/user-maker-spectrum.png
  guides/PATTERN-LIFECYCLE.md
  packages/docs/src/pages/guidelines/component-maturity.md
  packages/docs/src/scripts/components/PageHeader.jsx
Labels: Documentation

#389 Update WRITING-DOCUMENTATION.md
  guides/WRITING-DOCUMENTATION.md
Labels: Documentation, Ready for review

#308 End-to-end test suite with accessibility scans
  .prettierignore
  .travis.yml
  package.json
  packages/core/src/__tests__/smoke.e2e.test.js
  packages/core/src/components/Alert/Alert.e2e.test.js
  packages/core/src/components/Autocomplete/Autocomplete.e2e.test.js
  packages/core/src/components/Badge/Badge.e2e.test.js
  packages/core/src/components/Button/Button.e2e.test.js
  packages/core/src/components/ChoiceList/Choice.e2e.test.js
  packages/core/src/components/ChoiceList/Select.e2e.test.js
  packages/core/src/components/ChoiceList/Select.example.jsx
  packages/core/src/components/DateField/DateField.e2e.test.js
  packages/core/src/components/Dialog/Dialog.e2e.test.js
  packages/core/src/components/FormLabel/FormLabel.e2e.test.js
  packages/core/src/components/HelpDrawer/HelpDrawer.e2e.test.js
  packages/core/src/components/List/List.e2e.test.js
  packages/core/src/components/MonthPicker/MonthPicker.e2e.test.js
  packages/core/src/components/Spinner/Spinner.e2e.test.js
  packages/core/src/components/Table/Table.e2e.test.js
  packages/core/src/components/Tabs/Tabs.e2e.test.js
  packages/core/src/components/TextField/MaskedField.e2e.test.js
  packages/core/src/components/TextField/TextField.e2e.test.js
  packages/core/src/components/VerticalNav/VerticalNav.e2e.test.js
  packages/core/src/helpers/e2e/assertNoAxeViolations.js
  packages/core/src/helpers/e2e/constants.js
  packages/core/src/helpers/e2e/index.js
  scripts/jest.sh
  tools/jest/e2e.config.js
  tools/jest/e2e.environment.js
  tools/jest/e2e.global-setup.js
  tools/jest/e2e.global-teardown.js
  tools/jest/e2e.polyfills.js
  tools/jest/unit.config.js
  yarn.lock
Labels: Accessibility, Engineering, Ready for review, Testing

#411 [WNMGDS-50] - Fix formatting of docs page heading links
  packages/docs/src/scripts/components/PageHeader.jsx
Labels: Ready for review

#412 Updating PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation, Ready for review
