Repository CMSgov/design-system, pull requests merged in 2019-11, with the labels that each got.

#536 [WNMGDS-260] Consolidate code examples
  packages/core/src/components/Alert/Alert.example.jsx
  packages/core/src/components/Alert/_Alert.docs.scss
  packages/core/src/components/Alert/alert.example-additional.html
  packages/core/src/components/Alert/alert.example.html
  packages/core/src/components/Badge/Badge.e2e.test.js
  packages/core/src/components/Badge/_Badge.docs.scss
  packages/core/src/components/Badge/badge.example.html
  packages/core/src/components/Button/Button.e2e.test.js
  packages/core/src/components/Button/Button.scss
  packages/core/src/components/Button/_Button.docs.scss
  packages/core/src/components/Button/button-inverse.example.html
  packages/core/src/components/Button/button.example.html
  packages/core/src/components/ChoiceList/Choice.e2e.test.js
  packages/core/src/components/ChoiceList/_ChoiceList.docs.scss
  packages/core/src/components/ChoiceList/checkbox-radio-inverse.example.html
  packages/core/src/components/ChoiceList/checkbox-radio-size.example.html
  packages/core/src/components/ChoiceList/checkbox-radio.example.html
  packages/core/src/components/Dropdown/Dropdown.example.html
  packages/core/src/components/List/_List.docs.scss
  packages/core/src/components/List/list.example.html
  packages/core/src/components/TextField/TextField.example.jsx
  packages/core/src/components/TextField/_TextField.docs.scss
  packages/core/src/components/TextField/textfield-inverse.example.html
  packages/core/src/components/TextField/textfield.example.html
  packages/docs/src/styles/example.scss
Labels: Component, Documentation Content

#539 [WNMGDS-293] Adjust prettier config
  .prettierrc
  packages/core/src/components/Alert/Alert.example.jsx
  packages/core/src/components/Alert/alert.example.html
  packages/core/src/components/Badge/badge.example.html
  packages/core/src/components/Button/button.example.html
  packages/core/src/components/ChoiceList/checkbox-radio-right-to-left.example.html
  packages/core/src/components/ChoiceList/checkbox-radio-size.example.html
  packages/core/src/components/ChoiceList/checkbox-radio.example.html
  packages/core/src/components/ChoiceList/select.example.html
  packages/core/src/components/DateField/DateField.example.html
  packages/core/src/components/DateField/datefield.example.html
  packages/core/src/components/Dropdown/dropdown.example.html
  packages/core/src/components/FormLabel/form-label.example.html
  packages/core/src/components/HelpDrawer/help-drawer.example.html
  packages/core/src/components/Review/review.example.html
  packages/core/src/components/Spinner/spinner.example.html
  packages/core/src/components/StepList/steplist.example.html
  packages/core/src/components/Tabs/tabs.example.html
  packages/core/src/components/TextField/TextField.example.jsx
  packages/core/src/components/TextField/textfield.example.html
  packages/docs/src/pages/patterns/documentation-page.example.html
Labels: Ready for review

#540 Add concise modal example with javascript
  packages/core/src/components/Dialog/_Dialog.docs.scss
  packages/core/src/components/Dialog/dialog-size.example.html
  packages/core/src/components/Dialog/dialog.example.html
  packages/docs/src/scripts/example.js
Labels: Documentation Content, Ready for review

#538 [WNMGDS-285] Remove select page and right to left choice sections from doc site
  packages/core/src/components/Autocomplete/_Autocomplete.docs.scss
  packages/core/src/components/ChoiceList/Select.e2e.test.js
  packages/core/src/components/ChoiceList/Select.example.jsx
  packages/core/src/components/ChoiceList/_ChoiceList.docs.scss
  packages/core/src/components/ChoiceList/_Select.docs.scss
  packages/core/src/components/ChoiceList/select.example.html
  packages/core/src/components/TextField/_TextField.docs.scss
  packages/core/src/components/_index.scss
  packages/docs/src/pages/guidelines/forms.md
Labels: Documentation Content, Ready for review

#545 [WNMGDS-299] Update datefield component to use inputRef
  packages/core/src/components/DateField/DateField.jsx
Labels: Ready for review

#547 [WNMGDS-290] - Update disabled styling for buttons
  packages/core/src/components/Button/Button.scss
  packages/core/src/components/Button/_Button.docs.scss
  packages/core/src/components/Button/button.example.html
Labels: Ready for review

#548 [WNMGDS-297] Prevent accessing null refs on DateField
  packages/core/src/components/DateField/DateField.jsx
Labels: Bug, Component

#537 [WNMGDS-275] - Add links to the CMSDS
  packages/core/src/base/body.scss
  packages/core/src/base/index.scss
  packages/core/src/base/typography.scss
  packages/core/src/base/typography/_typography.docs.scss
  packages/core/src/base/typography/link.example.html
  packages/core/src/base/typography/link.scss
  packages/core/src/base/typography/typography.example.html
  packages/core/src/base/typography/typography.scss
  packages/core/src/components/Button/Button.scss
  packages/core/src/components/Tabs/Tabs.scss
  packages/core/src/components/VerticalNav/VerticalNav.scss
Labels: Component, Ready for review

#535 [WNMGDS-264] - Add pattern for third party external links
  packages/core/src/components/Dialog/ThirdPartyLink.example.jsx
  packages/core/src/components/Dialog/_ThirdPartyLink.docs.scss
Labels: Pattern, Ready for review

#550 [WNMGDS-92] Add react badge component
  packages/core/src/components/Badge/Badge.example.jsx
  packages/core/src/components/Badge/Badge.jsx
  packages/core/src/components/Badge/_Badge.docs.scss
  packages/core/src/components/Badge/badge.example.html
  packages/core/src/components/Button/Button.jsx
Labels: Component, Documentation Content

#551 [WNMGDS-282] Add editAriaLabel to Review
  packages/core/src/components/Review/Review.example.jsx
  packages/core/src/components/Review/Review.jsx
  packages/core/src/components/Review/ReviewLink.jsx
Labels: Accessibility, Bug

#549 [WNMGDS-278] Add default date formatter
  packages/core/src/components/DateField/DateField.example.jsx
  packages/core/src/components/DateField/DateField.jsx
  packages/core/src/components/TextField/Mask.example.jsx
Labels: Component
