Repository CMSgov/design-system, pull requests merged in 2019-07, with the labels that each got.

#445 [WNMGWINSHOP-196] Fix broken autocomplete in stateful tree
  packages/core/src/components/Autocomplete/Autocomplete.jsx
  packages/core/src/components/Autocomplete/WrapperDiv.jsx
  packages/core/src/components/__tests__/index.test.js
Labels: Bug, Priority-major, Ready for review

#444 [WNMGDS-210] Fix Inversed FormLabel
  packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
  packages/core/src/components/FormLabel/FormLabel.jsx
  packages/core/src/components/FormLabel/FormLabel.scss
  packages/core/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
Labels: Bug, Ready for review

#448 [MCT1802] - Update aria text on autocomplete to match visual
  packages/core/src/components/Autocomplete/Autocomplete.jsx
  packages/core/src/components/Autocomplete/Autocomplete.test.jsx
  packages/core/src/components/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
Labels: Accessibility, Ready for review

#435 [WNMGDS-62] Return original value in Mask component when unable to mask
  packages/core/src/components/TextField/Mask.example.jsx
  packages/core/src/components/TextField/Mask.jsx
  packages/core/src/components/TextField/Mask.test.jsx
  packages/core/src/components/TextField/TextField.jsx
Labels: Bug, Ready for review

#442 [WNMGDS-200] Add the “official government website” banner to docs site
  packages/docs/src/images/icon-dot-gov.svg
  packages/docs/src/images/icon-https.svg
  packages/docs/src/images/us_flag_small.png
  packages/docs/src/scripts/components/Header.jsx
  packages/docs/src/styles/components/_UsaBanner.scss
  packages/docs/src/styles/docs.scss
Labels: Design, Ready for review

#440 [WNMGDS-159] Move site package guide page into docs site
  README.md
  guides/WRITING-DOCUMENTATION.md
  packages/docs/src/pages/guidelines/themes.md
  packages/docs/src/pages/startup/site-package.md
Labels: Documentation-content, Ready for review

#447 [MCT-1695] Add aria and id to alert
  packages/core/src/components/Alert/Alert.jsx
  packages/core/src/components/Alert/Alert.test.jsx
Labels: Ready for review

#452 [WNMGDS-220] - Add browser support page and update getting started section
  packages/core/src/__tests__/smoke.e2e.test.js
  packages/docs/src/pages/index.md
  packages/docs/src/pages/startup/browser-support.md
  packages/docs/src/pages/startup/examples.md
  packages/docs/src/pages/startup/fonts-and-images.md
  packages/docs/src/pages/startup/installation.md
  packages/docs/src/pages/startup/react.md
  packages/docs/src/pages/startup/sass-and-css.md
  packages/docs/src/pages/startup/site-package.md
  tools/gulp/docs/index.js
Labels: Documentation-content, Ready for review

#454 [WNMGDS-71] - Update table to be consistent with USWDS standards
  packages/core/src/components/Table/Table.scss
Labels: Component, Design, Ready for review

#457 [WNMGDS-193] - Combine pattern lifecycle and contributing doc
  CONTRIBUTING.md
  guides/PATTERN-LIFECYCLE.md
Labels: Documentation-content, Ready for review

#458 [WNMGDS-110] - upgrade Lodash to 4.17.14 (latest)
  package.json
  yarn.lock
Labels: Ready for review, dependencies

#469 [WNMGWINSHOP-226] Can have alternative linkText for steps in StepList
  packages/core/src/components/StepList/Step.jsx
  packages/core/src/components/StepList/Step.test.jsx
  packages/core/src/components/StepList/StepList.jsx
  packages/core/src/components/StepList/StepList.scss
  packages/core/src/components/StepList/SubStep.jsx
Labels: Engineering
