Repository CMSgov/design-system, pull requests merged in 2019-05, with the labels that each got.

#417 Update release process documentation
  guides/RELEASE-PROCESS.md
Labels: Documentation/content

#419 Update links in GitHub
  CONTRIBUTING.md
  README.md
Labels: Ready for review

#407 [WNMGDS-66] Updating Autocomplete to use Downshift v3.
  packages/core/package.json
  packages/core/src/components/Autocomplete/Autocomplete.e2e.test.js
  packages/core/src/components/Autocomplete/Autocomplete.example.jsx
  packages/core/src/components/Autocomplete/Autocomplete.jsx
  packages/core/src/components/Autocomplete/Autocomplete.scss
  packages/core/src/components/Autocomplete/Autocomplete.test.jsx
  packages/core/src/components/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
  packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
  packages/core/src/components/TextField/TextField.jsx
  packages/core/src/components/TextField/__snapshots__/TextField.test.jsx.snap
  packages/core/src/helpers/e2e/index.js
  packages/core/yarn.lock
  tools/jest/e2e.environment.js
Labels: Component, Ready for review

#422 [WNMGDS-81] Updating measure variables to use ex instead of em.
  packages/core/src/utilities/index.scss
  packages/core/src/utilities/measure/measure.example.html
  packages/core/src/utilities/measure/measure.scss
  packages/support/src/settings/_variables.type.scss
Labels: Ready for review
