Repository CMSgov/design-system, pull requests merged in 2019-12, with the labels that each got.

#572 [WNMGDS-326] Fix react button styling
  packages/core/src/components/Badge/Badge.example.jsx
  packages/core/src/components/Button/Button.example.jsx
  packages/core/src/components/Button/Button.jsx
  packages/core/src/components/Button/Button.scss
  packages/core/src/components/Button/Button.test.jsx
Labels: Bug

#576 [WNMGDS-322] - Remove survey alert from homepage
  packages/docs/src/pages/index.md
Labels: Ready for review

#575 [NO TICKET] Update github link to use uploaded zip
  guides/RELEASE-PROCESS.md
  packages/docs/src/pages/index.md
  packages/docs/src/pages/startup/installation.md
  packages/docs/src/scripts/components/GitHubLinks.jsx
Labels: Build Process, Documentation Content

#577 [WNMGDS-309] Create flex utilities
  packages/core/src/utilities/flexbox/_flexbox.docs.scss
  packages/core/src/utilities/flexbox/align-items.example.html
  packages/core/src/utilities/flexbox/flex-direction.example.html
  packages/core/src/utilities/flexbox/flex-wrap.example.html
  packages/core/src/utilities/flexbox/flexbox-responsive.example.html
  packages/core/src/utilities/flexbox/flexbox.scss
  packages/core/src/utilities/flexbox/justify-content.example.html
Labels: Ready for review

#581 [WNMGDS-366] Remove animation on Tab
  packages/core/src/components/Tabs/Tabs.scss
Labels: Easy Review, Ready For Review

#580 [WNMGDS-89] Use size prop
  packages/core/src/components/ChoiceList/ChoiceList.jsx
Labels: Easy Review, Ready For Review

#566 [WNMGDS-318] - Updates to layout for style/color, utilities/color and utilities/background color pages
  packages/core/src/base/body.scss
  packages/core/src/utilities/_index.scss
  packages/core/src/utilities/background-color/_background-color.docs.scss
  packages/core/src/utilities/background-color/background-color.example.html
  packages/core/src/utilities/background-color/background-color.scss
  packages/core/src/utilities/color/_color.docs.scss
  packages/core/src/utilities/text-color/_text-color.docs.scss
  packages/core/src/utilities/text-color/text-color.example.html
  packages/core/src/utilities/text-color/text-color.scss
  packages/docs/src/styles/components/_swatch.scss
  packages/support/src/settings/_variables.color.docs.scss
  packages/support/src/settings/_variables.color.scss
Labels: Ready For Review

#582 [WNMGDS-341] Misc Button fixes
  packages/core/src/base/body.scss
  packages/core/src/base/typography/link.scss
  packages/core/src/components/Button/Button.jsx
  packages/core/src/components/Button/Button.scss
  packages/core/src/components/Button/Button.test.jsx
  packages/core/src/components/Button/button.example.html
  packages/docs/src/scripts/components/GitHubLinks.jsx
Labels: Ready For Review

#583 [NO TICKET] Run prettier
  examples/article/index.html
  examples/form/index.html
  examples/react-app/README.md
  examples/react-app/index.html
  examples/react-app/src/scripts/index.js
  examples/responsive/index.html
  examples/webpack-demo/README.md
  examples/webpack-demo/src/pages/index.html
  examples/webpack-demo/src/pages/page-2.html
  tools/gulp/common/log-util.js
  tools/gulp/common/packageVersions.js
  tools/gulp/docs/__tests__/createRoutes.test.js
  tools/gulp/docs/__tests__/generateHtmlExample.test.js
  tools/gulp/docs/__tests__/nestSections.test.js
  tools/gulp/docs/__tests__/processMarkdownPage.test.js
  tools/gulp/docs/__tests__/reactPathFromSource.test.js
  tools/gulp/docs/addReactDocProps.js
  tools/gulp/docs/convertMarkdownPages.js
  tools/gulp/docs/createRoutes.js
  tools/gulp/docs/generateReactExample.js
  tools/gulp/docs/index.js
  tools/gulp/docs/markdownRenderer.js
  tools/gulp/docs/nestSections.js
  tools/gulp/docs/parseReactFile.js
  tools/gulp/docs/processKssSection.js
  tools/gulp/docs/uniquePages.js
  tools/gulp/index.js
  tools/gulp/sass/index.js
  tools/gulp/sass/themeImporter.js
  tools/gulp/stats/__tests__/getValues.test.js
  tools/gulp/stats/getValues.js
  tools/gulp/stats/stats.js
  tools/gulp/watch.js
  tools/jest/e2e.config.js
  tools/jest/e2e.global-setup.js
  tools/jest/unit.config.js
Labels: Easy Review, Ready For Review
