Repository CMSgov/design-system, pull requests merged in 2019-09, with the labels that each got.

#480 Update lodash to fix security issue
  package.json
  yarn.lock
Labels: Ready for review

#491 [NO-TICKET] Fix issue in <Dropdown/> where <option/>s do not have `value` attributes.
  packages/core/dist/components/Dropdown/Dropdown.js
  packages/core/src/components/Dropdown/Dropdown.jsx
  packages/core/src/components/Dropdown/__snapshots__/Dropdown.test.jsx.snap
Labels: Ready for review

#490 [WNMGDS-234] Fix error message visibility
  packages/core/src/components/DateField/DateField.example.html
  packages/core/src/components/DateField/DateField.scss
  packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
  packages/core/src/components/FormLabel/FormLabel.example.html
  packages/core/src/components/FormLabel/FormLabel.jsx
  packages/core/src/components/FormLabel/FormLabel.scss
  packages/core/src/components/TextField/TextField.scss
Labels: Accessibility, Component

#494 [WNMGDS-112] Deprecate Right-to-Left and <Select>
  packages/core/src/components/ChoiceList/Choice.scss
  packages/core/src/components/ChoiceList/Select.scss
Labels: Ready for review

#495 [WNMGDS-239] Separate out inline styles
  packages/core/src/components/Alert/Alert.scss
  packages/core/src/components/Alert/_Alert.docs.scss
  packages/core/src/components/Autocomplete/Autocomplete.scss
  packages/core/src/components/Autocomplete/_Autocomplete.docs.scss
  packages/core/src/components/Badge/Badge.scss
  packages/core/src/components/Badge/_Badge.docs.scss
  packages/core/src/components/Button/Button.scss
  packages/core/src/components/Button/_Button.docs.scss
  packages/core/src/components/ChoiceList/Choice.scss
  packages/core/src/components/ChoiceList/Select.scss
  packages/core/src/components/ChoiceList/_Choice.docs.scss
  packages/core/src/components/ChoiceList/_Select.docs.scss
  packages/core/src/components/DateField/DateField.scss
  packages/core/src/components/DateField/_DateField.docs.scss
  packages/core/src/components/Dialog/Dialog.scss
  packages/core/src/components/Dialog/_Dialog.docs.scss
  packages/core/src/components/Dropdown/Dropdown.scss
  packages/core/src/components/Dropdown/_Dropdown.docs.scss
  packages/core/src/components/FormLabel/FormLabel.scss
  packages/core/src/components/FormLabel/_FormLabel.docs.scss
  packages/core/src/components/HelpDrawer/HelpDrawer.scss
  packages/core/src/components/HelpDrawer/_HelpDrawer.docs.scss
  packages/core/src/components/List/List.scss
  packages/core/src/components/List/_List.docs.scss
  packages/core/src/components/MonthPicker/MonthPicker.scss
  packages/core/src/components/MonthPicker/_MonthPicker.docs.scss
  packages/core/src/components/Review/_Review.docs.scss
  packages/core/src/components/SkipNav/SkipNav.scss
  packages/core/src/components/SkipNav/_SkipNav.docs.scss
  packages/core/src/components/Spinner/Spinner.scss
  packages/core/src/components/Spinner/_Spinner.docs.scss
  packages/core/src/components/StepList/StepList.scss
  packages/core/src/components/StepList/_StepList.docs.scss
  packages/core/src/components/Table/Table.scss
  packages/core/src/components/Table/_Table.docs.scss
  packages/core/src/components/Table/table-complex.example.html
  packages/core/src/components/Tabs/Tabs.scss
  packages/core/src/components/Tabs/_Tabs.docs.scss
  packages/core/src/components/TextField/Mask.e2e.test.js
  packages/core/src/components/TextField/Mask.jsx
  packages/core/src/components/TextField/Mask.scss
  packages/core/src/components/TextField/TextField.scss
  packages/core/src/components/TextField/_Mask.docs.scss
  packages/core/src/components/TextField/_TextField.docs.scss
  packages/core/src/components/VerticalNav/VerticalNav.scss
  packages/core/src/components/VerticalNav/_VerticalNav.docs.scss
  packages/core/src/components/_index.scss
Labels: Engineering, Ready for review
