Repository CMSgov/design-system, pull requests merged in 2019-08, with the labels that each got.

#460 [WNMGDS-203] - Update and document yeoman component generator
  package.json
  packages/generator-cmsgov/README.md
  packages/generator-cmsgov/generators/app/index.js
  packages/generator-cmsgov/generators/app/templates/index.example.html
  packages/generator-cmsgov/generators/app/templates/index.scss
  yarn.lock
Labels: Documentation-content, Engineering, Ready for review

#434 [WNMGDS-111] Create dropdown component
  packages/core/src/components/ChoiceList/Choice.example.jsx
  packages/core/src/components/Dropdown/Dropdown.e2e.test.js
  packages/core/src/components/Dropdown/Dropdown.example.html
  packages/core/src/components/Dropdown/Dropdown.example.jsx
  packages/core/src/components/Dropdown/Dropdown.jsx
  packages/core/src/components/Dropdown/Dropdown.scss
  packages/core/src/components/Dropdown/Dropdown.test.jsx
  packages/core/src/components/Dropdown/__snapshots__/Dropdown.test.jsx.snap
  packages/core/src/components/index.js
Labels: Component, Documentation-content, Ready for review

#437 [WNMGDS-154] Audit and upgrade dependencies
  package.json
  packages/core/src/components/Dialog/Dialog.scss
  packages/core/src/components/StepList/SubStep.jsx
  packages/generator-cmsgov/generators/app/index.js
  yarn.lock
Labels: Ready for review, dependencies

#485 Fix typo in left nav
  packages/core/src/utilities/font-family.scss
Labels: Ready for review
