Repository CMSgov/design-system, pull requests merged in 2019-10, with the labels that each got.

#497 [WNMGDS-244][WNMGWINSHOP-277] Fill for default buttons
  packages/core/src/components/Button/Button.scss
Labels: Component

#496 [WNMGDS-222] Add onComponentBlur to <ChoiceList>
  packages/core/src/components/ChoiceList/Choice.jsx
  packages/core/src/components/ChoiceList/ChoiceList.jsx
  packages/core/src/components/ChoiceList/ChoiceList.test.jsx
Labels: Component, Ready for review

#493 [WNMGD-219] Upgrade axe webdriverjs
  package.json
  packages/core/src/components/Dialog/Dialog.e2e.test.js
  packages/core/src/helpers/e2e/assertNoAxeViolations.js
  yarn.lock
Labels: Accessibility

#498 [WNMGDS-174] Define pattern template and add to docs
  guides/WRITING-DOCUMENTATION.md
  packages/core/src/utilities/_index.scss
  packages/core/src/utilities/index.scss
  packages/docs/src/pages/patterns/overview.md
  packages/docs/src/pages/utilities/overview.md
  tools/gulp/docs/createRoutes.js
  tools/gulp/docs/index.js
  tools/gulp/docs/processKssSection.js
  tools/gulp/docs/processMarkdownPage.js
Labels: Documentation-content, Ready for review

#504 [WNMGDS-259] Use responsive gui
  backstop.json
  packages/core/src/base/typography.scss
  packages/core/src/components/StepList/_StepList.docs.scss
  packages/core/src/utilities/display-visibility.scss
  packages/core/src/utilities/flexbox.scss
  packages/core/src/utilities/float.scss
  packages/core/src/utilities/font-size.scss
  packages/core/src/utilities/margin.scss
  packages/core/src/utilities/padding.scss
  packages/docs/src/images/responsive-demo.gif
  packages/docs/src/pages/guidelines/responsive.md
Labels: Documentation-content, Ready for review

#508 [WNMGDS-245 WNMGDS-249] Add deprecated warnings and remove select example from <ChoiceList>
  packages/core/src/components/ChoiceList/Choice.jsx
  packages/core/src/components/ChoiceList/ChoiceList.example.jsx
  packages/core/src/components/ChoiceList/ChoiceList.jsx
  packages/core/src/components/ChoiceList/Select.jsx
Labels: Documentation-content

#506 [WNMGDS-109] - Remove guidance tab and add guidance anchor link
  packages/core/src/base/typography.scss
  packages/core/src/components/Alert/_Alert.docs.scss
  packages/core/src/components/Autocomplete/_Autocomplete.docs.scss
  packages/core/src/components/Badge/_Badge.docs.scss
  packages/core/src/components/Button/Button.scss
  packages/core/src/components/Button/_Button.docs.scss
  packages/core/src/components/ChoiceList/_Choice.docs.scss
  packages/core/src/components/ChoiceList/_Select.docs.scss
  packages/core/src/components/DateField/_DateField.docs.scss
  packages/core/src/components/Dialog/_Dialog.docs.scss
  packages/core/src/components/Dropdown/_Dropdown.docs.scss
  packages/core/src/components/FormLabel/_FormLabel.docs.scss
  packages/core/src/components/List/_List.docs.scss
  packages/core/src/components/Spinner/_Spinner.docs.scss
  packages/core/src/components/Table/_Table.docs.scss
  packages/core/src/components/Tabs/_Tabs.docs.scss
  packages/core/src/components/TextField/_TextField.docs.scss
  packages/core/src/components/VerticalNav/_VerticalNav.docs.scss
  packages/core/src/utilities/border-radius.scss
  packages/core/src/utilities/border.scss
  packages/core/src/utilities/font-family.scss
  packages/docs/src/pages/patterns/documentation-page.md
  packages/docs/src/scripts/components/Page.jsx
  packages/docs/src/scripts/components/PageHeader.jsx
  packages/docs/src/scripts/components/__tests__/Page.test.js
  packages/layout/src/index.scss
Labels: Accessibility, Documentation-content, Ready for review

#513 [WNMGDS-269] Make children not required in <Alert>
  packages/core/src/components/Alert/Alert.example.jsx
  packages/core/src/components/Alert/Alert.jsx
Labels: Component, Ready for review

#509 [WNMGDS-257] Copy theme fonts during build
  tools/gulp/docs/index.js
  tools/gulp/index.js
Labels: Engineering

#516 [WNMGDS-177] Add P tag to React alert component
  packages/core/src/components/Alert/Alert.example.jsx
Labels: Ready for review

#515 [WNMGDS-250] Remove max and min from TextField prop documentation
  packages/core/src/components/TextField/TextField.jsx
Labels: Ready for review

#519 [WNMGDS-268] Remove source link in page headers
  packages/docs/src/scripts/components/PageHeader.jsx
Labels: Ready for review

#517 [WNMGDS-158] Update site package documentation
  packages/docs/src/pages/startup/site-package.md
Labels: Ready for review

#526 [WNMGDS-240] - Adding linting for Markdown and HTML that happens on lint-staged
  .prettierignore
  package.json
  packages/core/src/components/Alert/alert.example.html
  packages/core/src/components/Button/button-icons.example.html
  packages/core/src/components/Button/button-inverse.example.html
  packages/core/src/components/Button/button.example.html
  packages/core/src/components/ChoiceList/checkbox-radio-inverse.example.html
  packages/core/src/components/ChoiceList/checkbox-radio-right-to-left.example.html
  packages/core/src/components/ChoiceList/checkbox-radio-size.example.html
  packages/core/src/components/ChoiceList/checkbox-radio.example.html
  packages/core/src/components/ChoiceList/select.example.html
  packages/core/src/components/Dialog/dialog.example.html
  packages/core/src/components/Dropdown/Dropdown.example.html
  packages/core/src/components/HelpDrawer/help-drawer.example.html
  packages/core/src/components/Review/review.example.html
  packages/core/src/components/Spinner/spinner.example.html
  packages/core/src/components/StepList/steplist.example.html
  packages/core/src/components/Table/table-complex.example.html
  packages/core/src/components/Tabs/tabs.example.html
  packages/core/src/components/TextField/textfield-inverse.example.html
  packages/core/src/components/TextField/textfield.example.html
  packages/core/src/components/VerticalNav/verticalnav.example.html
  packages/docs/src/pages/patterns/documentation-page.example.html
Labels: Build Process, Ready for review

#525 [WNMGDS] - Change doc site block quote styling
  packages/docs/src/styles/base/_typography.scss
Labels: Design, Ready for review
