Repository CMSgov/design-system, pull requests merged in 2020-03, with the labels that each got.

#638 [WNMGDS-384] Allow custom heading level
  packages/core/src/components/Alert/Alert.jsx
  packages/core/src/components/Dialog/Dialog.example.jsx
  packages/core/src/components/Dialog/Dialog.jsx
  packages/core/src/components/Dialog/Dialog.test.jsx
  packages/core/src/components/Dialog/ThirdPartyLink.example.jsx
  packages/core/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
  packages/core/src/components/Dialog/dialog-size.example.html
  packages/core/src/components/Dialog/dialog.example.html
  packages/core/src/components/HelpDrawer/HelpDrawer.example.jsx
  packages/core/src/components/HelpDrawer/HelpDrawer.jsx
  packages/core/src/components/HelpDrawer/help-drawer.example.html
  packages/core/src/components/Review/Review.jsx
  packages/core/src/components/StepList/Step.jsx
  packages/core/src/components/StepList/Step.test.jsx
  packages/core/src/components/StepList/StepList.example.jsx
  packages/core/src/components/StepList/StepList.jsx
  packages/core/src/components/StepList/StepList.scss
  packages/core/src/components/StepList/SubStep.jsx
  packages/core/src/components/StepList/SubStep.test.jsx
  packages/core/src/components/StepList/_StepList.docs.scss
  packages/core/src/components/StepList/steplist.example.html
  packages/docs/src/scripts/example.js
Labels: Ready For Review

#639 [WNMGDS-385] - Update dialog to focus on window
  packages/core/src/components/Dialog/Dialog.jsx
  packages/core/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
Labels: Accessibility, Ready For Review

#642 v3.6.1
  lerna.json
  packages/core/package.json
  packages/docs/package.json
  packages/layout/package.json
  packages/support/package.json
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Alert_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Alert_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Alert_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_-_Default_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Modal_Dialog_-_Default_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Modal_Dialog_-_Default_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Modal_Dialog_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Modal_Dialog_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Modal_Dialog_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Code_conventions_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Patterns_-_External_Link_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Patterns_-_External_Link_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Patterns_-_External_Link_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Patterns_-_Step_List_-_React_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Patterns_-_Step_List_-_React_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Patterns_-_Step_List_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Patterns_-_Step_List_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Patterns_-_Step_List_0_document_2_desktop.png
Labels: Ready For Review

#645 [WNMGDS-388] Upgrade babel
  .babelrc
  babel.config.js
  browserslist
  package.json
  packages/docs/src/scripts/helpers/polyfills.js
  packages/docs/webpack.config.js
  tools/gulp/docs/generatePage.js
  tools/jest/e2e.config.js
  tools/jest/e2e.polyfills.js
  tools/jest/polyfills.js
  yarn.lock
Labels: Dependencies, Ready For Review

#646 [WNMGDS-359] Stop exporting VerticalNav and Tab internal components
  packages/core/src/components/Tabs/_Tabs.docs.scss
  packages/core/src/components/__tests__/index.test.js
  packages/core/src/components/index.js
Labels: Ready For Review

#649 [NO-TICKET] - Update contact to use the new qualtrics link
  packages/docs/src/scripts/components/Footer.jsx
Labels: Ready For Review

#643 [WNMGDS-376] - Add accessibility page to doc site
  packages/docs/src/pages/guidelines/accessibility.md
Labels: Accessibility

#641 [WNMGDS-391] Fix MonthPicker legend
  packages/core/src/components/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
  packages/core/src/components/Button/Button.example.jsx
  packages/core/src/components/Button/Button.jsx
  packages/core/src/components/Button/Button.test.jsx
  packages/core/src/components/Button/__snapshots__/Button.test.jsx.snap
  packages/core/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
  packages/core/src/components/HelpDrawer/__snapshots__/HelpDrawer.test.jsx.snap
  packages/core/src/components/MonthPicker/MonthPicker.example.jsx
  packages/core/src/components/MonthPicker/MonthPicker.jsx
  packages/core/src/components/MonthPicker/MonthPicker.scss
  packages/core/src/components/MonthPicker/MonthPicker.test.jsx
  packages/core/src/components/MonthPicker/__snapshots__/MonthPicker.test.jsx.snap
  packages/core/src/components/Spinner/Spinner.example.jsx
  packages/core/src/components/StepList/StepList.jsx
  packages/core/src/components/VerticalNav/VerticalNav.jsx
  packages/core/src/components/VerticalNav/VerticalNavItem.jsx
  packages/core/src/components/VerticalNav/VerticalNavItemLabel.jsx
  packages/docs/src/scripts/components/GitHubLinks.jsx
  packages/docs/src/scripts/components/Header.jsx
Labels: Ready For Review

#653 [NO-TICKET] Remove unnecessary core js imports
  packages/core/src/components/Autocomplete/Autocomplete.jsx
  packages/core/src/components/MonthPicker/MonthPicker.jsx
  packages/core/src/components/Tabs/Tabs.jsx
  packages/core/src/components/TextField/Mask.jsx
Labels: Easy Review

#647 [WNMGDS-382] Update datefield and textfield input type
  packages/core/src/components/DateField/DateField.jsx
  packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
  packages/core/src/components/DateField/datefield.example.html
  packages/core/src/components/FormLabel/_FormLabel.docs.scss
  packages/core/src/components/TextField/Mask.example.jsx
  packages/core/src/components/TextField/Mask.jsx
  packages/core/src/components/TextField/Mask.test.jsx
  packages/core/src/components/TextField/TextField.example.jsx
  packages/core/src/components/TextField/TextField.jsx
  packages/core/src/components/TextField/TextField.scss
  packages/core/src/components/TextField/TextField.test.jsx
  packages/core/src/components/TextField/__snapshots__/Mask.test.jsx.snap
  packages/core/src/components/TextField/__snapshots__/TextField.test.jsx.snap
  packages/core/src/components/TextField/textfield.example.html
Labels: Ready For Review

#654 [WNMGDS-405] Upgrade react-docgen
  package.json
  packages/core/src/components/Button/Button.jsx
  packages/docs/src/scripts/components/GitHubLinks.jsx
  yarn.lock
Labels: Easy Review

#655 Release v3.7.0
  lerna.json
  packages/core/package.json
  packages/docs/package.json
  packages/layout/package.json
  packages/support/package.json
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Badge_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Button_-_React_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Datefield_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Datefield_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Datefield_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Form_label__legend_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Form_label__legend_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Form_label__legend_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Masked_Field_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Masked_Field_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Masked_Field_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_-_React_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_-_React_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_-_React_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Tabs_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Tabs_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Tabs_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Textfield_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Textfield_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Components_-_Textfield_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Code_conventions_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Code_conventions_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Component_maturity_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Component_maturity_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Forms_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Forms_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Internationalization_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Internationalization_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Internationalization_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Responsive_design_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Responsive_design_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Themeing_0_document_1_tablet.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Guidelines_-_Themeing_0_document_2_desktop.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Utilities_-_Background_Color_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Utilities_-_Font_Style_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Utilities_-_Font_Weight_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Utilities_-_Margin_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Utilities_-_Overflow_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Utilities_-_Text_Decoration_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Utilities_-_Text_Transform_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Utilities_-_Truncate_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Utilities_-_Vertical_Align_0_document_0_phone.png
  tools/backstop_data/bitmaps_reference/backstop_default_CMSDS_-_Utilities_-_Word_Break_0_document_0_phone.png
Labels: Ready For Review

#660 [WNMGDS-380] add note about links in legends in IE11
  packages/design-system/src/components/FormLabel/_FormLabel.docs.scss
Labels: Easy Review, Ready For Review

#662 [NO-TICKET] Update component workflow image
  .github/images/CMS-Design-System-component-decision-workflow.jpg
Labels: Ready For Review

#661 [NO-TICKET] Updating proposal issue template
  .github/ISSUE_TEMPLATE/propose-a-new-item-for-the-cms-design-system.md
  CONTRIBUTING.md
Labels: Ready For Review
