Repository CMSgov/design-system, pull requests merged in 2020-08, with the labels that each got.

#739 [NO-TICKET] Update WRITING-DOCUMENTATION.md
  guides/WRITING-DOCUMENTATION.md
Labels: Ready For Review

#764 [WNMGDS-573] - Typo and grammar fixes
  packages/design-system-docs/src/pages/guidelines/forms.md
  packages/design-system-docs/src/pages/guidelines/responsive.md
  packages/design-system-docs/src/pages/index.md
  packages/design-system-docs/src/pages/startup/child-design-systems.md
  packages/design-system-docs/src/pages/startup/components.md
  packages/design-system-docs/src/pages/startup/installation.md
  packages/design-system-docs/src/pages/startup/migrating-v2.md
  packages/design-system-docs/src/pages/startup/theming.md
Labels: Easy Review

#763 [WNMGDS-570] Update installation, css, font image documentation
  examples/child-design-system/README.md
  packages/design-system-docs/src/pages/guidelines/browser-support.md
  packages/design-system-docs/src/pages/startup/child-design-systems.md
  packages/design-system-docs/src/pages/startup/fonts-and-images.md
  packages/design-system-docs/src/pages/startup/installation.md
  packages/design-system-docs/src/pages/startup/sass-and-css.md
  packages/design-system-docs/src/pages/startup/theming.md
  packages/design-system/README.md
Labels: Ready For Review

#766 [NO_TICKET] Update default font image path
  packages/design-system-docs/src/example.scss
  packages/design-system-docs/src/index.scss
  packages/design-system-docs/src/pages/startup/sass-and-css.md
  packages/design-system/src/styles/settings/variables/_build.scss
Labels: Easy Review

#706 [WNMGDS-65] Add table component
  packages/design-system-docs/src/index.scss
  packages/design-system-docs/src/pages/components/Table/Table.example.jsx
  packages/design-system-docs/src/pages/components/Table/_Table.docs.scss
  packages/design-system-docs/src/pages/components/Table/table-complex.example.html
  packages/design-system-docs/src/pages/components/Table/table.example.html
  packages/design-system-docs/src/scripts/components/ReactPropDoc.jsx
  packages/design-system-docs/src/scripts/components/ReactPropDocs.jsx
  packages/design-system-docs/src/scripts/components/__tests__/ReactPropDoc.test.js
  packages/design-system-docs/src/styles/components/_ReactPropDocs.scss
  packages/design-system/src/components/Table/Table.jsx
  packages/design-system/src/components/Table/Table.test.jsx
  packages/design-system/src/components/Table/TableBody.jsx
  packages/design-system/src/components/Table/TableBody.test.jsx
  packages/design-system/src/components/Table/TableCaption.jsx
  packages/design-system/src/components/Table/TableCaption.test.jsx
  packages/design-system/src/components/Table/TableContext.js
  packages/design-system/src/components/Table/TableDataCell.jsx
  packages/design-system/src/components/Table/TableDataCell.test.jsx
  packages/design-system/src/components/Table/TableHead.jsx
  packages/design-system/src/components/Table/TableHead.test.jsx
  packages/design-system/src/components/Table/TableHeaderCell.jsx
  packages/design-system/src/components/Table/TableHeaderCell.test.jsx
  packages/design-system/src/components/Table/TableRow.jsx
  packages/design-system/src/components/Table/TableRow.test.jsx
  packages/design-system/src/components/__tests__/index.test.js
  packages/design-system/src/components/index.js
  packages/design-system/src/styles/components/_Table.scss
Labels: Accessibility, Component, Ready For Review

#733 [WNMGDS-327] Change radio and checkbox checkmark to be created with SCSS instead of image
  packages/design-system-docs/src/pages/styles/icons/_icons.docs.scss
  packages/design-system-docs/src/pages/styles/icons/checkbox-radio-icons.example.html
  packages/design-system/src/images/checkmark-white.svg
  packages/design-system/src/styles/components/_Choice.scss
Labels: Ready For Review

#762 [WNMGDS-495] - Update CMSDS examples
  examples/README.md
  examples/article/style.css
  examples/create-react-app/.env
  examples/create-react-app/.gitignore
  examples/create-react-app/README.md
  examples/create-react-app/package.json
  examples/create-react-app/public/favicon.ico
  examples/create-react-app/public/index.html
  examples/create-react-app/public/logo192.png
  examples/create-react-app/public/logo512.png
  examples/create-react-app/public/manifest.json
  examples/create-react-app/public/robots.txt
  examples/create-react-app/src/components/App.js
  examples/create-react-app/src/components/App.test.js
  examples/create-react-app/src/images/us_flag_small.png
  examples/create-react-app/src/index.js
  examples/create-react-app/src/serviceWorker.js
  examples/create-react-app/src/setupTests.js
  examples/create-react-app/src/styles/index.scss
  examples/form/index.html
  examples/form/style.css
  examples/html-css/README.md
  examples/html-css/index.html
  examples/html-css/logo.svg
  examples/html-css/style.css
  examples/react-app/README.md
  examples/react-app/package.json
  examples/responsive/index.html
  examples/webpack-demo/README.md
  examples/webpack-demo/p_webpack.config.js
  examples/webpack-demo/package.json
  examples/webpack-demo/src/img/hero.png
  examples/webpack-demo/src/style.scss
  package.json
  packages/design-system-docs/src/pages/startup/components.md
  packages/design-system-docs/src/pages/startup/examples.md
  yarn.lock
Labels: Ready For Review

#775 [WNMGDS-581] Reorganize doc site scss
  packages/design-system-docs/src/example.scss
  packages/design-system-docs/src/index.scss
  packages/design-system-docs/src/scripts/components/PageBlock.jsx
  packages/design-system-docs/src/styles/_example.scss
  packages/design-system-docs/src/styles/_index.scss
  packages/design-system-docs/src/styles/components/_PageBlock.scss
  packages/design-system-docs/src/styles/components/_example.scss
  packages/design-system-docs/src/styles/components/_preview.scss
  packages/design-system-docs/src/styles/components/_swatch.scss
  packages/design-system-docs/src/styles/layouts/_content.scss
  packages/design-system-docs/src/styles/layouts/_grid.scss
  packages/design-system-docs/src/styles/layouts/_index.scss
  packages/design-system-docs/src/styles/settings/_index.scss
  packages/design-system-docs/src/styles/tools/_functions.scss
  packages/design-system-docs/src/styles/tools/_index.scss
  packages/design-system-docs/src/styles/utilities/_index.scss
Labels: Ready For Review

#778 [WNMGDS-579] Fix console warnings for HelpDrawer and Dialog
  packages/design-system/src/components/Dialog/Dialog.jsx
  packages/design-system/src/components/HelpDrawer/HelpDrawer.jsx
Labels: Ready For Review

#774 [WNMGDS-582] Improve css for child ds
  packages/design-system-docs/src/scripts/components/Footer.jsx
  packages/design-system-docs/src/styles/components/_UsaBanner.scss
  packages/design-system/src/styles/base/_link.scss
  packages/design-system/src/styles/components/_Alert.scss
  packages/design-system/src/styles/settings/variables/_animation.scss
  packages/design-system/src/styles/settings/variables/_color.scss
  packages/design-system/src/styles/settings/variables/_shadow.scss
  packages/design-system/src/styles/settings/variables/_type.scss
Labels: Ready For Review

#768 [WNMGDS-576] Update styles for transparent inverse buttons
  packages/design-system/src/styles/components/_Button.scss
Labels: Ready For Review

#782 [WNMGDS-591] Fix link color
  packages/design-system/src/styles/base/_link.scss
  packages/design-system/src/styles/components/_Alert.scss
  packages/design-system/src/styles/components/_Dialog.scss
Labels: Easy Review

#784 [WNMGTAXTOOLS-73] Export getMonthNames function from MonthPicker module
  packages/design-system/src/components/index.js
Labels: Bug, Easy Review, Ready For Review

#777 [WNMGDS-588] Update to use lifecycle methods
  lerna.json
  packages/design-system/src/components/Table/Table.jsx
  packages/design-system/src/components/Table/TableContext.js
  packages/design-system/src/components/Table/TableDataCell.jsx
  packages/design-system/src/components/Table/TableHeaderCell.jsx
  packages/design-system/src/components/__tests__/index.test.js
Labels: Ready For Review

#785 [WNMGDS-592] Add IE11 polyfill
  babel.config.js
  packages/design-system-scripts/package.json
  yarn.lock
Labels: Ready For Review

#783 Add spans to html examples with form labels
  packages/design-system-docs/src/pages/components/ChoiceList/Choice.example.jsx
  packages/design-system-docs/src/pages/components/ChoiceList/checkbox-radio-size.example.html
  packages/design-system-docs/src/pages/components/ChoiceList/checkbox-radio.example.html
  packages/design-system-docs/src/pages/components/DateField/datefield.example.html
  packages/design-system-docs/src/pages/components/Dropdown/dropdown.example.html
  packages/design-system-docs/src/pages/components/FormLabel/form-label.example.html
  packages/design-system-docs/src/pages/components/MonthPicker/MonthPicker.example.jsx
  packages/design-system-docs/src/pages/components/TextField/textfield.example.html
  packages/design-system-docs/src/pages/styles/icons/checkbox-radio-icons.example.html
Labels: Ready For Review

#790 [WNMGWINSHOP-655] Render the substep link if a substep is started
  packages/design-system/src/components/StepList/SubStep.jsx
  packages/design-system/src/components/StepList/SubStep.test.jsx
Labels: Ready For Review

#794 [WNMGDS-527] Add disabled prop to DateField
  packages/design-system-docs/src/pages/components/DateField/DateField.example.jsx
  packages/design-system/src/components/DateField/DateField.jsx
  packages/design-system/src/components/DateField/DateField.test.jsx
  packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
Labels: Ready For Review
