Repository CMSgov/design-system, pull requests merged in 2020-11, with the labels that each got.

#863 [NO-TICKET] Update Helpdrawer e2e test
  packages/design-system/src/components/HelpDrawer/HelpDrawer.e2e.test.js
Labels: Easy Review

#868 Sketch library Release-2.2.0
  design-assets/cms-design-system-ui-kit.xml
Labels: Ready For Review

#867 Fix substep definition file
  packages/design-system/src/types/StepList/Step.d.ts
  packages/design-system/src/types/StepList/StepList.d.ts
  packages/design-system/src/types/StepList/SubStep.d.ts
Labels: Ready For Review

#870 [WNMGTAXTOOLS-95] Add Downshift props to Autocomplete props' type def
  packages/design-system/src/types/Autocomplete/Autocomplete.d.ts
Labels: Engineering, Ready For Review

#866 [WNMGDS-621] Add dense table style
  lerna.json
  packages/design-system-docs/src/pages/components/Table/_Table.docs.scss
  packages/design-system-docs/src/pages/components/Table/table.example.html
  packages/design-system/src/components/Table/Table.jsx
  packages/design-system/src/components/Table/Table.test.jsx
  packages/design-system/src/components/Table/__snapshots__/Table.test.jsx.snap
  packages/design-system/src/styles/components/_Table.scss
  packages/design-system/src/types/Table/Table.d.ts
Labels: Ready For Review

#872 [NO_TICKET] Update Step List background image to no-repeat
  packages/design-system/src/styles/components/_StepList.scss
Labels: Easy Review

#869 [WNMGDS-480] Add usa banner component
  babel.config.js
  packages/design-system-docs/src/images/icon-dot-gov.svg
  packages/design-system-docs/src/images/icon-https.svg
  packages/design-system-docs/src/images/icon-lock.svg
  packages/design-system-docs/src/images/us_flag_small.png
  packages/design-system-docs/src/pages/components/UsaBanner/UsaBanner.example.jsx
  packages/design-system-docs/src/pages/components/UsaBanner/_UsaBanner.docs.scss
  packages/design-system-docs/src/pages/components/UsaBanner/usabanner.example.html
  packages/design-system-docs/src/scripts/components/Header.jsx
  packages/design-system-docs/src/scripts/components/UsaBanner.jsx
  packages/design-system-docs/src/styles/_index.scss
  packages/design-system-scripts/package.json
  packages/design-system/src/components/UsaBanner/UsaBanner.e2e.test.js
  packages/design-system/src/components/UsaBanner/UsaBanner.jsx
  packages/design-system/src/components/UsaBanner/UsaBanner.test.jsx
  packages/design-system/src/components/UsaBanner/__snapshots__/UsaBanner.test.jsx.snap
  packages/design-system/src/components/index.js
  packages/design-system/src/images/usa-banner-dot-gov.svg
  packages/design-system/src/images/usa-banner-flag.svg
  packages/design-system/src/images/usa-banner-https.svg
  packages/design-system/src/images/usa-banner-lock.svg
  packages/design-system/src/styles/components/_UsaBanner.scss
  packages/design-system/src/styles/components/index.scss
  yarn.lock
Labels: Ready For Review

#871 [WNMGDS-689] Use SVG in react, process SVG in build scripts
  babel.config.js
  cmsds.config.js
  examples/child-design-system/README.md
  examples/child-design-system/babel.config.js
  examples/child-design-system/cmsds.config.js
  examples/child-design-system/src/images/logo-usa.svg
  packages/design-system-docs/src/images/symbols.svg
  packages/design-system-docs/src/pages/components/Button/button-icons.example.html
  packages/design-system-docs/src/pages/components/Tabs/tabs.example.html
  packages/design-system-scripts/configDefaults.js
  packages/design-system-scripts/gulp/build.js
  packages/design-system-scripts/gulp/common/copyAssets.js
  packages/design-system-scripts/gulp/common/copyFontsImages.js
  packages/design-system-scripts/gulp/docs/assets.js
  packages/design-system-scripts/gulp/docs/extractReactData/index.js
  packages/design-system-scripts/gulp/watch.js
  packages/design-system-scripts/package.json
  packages/design-system/src/images/arrow-both.svg
  packages/design-system/src/images/arrow-down.svg
  packages/design-system/src/images/arrow-up.svg
  packages/design-system/src/images/checkmark-green.svg
  packages/design-system/src/images/checkmark-white.svg
  packages/design-system/src/images/close--primary-darker.svg
  packages/design-system/src/images/close--primary.svg
  packages/design-system/src/images/close.svg
  packages/design-system/src/images/download.svg
  packages/design-system/src/images/error.svg
  packages/design-system/src/images/image.svg
  packages/design-system/src/images/information-new-hover.svg
  packages/design-system/src/images/information-new.svg
  packages/design-system/src/images/information.svg
  packages/design-system/src/images/next.svg
  packages/design-system/src/images/pdf.svg
  packages/design-system/src/images/star-filled.svg
  packages/design-system/src/images/star.svg
  packages/design-system/src/images/success-fill.svg
  packages/design-system/src/images/success.svg
  packages/design-system/src/images/warning.svg
  packages/design-system/src/styles/test
  yarn.lock
Labels: Ready For Review

#873 Omit Autocomplete-only props from AutocompleteProps type def
  packages/design-system/src/types/Autocomplete/Autocomplete.d.ts
Labels: Engineering

#876 [WNMGDS-658] Move grid styles to utilities
  backstop.json
  guides/WRITING-DOCUMENTATION.md
  packages/design-system-docs/src/pages/components/DateField/_DateField.docs.scss
  packages/design-system-docs/src/pages/guidelines/responsive.md
  packages/design-system-docs/src/pages/index.md
  packages/design-system-docs/src/pages/patterns/documentation-page.md
  packages/design-system-docs/src/pages/styles/layout-grid/grid-alignment.example.html
  packages/design-system-docs/src/pages/utilities/flexbox/_flexbox.docs.scss
  packages/design-system-docs/src/pages/utilities/layout-grid/_grid.docs.scss
  packages/design-system-docs/src/pages/utilities/layout-grid/grid-alignment.example.html
  packages/design-system-docs/src/pages/utilities/layout-grid/grid-default.example.html
  packages/design-system-docs/src/pages/utilities/layout-grid/grid-forms.example.html
  packages/design-system-docs/src/pages/utilities/layout-grid/grid-natural-width.example.html
  packages/design-system-docs/src/pages/utilities/layout-grid/grid-nested.example.html
  packages/design-system-docs/src/pages/utilities/layout-grid/grid-number-col.example.html
  packages/design-system-docs/src/pages/utilities/layout-grid/grid-offset.example.html
  packages/design-system-docs/src/pages/utilities/layout-grid/grid-responsive.example.html
  packages/design-system-docs/src/pages/utilities/overview.md
  packages/design-system-scripts/gulp/docs/generatePages/processKssSection.js
  packages/design-system/src/styles/base/index.scss
  packages/design-system/src/styles/utilities/_grid.scss
  packages/design-system/src/styles/utilities/index.scss
Labels: Ready For Review

#878 [WNMGDS-693] Allow hiding doc site pages
  guides/WRITING-DOCUMENTATION.md
  packages/design-system-scripts/gulp/docs/generatePages/generatePages.js
  packages/design-system-scripts/gulp/docs/generatePages/processKssSection.js
Labels: Ready For Review

#883 [WNMGDS-691] Add guidance for help drawer
  packages/design-system-docs/src/pages/components/HelpDrawer/_HelpDrawer.docs.scss
Labels: Ready For Review

#882 [WNMGDS-633] Tooltip update
  packages/design-system-docs/src/pages/components/Tooltip/Tooltip.example.jsx
  packages/design-system/src/components/Tooltip/Tooltip.jsx
  packages/design-system/src/components/Tooltip/TooltipIcon.jsx
  packages/design-system/src/components/Tooltip/__snapshots__/Tooltip.test.jsx.snap
  packages/design-system/src/components/Tooltip/__snapshots__/TooltipIcon.test.jsx.snap
  packages/design-system/src/images/information-new-generic.svg
  packages/design-system/src/styles/components/_Tooltip.scss
  packages/design-system/src/styles/components/_TooltipIcon.scss
Labels: Ready For Review
