Repository CMSgov/design-system, pull requests merged in 2020-05, with the labels that each got.

#686 [WNMGDS-351] Remove determine props 'type' logic from ChoiceList component
  packages/design-system-docs/src/pages/components/Button/_Button.docs.scss
  packages/design-system-docs/src/pages/components/ChoiceList/Choice.example.jsx
  packages/design-system-docs/src/pages/components/ChoiceList/ChoiceList.example.jsx
  packages/design-system-docs/src/pages/components/ChoiceList/_ChoiceList.docs.scss
  packages/design-system-docs/src/scripts/components/__tests__/ReactPropDoc.test.js
  packages/design-system/src/scripts/components/ChoiceList/Choice.jsx
  packages/design-system/src/scripts/components/ChoiceList/Choice.test.jsx
  packages/design-system/src/scripts/components/ChoiceList/ChoiceList.jsx
  packages/design-system/src/scripts/components/ChoiceList/ChoiceList.test.jsx
  packages/design-system/src/scripts/components/MonthPicker/MonthPicker.jsx
Labels: Ready For Review

#693 [WNMGDS-350] Add autoComplete prop to Date field component
  packages/design-system/src/scripts/components/DateField/DateField.jsx
Labels: Ready For Review

#697 [WNMGDS-466] Update Datefield html example
  packages/design-system-docs/src/pages/components/DateField/datefield.example.html
Labels: Easy Review, Ready For Review

#696 [WNMGDS-452] [WNMGDS-454] Update Sketch grid and fix font used in vertical nav
  design-assets/CMS-Design-System-UI-kit.sketch
  design-assets/cms-design-system-ui-kit.xml
Labels: Design, Ready For Review

#695 [WNMGDS-422] Create release scripts
  .gitattributes
  .gitignore
  Gulpfile.js
  babel.config.js
  backstop.json
  guides/RELEASE-PROCESS.md
  lerna.json
  package.json
  packages/design-system-docs/.npmignore
  packages/design-system-docs/src/pages/components/TextField/_TextField.docs.scss
  packages/design-system-docs/src/scripts/components/GitHubLinks.jsx
  packages/design-system-scripts/.npmignore
  packages/design-system-scripts/publish.sh
  packages/design-system/.npmignore
  packages/design-system/src/scripts/components/__tests__/smoke.e2e.test.js
  prepublish.sh
  scripts/prepublish.sh
  scripts/publish.sh
  setupTests.js
  yarn.lock
Labels: Ready For Review

#704 [WNMGDS-483] Fix currency mask for Firefox
  packages/design-system-docs/src/pages/components/TextField/Mask.example.jsx
  packages/design-system/src/components/TextField/Mask.jsx
  packages/design-system/src/components/TextField/__snapshots__/Mask.test.jsx.snap
Labels: Bug, Ready For Review

#705 [WNMGDS-444] Fix dev console warning msg for VerticalNav
  packages/design-system/src/components/VerticalNav/VerticalNav.jsx
Labels: Easy Review, Ready For Review

#701 [WNMGDS-450] [WMNGDS-441] [WMNGDS-451] Sketch file updates
  design-assets/CMS-Design-System-UI-kit.sketch
  design-assets/cms-design-system-ui-kit.xml
Labels: Ready For Review
