Repository CMSgov/design-system, pull requests merged in 2020-10, with the labels that each got.

#829 [WNMGDS-613] Additional table props
  packages/design-system-docs/src/pages/components/Table/_Table.docs.scss
  packages/design-system-docs/src/pages/components/Table/table-complex.example.html
  packages/design-system/src/components/Table/Table.test.jsx
  packages/design-system/src/components/Table/TableBody.test.jsx
  packages/design-system/src/components/Table/TableCaption.test.jsx
  packages/design-system/src/components/Table/TableCell.test.jsx
  packages/design-system/src/components/Table/TableHead.test.jsx
  packages/design-system/src/components/Table/TableRow.test.jsx
  packages/design-system/src/components/Table/__snapshots__/Table.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableBody.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableCaption.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableCell.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableHead.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableRow.test.jsx.snap
  packages/design-system/src/styles/components/_Table.scss
Labels: Ready For Review

#833 [NO-TICKET] ESLint fixes
  packages/design-system-docs/src/scripts/components/CodeSnippet.jsx
  packages/design-system-docs/src/scripts/components/Frame.jsx
  packages/design-system-docs/src/scripts/components/HtmlExample.jsx
  packages/design-system-docs/src/scripts/components/PageHeader.jsx
  packages/design-system/src/components/Tooltip/Tooltip.e2e.test.js
  packages/design-system/src/styles/settings/uswds/_uswds-theme-utilities.scss
Labels: Ready For Review

#832 [NO-TICKET] Backstop updates for v2.1.0
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Alert_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Autocomplete_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Badge_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Button_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_ChoiceList_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_ChoiceList_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_ChoiceList_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_Default_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_React_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Dropdown_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Form_label__legend_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_List_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Masked_Field_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Modal_Dialog_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Skipnav_-_Default_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Skipnav_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Skipnav_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Skipnav_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Skipnav_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Skipnav_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Spinner_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_-_Complex_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_-_Complex_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_-_React_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Tabs_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Textfield_-_Default_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Textfield_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Vertical_Navigation_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Patterns_-_External_Link_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Patterns_-_Review_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Patterns_-_Step_List_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Styles_-_Icons_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Styles_-_Icons_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Styles_-_Icons_0_document_2_desktop.png
Labels: Easy Review

#835 [NO_TICKET] Update release process doc
  README.md
  guides/RELEASE-PROCESS.md
  package.json
Labels: Easy Review, Ready For Review

#837 [WNMGDS-568] Add styles for field error message class
  packages/design-system-docs/src/pages/components/ChoiceList/checkbox-radio.example.html
  packages/design-system-docs/src/pages/components/DateField/datefield.example.html
  packages/design-system-docs/src/pages/components/Dropdown/dropdown.example.html
  packages/design-system-docs/src/pages/components/FormLabel/_FormLabel.docs.scss
  packages/design-system-docs/src/pages/components/FormLabel/form-label.example.html
  packages/design-system-docs/src/pages/components/TextField/textfield.example.html
  packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
  packages/design-system/src/components/FormLabel/FormLabel.jsx
  packages/design-system/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
  packages/design-system/src/styles/components/_FormLabel.scss
Labels: Ready For Review

#843 [WNMGDS-656] Fix USWDS import
  packages/design-system-docs/src/pages/components/ChoiceList/checkbox-radio.example.html
  packages/design-system-docs/src/pages/components/DateField/datefield.example.html
  packages/design-system-docs/src/pages/components/Dropdown/dropdown.example.html
  packages/design-system-docs/src/pages/components/FormLabel/_FormLabel.docs.scss
  packages/design-system-docs/src/pages/components/FormLabel/form-label.example.html
  packages/design-system-docs/src/pages/components/TextField/textfield.example.html
  packages/design-system-scripts/gulp/sass.js
  packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
  packages/design-system/src/components/FormLabel/FormLabel.jsx
  packages/design-system/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
  packages/design-system/src/styles/components/_FormLabel.scss
  packages/design-system/src/styles/settings/uswds/_index.scss
Labels: Ready For Review

#839 [WNMGDS-546] - Add guidance for placeholder dropdowns
  packages/design-system-docs/src/pages/components/Dropdown/Dropdown.example.jsx
  packages/design-system-docs/src/pages/components/Dropdown/_Dropdown.docs.scss
  packages/design-system-docs/src/pages/components/Dropdown/dropdown.example.html
Labels: Ready For Review

#846 [NO_TICKET] Add back styles for field error message class
  packages/design-system-docs/src/pages/components/ChoiceList/checkbox-radio.example.html
  packages/design-system-docs/src/pages/components/DateField/datefield.example.html
  packages/design-system-docs/src/pages/components/Dropdown/dropdown.example.html
  packages/design-system-docs/src/pages/components/FormLabel/_FormLabel.docs.scss
  packages/design-system-docs/src/pages/components/FormLabel/form-label.example.html
  packages/design-system-docs/src/pages/components/TextField/textfield.example.html
  packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
  packages/design-system/src/components/FormLabel/FormLabel.jsx
  packages/design-system/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
  packages/design-system/src/styles/components/_FormLabel.scss
Labels: Easy Review

#836 [WNMGDS-632] Apply Review classes
  packages/design-system-docs/src/pages/components/Review/review.example.html
  packages/design-system/src/components/Review/Review.jsx
  packages/design-system/src/components/Review/__snapshots__/Review.test.jsx.snap
  packages/design-system/src/styles/components/_Review.scss
  packages/design-system/src/styles/components/index.scss
Labels: Ready For Review

#848 [NO_TICKET] Remove USWDS SCSS
  packages/design-system/package.json
  packages/design-system/src/styles/settings/_index.scss
  packages/design-system/src/styles/settings/uswds/_index.scss
  packages/design-system/src/styles/settings/uswds/_uswds-theme-color.scss
  packages/design-system/src/styles/settings/uswds/_uswds-theme-components.scss
  packages/design-system/src/styles/settings/uswds/_uswds-theme-general.scss
  packages/design-system/src/styles/settings/uswds/_uswds-theme-spacing.scss
  packages/design-system/src/styles/settings/uswds/_uswds-theme-typography.scss
  packages/design-system/src/styles/settings/uswds/_uswds-theme-utilities.scss
  yarn.lock
Labels: Easy Review

#841 [WNMGDS-648] Apply cursor: not-allowed to disabled label and box
  packages/design-system/src/styles/components/_Choice.scss
  packages/design-system/src/styles/components/_Review.scss
Labels: Ready For Review

#850 [WNMGDS-664] Update DateField markup
  packages/design-system-docs/src/pages/components/DateField/datefield.example.html
  packages/design-system/src/components/DateField/DateField.jsx
  packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
  packages/design-system/src/styles/components/_DateField.scss
Labels: Ready For Review

#851 [WNMGDS-659] Remove default currency ariaLabel
  packages/design-system/src/components/TextField/TextField.jsx
  packages/design-system/src/components/TextField/TextField.test.jsx
  packages/design-system/src/components/TextField/__snapshots__/TextField.test.jsx.snap
Labels: Ready For Review

#855 [WNMGDS-645] [WNMGDS-488] - Add date picker and update font bug
  design-assets/CMS-Design-System-UI-kit.sketch
Labels: Design, Ready For Review

#857 [WNMGDS-671] Fix check icon box sizing
  packages/design-system/src/styles/components/_Choice.scss
  packages/design-system/src/styles/test
Labels: Ready For Review

#856 [WNMGDS-667] Update inverse html examples
  packages/design-system-docs/src/pages/components/DateField/datefield.example.html
  packages/design-system/src/styles/components/_FormLabel.scss
Labels: Ready For Review

#852 [WNMGDS-665] Add polyfills required for ie11 support
  packages/design-system-docs/src/pages/components/Tooltip/_Tooltip.docs.scss
  packages/design-system-scripts/gulp/docs/webpack/createWebpackConfig.js
  packages/design-system/src/components/ChoiceList/ChoiceList.jsx
  packages/design-system/src/components/MonthPicker/MonthPicker.jsx
  packages/design-system/src/components/TextField/Mask.jsx
  packages/design-system/src/components/Tooltip/Tooltip.jsx
Labels: Ready For Review

#858 [WNMGDS-669] Update sketch to use color variables!
  design-assets/CMS-Design-System-UI-kit.sketch
Labels: Ready For Review

#853 [WNMGDS-650] Table followup
  lerna.json
  packages/design-system/src/components/Table/Table.jsx
  packages/design-system/src/components/Table/TableBody.jsx
  packages/design-system/src/components/Table/TableCaption.jsx
  packages/design-system/src/components/Table/TableCell.jsx
  packages/design-system/src/components/Table/TableCell.test.jsx
  packages/design-system/src/components/Table/TableHead.jsx
  packages/design-system/src/components/Table/__snapshots__/TableCell.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableHead.test.jsx.snap
  packages/design-system/src/styles/components/_Table.scss
  packages/design-system/src/types/Table/TableCell.d.ts
Labels: Ready For Review

#862 [NO_TICKET] Update Tooltip e2e test
  packages/design-system/src/components/Tooltip/Tooltip.e2e.test.js
Labels: Easy Review

#860 [WNMGDS-676] Update help drawer toggle to be a button
  packages/design-system-docs/src/pages/components/HelpDrawer/help-drawer.example.html
  packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.jsx
  packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.test.jsx
  packages/design-system/src/components/HelpDrawer/__snapshots__/HelpDrawerToggle.test.jsx.snap
  packages/design-system/src/styles/components/_HelpDrawer.scss
Labels: Ready For Review

#861 [NO_TICKET] Update StepList definitions
  examples/create-react-app-typescript/package.json
  packages/design-system/src/types/StepList/Step.d.ts
  packages/design-system/src/types/StepList/StepList.d.ts
  packages/design-system/src/types/StepList/SubStep.d.ts
Labels: Easy Review
