Repository CMSgov/design-system, pull requests merged in 2020-07, with the labels that each got.

#731 [WNMGDS-526] Optimize scripts
  babel.config.js
  package.json
  packages/design-system-scripts/cli.js
  packages/design-system-scripts/gulp/build.js
  packages/design-system-scripts/gulp/common/__tests__/replaceTemplateTags.test.js
  packages/design-system-scripts/gulp/common/constants.js
  packages/design-system-scripts/gulp/common/replaceTemplateTags.js
  packages/design-system-scripts/gulp/docs/docs.js
  packages/design-system-scripts/gulp/docs/extractReactData/index.js
  packages/design-system-scripts/gulp/docs/extractReactData/parseReactFile.js
  packages/design-system-scripts/gulp/docs/extractReactData/reactDocgenHandler.js
  packages/design-system-scripts/gulp/docs/generatePages/addReactData.js
  packages/design-system-scripts/gulp/docs/generatePages/addReactDocs.js
  packages/design-system-scripts/gulp/docs/generatePages/generateDocPage.js
  packages/design-system-scripts/gulp/docs/generatePages/generateExamplePage.js
  packages/design-system-scripts/gulp/docs/generatePages/generatePage.js
  packages/design-system-scripts/gulp/docs/generatePages/generatePages.js
  packages/design-system-scripts/gulp/docs/generatePages/processKssSection.js
  packages/design-system-scripts/gulp/docs/generatePages/processMarkdownPage.js
  packages/design-system-scripts/gulp/docs/generatePages/processMarkup.js
  packages/design-system-scripts/gulp/docs/generatePages/uniquePages.js
  packages/design-system-scripts/gulp/docs/react-docgen-handlers/index.js
  packages/design-system-scripts/gulp/lint.js
  packages/design-system-scripts/gulp/stats/stats.js
  packages/design-system-scripts/gulp/watch.js
  packages/design-system-scripts/package.json
  packages/design-system/package.json
  yarn.lock
Labels: Ready For Review

#732 [WNMGDS-534] Generate ts definition files
  package.json
  packages/design-system-scripts/cli.js
  packages/design-system-scripts/gulp/build.js
  packages/design-system-scripts/gulp/docs/webpack/createReactExampleWebpackConfig.js
  packages/design-system-scripts/package.json
  tsconfig.json
  yarn.lock
Labels: Ready For Review

#734 [WNMGDS-537] Update "Download code and design files" button
  packages/design-system-docs/src/scripts/components/GitHubLinks.jsx
  packages/design-system-scripts/gulp/docs/assets.js
  packages/design-system-scripts/gulp/docs/docs.js
  packages/design-system-scripts/package.json
  yarn.lock
Labels: Ready For Review

#736 [WNMGDS-536] Add more doc content templates
  packages/design-system-docs/src/pages/guidelines/accessibility.md
  packages/design-system-docs/src/pages/guidelines/i18n.md
  packages/design-system-docs/src/pages/startup/browser-support.md
  packages/design-system-docs/src/pages/startup/components.md
  packages/design-system-docs/src/pages/startup/examples.md
  packages/design-system-docs/src/pages/startup/fonts-and-images.md
  packages/design-system-docs/src/pages/startup/installation.md
  packages/design-system-docs/src/pages/startup/sass-and-css.md
  packages/design-system-docs/src/pages/startup/theming.md
  packages/design-system-docs/src/scripts/components/Header.jsx
  packages/design-system-scripts/cli.js
  packages/design-system-scripts/gulp/common/__tests__/replaceTemplateTags.test.js
  packages/design-system-scripts/gulp/common/replaceTemplateTags.js
  packages/design-system-scripts/gulp/docs/__tests__/processKssSection.test.js
  packages/design-system-scripts/gulp/docs/__tests__/processMarkdownPage.test.js
  packages/design-system-scripts/gulp/docs/__tests__/processMarkup.test.js
  packages/design-system-scripts/gulp/docs/extractReactData/parseReactFile.js
  packages/design-system-scripts/gulp/docs/extractReactData/reactDocgenHandler.js
  packages/design-system-scripts/gulp/docs/generatePages/convertMarkdownPages.js
  packages/design-system-scripts/gulp/docs/generatePages/generateDocPage.js
  packages/design-system-scripts/gulp/docs/generatePages/generatePages.js
  packages/design-system-scripts/gulp/docs/generatePages/processKssSection.js
  packages/design-system-scripts/gulp/docs/generatePages/processMarkdownPage.js
  packages/design-system-scripts/gulp/docs/generatePages/processMarkup.js
  packages/design-system-scripts/gulp/docs/webpack/createWebpackConfig.js
Labels: Ready For Review

#737 [WNMGDS-500] Add cmsds.config.js
  cmsds.config.js
  package.json
  packages/design-system-scripts/cli.js
  packages/design-system-scripts/configDefaults.js
  packages/design-system/src/styles/components/_Choice.scss
  packages/design-system/src/styles/components/_Dialog.scss
  packages/design-system/src/styles/components/_TextField.scss
  tsconfig.json
  yarn.lock
Labels: Ready For Review

#738 2.0.0-beta.4 Release
  lerna.json
  packages/design-system-docs/package.json
  packages/design-system-scripts/cli.js
  packages/design-system-scripts/package.json
  packages/design-system/package.json
Labels: Easy Review

#741 [NO_TICKET] Misc fixes changes
  .nvmrc
  package.json
  packages/design-system-scripts/cli.js
  packages/design-system-scripts/gulp/docs/webpack/createReactExampleWebpackConfig.js
  packages/design-system-scripts/package.json
  yarn.lock
Labels: Easy Review

#744 [WNMGDS-539] Finalize on ESM module naming
  packages/design-system-docs/src/pages/startup/components.md
  packages/design-system-docs/src/pages/startup/migrating-v2.md
  packages/design-system-scripts/gulp/build.js
  packages/design-system/package.json
Labels: Easy Review

#743 [WNMGDS-545] Fix rootPath option
  cmsds.config.js
  packages/design-system-docs/src/pages/components/Alert/_Alert.docs.scss
  packages/design-system-docs/src/pages/components/Autocomplete/_Autocomplete.docs.scss
  packages/design-system-docs/src/pages/components/ChoiceList/_ChoiceList.docs.scss
  packages/design-system-docs/src/pages/components/DateField/_DateField.docs.scss
  packages/design-system-docs/src/pages/components/Dialog/_Dialog.docs.scss
  packages/design-system-docs/src/pages/components/Dropdown/_Dropdown.docs.scss
  packages/design-system-docs/src/pages/components/FormLabel/_FormLabel.docs.scss
  packages/design-system-docs/src/pages/components/Spinner/_Spinner.docs.scss
  packages/design-system-docs/src/pages/components/Table/_Table.docs.scss
  packages/design-system-docs/src/pages/components/Tabs/_Tabs.docs.scss
  packages/design-system-docs/src/pages/components/TextField/_TextField.docs.scss
  packages/design-system-docs/src/pages/components/VerticalNav/_VerticalNav.docs.scss
  packages/design-system-docs/src/pages/index.md
  packages/design-system-docs/src/pages/startup/theming.md
  packages/design-system-docs/src/pages/styles/layout-grid/_grid.docs.scss
  packages/design-system-docs/src/pages/styles/spacing/_spacing.docs.scss
  packages/design-system-docs/src/pages/styles/typography/_typography.docs.scss
  packages/design-system-docs/src/pages/utilities/display-visibility/_display-visibility.docs.scss
  packages/design-system-docs/src/pages/utilities/flexbox/_flexbox.docs.scss
  packages/design-system-docs/src/pages/utilities/float/_float.docs.scss
  packages/design-system-docs/src/pages/utilities/font-size/_font-size.docs.scss
  packages/design-system-docs/src/pages/utilities/margin/_margin.docs.scss
  packages/design-system-docs/src/pages/utilities/padding/_padding.docs.scss
  packages/design-system-docs/src/pages/utilities/text-align/_text-align.docs.scss
  packages/design-system-docs/src/scripts/components/GitHubLinks.jsx
  packages/design-system-docs/src/scripts/components/Header.jsx
  packages/design-system-docs/src/scripts/components/Nav.jsx
  packages/design-system-docs/src/scripts/components/UsaBanner.jsx
  packages/design-system-scripts/cli.js
  packages/design-system-scripts/gulp/common/getDocsDistPath.js
  packages/design-system-scripts/gulp/common/replaceTemplateTags.js
  packages/design-system-scripts/gulp/docs/__tests__/processKssSection.test.js
  packages/design-system-scripts/gulp/docs/__tests__/processMarkdownPage.test.js
  packages/design-system-scripts/gulp/docs/docs.js
  packages/design-system-scripts/gulp/docs/generatePages/generateDocPage.js
  packages/design-system-scripts/gulp/docs/generatePages/generateHtmlExample.js
  packages/design-system-scripts/gulp/docs/generatePages/generatePages.js
  packages/design-system-scripts/gulp/docs/generatePages/generateReactExample.js
  packages/design-system-scripts/gulp/docs/generatePages/processKssSection.js
  packages/design-system-scripts/gulp/docs/generatePages/processMarkdownPage.js
  packages/design-system-scripts/gulp/docs/webpack/createWebpackConfig.js
  packages/design-system-scripts/gulp/docs/webpack/index.js
  packages/design-system-scripts/gulp/sass.js
  packages/design-system-scripts/jest/e2e.global-setup.js
Labels: Ready For Review

#748 [NO_TICKET] Misc beta updates
  cmsds.config.js
  lerna.json
  package.json
  packages/design-system-docs/.npmignore
  packages/design-system-docs/package.json
  packages/design-system-docs/src/scripts/components/Header.jsx
  packages/design-system-docs/src/scripts/components/Nav.jsx
  packages/design-system-docs/src/scripts/components/UsaBanner.jsx
  packages/design-system-scripts/.npmignore
  packages/design-system-scripts/cli.js
  packages/design-system-scripts/gulp/common/replaceTemplateTags.js
  packages/design-system-scripts/gulp/docs/docs.js
  packages/design-system-scripts/gulp/docs/generatePages/generateDocPage.js
  packages/design-system-scripts/gulp/docs/generatePages/generateHtmlExample.js
  packages/design-system-scripts/package.json
  packages/design-system/.npmignore
  packages/design-system/package.json
  prepublish.sh
  yarn.lock
Labels: Easy Review

#751 [NO_TICKET] Update dependencies version
  packages/design-system-docs/package.json
Labels: Easy Review

#749 [NO-TICKET] Update ARIA role prop to include `status`
  packages/design-system/src/components/Alert/Alert.jsx
Labels: Easy Review, Ready For Review

#750 [NO_TICKET] Misc beta changes
  package.json
  packages/design-system-docs/src/pages/components/Button/button.example.html
  packages/design-system-docs/src/styles/components/_details.scss
  packages/design-system-scripts/gulp/lint.js
  packages/design-system-scripts/package.json
  packages/design-system/src/styles/_font.scss
  packages/design-system/src/styles/index.scss
  packages/design-system/src/styles/settings/_index.scss
  yarn.lock
Labels: Ready For Review

#740 [WNMGDS-152] Child design system example
  examples/child-design-system/.gitignore
  examples/child-design-system/README.md
  examples/child-design-system/babel.config.js
  examples/child-design-system/cmsds.config.js
  examples/child-design-system/docs/src/example.scss
  examples/child-design-system/docs/src/index.scss
  examples/child-design-system/docs/src/pages/components/Button/Button.docs.scss
  examples/child-design-system/docs/src/pages/components/Button/Button.example.jsx
  examples/child-design-system/docs/src/pages/components/Button/button.example.html
  examples/child-design-system/docs/src/pages/components/Card/Card.docs.scss
  examples/child-design-system/docs/src/pages/components/Card/Card.example.jsx
  examples/child-design-system/docs/src/pages/components/Card/card.example.html
  examples/child-design-system/docs/src/pages/utilities/border-style/_border-style.docs.scss
  examples/child-design-system/docs/src/pages/utilities/border-style/border-style.example.html
  examples/child-design-system/eslintrc.js
  examples/child-design-system/package.json
  examples/child-design-system/src/components/Button/Button.jsx
  examples/child-design-system/src/components/Button/Button.test.jsx
  examples/child-design-system/src/components/Button/__snapshots__/Button.test.jsx.snap
  examples/child-design-system/src/components/Card/Card.e2e.test.js
  examples/child-design-system/src/components/Card/Card.jsx
  examples/child-design-system/src/components/Card/Card.test.jsx
  examples/child-design-system/src/components/index.js
  examples/child-design-system/src/fonts/Lato/Lato-Bold.ttf
  examples/child-design-system/src/fonts/Lato/Lato-Italic.ttf
  examples/child-design-system/src/fonts/Lato/Lato-Regular.ttf
  examples/child-design-system/src/fonts/Raleway/Raleway-Bold.ttf
  examples/child-design-system/src/fonts/Raleway/Raleway-Italic.ttf
  examples/child-design-system/src/fonts/Raleway/Raleway-Regular.ttf
  examples/child-design-system/src/fonts/Raleway/Raleway-SemiBold.ttf
  examples/child-design-system/src/setupTests.js
  examples/child-design-system/src/styles/base/_index.scss
  examples/child-design-system/src/styles/base/_override.body.scss
  examples/child-design-system/src/styles/base/_override.link.scss
  examples/child-design-system/src/styles/base/_override.typography.scss
  examples/child-design-system/src/styles/components/_Button.scss
  examples/child-design-system/src/styles/components/_Card.scss
  examples/child-design-system/src/styles/components/_index.scss
  examples/child-design-system/src/styles/index.scss
  examples/child-design-system/src/styles/settings/_font.scss
  examples/child-design-system/src/styles/settings/_index.scss
  examples/child-design-system/src/styles/settings/variables/_index.scss
  examples/child-design-system/src/styles/settings/variables/_override.build.scss
  examples/child-design-system/src/styles/settings/variables/_override.color.scss
  examples/child-design-system/src/styles/settings/variables/_override.forms.scss
  examples/child-design-system/src/styles/settings/variables/_override.type.scss
  examples/child-design-system/src/styles/utilities/_border-style.scss
  examples/child-design-system/src/styles/utilities/_index.scss
  examples/child-design-system/stylelintrc.js
  examples/child-design-system/tsconfig.js
Labels: Ready For Review

#756 [WNMGDS-566] Always compile to ESM and Common JS
  babel.config.js
  examples/child-design-system/README.md
  examples/child-design-system/babel.config.js
  examples/child-design-system/docs/src/pages/components/Button/button.example.html
  examples/child-design-system/package.json
  packages/design-system-scripts/gulp/build.js
  packages/design-system/src/styles/components/_Button.scss
Labels: Easy Review

#761 Test babel register
  packages/design-system-scripts/gulp/docs/generatePages/generatePages.js
Labels: Easy Review

#755 Add product/application info to migration page
  packages/design-system-docs/src/pages/startup/migrating-v2.md
Labels: Ready For Review
