Repository CMSgov/design-system, pull requests merged in 2020-06, with the labels that each got.

#712 [WNMGDS-459] Add red border to Dropdown with error message
  packages/design-system-docs/src/pages/components/Dropdown/Dropdown.example.jsx
  packages/design-system/src/components/Dropdown/Dropdown.jsx
  packages/design-system/src/components/Dropdown/Dropdown.test.jsx
Labels: Ready For Review

#711 [WNMGDS-456] Remove aria-labels from StepList list items
  packages/design-system-docs/src/pages/components/StepList/StepList.example.jsx
  packages/design-system/src/components/StepList/Step.jsx
  packages/design-system/src/components/StepList/StepList.jsx
Labels: In JIRA, Ready For Review

#707 [WNMGDS-455] Fix webpack tree shaking
  examples/react-app/Gulpfile.js
  examples/react-app/babel.config.js
  examples/react-app/package.json
  examples/react-app/src/scripts/index.js
  examples/react-app/src/styles/index.scss
  examples/react-app/webpack.config.js
  packages/design-system-docs/src/pages/startup/components.md
  packages/design-system-docs/src/pages/startup/react.md
  packages/design-system-scripts/gulp/build.js
  packages/design-system-scripts/gulp/common/copyAssets.js
  packages/design-system-scripts/gulp/common/copyDir.js
  packages/design-system-scripts/gulp/docs/docs.js
  packages/design-system-scripts/package.json
  packages/design-system-scripts/yarn.lock
  packages/design-system/README.md
  packages/design-system/package.json
  packages/design-system/src/components/index.js
  packages/design-system/src/index.js
Labels: Ready For Review

#713 [WNMGDS-457] Change HelpDrawerToggle to use inline instead of inline-block
  packages/design-system-docs/src/pages/utilities/display-visibility/_display-visibility.docs.scss
  packages/design-system-docs/src/pages/utilities/display-visibility/display.example.html
  packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.jsx
  packages/design-system/src/components/HelpDrawer/__snapshots__/HelpDrawerToggle.test.jsx.snap
  packages/design-system/src/styles/utilities/_display-visibility.scss
Labels: Ready For Review

#715 [NO TICKET] Update dist folder structure
  examples/react-app/src/styles/index.scss
  packages/design-system-docs/README.md
  packages/design-system-docs/src/example.scss
  packages/design-system-docs/src/index.scss
  packages/design-system-docs/src/pages/startup/components.md
  packages/design-system-docs/src/pages/startup/migrating-v2.md
  packages/design-system-docs/src/pages/startup/sass-and-css.md
  packages/design-system-docs/src/pages/startup/theming.md
  packages/design-system-scripts/gulp/build.js
  packages/design-system-scripts/gulp/sass.js
  packages/design-system-scripts/gulp/stats/stats.js
  packages/design-system-scripts/gulp/watch.js
  packages/design-system-scripts/jest/unit.config.js
  packages/design-system/README.md
  packages/design-system/package.json
  packages/design-system/src/components/__tests__/index.test.js
  packages/design-system/src/components/helpers/e2e/assertNoAxeViolations.js
  packages/design-system/src/components/index.js
  packages/design-system/src/index.js
  packages/design-system/src/index.scss
  packages/design-system/src/styles/index.scss
  yarn.lock
Labels: Ready For Review

#719 v2.0.0-beta.1
  examples/react-app/package.json
  packages/design-system-docs/.npmignore
  packages/design-system-docs/package.json
  packages/design-system-scripts/package.json
  packages/design-system-scripts/publish.sh
  packages/design-system/package.json
  yarn.lock
Labels: Easy Review, Ready For Review

#721 [WNMGDS-511] Fix lint scripts for Child DS
  .eslintrc.js
  .prettierrc.js
  .stylelintrc.js
  package.json
  packages/design-system-scripts/gulp/lint.js
  packages/design-system-scripts/package.json
  packages/design-system-scripts/yarn.lock
  packages/design-system/.npmignore
  packages/design-system/.stylelintrc.js
  packages/eslint-config-design-system/README.md
  packages/eslint-config-design-system/index.js
  packages/eslint-config-design-system/package.json
  packages/eslint-config-design-system/yarn.lock
  packages/stylelint-config-design-system/README.md
  packages/stylelint-config-design-system/index.js
  packages/stylelint-config-design-system/package.json
  packages/stylelint-config-design-system/yarn.lock
  yarn.lock
Labels: Ready For Review

#722 [NO_TICKET] Misc script bug fixes
  babel.config.js
  packages/design-system-scripts/gulp/build.js
  packages/design-system-scripts/gulp/docs/docs.js
  packages/design-system-scripts/gulp/docs/generatePages/generatePage.js
  packages/design-system-scripts/gulp/docs/generatePages/generatePages.js
  packages/design-system-scripts/gulp/docs/generatePages/generateReactExample.js
  packages/design-system-scripts/gulp/docs/webpack/createReactExampleWebpackConfig.js
  packages/design-system-scripts/jest/unit.config.js
  packages/design-system-scripts/package.json
  packages/design-system/src/styles/base/index.scss
  packages/design-system/src/styles/index.scss
  packages/design-system/src/styles/settings/_font.scss
  packages/design-system/src/styles/settings/_index.scss
  setupTests.js
  yarn.lock
Labels: Ready For Review

#726 [NO_TICKET] Fix icon paths and other misc SCSS updates
  packages/design-system-docs/src/index.scss
  packages/design-system-docs/src/pages/components/Button/button-icons.example.html
  packages/design-system-docs/src/pages/components/Tabs/tabs.example.html
  packages/design-system-docs/src/pages/styles/icons/interaction-icons.example.html
  packages/design-system-docs/src/pages/styles/icons/status-icons.example.html
  packages/design-system-docs/src/pages/styles/icons/supplemental-icons.example.html
  packages/design-system-docs/src/styles/components/_UsaBanner.scss
  packages/design-system-docs/src/styles/settings/_color.scss
  packages/design-system-docs/src/styles/settings/_index.scss
  packages/design-system-docs/src/styles/utilities/_colors.scss
  packages/design-system-docs/src/styles/utilities/_index.scss
Labels: Easy Review, Ready For Review

#725 [WNMGDS-507] Fix cannot read property 'checked' of null
  packages/design-system-docs/src/pages/components/ChoiceList/Choice.example.jsx
  packages/design-system/src/components/ChoiceList/Choice.jsx
Labels: Ready For Review
