Repository CMSgov/design-system, pull requests merged in 2020-01, with the labels that each got.

#585 [NO-TICKET] Fix inverse disabled link button styling
  packages/core/src/base/typography/link.scss
  packages/core/src/components/Button/Button.test.jsx
  packages/core/src/components/Button/__snapshots__/Button.test.jsx.snap
Labels: Easy Review, Ready For Review

#587 [WNMGDS-330] Remove USWDS dep
  examples/webpack-demo/src/style.scss
  packages/docs/src/pages/startup/site-package.md
  packages/support/package.json
  packages/support/src/settings/_index.scss
  packages/support/src/settings/_override.uswds.scss
  packages/support/src/settings/_variables.build.scss
  packages/support/src/settings/_variables.color.docs.scss
  packages/support/src/settings/_variables.color.scss
  packages/support/src/settings/_variables.forms.scss
  packages/support/src/settings/_variables.layout.docs.scss
  packages/support/src/settings/_variables.layout.scss
  packages/support/src/settings/_variables.shadow.scss
  packages/support/src/settings/_variables.type.scss
  packages/support/src/vendor/uswds/core/_variables.scss
  packages/support/yarn.lock
  tools/gulp/sass/index.js
Labels: Ready For Review

#593 [WNMGDS-343] Update dropdown to allow custom options
  packages/core/src/components/Dropdown/Dropdown.example.jsx
  packages/core/src/components/Dropdown/Dropdown.jsx
Labels: Ready For Review

#596 [WNMGDS-346] Use console warn and remove logs from production
  packages/core/src/components/Alert/Alert.jsx
  packages/core/src/components/Button/Button.jsx
  packages/core/src/components/ChoiceList/Choice.jsx
  packages/core/src/components/ChoiceList/Select.jsx
  packages/core/src/components/TextField/TextField.jsx
Labels: Ready For Review

#591 [WNMGDS-347] Fix ARIA label not being applied to Dropdown.
  packages/core/src/components/Dropdown/Dropdown.example.jsx
  packages/core/src/components/Dropdown/Dropdown.jsx
  packages/core/src/components/Dropdown/Dropdown.test.jsx
  packages/core/src/components/Dropdown/__snapshots__/Dropdown.test.jsx.snap
Labels: Accessibility, Ready For Review

#594 [WNMGDS-345] Improve USA Banner
  packages/docs/src/scripts/components/Header.jsx
  packages/docs/src/scripts/components/UsaBanner.jsx
  packages/docs/src/styles/components/_UsaBanner.scss
Labels: Ready For Review

#604 [WNMGDS-292] Support react router in <VerticalNav> and <StepList>
  packages/core/src/components/Button/Button.example.jsx
  packages/core/src/components/Button/Button.jsx
  packages/core/src/components/Button/__snapshots__/Button.test.jsx.snap
  packages/core/src/components/StepList/Step.jsx
  packages/core/src/components/StepList/StepLink.jsx
  packages/core/src/components/StepList/StepList.example.jsx
  packages/core/src/components/StepList/StepList.jsx
  packages/core/src/components/StepList/SubStep.jsx
  packages/core/src/components/StepList/_StepList.docs.scss
  packages/core/src/components/VerticalNav/VerticalNav.example.jsx
  packages/core/src/components/VerticalNav/VerticalNav.jsx
  packages/core/src/components/VerticalNav/VerticalNavItem.jsx
  packages/core/src/components/VerticalNav/VerticalNavItemLabel.jsx
Labels: Ready For Review

#602 [WNMGDS-353] Rename labelClassName prop in <FormLabel>
  packages/core/src/components/Button/Button.jsx
  packages/core/src/components/ChoiceList/Choice.jsx
  packages/core/src/components/ChoiceList/ChoiceList.jsx
  packages/core/src/components/Dropdown/Dropdown.jsx
  packages/core/src/components/FormLabel/FormLabel.jsx
  packages/core/src/components/MonthPicker/MonthPicker.jsx
  packages/core/src/components/MonthPicker/MonthPicker.test.jsx
  packages/core/src/components/MonthPicker/__snapshots__/MonthPicker.test.jsx.snap
  packages/core/src/components/TextField/TextField.jsx
Labels: Ready For Review

#614 Upgrade gulp to version 4.0.2
  package.json
  tools/gulp/build.js
  tools/gulp/docs/index.js
  tools/gulp/lint.js
  tools/gulp/sass/index.js
  tools/gulp/watch.js
  yarn.lock
Labels: Ready For Review

#610 Add hidden print utility class
  packages/core/src/utilities/display-visibility/_display-visibility.docs.scss
  packages/core/src/utilities/display-visibility/display-visibility.scss
  packages/core/src/utilities/display-visibility/visibility.example.html
Labels: Ready For Review
