Repository CMSgov/design-system, pull requests merged in 2020-02, with the labels that each got.

#573 [WNMGDS-325] Fix position sticky in IE11
  packages/core/src/components/HelpDrawer/HelpDrawer.jsx
  packages/core/src/components/HelpDrawer/HelpDrawer.scss
  packages/core/src/components/HelpDrawer/__snapshots__/HelpDrawer.test.jsx.snap
Labels: Bug, Help Wanted

#616 get gulp watch working
  tools/gulp/watch.js
Labels: Dependencies, Ready For Review

#615 Upgrade node/yarn
  .nvmrc
  .travis.yml
  package.json
  yarn.lock
Labels: Dependencies, Ready For Review

#510 [WNMGDS-256] Add focus styles across the DS
  packages/core/src/base/typography/link.scss
  packages/core/src/components/Autocomplete/Autocomplete.jsx
  packages/core/src/components/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
  packages/core/src/components/Button/Button.example.jsx
  packages/core/src/components/Button/Button.scss
  packages/core/src/components/Button/button.example.html
  packages/core/src/components/ChoiceList/Choice.scss
  packages/core/src/components/Dialog/Dialog.scss
  packages/core/src/components/Dropdown/Dropdown.scss
  packages/core/src/components/HelpDrawer/HelpDrawer.scss
  packages/core/src/components/SkipNav/SkipNav.scss
  packages/core/src/components/Tabs/Tabs.scss
  packages/core/src/components/TextField/TextField.scss
  packages/core/src/components/TextField/_TextField.docs.scss
  packages/core/src/components/VerticalNav/VerticalNav.scss
  packages/core/src/utilities/background-color/background-color.example.html
  packages/core/src/utilities/background-color/background-color.scss
  packages/core/src/utilities/text-color/text-color.scss
  packages/docs/src/scripts/components/Header.jsx
  packages/docs/src/styles/components/_Header.scss
  packages/support/src/settings/_variables.color.docs.scss
  packages/support/src/settings/_variables.color.scss
  packages/support/src/settings/_variables.forms.scss
  packages/support/src/settings/_variables.shadow.scss
  packages/support/src/tools/_index.scss
  packages/support/src/tools/_mixins.focus-text.scss
Labels: Accessibility, Design, Ready For Review

#618 [WNMGDS-365] - Update postcss-image-inliner
  package.json
  yarn.lock
Labels: Dependencies

#620 [WNMGDS-356] Update browser support page
  browserslist
  packages/docs/src/pages/startup/browser-support.md
Labels: Ready For Review

#627 [NO-TICKET] doc site update to usa flag path for header
  packages/docs/src/scripts/components/UsaBanner.jsx
Labels: Documentation Content, Ready For Review

#634 Fix gulp stats task
  package.json
  tools/gulp/stats/__tests__/getValues.test.js
  tools/gulp/stats/getValues.js
  tools/gulp/stats/stats.js
  yarn.lock
Labels: Ready For Review

#635 [WNMGDS-286] Remove deprecated items
  packages/core/src/components/Button/Button.jsx
  packages/core/src/components/ChoiceList/Choice.jsx
  packages/core/src/components/ChoiceList/Choice.test.jsx
  packages/core/src/components/ChoiceList/ChoiceList.jsx
  packages/core/src/components/ChoiceList/ChoiceList.test.jsx
  packages/core/src/components/ChoiceList/Select.jsx
  packages/core/src/components/ChoiceList/Select.test.jsx
  packages/core/src/components/ChoiceList/checkbox-radio-right-to-left.example.html
  packages/core/src/components/Dropdown/Dropdown.jsx
  packages/core/src/components/FormLabel/FormLabel.jsx
  packages/core/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
  packages/core/src/components/TextField/TextField.jsx
  packages/core/src/components/TextField/TextField.test.jsx
  packages/core/src/components/index.js
Labels: Ready For Review
