Repository CMSgov/design-system, pull requests merged in 2020-09, with the labels that each got.

#795 [WNMGDS-487] Add aria-label to FormLabel label and ChoiceList legend
  packages/design-system/src/components/ChoiceList/ChoiceList.jsx
  packages/design-system/src/components/FormLabel/FormLabel.jsx
  packages/design-system/src/components/FormLabel/FormLabel.test.jsx
  packages/design-system/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
  packages/design-system/src/types/FormLabel/FormLabel.d.ts
Labels: Ready For Review

#709 [WNMGDS-453] - Make components more responsive when resizing
  design-assets/CMS-Design-System-UI-kit.sketch
  design-assets/cms-design-system-ui-kit.xml
Labels: Design, Ready For Review

#798 [WNMGDS-543] Allow markdown in typescript documentation
  packages/design-system-scripts/gulp/docs/extractReactData/parseReactFile.js
  packages/design-system-scripts/gulp/docs/extractReactData/reactDocgenHandler.js
Labels: Ready For Review

#796 [WNMGDS-558] Followup table layout changes
  lerna.json
  packages/design-system-docs/src/pages/components/Table/Table.example.jsx
  packages/design-system-docs/src/pages/components/Table/_Table.docs.scss
  packages/design-system-docs/src/pages/components/Table/table-complex.example.html
  packages/design-system-docs/src/scripts/components/ReactPropDoc.jsx
  packages/design-system-docs/src/scripts/components/ReactPropDocs.jsx
  packages/design-system/src/components/Table/Table.jsx
  packages/design-system/src/components/Table/Table.test.jsx
  packages/design-system/src/components/Table/TableBody.jsx
  packages/design-system/src/components/Table/TableBody.test.jsx
  packages/design-system/src/components/Table/TableCaption.jsx
  packages/design-system/src/components/Table/TableCaption.test.jsx
  packages/design-system/src/components/Table/TableCell.jsx
  packages/design-system/src/components/Table/TableCell.test.jsx
  packages/design-system/src/components/Table/TableDataCell.jsx
  packages/design-system/src/components/Table/TableDataCell.test.jsx
  packages/design-system/src/components/Table/TableHead.jsx
  packages/design-system/src/components/Table/TableHead.test.jsx
  packages/design-system/src/components/Table/TableHeaderCell.jsx
  packages/design-system/src/components/Table/TableHeaderCell.test.jsx
  packages/design-system/src/components/Table/TableRow.jsx
  packages/design-system/src/components/Table/TableRow.test.jsx
  packages/design-system/src/components/Table/__snapshots__/Table.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableBody.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableCaption.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableCell.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableHead.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableRow.test.jsx.snap
  packages/design-system/src/components/index.js
  packages/design-system/src/styles/components/_Table.scss
  packages/design-system/src/types/Table/Table.d.ts
  packages/design-system/src/types/Table/TableBody.d.ts
  packages/design-system/src/types/Table/TableCell.d.ts
  packages/design-system/src/types/Table/TableContext.d.ts
  packages/design-system/src/types/Table/TableDataCell.d.ts
  packages/design-system/src/types/Table/TableHead.d.ts
  packages/design-system/src/types/Table/TableHeaderCell.d.ts
  packages/design-system/src/types/Table/TableRow.d.ts
  packages/design-system/src/types/index.d.ts
Labels: Ready For Review

#800 [NO-TICKET] Remove Initialize parameter from tsc definition
  packages/design-system/src/types/MonthPicker/MonthPicker.d.ts
Labels: Easy Review

#799 [WNMGDS-593] Document disabled choices
  packages/design-system-docs/src/pages/components/ChoiceList/Choice.example.jsx
  packages/design-system-docs/src/pages/components/ChoiceList/ChoiceList.example.jsx
  packages/design-system-docs/src/pages/components/ChoiceList/checkbox-radio.example.html
  packages/design-system-scripts/gulp/docs/extractReactData/reactDocgenHandler.js
  packages/design-system/src/components/ChoiceList/Choice.jsx
  packages/design-system/src/components/ChoiceList/Choice.test.jsx
  packages/design-system/src/components/ChoiceList/ChoiceList.jsx
  packages/design-system/src/components/MonthPicker/MonthPicker.jsx
  packages/design-system/src/components/MonthPicker/MonthPicker.test.jsx
  packages/design-system/src/components/StepList/Step.jsx
  packages/design-system/src/components/StepList/StepList.jsx
  packages/design-system/src/components/VerticalNav/VerticalNav.jsx
  packages/design-system/src/types/ChoiceList/Choice.d.ts
  packages/design-system/src/types/ChoiceList/ChoiceList.d.ts
  packages/design-system/src/types/StepList/StepList.d.ts
  packages/design-system/src/types/VerticalNav/VerticalNav.d.ts
Labels: Ready For Review

#801 [NO_TICKET] Remove .d.ts from imports
  packages/design-system/src/types/ChoiceList/ChoiceList.d.ts
  packages/design-system/src/types/StepList/StepList.d.ts
  packages/design-system/src/types/VerticalNav/VerticalNav.d.ts
  packages/design-system/src/types/index.d.ts
Labels: Easy Review

#802 [NO-TICKET] Backstop updates for v2.0.2
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Alert_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Autocomplete_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Badge_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Button_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_ChoiceList_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_ChoiceList_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_ChoiceList_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_Default_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_React_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_React_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_React_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_-_React_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_-_React_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Dropdown_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Form_label__legend_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Masked_Field_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Modal_Dialog_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Skipnav_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Spinner_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_-_Complex_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_-_Complex_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_-_Complex_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_-_React_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_-_React_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_-_React_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Table_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Tabs_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Textfield_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Vertical_Navigation_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Patterns_-_External_Link_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Patterns_-_Review_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Patterns_-_Step_List_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Patterns_-_Step_List_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Patterns_-_Step_List_0_document_2_desktop.png
Labels: Easy Review

#806 [NO_TICKET] Hotfix Choice definition
  packages/design-system/src/types/ChoiceList/Choice.d.ts
Labels: Ready For Review

#814 [WNMGDS-616] Fix disabled choice style bug
  packages/design-system/src/styles/components/_Choice.scss
Labels: Ready For Review

#805 [WNMGDS-611] Generically copy src files
  packages/design-system-scripts/gulp/build.js
Labels: Ready For Review

#816 [WNMGDS-630] Update USA banner
  packages/design-system-docs/src/images/icon-lock.svg
  packages/design-system-docs/src/scripts/components/UsaBanner.jsx
  packages/design-system-docs/src/styles/components/_UsaBanner.scss
Labels: Ready For Review

#813 [WNMGDS-622] Update inverse examples
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Button_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Button_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_ChoiceList_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_ChoiceList_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_ChoiceList_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_Default_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_-_Default_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_-_React_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_-_React_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_-_React_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Dropdown_-_Default_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Dropdown_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Dropdown_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Dropdown_-_React_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Dropdown_-_React_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Dropdown_-_React_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Form_label__legend_-_Default_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Form_label__legend_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Form_label__legend_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Form_label__legend_-_React_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Form_label__legend_-_React_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Form_label__legend_-_React_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Masked_Field_-_React_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Masked_Field_-_React_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Masked_Field_-_React_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_-_React_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_-_React_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_-_React_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Textfield_-_Default_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Textfield_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Textfield_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Textfield_-_React_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Textfield_-_React_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Textfield_-_React_0_document_2_desktop.png
  packages/design-system-docs/src/pages/components/Button/button.example.html
  packages/design-system-docs/src/pages/components/ChoiceList/ChoiceList.example.jsx
  packages/design-system-docs/src/pages/components/ChoiceList/checkbox-radio.example.html
  packages/design-system-docs/src/pages/components/DateField/DateField.example.jsx
  packages/design-system-docs/src/pages/components/DateField/datefield.example.html
  packages/design-system-docs/src/pages/components/Dropdown/Dropdown.example.jsx
  packages/design-system-docs/src/pages/components/Dropdown/dropdown.example.html
  packages/design-system-docs/src/pages/components/FormLabel/FormLabel.example.jsx
  packages/design-system-docs/src/pages/components/FormLabel/form-label.example.html
  packages/design-system-docs/src/pages/components/MonthPicker/MonthPicker.example.jsx
  packages/design-system-docs/src/pages/components/TextField/Mask.example.jsx
  packages/design-system-docs/src/pages/components/TextField/TextField.example.jsx
  packages/design-system-docs/src/pages/components/TextField/textfield.example.html
  packages/design-system-docs/src/styles/components/_example.scss
  packages/design-system/src/components/ChoiceList/Choice.e2e.test.js
  packages/design-system/src/components/Dropdown/Dropdown.jsx
Labels: Ready For Review

#819 [NO-TICKET] Backstop updates for v2.0.4
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_ChoiceList_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_-_Default_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_-_Default_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Dropdown_-_React_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Dropdown_-_React_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Dropdown_-_React_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Form_label__legend_-_Default_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_-_React_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_-_React_0_document_1_tablet.png
Labels: Easy Review

#825 [WNMGDS-615] Set inverse choice bg to transparent
  packages/design-system/src/styles/components/_Choice.scss
Labels: Ready For Review

#821 [WNMGDS-524] Fix eslint logging and run linter
  examples/create-react-app/src/components/App.test.js
  lerna.json
  package.json
  packages/design-system-docs/src/pages/components/Badge/Badge.example.jsx
  packages/design-system-docs/src/pages/components/Button/Button.example.jsx
  packages/design-system-docs/src/scripts/components/ReactExample.jsx
  packages/design-system-scripts/cli.js
  packages/design-system-scripts/gulp/docs/generatePages/markdownRenderer.js
  packages/design-system-scripts/gulp/docs/generatePages/savePage.js
  packages/design-system-scripts/gulp/lint.js
  packages/design-system/src/types/ChoiceList/ChoiceList.d.ts
Labels: Ready For Review

#534 [WNMGDS-230] Add Tooltip component
  babel.config.js
  packages/design-system-docs/src/pages/components/Tooltip/Tooltip.example.jsx
  packages/design-system-docs/src/pages/components/Tooltip/TooltipIcon.example.jsx
  packages/design-system-docs/src/pages/components/Tooltip/_Tooltip.docs.scss
  packages/design-system-scripts/gulp/docs/webpack/createWebpackConfig.js
  packages/design-system/package.json
  packages/design-system/src/components/Tooltip/Tooltip.e2e.test.js
  packages/design-system/src/components/Tooltip/Tooltip.jsx
  packages/design-system/src/components/Tooltip/Tooltip.test.jsx
  packages/design-system/src/components/Tooltip/TooltipIcon.jsx
  packages/design-system/src/components/Tooltip/TooltipIcon.test.jsx
  packages/design-system/src/components/Tooltip/__snapshots__/Tooltip.test.jsx.snap
  packages/design-system/src/components/Tooltip/__snapshots__/TooltipIcon.test.jsx.snap
  packages/design-system/src/components/index.js
  packages/design-system/src/styles/components/_Tooltip.scss
  packages/design-system/src/styles/components/_TooltipIcon.scss
  packages/design-system/src/styles/components/index.scss
  packages/design-system/yarn.lock
  yarn.lock
Labels: Component, Ready For Review

#828 Fix Tooltips with React versions < 16.6
  .travis.yml
  package.json
  packages/design-system-scripts/package.json
  packages/design-system/package.json
  packages/design-system/src/components/Tooltip/Tooltip.jsx
  yarn.lock
Labels: Ready For Review

#810 [WNMGDS-529] Error styling on radio button and checkbox options
  packages/design-system-docs/src/pages/components/ChoiceList/ChoiceList.example.jsx
  packages/design-system-docs/src/pages/components/ChoiceList/checkbox-radio.example.html
  packages/design-system-docs/src/pages/components/TextField/textfield.example.html
  packages/design-system/src/components/ChoiceList/Choice.test.jsx
  packages/design-system/src/components/ChoiceList/ChoiceList.jsx
  packages/design-system/src/styles/components/_Choice.scss
Labels: Ready For Review

#823 [WNMGDS-637] Update release process guide
  README.md
  guides/RELEASE-PROCESS.md
  package.json
  prerelease.sh
Labels: Ready For Review

#826 [WNMGDS-478] Add USWDS to build scripts
  packages/design-system-scripts/gulp/build.js
  packages/design-system-scripts/gulp/sass.js
  packages/design-system-scripts/gulp/stats/stats.js
  packages/design-system-scripts/gulp/watch.js
  packages/design-system-scripts/package.json
  packages/design-system/package.json
  packages/design-system/src/components/Tooltip/Tooltip.jsx
  packages/design-system/src/styles/index.scss
  packages/design-system/src/styles/settings/_index.scss
  packages/design-system/src/styles/settings/uswds/_index.scss
  packages/design-system/src/styles/settings/uswds/_uswds-theme-color.scss
  packages/design-system/src/styles/settings/uswds/_uswds-theme-components.scss
  packages/design-system/src/styles/settings/uswds/_uswds-theme-general.scss
  packages/design-system/src/styles/settings/uswds/_uswds-theme-spacing.scss
  packages/design-system/src/styles/settings/uswds/_uswds-theme-typography.scss
  packages/design-system/src/styles/settings/uswds/_uswds-theme-utilities.scss
  yarn.lock
Labels: Ready For Review

#827 [WNMGDS-596] Improve choice variables and unrevert the checkmark change
  packages/design-system-docs/src/pages/components/ChoiceList/_ChoiceList.docs.scss
  packages/design-system-docs/src/pages/styles/icons/_icons.docs.scss
  packages/design-system/src/styles/components/_Choice.scss
  packages/design-system/src/styles/settings/variables/_build.scss
  packages/design-system/src/styles/settings/variables/_forms.scss
Labels: Ready For Review
