Repository CMSgov/design-system, pull requests merged in 2021-03, with the labels that each got.

#953 [NO_TICKET] Reorganize exports
  packages/design-system/src/components/Alert/index.js
  packages/design-system/src/components/Autocomplete/index.js
  packages/design-system/src/components/Badge/index.js
  packages/design-system/src/components/Button/index.js
  packages/design-system/src/components/ChoiceList/index.js
  packages/design-system/src/components/DateField/index.js
  packages/design-system/src/components/Dialog/index.js
  packages/design-system/src/components/Dropdown/index.js
  packages/design-system/src/components/FormControl/FormControl.tsx
  packages/design-system/src/components/FormLabel/index.js
  packages/design-system/src/components/HelpDrawer/index.js
  packages/design-system/src/components/MonthPicker/MonthPicker.jsx
  packages/design-system/src/components/MonthPicker/getMonthNames.js
  packages/design-system/src/components/MonthPicker/index.js
  packages/design-system/src/components/Review/index.js
  packages/design-system/src/components/SkipNav/index.js
  packages/design-system/src/components/Spinner/index.js
  packages/design-system/src/components/StepList/index.js
  packages/design-system/src/components/Table/index.js
  packages/design-system/src/components/Tabs/index.js
  packages/design-system/src/components/TextField/Mask.jsx
  packages/design-system/src/components/TextField/Mask.test.jsx
  packages/design-system/src/components/TextField/TextField.jsx
  packages/design-system/src/components/TextField/index.js
  packages/design-system/src/components/TextField/maskHelpers.js
  packages/design-system/src/components/TextField/maskHelpers.test.js
  packages/design-system/src/components/Tooltip/index.js
  packages/design-system/src/components/UsaBanner/index.js
  packages/design-system/src/components/VerticalNav/index.js
  packages/design-system/src/components/__tests__/index.test.js
  packages/design-system/src/components/index.js
Labels: Easy Review

#952 [WNMGDS-819] Allow doc site to use the feature flag
  examples/child-design-system/docs/src/pages/components/Button/Button.example.jsx
  examples/child-design-system/docs/src/pages/components/Card/Card.example.jsx
  examples/child-design-system/tsconfig.json
  packages/design-system-docs/src/pages/components/Alert/Alert.example.jsx
  packages/design-system-docs/src/pages/components/Autocomplete/Autocomplete.example.jsx
  packages/design-system-docs/src/pages/components/Badge/Badge.example.jsx
  packages/design-system-docs/src/pages/components/Button/Button.example.jsx
  packages/design-system-docs/src/pages/components/ChoiceList/Choice.example.jsx
  packages/design-system-docs/src/pages/components/ChoiceList/ChoiceList.example.jsx
  packages/design-system-docs/src/pages/components/DateField/DateField.example.jsx
  packages/design-system-docs/src/pages/components/Dialog/Dialog.example.jsx
  packages/design-system-docs/src/pages/components/Dialog/ThirdPartyLink.example.jsx
  packages/design-system-docs/src/pages/components/Dropdown/Dropdown.example.jsx
  packages/design-system-docs/src/pages/components/FormLabel/FormLabel.example.jsx
  packages/design-system-docs/src/pages/components/HelpDrawer/HelpDrawer.example.jsx
  packages/design-system-docs/src/pages/components/MonthPicker/MonthPicker.example.jsx
  packages/design-system-docs/src/pages/components/Review/Review.example.jsx
  packages/design-system-docs/src/pages/components/SkipNav/SkipNav.example.jsx
  packages/design-system-docs/src/pages/components/Spinner/Spinner.example.jsx
  packages/design-system-docs/src/pages/components/StepList/StepList.example.jsx
  packages/design-system-docs/src/pages/components/Table/Table.example.jsx
  packages/design-system-docs/src/pages/components/Tabs/Tab.example.jsx
  packages/design-system-docs/src/pages/components/Tabs/Tabs.example.jsx
  packages/design-system-docs/src/pages/components/TextField/Mask.example.jsx
  packages/design-system-docs/src/pages/components/TextField/TextField.example.jsx
  packages/design-system-docs/src/pages/components/Tooltip/Tooltip.example.jsx
  packages/design-system-docs/src/pages/components/Tooltip/TooltipIcon.example.jsx
  packages/design-system-docs/src/pages/components/VerticalNav/VerticalNav.example.jsx
  packages/design-system-scripts/gulp/docs/webpack/createReactExampleWebpackConfig.js
  packages/design-system/src/components/Autocomplete/Autocomplete.jsx
  packages/design-system/src/styles/components/_Autocomplete.scss
  tsconfig.json
Labels: Ready For Review

#946 [WNMGDS-753] Update styles for focus buttons
  packages/design-system/src/styles/components/_Button.scss
Labels: Ready For Review

#947 [WNMGDS-811] Tooltip updates
  packages/design-system-docs/src/pages/components/Tooltip/Tooltip.example.jsx
  packages/design-system/src/components/Tooltip/Tooltip.jsx
  packages/design-system/src/components/Tooltip/__snapshots__/Tooltip.test.jsx.snap
  packages/design-system/src/styles/components/_Tooltip.scss
  packages/design-system/src/styles/components/_TooltipIcon.scss
Labels: Ready For Review

#959 [NO_TICKET] Export form components
  packages/design-system/src/components/Dropdown/Select.jsx
  packages/design-system/src/components/Dropdown/index.js
  packages/design-system/src/components/FormControl/FormControl.tsx
  packages/design-system/src/components/FormControl/index.js
  packages/design-system/src/components/InlineError/InlineError.tsx
  packages/design-system/src/components/InlineError/index.js
  packages/design-system/src/components/TextField/TextInput.jsx
  packages/design-system/src/components/TextField/index.js
  packages/design-system/src/components/__tests__/index.test.js
  packages/design-system/src/components/index.js
Labels: Ready For Review

#958 [NO-TICKET] Backstop updates for v2.4.1
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Button_-_Default_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Button_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Button_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Checkbox__Radio_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Datefield_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Dropdown_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_-_Default_0_document_1_tablet.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Help_drawer_-_Default_0_document_2_desktop.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Masked_Field_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Month_Picker_0_document_0_phone.png
  packages/design-system-docs/src/__tests__/backstop_reference/backstop_default_CMSDS_-_Components_-_Textfield_0_document_0_phone.png
Labels: Ready For Review

#960 Release 2.4.1
  lerna.json
  packages/design-system-docs/package.json
  packages/design-system-scripts/package.json
  packages/design-system/package.json
Labels: Ready For Review

#973 [NO-TICKET] Update chromedriver to v89.0.0
  packages/design-system-scripts/package.json
  yarn.lock
Labels: Easy Review

#972 [WNMGDS-44] Disable firefox styles for :invalid pseudo-class
  packages/design-system/src/styles/components/_TextField.scss
Labels: Ready For Review

#970 [WNMGDS-829] Fix docs site nav url
  packages/design-system-docs/src/scripts/components/Nav.jsx
  packages/design-system/src/styles/components/_UsaBanner.scss
Labels: Ready For Review

#975 [WNMGDS-823] Update build release files
  packages/design-system/package.json
  prerelease.sh
Labels: Ready For Review

#971 [WNMGDS-816] Improve tooltip trigger customization
  .eslintrc.js
  packages/design-system-docs/src/pages/components/Tooltip/Tooltip.example.jsx
  packages/design-system/src/components/FormControl/FormControl.test.jsx
  packages/design-system/src/components/FormControl/FormControl.tsx
  packages/design-system/src/components/FormControl/__snapshots__/FormControl.test.jsx.snap
  packages/design-system/src/components/Tooltip/Tooltip.jsx
  packages/design-system/src/components/Tooltip/Tooltip.test.jsx
  packages/design-system/src/components/Tooltip/__snapshots__/Tooltip.test.jsx.snap
  packages/design-system/src/styles/components/_Tooltip.scss
  packages/design-system/src/types/Tooltip/Tooltip.d.ts
Labels: Ready For Review

#977 [WNMGDS-853] Generate proptypes automatically
  babel.config.js
  packages/design-system-scripts/gulp/docs/extractReactData/index.js
  packages/design-system-scripts/package.json
  packages/design-system/src/components/FormControl/FormControl.tsx
  packages/design-system/src/components/InlineError/InlineError.tsx
  yarn.lock
Labels: Ready For Review

#978 [WNMGDS-854] Fix IE 11 'forEach' error
  packages/design-system-docs/src/example.js
Labels: Ready For Review

#980 [WNMGDS-764] Remove line on last review item
  packages/design-system-docs/src/pages/components/Review/Review.example.jsx
  packages/design-system/src/styles/components/_Review.scss
Labels: Ready For Review

#983 [NO-TICKET] Update tooltip variable names and documentation
  packages/design-system-docs/src/pages/components/Tooltip/_Tooltip.docs.scss
  packages/design-system/src/styles/components/_Tooltip.scss
  packages/design-system/src/styles/components/_TooltipIcon.scss
Labels: Easy Review, Ready For Review

#982 [WNMGDS-850] Fix tooltip trigger link styles
  packages/design-system-docs/src/pages/components/Tooltip/Tooltip.example.jsx
  packages/design-system-docs/src/pages/components/Tooltip/_Tooltip.docs.scss
  packages/design-system/src/styles/base/_link.scss
  packages/design-system/src/styles/components/_Tooltip.scss
  packages/design-system/src/styles/components/_TooltipIcon.scss
Labels: Ready For Review

#981 [WNMGDS-719] Update Dialog to expose 'AriaModal' props
  packages/design-system-docs/src/pages/components/Dialog/_Dialog.docs.scss
  packages/design-system/src/components/Dialog/Dialog.jsx
  packages/design-system/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
  packages/design-system/src/types/Dialog/Dialog.d.ts
Labels: Ready For Review

#979 [WNMGDS-826] - Improve tooltipby fixing invalid HTML of unallowed elements in Span
  packages/design-system/src/components/Tooltip/Tooltip.jsx
  packages/design-system/src/components/Tooltip/__snapshots__/Tooltip.test.jsx.snap
  packages/design-system/src/styles/components/_Tooltip.scss
Labels: Ready For Review

#964 [WNMGDS-41] Create draft accordion component
  backstop.json
  packages/design-system-docs/src/pages/components/Accordion/Accordion.example.jsx
  packages/design-system-docs/src/pages/components/Accordion/_Accordion.docs.scss
  packages/design-system-docs/src/pages/components/Accordion/accordion.example.html
  packages/design-system/src/components/Accordion/Accordion.test.tsx
  packages/design-system/src/components/Accordion/Accordion.tsx
  packages/design-system/src/components/Accordion/AccordionItem.test.tsx
  packages/design-system/src/components/Accordion/AccordionItem.tsx
  packages/design-system/src/components/Accordion/__snapshots__/AccordionItem.test.tsx.snap
  packages/design-system/src/components/Accordion/index.js
  packages/design-system/src/components/index.js
  packages/design-system/src/images/add.svg
  packages/design-system/src/images/remove.svg
  packages/design-system/src/styles/components/_Accordion.scss
  packages/design-system/src/styles/components/index.scss
Labels: Ready For Review

#985 [WNMGDS-602] Change close button prop name in Dialog component
  packages/design-system/src/components/Dialog/Dialog.jsx
  packages/design-system/src/components/Dialog/Dialog.test.jsx
  packages/design-system/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
  packages/design-system/src/types/Dialog/Dialog.d.ts
Labels: Ready For Review

#990 [WNMGDS-830] Update icon for success alert
  packages/design-system-docs/src/pages/components/Alert/_Alert.docs.scss
  packages/design-system/src/styles/components/_Alert.scss
Labels: Ready For Review
