Repository CMSgov/design-system, pull requests merged in 2021-02, with the labels that each got.

#914 [WNMGDS-564] Allow bottom placement error messages
  packages/design-system/src/components/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
  packages/design-system/src/components/ChoiceList/ChoiceList.jsx
  packages/design-system/src/components/ChoiceList/__snapshots__/ChoiceList.test.jsx.snap
  packages/design-system/src/components/DateField/DateField.jsx
  packages/design-system/src/components/DateField/DateInput.jsx
  packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
  packages/design-system/src/components/DateField/__snapshots__/DateInput.test.jsx.snap
  packages/design-system/src/components/Dropdown/Dropdown.jsx
  packages/design-system/src/components/Dropdown/Select.jsx
  packages/design-system/src/components/FieldContainer/FieldContainer.test.tsx
  packages/design-system/src/components/FieldContainer/FieldContainer.tsx
  packages/design-system/src/components/FieldContainer/InlineError.test.tsx
  packages/design-system/src/components/FieldContainer/InlineError.tsx
  packages/design-system/src/components/FieldContainer/__snapshots__/FieldContainer.test.tsx.snap
  packages/design-system/src/components/FieldContainer/__snapshots__/InlineError.test.tsx.snap
  packages/design-system/src/components/FormLabel/FormLabel.jsx
  packages/design-system/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
  packages/design-system/src/components/MonthPicker/MonthPicker.jsx
  packages/design-system/src/components/MonthPicker/__snapshots__/MonthPicker.test.jsx.snap
  packages/design-system/src/components/TextField/TextField.jsx
  packages/design-system/src/components/TextField/TextInput.jsx
  packages/design-system/src/components/TextField/__snapshots__/TextField.test.jsx.snap
Labels: Ready For Review

#922 [WNMGDS-686] Use aria-invalid attribute in form components
  .eslintrc.js
  packages/design-system/src/components/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
  packages/design-system/src/components/DateField/DateField.jsx
  packages/design-system/src/components/DateField/DateInput.jsx
  packages/design-system/src/components/DateField/__snapshots__/DateInput.test.jsx.snap
  packages/design-system/src/components/Dropdown/Dropdown.jsx
  packages/design-system/src/components/Dropdown/Select.jsx
  packages/design-system/src/components/Dropdown/Select.test.jsx
  packages/design-system/src/components/Dropdown/__snapshots__/Select.test.jsx.snap
  packages/design-system/src/components/FieldContainer/FieldContainer.test.tsx
  packages/design-system/src/components/FieldContainer/FieldContainer.tsx
  packages/design-system/src/components/FieldContainer/InlineError.tsx
  packages/design-system/src/components/FieldContainer/__snapshots__/FieldContainer.test.tsx.snap
  packages/design-system/src/components/FormLabel/FormLabel.jsx
  packages/design-system/src/components/FormLabel/FormLabel.test.jsx
  packages/design-system/src/components/TextField/TextField.jsx
  packages/design-system/src/components/TextField/TextInput.jsx
  packages/design-system/src/components/TextField/TextInput.test.jsx
  packages/design-system/src/components/TextField/__snapshots__/TextInput.test.jsx.snap
  tsconfig.json
Labels: Ready For Review

#919 [WNMGDS-731] Update responsive stacked table
  packages/design-system-docs/src/pages/components/Table/_Table.docs.scss
  packages/design-system/src/components/Table/Table.test.jsx
  packages/design-system/src/components/Table/TableCell.jsx
  packages/design-system/src/components/Table/__snapshots__/Table.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableCell.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableHead.test.jsx.snap
  packages/design-system/src/styles/components/_Table.scss
Labels: Ready For Review

#927 [WNMGDS-781] Rename dense table
  packages/design-system-docs/src/pages/components/Table/_Table.docs.scss
  packages/design-system-docs/src/pages/components/Table/table.example.html
  packages/design-system/src/components/Table/Table.jsx
  packages/design-system/src/components/Table/Table.test.jsx
  packages/design-system/src/styles/components/_Table.scss
  packages/design-system/src/types/Table/Table.d.ts
Labels: Ready For Review

#932 [WNMGDS-766] Handle bottom placed error in Autocomplete
  packages/design-system-docs/src/pages/components/Autocomplete/Autocomplete.example.jsx
  packages/design-system/src/components/Autocomplete/Autocomplete.jsx
  packages/design-system/src/styles/components/_Autocomplete.scss
Labels: Ready For Review

#937 [WNMGDS-801] Fix rootPath on docs site
  packages/design-system-scripts/cli.js
Labels: Ready For Review

#938 [NO_TICKET] Update release notes to reference CB Core
  guides/RELEASE-PROCESS.md
Labels: Easy Review

#939 [NO_TICKET] Allow react-docgen-typescript to find tsconfig.json with path.resolve
  packages/design-system-scripts/gulp/docs/extractReactData/parseReactFile.js
  packages/design-system-scripts/gulp/docs/webpack/createWebpackConfig.js
Labels: Easy Review

#934 [WNMGDS-751] Create react feature flags
  packages/design-system-scripts/gulp/docs/webpack/createReactExampleWebpackConfig.js
  packages/design-system/src/components/ChoiceList/ChoiceList.jsx
  packages/design-system/src/components/ChoiceList/__snapshots__/ChoiceList.test.jsx.snap
  packages/design-system/src/components/DateField/DateField.jsx
  packages/design-system/src/components/DateField/__snapshots__/DateInput.test.jsx.snap
  packages/design-system/src/components/Dropdown/Dropdown.jsx
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.jsx.snap
  packages/design-system/src/components/Dropdown/__snapshots__/Select.test.jsx.snap
  packages/design-system/src/components/FieldContainer/FieldContainer.tsx
  packages/design-system/src/components/MonthPicker/MonthPicker.jsx
  packages/design-system/src/components/TextField/TextField.jsx
  packages/design-system/src/components/TextField/__snapshots__/TextField.test.jsx.snap
  packages/design-system/src/components/flags.js
  packages/design-system/src/components/index.js
Labels: Ready For Review

#940 [NO_TICKET] Remove console.log
  packages/design-system/src/components/FieldContainer/FieldContainer.tsx
Labels: Easy Review

#929 [WNMGDS-795] Reorganize and rename form components
  packages/design-system/src/components/ChoiceList/ChoiceList.jsx
  packages/design-system/src/components/ChoiceList/ChoiceList.test.jsx
  packages/design-system/src/components/ChoiceList/__snapshots__/ChoiceList.test.jsx.snap
  packages/design-system/src/components/DateField/DateField.jsx
  packages/design-system/src/components/Dropdown/Dropdown.jsx
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.jsx.snap
  packages/design-system/src/components/Dropdown/__snapshots__/Select.test.jsx.snap
  packages/design-system/src/components/FormControl/FormControl.test.tsx
  packages/design-system/src/components/FormControl/FormControl.tsx
  packages/design-system/src/components/FormControl/__snapshots__/FormControl.test.tsx.snap
  packages/design-system/src/components/FormLabel/FormLabel.jsx
  packages/design-system/src/components/InlineError/InlineError.test.tsx
  packages/design-system/src/components/InlineError/InlineError.tsx
  packages/design-system/src/components/InlineError/__snapshots__/InlineError.test.tsx.snap
  packages/design-system/src/components/MonthPicker/MonthPicker.jsx
  packages/design-system/src/components/MonthPicker/MonthPicker.test.jsx
  packages/design-system/src/components/TextField/TextField.jsx
  packages/design-system/src/components/TextField/__snapshots__/TextField.test.jsx.snap
  packages/design-system/src/components/__tests__/index.test.js
Labels: Ready For Review

#941 [NO-TICKET] Direct import of lodash
  packages/design-system/src/components/ChoiceList/ChoiceList.jsx
  packages/design-system/src/components/ChoiceList/__snapshots__/ChoiceList.test.jsx.snap
  packages/design-system/src/components/DateField/DateField.jsx
  packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
  packages/design-system/src/components/Dropdown/Dropdown.jsx
  packages/design-system/src/components/FieldContainer/FieldContainer.tsx
  packages/design-system/src/components/MonthPicker/MonthPicker.jsx
  packages/design-system/src/components/MonthPicker/__snapshots__/MonthPicker.test.jsx.snap
  packages/design-system/src/components/TextField/TextField.jsx
Labels: Easy Review, Ready For Review

#943 [NO-TICKET] Code format changes by eslint
  lerna.json
  packages/design-system/src/components/FieldContainer/FieldContainer.tsx
Labels: Easy Review

#945 Release 2.4.0
  lerna.json
  packages/design-system-docs/package.json
  packages/design-system-scripts/package.json
  packages/design-system/package.json
Labels: Ready For Review

#951 [WNMGDS-817] Remove unnecessary aria-describedby
  packages/design-system/src/components/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
  packages/design-system/src/components/Button/Button.test.jsx
  packages/design-system/src/components/Dropdown/Select.jsx
  packages/design-system/src/components/Dropdown/__snapshots__/Select.test.jsx.snap
  packages/design-system/src/components/TextField/TextInput.jsx
  packages/design-system/src/components/TextField/__snapshots__/TextInput.test.jsx.snap
Labels: Easy Review

#948 [NO-TICKET] Move governance doc into confluence
  guides/GOVERNANCE.md
Labels: Easy Review, Ready For Review

#935 [WNMGDS-810] Update stacked table for screen reader
  packages/design-system-docs/src/pages/components/Table/Table.example.jsx
  packages/design-system/src/components/Table/TableBody.jsx
  packages/design-system/src/components/Table/TableHead.jsx
  packages/design-system/src/components/Table/__snapshots__/TableBody.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableCell.test.jsx.snap
  packages/design-system/src/components/Table/__snapshots__/TableHead.test.jsx.snap
  packages/design-system/src/styles/components/_Table.scss
Labels: Easy Review
