Repository CMSgov/design-system, pull requests merged in 2021-09, with the labels that each got.

#1126 WNMGDS-1064 - Fix text-underline bug
  packages/design-system/src/styles/base/_link.scss
Labels: Ready For Review

#1125 WNMGDS-1064 - Fix text-underline bug
  packages/design-system/src/styles/base/_link.scss
Labels: Ready For Review

#1136 [NO-TICKET] Update chromedriver from version 91 to 93
  packages/design-system-scripts/package.json
  yarn.lock
Labels: Ready For Review, Engineering

#1133 [WNMGWINSHOP-934] Add more customization options to Autocomplete items
  packages/design-system-docs/src/pages/components/Autocomplete/Autocomplete.example.jsx
  packages/design-system-docs/src/pages/components/Autocomplete/_Autocomplete.docs.scss
  packages/design-system-docs/src/styles/components/_example.scss
  packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
Labels: Ready For Review, Engineering

#1140 [NO-TICKET] Add transparent background to transparent button
  packages/design-system/src/styles/components/_Button.scss
Labels: Ready For Review

#1141 [WNMGWINSHOP-934] Revert one prop type change for Autocomplete
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
Labels: Ready For Review

#1130 WNMGDS 814/e2e tool update
  packages/design-system-scripts/helpers/e2e/assertNoAxeViolations.js
  packages/design-system-scripts/helpers/e2e/constants.js
  packages/design-system-scripts/jest/e2e.environment.js
  packages/design-system-scripts/package.json
  yarn.lock
Labels: Ready For Review

#1142 Simplify analytics API
  packages/design-system/src/components/Alert/Alert.test.tsx
  packages/design-system/src/components/Alert/Alert.tsx
  packages/design-system/src/components/Dialog/Dialog.jsx
  packages/design-system/src/components/Dialog/Dialog.test.jsx
  packages/design-system/src/components/HelpDrawer/HelpDrawer.jsx
  packages/design-system/src/components/HelpDrawer/HelpDrawer.test.jsx
  packages/design-system/src/components/analytics/SendAnalytics.test.ts
  packages/design-system/src/components/analytics/SendAnalytics.ts
  packages/design-system/src/components/analytics/index.ts
Labels: Ready For Review

#1145 [NO-TICKET] Expose type definitions for analytics modules
  packages/design-system/src/types/index.d.ts
Labels: Ready For Review, Engineering

#1153 [NO-TICKET] Update table example to fix right aligned header
  packages/design-system-docs/src/pages/components/Table/table.example.html
Labels: Ready For Review

#1149 [NO-TICKET] Update link to Jenkins job
  guides/RELEASE-PROCESS.md
Labels: Ready For Review, Engineering, Build Process

#1135 [NO-TICKET] Add clearInputOnBlur prop to Autocomplete
  packages/design-system-scripts/helpers/e2e/assertNoAxeViolations.js
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/Autocomplete/keepInputDownshiftStateReducer.ts
Labels: Enhancement, Engineering

#1154 [WNMGDS-1094] Remove development branch from CI tests
  .github/workflows/build.yml
Labels: Engineering, Build Process

#1156 [WNMGDS-1094] Tagged release docs and scripts
  guides/RELEASE-PROCESS.md
  lerna.json
  package.json
  prerelease.sh
  publish.sh
  release.sh
Labels: Ready For Review, Engineering, Documentation, Build Process

#1157 Update master from dev again
  guides/RELEASE-PROCESS.md
  packages/design-system-docs/src/pages/components/Table/table.example.html
  packages/design-system-scripts/helpers/e2e/assertNoAxeViolations.js
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/Autocomplete/keepInputDownshiftStateReducer.ts
  packages/design-system/src/types/index.d.ts
Labels: Ready For Review

#1159 [NO-TICKET] Reduce OS notifications for build process
  packages/design-system-scripts/gulp/build.js
  packages/design-system-scripts/gulp/common/logUtil.js
  packages/design-system-scripts/gulp/docs/docs.js
Labels: Ready For Review, Engineering

#1160 [NO-TICKET] Remove linter rule that hinders productivity
  packages/eslint-config-design-system/index.js
Labels: Ready For Review, Engineering

#1158 [WNMGDS-1094] Add logic for determining npm dist-tags for beta releases
  publish.sh
Labels: Ready For Review

#1111 [WNMGDS-963] updating vertical nav for improved accessibility
  lerna.json
  packages/design-system-docs/src/pages/components/VerticalNav/VerticalNav.example.jsx
  packages/design-system-docs/src/pages/components/VerticalNav/_VerticalNav.docs.scss
  packages/design-system-docs/src/pages/components/VerticalNav/verticalnav.example.html
  packages/design-system/src/components/VerticalNav/VerticalNav.jsx
  packages/design-system/src/components/VerticalNav/VerticalNav.test.jsx
  yarn.lock
Labels: Accessibility, Ready For Review

#1089 Feature/pagination
  .github/workflows/build.yml
  examples/create-react-app-typescript/src/components/App.tsx
  examples/create-react-app-typescript/src/components/Examples/PaginationExample.tsx
  examples/create-react-app/src/components/App.js
  examples/create-react-app/src/components/Examples/PaginationExample.js
  packages/design-system-docs/src/pages/components/Pagination/Pagination.example.jsx
  packages/design-system-docs/src/pages/components/Pagination/_Pagination.docs.scss
  packages/design-system-docs/src/pages/components/Pagination/pagination.example.html
  packages/design-system-docs/src/pages/components/State/State.jsx
  packages/design-system/src/components/Pagination/Ellipses.tsx
  packages/design-system/src/components/Pagination/Page.test.tsx
  packages/design-system/src/components/Pagination/Page.tsx
  packages/design-system/src/components/Pagination/Pagination.e2e.test.js
  packages/design-system/src/components/Pagination/Pagination.test.tsx
  packages/design-system/src/components/Pagination/Pagination.tsx
  packages/design-system/src/components/Pagination/__snapshots__/Page.test.tsx.snap
  packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/design-system/src/components/Pagination/index.ts
  packages/design-system/src/components/Pagination/matchMedia.mock.js
  packages/design-system/src/components/index.js
  packages/design-system/src/images/chevron-left-solid.svg
  packages/design-system/src/images/chevron-right-solid.svg
  packages/design-system/src/styles/components/_Pagination.scss
  packages/design-system/src/styles/components/index.scss
  packages/design-system/src/types/index.d.ts
Labels: Ready For Review
