Repository CMSgov/design-system, pull requests merged in 2021-11, with the labels that each got.

#1201 [WNMGDS-1175] Update testing scripts to support child design systems in monorepo
  package.json
  packages/design-system-scripts/cli.js
  packages/design-system-scripts/jest/e2e.global-setup.js
  packages/design-system-scripts/package.json
  packages/ds-healthcare-gov/src/components/Footer/Logo.jsx
  packages/ds-healthcare-gov/src/components/Footer/LogosRow.jsx
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/LogosRow.test.jsx.snap
  packages/ds-healthcare-gov/src/components/Header/ActionMenu.jsx
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/ActionMenu.test.jsx.snap
  packages/ds-healthcare-gov/src/components/PrivacySettings/PrivacySettingsDialog.jsx
  yarn.lock
Labels: Status: Ready For Review

#1204 [WNMGDS-1175] Run prettier on ds-healthcare-gov files
  lerna.json
  packages/design-system/src/styles/base/_link.scss
  packages/ds-healthcare-gov/README.md
  packages/ds-healthcare-gov/docs/src/pages/components/Button/button-secondary.example.html
  packages/ds-healthcare-gov/docs/src/pages/components/DateField/datefield.example.html
  packages/ds-healthcare-gov/src/__mocks__/react-i18next.js
  packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.jsx
  packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.test.jsx
  packages/ds-healthcare-gov/src/components/Footer/Logo.jsx
  packages/ds-healthcare-gov/src/components/Footer/LogosRow.jsx
  packages/ds-healthcare-gov/src/components/Footer/PrivacySettingsLink.jsx
  packages/ds-healthcare-gov/src/components/Header/DeConsumerMessage.jsx
  packages/ds-healthcare-gov/src/components/Header/DeConsumerMessage.test.jsx
  packages/ds-healthcare-gov/src/components/Header/localeLink.test.js
  packages/ds-healthcare-gov/src/components/Header/loginLink.js
  packages/ds-healthcare-gov/src/components/Header/loginLink.test.js
  packages/ds-healthcare-gov/src/components/Logo/Logo.jsx
  packages/ds-healthcare-gov/src/components/PrivacySettings/PrivacySettingsTable.jsx
  packages/ds-healthcare-gov/src/components/PrivacySettings/privacySettings.test.js
  packages/ds-healthcare-gov/tsconfig.json
Labels: Status: Ready For Review

#1205 [NO-TICKET] Update the release docs to address beta releases
  guides/RELEASE-PROCESS.md
Labels: Status: Ready For Review

#1208 [WNMGDS-1141] Update release scripts
  publish.sh
  release.sh
Labels: Status: Ready For Review

#1209 [NO-TICKET] Update ds-healthcare-gov package.json versions
  packages/ds-healthcare-gov/package.json
Labels: Status: Ready For Review

#1211 [WNMGTAXTOOLS-136] Update skip-nav Spanish translation
  packages/ds-healthcare-gov/src/locale/es.json
Labels: Status: Ready For Review

#1210 [WNMGDS-1178] icon rfc update for mgov
  rfcs/2021-10-icons-in-core-DS.md
Labels: Status: Ready For Review, Release: Internal

#1216 [WNMGDS-1136] Fix box-shadow on HCgov header
  packages/ds-healthcare-gov/src/styles/components/_Header.scss
Labels: Status: Ready For Review

#1217 [NO-TICKET] Add bg color to HC header
  packages/ds-healthcare-gov/src/styles/components/_Header.scss
Labels: Status: Ready For Review

#1215 [WNMGDS-1142] Clean up files and READMEs for ds-medicare-gov
  README.md
  packages/design-system-docs/src/pages/startup/child-design-systems.md
  packages/design-system-docs/src/pages/startup/installation.md
  packages/ds-healthcare-gov/.nvmrc
  packages/ds-healthcare-gov/PUBLISHING.md
  packages/ds-healthcare-gov/README.md
  packages/ds-healthcare-gov/babel.config.js
  packages/ds-healthcare-gov/publish-release.sh
  packages/ds-healthcare-gov/release.sh
  packages/ds-healthcare-gov/tsconfig.json
  packages/ds-medicare-gov/README.md
  packages/ds-medicare-gov/babel.config.js
  packages/ds-medicare-gov/tsconfig.json
Labels: Status: Ready For Review

#1218 [WNMGDS-1142] Update release-publish and gh-pages commands for medicare
  package.json
  publish.sh
Labels: Status: Ready For Review

#1221 [WNMGDS-1142] Fix footer SVG rendering
  packages/ds-healthcare-gov/src/components/Footer/Logo.jsx
  packages/ds-healthcare-gov/src/components/Footer/LogosRow.jsx
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/LogosRow.test.jsx.snap
Labels: Status: Ready For Review

#1227 Release 2.10.0
  packages/design-system-docs/package.json
  packages/design-system-scripts/package.json
  packages/design-system/package.json
Labels: Status: Ready For Review

#1226 [WNMGDS 1166] Add lightweight alert
  packages/design-system-docs/src/pages/components/Alert/Alert.example.jsx
  packages/design-system-docs/src/pages/components/Alert/_Alert.docs.scss
  packages/design-system-docs/src/pages/components/Alert/alert.example-additional.html
  packages/design-system-docs/src/pages/components/Alert/alert.example.html
  packages/design-system/src/components/Alert/Alert.test.tsx
  packages/design-system/src/components/Alert/Alert.tsx
  packages/design-system/src/styles/components/_Alert.scss
Labels: Status: Ready For Review

#1225 [WNMGDS-1144] storybook for child systems
  .nvmrc
  .storybook/main.js
  .storybook/preview-body.html
  .storybook/storybookStyles.scss
  .storybook/webpack.config.js
  README.md
  package.json
  packages/design-system/src/components/Button/Button.stories.jsx
  packages/ds-healthcare-gov/.eslintrc.js
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/LogosRow.test.jsx.snap
  packages/ds-healthcare-gov/src/components/Header/Header.stories.jsx
  packages/ds-medicare-gov/src/components/GlobalHeader/GlobalHeader.stories.jsx
Labels: Status: Ready For Review, Release: Internal

#1230 [WNMGDS-1097] Separate our build commands in package.json
  README.md
  package.json
  packages/design-system-scripts/cli.js
  packages/design-system-scripts/jest/a11y.global-setup.js
Labels: Status: Ready For Review, Release: Internal

#1220 [WNMGDS 1144] Adding storybook for local development
  .eslintrc.js
  .nvmrc
  .storybook/CmsTheme.js
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview-body.html
  .storybook/preview.js
  .storybook/storybookStyles.scss
  .storybook/webpack.config.js
  README.md
  package.json
  packages/design-system/src/components/Button/Button.stories.jsx
  packages/ds-healthcare-gov/.eslintrc.js
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/LogosRow.test.jsx.snap
  packages/ds-healthcare-gov/src/components/Header/Header.stories.jsx
  packages/ds-medicare-gov/src/components/GlobalHeader/GlobalHeader.stories.jsx
  yarn.lock
Labels: Status: Ready For Review, Release: Internal

#1232 [WNMGDS-1089] Set error-placement flag default in ds-healthcare-gov
  packages/ds-healthcare-gov/docs/src/example.js
  packages/ds-healthcare-gov/package.json
  packages/ds-healthcare-gov/src/components/index.js
Labels: Status: Ready For Review, Release: Patch

#1228 [NO-TICKET] Update m.gov to use latest version of core package
  packages/ds-medicare-gov/package.json
  yarn.lock
Labels: Status: Ready For Review, Release: Minor

#1229 No ticket: Preserve border width for input fields in error state
  packages/ds-medicare-gov/src/styles/components/_override.forms.scss
Labels: Type: Bug, Status: Ready For Review

#1233 [WNMGDS-1206] mgov helpdrawer overrides
  packages/ds-medicare-gov/src/styles/components/_override.help_drawer.scss
Labels: Status: Ready For Review

#1238 [NO-TICKET] Add dependabot.yml
  .github/dependabot.yml
Labels: Status: Ready For Review, Release: Internal

#1249 [NO-TICKET] Sync ds-medicare-gov with latest core
  packages/ds-medicare-gov/package.json
Labels: Status: Ready For Review, Release: Internal

#1234 [WNMGDS-1180] mgov icons
  package.json
  packages/design-system-docs/src/pages/components/Icon/IconComponent.example.jsx
  packages/design-system/src/components/Icons/MenuIconThin.tsx
  packages/design-system/src/components/Icons/StarIcon.tsx
  packages/design-system/src/components/Icons/index.ts
  packages/ds-medicare-gov/docs/src/pages/components/Caret/Caret.docs.scss
  packages/ds-medicare-gov/docs/src/pages/components/Checkmark/Checkmark.docs.scss
  packages/ds-medicare-gov/docs/src/pages/components/CloseSymbol/CloseSymbol.docs.scss
  packages/ds-medicare-gov/docs/src/pages/components/HamburgerSymbol/HamburgerSymbol.docs.scss
  packages/ds-medicare-gov/docs/src/pages/components/Icon/IconComponent.docs.scss
  packages/ds-medicare-gov/docs/src/pages/components/Icon/mgovIcons.example.jsx
  packages/ds-medicare-gov/docs/src/pages/components/No/No.docs.scss
  packages/ds-medicare-gov/src/components/Caret/Caret.a11y.test.js
  packages/ds-medicare-gov/src/components/Caret/Caret.spec.tsx
  packages/ds-medicare-gov/src/components/Caret/Caret.tsx
  packages/ds-medicare-gov/src/components/Caret/index.ts
  packages/ds-medicare-gov/src/components/Checkmark/Checkmark.a11y.test.js
  packages/ds-medicare-gov/src/components/Checkmark/Checkmark.spec.tsx
  packages/ds-medicare-gov/src/components/Checkmark/Checkmark.tsx
  packages/ds-medicare-gov/src/components/Checkmark/index.ts
  packages/ds-medicare-gov/src/components/CloseSymbol/CloseSymbol.a11y.test.js
  packages/ds-medicare-gov/src/components/CloseSymbol/CloseSymbol.spec.tsx
  packages/ds-medicare-gov/src/components/CloseSymbol/CloseSymbol.tsx
  packages/ds-medicare-gov/src/components/CloseSymbol/index.ts
  packages/ds-medicare-gov/src/components/GlobalHeader/GlobalHeader.tsx
  packages/ds-medicare-gov/src/components/HamburgerSymbol/HamburgerSymbol.a11y.test.js
  packages/ds-medicare-gov/src/components/HamburgerSymbol/HamburgerSymbol.spec.tsx
  packages/ds-medicare-gov/src/components/HamburgerSymbol/index.ts
  packages/ds-medicare-gov/src/components/Icons/Caret.tsx
  packages/ds-medicare-gov/src/components/Icons/Checkmark.tsx
  packages/ds-medicare-gov/src/components/Icons/CloseSymbol.tsx
  packages/ds-medicare-gov/src/components/Icons/HamburgerSymbol.tsx
  packages/ds-medicare-gov/src/components/Icons/No.tsx
  packages/ds-medicare-gov/src/components/Icons/RoundedStarEmptyIcon.tsx
  packages/ds-medicare-gov/src/components/Icons/RoundedStarFilledIcon.tsx
  packages/ds-medicare-gov/src/components/Icons/RoundedStarHalfIcon.tsx
  packages/ds-medicare-gov/src/components/Icons/RoundedStarIcon.tsx
  packages/ds-medicare-gov/src/components/Icons/index.ts
  packages/ds-medicare-gov/src/components/NavigationMenu/NavigationMenu.tsx
  packages/ds-medicare-gov/src/components/No/No.a11y.test.js
  packages/ds-medicare-gov/src/components/No/No.spec.tsx
  packages/ds-medicare-gov/src/components/No/No.tsx
  packages/ds-medicare-gov/src/components/No/index.ts
  packages/ds-medicare-gov/src/components/Stars/Stars.tsx
  packages/ds-medicare-gov/src/components/index.ts
  packages/ds-medicare-gov/src/styles/components/_index.scss
  packages/ds-medicare-gov/src/styles/components/_override.icons.scss
Labels: Status: Ready For Review

#1288 [NO-TICKET] nov dependabot updates
  packages/design-system-docs/yarn.lock
  packages/design-system-scripts/package.json
  packages/design-system-scripts/yarn.lock
  packages/design-system/package.json
  packages/design-system/yarn.lock
  packages/ds-healthcare-gov/yarn.lock
  packages/ds-medicare-gov/yarn.lock
  yarn.lock
Labels: dependencies

#1231 [WNMGDS-1188] filterchip a11y
  packages/design-system-docs/src/pages/components/FilterChip/FilterChip.example.jsx
  packages/design-system-docs/src/pages/components/FilterChip/_FilterChip.docs.scss
  packages/design-system-docs/src/pages/components/FilterChip/filterchip.example.html
  packages/design-system/src/components/FilterChip/FilterChip.a11y.test.tsx
  packages/design-system/src/components/FilterChip/FilterChip.tsx
  packages/design-system/src/styles/components/_FilterChip.scss
Labels: Status: Ready For Review

#1289 Release 2021-11-23
  packages/design-system-docs/package.json
  packages/design-system-scripts/package.json
  packages/design-system/package.json
  packages/ds-healthcare-gov/package.json
  packages/ds-medicare-gov/package.json
Labels: Status: Ready For Review

#1301 [NO-TICKET] Remove package lockfiles because yarn workspaces uses only one
  packages/design-system-scripts/yarn.lock
  packages/design-system/yarn.lock
  packages/ds-healthcare-gov/yarn.lock
  packages/ds-medicare-gov/yarn.lock
  packages/eslint-config-design-system/yarn.lock
  packages/stylelint-config-design-system/yarn.lock
Labels: Status: Ready For Review, Release: Internal

#1315 [WNMGDS-1148] stories for FilterChip, Drawer & FormLabel
  packages/design-system/src/components/Drawer/Drawer.stories.jsx
  packages/design-system/src/components/FilterChip/FilterChip.stories.jsx
  packages/design-system/src/components/FormLabel/FormLabel.stories.jsx
Labels: Status: Ready For Review, Release: Internal
