Repository CMSgov/design-system, pull requests merged in 2021-12, with the labels that each got.

#1358 [WNMGDS-828] Update homepages to point to Sketch cloud toolkits
  packages/design-system-docs/src/pages/index.md
  packages/ds-healthcare-gov/docs/src/pages/index.md
  packages/ds-medicare-gov/docs/src/pages/index.md
Labels: Status: Ready For Review

#1360 [WNMGDS-1152] step list story
  packages/design-system/src/components/StepList/StepList.stories.jsx
Labels: Status: Ready For Review, Release: Internal

#1368 [WNMGDS-1155] Init stories for USA Banner and vert nav
  packages/design-system/src/components/UsaBanner/UsaBanner.stories.jsx
  packages/design-system/src/components/VerticalNav/VerticalNav.stories.jsx
Labels: Status: Ready For Review

#1362 [WNMGDS-1149] Create List and MonthPicker stories
  packages/design-system/src/components/Button/Button.stories.jsx
  packages/design-system/src/components/List/List.stories.jsx
  packages/design-system/src/components/MonthPicker/MonthPicker.stories.jsx
Labels: Status: Ready For Review

#1367 [WNMGDS-1205] help drawer toggle icon replacement
  .eslintrc.js
  packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.jsx
  packages/design-system/src/components/HelpDrawer/__snapshots__/HelpDrawerToggle.test.jsx.snap
  packages/design-system/src/types/HelpDrawer/HelpDrawer.d.ts
  packages/ds-healthcare-gov/.eslintrc.js
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.stories.jsx
  packages/ds-medicare-gov/src/components/HelpDrawer/index.js
  packages/ds-medicare-gov/src/components/Icons/InfoCircleOutlineIcon.tsx
  packages/ds-medicare-gov/src/styles/components/_override.help_drawer.scss
Labels: Status: Ready For Review

#1388 [NO-TICKET] Revert major version upgrade of css-loader
  package.json
  yarn.lock
Labels: dependencies

#1394 [WNMGDS-1156] updating scripts to build storybook
  .gitignore
  package.json
Labels: Status: Ready For Review, Release: Internal

#1366 [WNMGS-919] Adding Medicare focus styles
  packages/ds-medicare-gov/src/styles/components/_GlobalHeader.scss
  packages/ds-medicare-gov/src/styles/components/_override.buttons.scss
  packages/ds-medicare-gov/src/styles/components/_override.forms.scss
  packages/ds-medicare-gov/src/styles/settings/_variables.build.scss
  packages/ds-medicare-gov/src/styles/settings/_variables.color.scss
Labels: Status: Ready For Review

#1402 [WNMGDS-983] Remove base html ruleset variable
  examples/child-design-system/src/styles/settings/variables/_override.build.scss
  packages/design-system-docs/src/pages/styles/typography/_typography.docs.scss
  packages/design-system/src/styles/base/_link.scss
  packages/design-system/src/styles/components/_Alert.scss
  packages/design-system/src/styles/settings/variables/_build.scss
  packages/ds-medicare-gov/docs/src/pages/styles/typography/_typography.docs.scss
  packages/ds-medicare-gov/src/styles/settings/_variables.build.scss
Labels: Status: Ready For Review

#1392 [WNMGDS-972] Convert MonthPicker to TypeScript
  packages/design-system-docs/src/pages/components/MonthPicker/_MonthPicker.docs.scss
  packages/design-system/src/components/ChoiceList/Choice.tsx
  packages/design-system/src/components/MonthPicker/MonthPicker.jsx
  packages/design-system/src/components/MonthPicker/MonthPicker.test.jsx
  packages/design-system/src/components/MonthPicker/MonthPicker.tsx
  packages/design-system/src/components/MonthPicker/getMonthNames.ts
  packages/design-system/src/components/MonthPicker/index.js
  packages/design-system/src/components/MonthPicker/index.ts
  packages/design-system/src/types/MonthPicker/MonthPicker.d.ts
  packages/design-system/src/types/index.d.ts
Labels: Status: Ready For Review

#1413 [WNMGDS-1207] Update spacer utils
  packages/design-system-docs/src/pages/utilities/margin/margin.example.html
  packages/design-system-docs/src/pages/utilities/padding/padding.example.html
  packages/design-system/src/styles/settings/variables/_layout.scss
  packages/design-system/src/styles/utilities/_margin.scss
  packages/design-system/src/styles/utilities/_padding.scss
Labels: Status: Ready For Review

#1408 [NO-TICKET] Fix known typing bugs
  examples/create-react-app-typescript/package.json
  examples/create-react-app-typescript/src/components/Examples/PaginationExample.tsx
  packages/design-system/src/types/Dialog/Dialog.d.ts
  packages/design-system/src/types/HelpDrawer/HelpDrawer.d.ts
Labels: Status: Ready For Review

#1404 [WNMGDS-1099] Update alert link styling with more component variables
  packages/design-system-docs/src/pages/components/Alert/_Alert.docs.scss
  packages/design-system/src/styles/components/_Alert.scss
  packages/ds-medicare-gov/src/styles/components/_override.alert.scss
Labels: Status: Ready For Review

#1419 [WNMGDS-1279] Fix definition of window.utag conflicting with consuming products
  examples/create-react-app-typescript/.env
  packages/design-system/src/components/analytics/SendAnalytics.ts
  packages/ds-healthcare-gov/src/__mocks__/react-i18next.js
  packages/ds-healthcare-gov/src/components/Footer/Footer.jsx
  packages/ds-healthcare-gov/src/components/Footer/PrivacySettingsLink.jsx
  packages/ds-healthcare-gov/src/components/Header/ActionMenu.jsx
  packages/ds-healthcare-gov/src/components/Header/DeConsumerMessage.jsx
  packages/ds-healthcare-gov/src/components/Header/Header.jsx
  packages/ds-healthcare-gov/src/components/Header/I18nHeader.js
  packages/ds-healthcare-gov/src/components/PrivacySettings/PrivacySettingsDialog.jsx
Labels: Status: Ready For Review

#1416 [WNMGDS-1087] Update focus styles to fix link and remove unneeded conditional focus style SCSS
  examples/child-design-system/src/styles/settings/variables/_override.build.scss
  packages/design-system-docs/src/pages/startup/theming.md
  packages/design-system/src/styles/base/_link.scss
  packages/design-system/src/styles/components/_Accordion.scss
  packages/design-system/src/styles/components/_Alert.scss
  packages/design-system/src/styles/components/_Autocomplete.scss
  packages/design-system/src/styles/components/_Button.scss
  packages/design-system/src/styles/components/_Choice.scss
  packages/design-system/src/styles/components/_Drawer.scss
  packages/design-system/src/styles/components/_Dropdown.scss
  packages/design-system/src/styles/components/_FilterChip.scss
  packages/design-system/src/styles/components/_Tabs.scss
  packages/design-system/src/styles/components/_TextField.scss
  packages/design-system/src/styles/components/_Tooltip.scss
  packages/design-system/src/styles/components/_VerticalNav.scss
  packages/design-system/src/styles/settings/mixins/_focus-styles.scss
  packages/design-system/src/styles/settings/variables/_build.scss
  packages/ds-healthcare-gov/src/styles/components/_Button.scss
  packages/ds-medicare-gov/src/styles/settings/_index.scss
  packages/ds-medicare-gov/src/styles/settings/_variables.build.scss
Labels: Status: Ready For Review

#1426 [WNMGDS-1287] Fix a11y error about logo links having no text
  packages/ds-healthcare-gov/src/components/Footer/LogosRow.jsx
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/LogosRow.test.jsx.snap
Labels: Status: Ready For Review

#1298 [WNMGDS-1218] Create RFC for WHCM
  rfcs/2021-11-whcm-support.md
Labels: Status: Ready For Review

#1292 [NO-TICKET] Update release script to support bumping unchanged betas to full releases
  release.sh
Labels: Status: Ready For Review, Status: Work In Progress

#1423 [NO-TICKET] Update release script to only push the new tags to origin
  release.sh
Labels: Status: Ready For Review, Release: Internal

#1424 [WNMGDS-821] Move lists to typography page
  packages/design-system-docs/src/pages/components/List/_List.docs.scss
  packages/design-system-docs/src/pages/components/List/list.example.html
  packages/design-system-docs/src/pages/styles/typography/_typography.docs.scss
  packages/design-system-docs/src/pages/styles/typography/list.example.html
Labels: Status: Ready For Review

#1447 [WNMGDS-1299] Fix Storybook config for child design systems
  .storybook/main.js
  package.json
Labels: Status: Ready For Review

#1445 [WNMGDS-1272] Configure project for type-checking and fix errors
  .eslintrc.js
  package.json
  packages/design-system/src/components/Alert/Alert.test.tsx
  packages/design-system/src/components/Button/Button.test.tsx
  packages/design-system/src/components/Button/Button.tsx
  packages/design-system/src/components/DateField/DateInput.test.tsx
  packages/design-system/src/components/DateField/__snapshots__/DateInput.test.tsx.snap
  packages/design-system/src/components/List/List.a11y.test.tsx
  packages/design-system/src/components/TextField/TextInput.tsx
  packages/design-system/src/components/TextField/maskHelpers.ts
  packages/design-system/src/components/analytics/SendAnalytics.test.ts
  packages/design-system/src/components/analytics/SendAnalytics.ts
  packages/design-system/src/components/analytics/index.ts
  tsconfig.json
Labels: Status: Ready For Review

#1452 [NO-TICKET] Upgrade TypeScript to 4.5.4
  packages/design-system-scripts/gulp/build.js
  packages/design-system-scripts/package.json
  packages/design-system/src/components/UsaBanner/UsaBanner.tsx
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
  packages/ds-healthcare-gov/src/components/i18n.js
  packages/ds-healthcare-gov/src/components/locale/en.json
  packages/ds-healthcare-gov/src/components/locale/es.json
  yarn.lock
Labels: Status: Ready For Review
