Repository CMSgov/design-system, pull requests merged in 2022-08, with the labels that each got.

#1999 [NO-TICKET] Table of Contents update
  packages/docs/gatsby-config.ts
  packages/docs/package.json
  packages/docs/src/components/ComponentThemeOptions.tsx
  packages/docs/src/components/ContentRenderer.tsx
  packages/docs/src/components/InfoPage.tsx
  packages/docs/src/components/Layout.tsx
  packages/docs/src/components/StorybookExample.tsx
  packages/docs/src/components/TableOfContents.tsx
  packages/docs/src/components/TableOfContentsMobile.tsx
  packages/docs/src/helpers/useTheme.ts
  packages/docs/src/styles/components/tableOfContents.scss
  yarn.lock
Labels: Status: Ready For Review

#2015 [NO-TICKET] documentation updates for running the gatsby doc site
  README.md
  packages/docs/README.md
Labels: Status: Ready For Review, Type: Documentation

#2011 [WNMGDS-1813] updating markup on usa banner
  packages/design-system/src/components/UsaBanner/UsaBanner.tsx
  packages/design-system/src/components/UsaBanner/__snapshots__/UsaBanner.test.jsx.snap
Labels: Status: Ready For Review

#1971 [NO-TICKET] Introduce `scan-dependents` sub-commands and implement code search
  scripts/scanDependents/README.md
  scripts/scanDependents/index.ts
  scripts/scanDependents/requests.ts
  scripts/scanDependents/scans.ts
Labels: Status: Ready For Review

#2010 [WNMGDS-1803][WNMGDS-1802] Storybook-based examples can show React source
  packages/design-system/src/components/TextField/TextField.stories.jsx
  packages/docs/content/components/button.mdx
  packages/docs/content/components/masked-field.mdx
  packages/docs/content/components/table.mdx
  packages/docs/src/components/CodeSnippet.tsx
  packages/docs/src/components/EmbeddedExample.tsx
  packages/docs/src/components/ExampleFooter.tsx
  packages/docs/src/components/ResponsiveExample.tsx
  packages/docs/src/components/StorybookExample.tsx
  packages/docs/src/components/StorybookExampleFooter.tsx
  packages/docs/src/helpers/syntaxHighlighting.ts
  packages/docs/src/styles/components/codeSnippet.scss
  packages/docs/src/styles/components/embeddedExamples.scss
  packages/docs/src/styles/components/storybookExample.scss
  packages/docs/src/styles/index.scss
  packages/docs/src/styles/pages/layout.scss
Labels: Status: Ready For Review

#2013 [NO-TICKET] Update component pages to match new content structure
  packages/docs/content/components/accordion.mdx
  packages/docs/content/components/alert.mdx
  packages/docs/content/components/autocomplete.mdx
  packages/docs/content/components/badge.mdx
  packages/docs/content/components/checkbox.mdx
  packages/docs/content/components/date-field/date-picker.mdx
  packages/docs/content/components/date-field/multi-input-date-field.mdx
  packages/docs/content/components/date-field/single-input-date-field.mdx
  packages/docs/content/components/drawer.mdx
  packages/docs/content/components/dropdown.mdx
  packages/docs/content/components/filter-chip.mdx
  packages/docs/content/components/form-label.mdx
  packages/docs/content/components/icon.mdx
  packages/docs/content/components/idle-timeout.mdx
  packages/docs/content/components/masked-field.mdx
  packages/docs/content/components/modal-dialog.mdx
  packages/docs/content/components/month-picker.mdx
  packages/docs/content/components/pagination.mdx
  packages/docs/content/components/radio.mdx
  packages/docs/content/components/review.mdx
  packages/docs/content/components/skip-nav.mdx
  packages/docs/content/components/spinner.mdx
  packages/docs/content/components/step-list.mdx
  packages/docs/content/components/table.mdx
  packages/docs/content/components/tabs.mdx
  packages/docs/content/components/text-field.mdx
  packages/docs/content/components/tooltip.mdx
  packages/docs/content/components/usa-banner.mdx
  packages/docs/content/components/vertical-navigation.mdx
Labels: Status: Ready For Review

#2027 [NO-TICKET] Clean scripts
  package.json
  scripts/loki.sh
  scripts/release.sh
  scripts/scanDependents/README.md
  scripts/scanDependents/index.ts
  scripts/scanDependents/output.ts
  scripts/scanDependents/requests.ts
  scripts/scanDependents/scans.ts
  scripts/test-locally.sh
  scripts/tsconfig.json
Labels: Status: Ready For Review

#2032 [WNMGDS-1829] Hgov Inset component documentation
  packages/design-system-tokens/src/themes/healthcare-components.ts
  packages/docs/content/components/inset.mdx
  packages/docs/src/styles/index.scss
  packages/docs/src/styles/theme-variables/_healthcare-components-scss-to-css.map.scss
  packages/docs/src/styles/theme-variables/_healthcare-components-theme.css
  packages/ds-healthcare-gov/src/styles/components/_Inset.scss
  packages/ds-healthcare-gov/src/styles/settings/_healthcare-components-theme.scss
Labels: Status: Ready For Review

#2033 [WNMGDS-1796] Fix border width issue for pickers in error state
  packages/design-system-tokens/src/themes/core-components.ts
  packages/design-system-tokens/src/themes/healthcare-components.ts
  packages/design-system-tokens/src/themes/medicare-components.ts
  packages/design-system/src/styles/components/_SingleInputDateField.scss
  packages/design-system/src/styles/components/_TextField.scss
  packages/design-system/src/styles/settings/variables/_core-components-theme.scss
  packages/docs/src/styles/theme-variables/_core-components-scss-to-css.map.scss
  packages/docs/src/styles/theme-variables/_core-components-theme.css
  packages/docs/src/styles/theme-variables/_healthcare-components-scss-to-css.map.scss
  packages/docs/src/styles/theme-variables/_healthcare-components-theme.css
  packages/docs/src/styles/theme-variables/_medicare-components-scss-to-css.map.scss
  packages/docs/src/styles/theme-variables/_medicare-components-theme.css
  packages/ds-healthcare-gov/src/styles/settings/_healthcare-components-theme.scss
  packages/ds-medicare-gov/src/styles/settings/variables/_medicare-components-theme.scss
Labels: Status: Ready For Review

#2038 [WNMGDS-1829] hgov logo and footer documentation
  packages/design-system-tokens/src/themes/healthcare-components.ts
  packages/docs/content/components/footer/healthcare-footer.mdx
  packages/docs/content/components/inset.mdx
  packages/docs/content/components/logos/healthcare-logo.mdx
  packages/docs/gatsby-config.ts
  packages/docs/src/components/DocSiteNavigation.tsx
  packages/docs/src/styles/components/navigation.scss
  packages/docs/src/styles/index.scss
  packages/docs/src/styles/theme-variables/_healthcare-components-scss-to-css.map.scss
  packages/docs/src/styles/theme-variables/_healthcare-components-theme.css
  packages/ds-healthcare-gov/src/components/Logo/Logo.stories.tsx
  packages/ds-healthcare-gov/src/styles/components/_Footer.scss
  packages/ds-healthcare-gov/src/styles/settings/_healthcare-components-theme.scss
Labels: Status: Ready For Review

#2044 [WNMGDS-1829] healthcare header docs
  packages/docs/content/components/header/healthcare-header.mdx
  packages/docs/src/styles/index.scss
  packages/ds-healthcare-gov/src/components/Footer/Logo.tsx
Labels: Status: Ready For Review

#2045 Wnmgds 1829/hgov component docs
  packages/design-system-tokens/src/themes/healthcare-components.ts
  packages/docs/content/components/date-field/multi-input-date-field.mdx
  packages/docs/content/components/date-field/single-input-date-field.mdx
  packages/docs/content/components/footer/healthcare-footer.mdx
  packages/docs/content/components/header/healthcare-header.mdx
  packages/docs/content/components/inset.mdx
  packages/docs/content/components/logos/healthcare-logo.mdx
  packages/docs/content/components/masked-field.mdx
  packages/docs/content/components/modal-dialog.mdx
  packages/docs/content/components/radio.mdx
  packages/docs/content/components/text-field.mdx
  packages/docs/content/components/usa-banner.mdx
  packages/docs/content/components/vertical-navigation.mdx
  packages/docs/content/getting-started/developers/code-conventions.mdx
  packages/docs/content/patterns/layouts/documentation-page.mdx
  packages/docs/content/patterns/third-party-external-link.mdx
  packages/docs/content/utilities/background-color.mdx
  packages/docs/content/utilities/font/font-family.mdx
  packages/docs/content/utilities/font/font-size.mdx
  packages/docs/content/utilities/font/font-style.mdx
  packages/docs/content/utilities/font/font-weight.mdx
  packages/docs/content/utilities/text/line-height.mdx
  packages/docs/content/utilities/text/text-align.mdx
  packages/docs/content/utilities/text/text-color.mdx
  packages/docs/content/utilities/text/text-decoration.mdx
  packages/docs/content/utilities/text/text-transform.mdx
  packages/docs/content/utilities/vertical-align.mdx
  packages/docs/gatsby-config.ts
  packages/docs/src/components/DocSiteNavigation.tsx
  packages/docs/src/styles/components/navigation.scss
  packages/docs/src/styles/index.scss
  packages/docs/src/styles/theme-variables/_healthcare-components-scss-to-css.map.scss
  packages/docs/src/styles/theme-variables/_healthcare-components-theme.css
  packages/ds-healthcare-gov/src/components/Footer/Logo.tsx
  packages/ds-healthcare-gov/src/components/Logo/Logo.stories.tsx
  packages/ds-healthcare-gov/src/styles/components/_Footer.scss
  packages/ds-healthcare-gov/src/styles/components/_Inset.scss
  packages/ds-healthcare-gov/src/styles/settings/_healthcare-components-theme.scss
Labels: Status: Ready For Review

#2051 [WNMGDS-1809] Migrate HCgov DSM content into doc site
  packages/docs/content/components/alert.mdx
  packages/docs/content/components/button.mdx
  packages/docs/content/components/form-label.mdx
  packages/docs/content/components/icon.mdx
  packages/docs/content/foundation/color.mdx
  packages/docs/content/foundation/layout-grid/layout-grid.mdx
  packages/docs/content/foundation/layout-grid/responsive-design.mdx
  packages/docs/content/foundation/typography.mdx
  packages/docs/content/foundation/typography/body.mdx
  packages/docs/content/foundation/typography/headings.mdx
  packages/docs/content/foundation/typography/links.mdx
  packages/docs/content/foundation/typography/list.mdx
  packages/docs/content/patterns/Forms/forms.mdx
  packages/docs/content/patterns/Forms/validation.mdx
  packages/docs/content/utilities/text/measure.mdx
  packages/docs/src/styles/pages/layout.scss
Labels: Status: Ready For Review

#2057 [WNMGDS-1816] removing child ds doc site commands from command list
  package.json
Labels: Status: Ready For Review

#2052 [WNMGDS-1830] mgov component docs
  .loki/reference/medicare_chrome_iphone7_Components_Icons_Hhs_Logo.png
  .loki/reference/medicare_chrome_iphone7_Medicare_Icons_Available_Icons.png
  .loki/reference/medicare_chrome_iphone7_Medicare_Logo_Logo.png
  .loki/reference/medicare_chrome_iphone7_Medicare_Stars_Default.png
  .loki/reference/medicare_chrome_laptop_Components_Icons_Hhs_Logo.png
  .loki/reference/medicare_chrome_laptop_Medicare_Icons_Available_Icons.png
  .loki/reference/medicare_chrome_laptop_Medicare_Logo_Logo.png
  .loki/reference/medicare_chrome_laptop_Medicare_Stars_Default.png
  packages/design-system/src/components/Icons/icons.stories.tsx
  packages/docs/content/components/card.mdx
  packages/docs/content/components/footer/medicare-footer.mdx
  packages/docs/content/components/header/medicare-header.mdx
  packages/docs/content/components/icon.mdx
  packages/docs/content/components/logos/hhs-logo.mdx
  packages/docs/content/components/logos/medicare-logo.mdx
  packages/docs/content/components/stars.mdx
  packages/docs/gatsby-config.ts
  packages/docs/src/components/InfoPage.tsx
  packages/docs/src/components/StorybookExample.tsx
  packages/ds-healthcare-gov/src/components/Accordion/Accordion.stories.jsx
  packages/ds-healthcare-gov/src/components/Footer/Footer.stories.jsx
  packages/ds-healthcare-gov/src/components/Header/Header.stories.jsx
  packages/ds-healthcare-gov/src/components/Logo/Logo.stories.tsx
  packages/ds-medicare-gov/src/components/Card/Card.stories.jsx
  packages/ds-medicare-gov/src/components/Card/Card.tsx
  packages/ds-medicare-gov/src/components/GlobalHeader/GlobalHeader.stories.jsx
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.stories.jsx
  packages/ds-medicare-gov/src/components/Icons/icons.stories.tsx
  packages/ds-medicare-gov/src/components/MedicaregovLogo/medicaregovLogo.stories.tsx
  packages/ds-medicare-gov/src/components/Navbar/Navbar.stories.jsx
  packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.stories.jsx
  packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.tsx
  packages/ds-medicare-gov/src/components/Stars/Stars.tsx
  packages/ds-medicare-gov/src/components/Stars/stars.stories.tsx
Labels: Status: Ready For Review

#2047 Migrated guidance from the DSM to the docs site for M.gov
  packages/docs/content/components/alert.mdx
  packages/docs/content/components/button.mdx
  packages/docs/content/components/drawer.mdx
  packages/docs/content/components/icon.mdx
  packages/docs/content/components/tooltip.mdx
  packages/docs/content/foundation/layout-grid/layout-grid.mdx
  packages/docs/content/foundation/typography/body.mdx
  packages/docs/content/foundation/typography/headings.mdx
  packages/docs/content/foundation/typography/links.mdx
Labels: Status: Ready For Review

#2064 [WNMGDS-1876] tabs test updates
  packages/design-system-scripts/jest/unit.config.js
  packages/design-system/src/components/Tabs/Tab.test.tsx
  packages/design-system/src/components/Tabs/TabPanel.test.tsx
  packages/design-system/src/components/Tabs/Tabs.test.tsx
Labels: Status: Ready For Review, Release: Internal

#2086 [WNMGDS-1877] filter chip, pagination, & spinner test updates
  .prettierignore
  packages/design-system/src/components/FilterChip/FilterChip.test.jsx
  packages/design-system/src/components/FilterChip/FilterChip.test.tsx
  packages/design-system/src/components/FilterChip/__snapshots__/FilterChip.test.tsx.snap
  packages/design-system/src/components/Pagination/Page.test.tsx
  packages/design-system/src/components/Pagination/__snapshots__/Page.test.tsx.snap
  packages/design-system/src/components/Spinner/Spinner.test.tsx
  packages/design-system/src/components/Spinner/__snapshots__/Spinner.test.tsx.snap
Labels: Status: Ready For Review, Release: Internal

#2092 [WNMGDS-1895] mgov help drawer
  .loki/reference/medicare_chrome_iphone7_Medicare_Icons_Available_Icons.png
  .loki/reference/medicare_chrome_laptop_Medicare_Icons_Available_Icons.png
  packages/design-system/src/components/Dialog/Dialog.tsx
  packages/docs/content/components/drawer.mdx
  packages/docs/content/components/modal-dialog.mdx
  packages/ds-medicare-gov/src/components/Dialog/Dialog.jsx
  packages/ds-medicare-gov/src/components/Dialog/Dialog.stories.jsx
  packages/ds-medicare-gov/src/components/Dialog/index.ts
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.stories.jsx
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawerToggle.jsx
  packages/ds-medicare-gov/src/components/HelpDrawer/index.ts
  packages/ds-medicare-gov/src/components/Icons/Checkmark.tsx
  packages/ds-medicare-gov/src/components/Icons/icons.stories.tsx
  packages/ds-medicare-gov/src/components/Icons/index.ts
  packages/ds-medicare-gov/src/components/index.ts
Labels: Status: Ready For Review
