Repository CMSgov/design-system, pull requests merged in 2022-03, with the labels that each got.

#1617 [WNMGDS-1465] Update privacy settings dialog
  packages/ds-healthcare-gov/src/components/PrivacySettings/PrivacySettingsDialog.test.jsx
  packages/ds-healthcare-gov/src/components/PrivacySettings/PrivacySettingsDialog.tsx
  packages/ds-healthcare-gov/src/components/PrivacySettings/PrivacySettingsTable.tsx
  packages/ds-healthcare-gov/src/components/PrivacySettings/__snapshots__/PrivacySettingsTable.test.jsx.snap
  packages/ds-healthcare-gov/src/styles/components/_Footer.scss
  packages/ds-healthcare-gov/src/styles/components/_PrivacySettingsDialog.scss
  packages/ds-healthcare-gov/src/styles/components/_PrivacySettingsTable.scss
  packages/ds-healthcare-gov/src/styles/components/_index.scss
Labels: Status: Ready For Review

#1620 [WNMGDS-1467] Fix StepLink custom component typedef rejecting correct usage
  packages/design-system/src/components/StepList/Step.tsx
  packages/design-system/src/components/StepList/StepLink.tsx
  packages/design-system/src/components/StepList/index.ts
Labels: Status: Ready For Review, Release: Patch

#1622 [WNMGDS-1445] updating link styles for active and focus state
  packages/design-system/src/components/Links/Links.stories.jsx
  packages/design-system/src/styles/base/_link.scss
Labels: Status: Ready For Review, Release: Patch

#1627 [NO-TICKET] Restrict dependabot's scope
  .github/dependabot.yml
Labels: Status: Ready For Review

#1625 [WNMGDS-1443] updating tooltip to support close button
  packages/design-system/src/components/Drawer/DrawerToggle.tsx
  packages/design-system/src/components/Tooltip/Tooltip.stories.jsx
  packages/design-system/src/components/Tooltip/Tooltip.test.jsx
  packages/design-system/src/components/Tooltip/Tooltip.tsx
  packages/design-system/src/components/Tooltip/__snapshots__/Tooltip.test.jsx.snap
  packages/design-system/src/components/utilities/usePrevious.ts
  packages/design-system/src/styles/components/_Tooltip.scss
Labels: Status: Ready For Review

#1631 [WNMGDS-1475] Add release script undo feature and pass args through to lerna command
  lerna.json
  release.sh
Labels: Status: Ready For Review, Release: Internal

#1634 Beta release 3.1.0-beta.1
  packages/design-system-docs/package.json
  packages/design-system-scripts/package.json
  packages/design-system/package.json
  packages/ds-healthcare-gov/package.json
  packages/ds-medicare-gov/package.json
Labels: Status: Ready For Review

#1635 [WNMGDS 1447] [WNMGDS-1483] External link adding and pattern update
  packages/design-system-docs/src/pages/components/Dialog/ThirdPartyLink.example.jsx
  packages/design-system-docs/src/pages/components/Dialog/_ThirdPartyLink.docs.scss
  packages/design-system-docs/src/pages/components/Icon/IconComponent.example.jsx
  packages/design-system/src/components/Icons/ExternalLinkIcon.tsx
  packages/design-system/src/components/Icons/index.ts
  packages/design-system/src/styles/components/_Dialog.scss
Labels: Status: Ready For Review

#1632 [WNMGDS-1319] removing role button from links
  packages/design-system/src/components/Button/Button.tsx
  packages/design-system/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/design-system/src/components/Tooltip/Tooltip.tsx
  packages/design-system/src/components/Tooltip/__snapshots__/Tooltip.test.jsx.snap
Labels: Status: Ready For Review, Release: Minor

#1638 [WNMGDS-1427] [WNMGDS-1426] Add consistent header documentation deprecate navbar and global header
  packages/ds-medicare-gov/docs/src/pages/components/GlobalHeader/GlobalHeader.docs.scss
  packages/ds-medicare-gov/docs/src/pages/components/Navbar/Navbar.docs.scss
  packages/ds-medicare-gov/docs/src/pages/patterns/consistent-header.md
Labels: Status: Ready For Review

#1649 [WNMGDS-1413] Add spacing example to page
  packages/design-system-docs/src/pages/styles/spacing/_spacing.docs.scss
  packages/design-system-docs/src/pages/styles/spacing/spacing.example.html
  packages/design-system-docs/src/styles/base/_index.scss
  packages/design-system-docs/src/styles/base/_spacing.scss
Labels: Status: Ready For Review

#1651 [WNMGDS-1432] Add error icon to html error examples
  packages/design-system-docs/src/pages/components/ChoiceList/checkbox-radio.example.html
  packages/design-system-docs/src/pages/components/DateField/datefield.example.html
  packages/design-system-docs/src/pages/components/Dropdown/dropdown.example.html
  packages/design-system-docs/src/pages/components/FormLabel/form-label.example.html
  packages/design-system-docs/src/pages/components/TextField/textfield.example.html
  packages/ds-healthcare-gov/docs/src/pages/components/DateField/datefield.example.html
Labels: Status: Ready For Review

#1650 [WNMGDS-1455] removing visited link color from hgov menu items
  packages/ds-healthcare-gov/src/components/Header/ActionMenu.tsx
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/ActionMenu.test.jsx.snap
  packages/ds-healthcare-gov/src/styles/components/_Header.scss
Labels: Status: Ready For Review, Release: Minor

#1661 [NO-TICKET] Update @types/node as alternative to #1658
  package.json
  packages/design-system-tokens/package.json
  packages/ds-medicare-gov/package.json
  yarn.lock
Labels: Status: Ready For Review, dependencies

#1660 [WNMGDS-1516] Fix null-ref error for uncontrolled Choice components
  packages/design-system/src/components/ChoiceList/Choice.tsx
Labels: Status: Ready For Review, Release: Patch

#1662 Update tooltip display to inline-block.
  packages/design-system/src/styles/components/_Tooltip.scss
Labels: Status: Ready For Review

#1669 [NO-TICKET] Remove outdated documentation
  packages/design-system-docs/src/pages/components/DateField/_DateField.docs.scss
Labels: Status: Ready For Review

#1653 [WNMGDS-1367] web components rfc
  rfcs/2022-03-web-components.md
Labels: Release: Internal

#1672 [WNMGDS-1551] Remove translation parameter from defaultMenuLinks function
  packages/design-system/src/__mocks__/i18next.js
  packages/design-system/src/__mocks__/react-i18next.js
  packages/ds-healthcare-gov/src/components/Header/Header.test.jsx
  packages/ds-healthcare-gov/src/components/Header/Header.tsx
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/Header.test.jsx.snap
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/defaultMenuLinks.test.js.snap
  packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.test.js
  packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.ts
Labels: Status: Ready For Review

#1671 [WNMGDS-1535] choice ref update
  packages/design-system/src/components/ChoiceList/ChoiceList.stories.jsx
  packages/design-system/src/components/ChoiceList/ChoiceList.test.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.tsx
  packages/design-system/src/components/ChoiceList/__snapshots__/ChoiceList.test.tsx.snap
Labels: Status: Ready For Review, Release: Minor

#1668 [WNMGDS-1355][WNMGDS-1551] Translate a11y labels for Alert and Badge and add new i18n module
  .loki/reference/chrome_iphone7_Components_USA_Banner_Default.png
  .loki/reference/chrome_laptop_Components_USA_Banner_Default.png
  packages/design-system-scripts/gulp/build.js
  packages/design-system/src/components/Alert/Alert.test.tsx
  packages/design-system/src/components/Alert/Alert.tsx
  packages/design-system/src/components/Badge/Badge.test.tsx
  packages/design-system/src/components/Badge/Badge.tsx
  packages/design-system/src/components/Badge/__snapshots__/Badge.test.tsx.snap
  packages/design-system/src/components/MonthPicker/MonthPicker.test.jsx
  packages/design-system/src/components/MonthPicker/MonthPicker.tsx
  packages/design-system/src/components/UsaBanner/UsaBanner.stories.jsx
  packages/design-system/src/components/UsaBanner/UsaBanner.test.jsx
  packages/design-system/src/components/UsaBanner/UsaBanner.tsx
  packages/design-system/src/components/UsaBanner/__snapshots__/UsaBanner.test.jsx.snap
  packages/design-system/src/components/__snapshots__/i18n.test.ts.snap
  packages/design-system/src/components/i18n.test.ts
  packages/design-system/src/components/i18n.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
  packages/ds-healthcare-gov/package.json
  packages/ds-healthcare-gov/src/__mocks__/i18next.js
  packages/ds-healthcare-gov/src/__mocks__/react-i18next.js
  packages/ds-healthcare-gov/src/components/Footer/Footer.stories.jsx
  packages/ds-healthcare-gov/src/components/Footer/Footer.tsx
  packages/ds-healthcare-gov/src/components/Footer/I18nFooter.tsx
  packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.tsx
  packages/ds-healthcare-gov/src/components/Footer/PrivacySettingsLink.tsx
  packages/ds-healthcare-gov/src/components/Footer/index.ts
  packages/ds-healthcare-gov/src/components/Header/ActionMenu.tsx
  packages/ds-healthcare-gov/src/components/Header/DeConsumerMessage.tsx
  packages/ds-healthcare-gov/src/components/Header/Header.stories.jsx
  packages/ds-healthcare-gov/src/components/Header/Header.test.jsx
  packages/ds-healthcare-gov/src/components/Header/Header.tsx
  packages/ds-healthcare-gov/src/components/Header/I18nHeader.tsx
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/Header.test.jsx.snap
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/defaultMenuLinks.test.js.snap
  packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.test.js
  packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.ts
  packages/ds-healthcare-gov/src/components/Header/index.ts
  packages/ds-healthcare-gov/src/components/Header/localeLink.ts
  packages/ds-healthcare-gov/src/components/Header/loginLink.ts
  packages/ds-healthcare-gov/src/components/Logo/Logo.tsx
  packages/ds-healthcare-gov/src/components/PrivacySettings/PrivacySettingsDialog.tsx
  packages/ds-healthcare-gov/src/components/i18n.ts
  yarn.lock
Labels: Status: Ready For Review

#1673 [WNMGDS-831] Refactor choice to use native input element
  .loki/reference/chrome_iphone7_Components_ChoiceList_Default_Checkbox.png
  .loki/reference/chrome_iphone7_Components_ChoiceList_Default_Radio.png
  .loki/reference/chrome_iphone7_Components_ChoiceList_Inverse_Option.png
  .loki/reference/chrome_iphone7_Components_ChoiceList_Small_Option.png
  .loki/reference/chrome_iphone7_Components_Month_Picker_Inverse_Selected_Month_Picker.png
  .loki/reference/chrome_iphone7_Components_Month_Picker_Selected_Month_Picker.png
  .loki/reference/chrome_laptop_Components_ChoiceList_Default_Checkbox.png
  .loki/reference/chrome_laptop_Components_ChoiceList_Default_Radio.png
  .loki/reference/chrome_laptop_Components_ChoiceList_Inverse_Option.png
  .loki/reference/chrome_laptop_Components_ChoiceList_Small_Option.png
  .loki/reference/chrome_laptop_Components_Month_Picker_Inverse_Selected_Month_Picker.png
  .loki/reference/chrome_laptop_Components_Month_Picker_Selected_Month_Picker.png
  README.md
  packages/design-system-docs/src/pages/components/ChoiceList/checkbox-radio.example.html
  packages/design-system/src/components/ChoiceList/Choice.tsx
  packages/design-system/src/components/ChoiceList/__snapshots__/ChoiceList.test.tsx.snap
  packages/design-system/src/components/MonthPicker/__snapshots__/MonthPicker.test.jsx.snap
  packages/design-system/src/styles/components/_Choice.scss
Labels: Status: Ready For Review

#1677 [WNMGDS-1355] Fix "document is not defined" error during doc-site build
  packages/design-system/src/components/i18n.ts
Labels: Status: Ready For Review
