Repository CMSgov/design-system, pull requests merged in 2022-04, with the labels that each got.

#1680 [WNMGDS-1355] Update i18n documentation
  packages/design-system-docs/src/pages/guidelines/i18n.md
  packages/design-system/src/components/MonthPicker/MonthPicker.stories.jsx
  packages/design-system/src/components/MonthPicker/MonthPicker.tsx
  packages/design-system/src/components/UsaBanner/UsaBanner.stories.jsx
  packages/design-system/src/components/UsaBanner/UsaBanner.tsx
  packages/ds-healthcare-gov/src/components/Footer/Footer.stories.jsx
  packages/ds-healthcare-gov/src/components/Footer/Footer.tsx
  packages/ds-healthcare-gov/src/components/Header/Header.stories.jsx
  packages/ds-healthcare-gov/src/components/Header/Header.tsx
  packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.ts
Labels: Status: Ready For Review

#1687 [NO-TICKET] Remove the `child-design-system` example
  examples/README.md
  examples/child-design-system/.gitignore
  examples/child-design-system/README.md
  examples/child-design-system/babel.config.js
  examples/child-design-system/cmsds.config.js
  examples/child-design-system/docs/src/example.scss
  examples/child-design-system/docs/src/index.scss
  examples/child-design-system/docs/src/pages/components/Button/Button.docs.scss
  examples/child-design-system/docs/src/pages/components/Button/Button.example.jsx
  examples/child-design-system/docs/src/pages/components/Button/button.example.html
  examples/child-design-system/docs/src/pages/components/Card/Card.docs.scss
  examples/child-design-system/docs/src/pages/components/Card/Card.example.jsx
  examples/child-design-system/docs/src/pages/components/Card/card.example.html
  examples/child-design-system/docs/src/pages/utilities/border-style/_border-style.docs.scss
  examples/child-design-system/docs/src/pages/utilities/border-style/border-style.example.html
  examples/child-design-system/package.json
  examples/child-design-system/src/components/Button/Button.jsx
  examples/child-design-system/src/components/Button/Button.test.jsx
  examples/child-design-system/src/components/Button/__snapshots__/Button.test.jsx.snap
  examples/child-design-system/src/components/Card/Card.e2e.test.js
  examples/child-design-system/src/components/Card/Card.jsx
  examples/child-design-system/src/components/Card/Card.test.jsx
  examples/child-design-system/src/components/index.js
  examples/child-design-system/src/fonts/Lato/Lato-Bold.ttf
  examples/child-design-system/src/fonts/Lato/Lato-Italic.ttf
  examples/child-design-system/src/fonts/Lato/Lato-Regular.ttf
  examples/child-design-system/src/fonts/Raleway/Raleway-Bold.ttf
  examples/child-design-system/src/fonts/Raleway/Raleway-Italic.ttf
  examples/child-design-system/src/fonts/Raleway/Raleway-Regular.ttf
  examples/child-design-system/src/fonts/Raleway/Raleway-SemiBold.ttf
  examples/child-design-system/src/images/logo-usa.svg
  examples/child-design-system/src/setupTests.js
  examples/child-design-system/src/styles/base/_index.scss
  examples/child-design-system/src/styles/base/_override.body.scss
  examples/child-design-system/src/styles/base/_override.link.scss
  examples/child-design-system/src/styles/base/_override.typography.scss
  examples/child-design-system/src/styles/components/_Button.scss
  examples/child-design-system/src/styles/components/_Card.scss
  examples/child-design-system/src/styles/components/_index.scss
  examples/child-design-system/src/styles/index.scss
  examples/child-design-system/src/styles/settings/_font.scss
  examples/child-design-system/src/styles/settings/_index.scss
  examples/child-design-system/src/styles/settings/variables/_index.scss
  examples/child-design-system/src/styles/settings/variables/_override.build.scss
  examples/child-design-system/src/styles/settings/variables/_override.color.scss
  examples/child-design-system/src/styles/settings/variables/_override.forms.scss
  examples/child-design-system/src/styles/settings/variables/_override.type.scss
  examples/child-design-system/src/styles/utilities/_border-style.scss
  examples/child-design-system/src/styles/utilities/_index.scss
  examples/child-design-system/tsconfig.json
  packages/design-system-docs/src/pages/startup/child-design-systems.md
  packages/design-system-docs/src/pages/startup/theming.md
  packages/ds-healthcare-gov/README.md
  packages/ds-medicare-gov/README.md
Labels: Status: Ready For Review, Type: Documentation

#1682 [WNMGDS-1340] Replace use of @extend for util classes in Medicare SCSS
  packages/ds-medicare-gov/src/styles/components/_Card.scss
  packages/ds-medicare-gov/src/styles/components/_Navbar.scss
  packages/ds-medicare-gov/src/styles/components/_NavigationMenu.scss
  packages/ds-medicare-gov/src/styles/components/_SimpleFooter.scss
Labels: Status: Ready For Review

#1700 [NO-TICKET] Update README section about loki
  README.md
Labels: Type: Documentation

#1698 [WNMGDS-1376] initial add of gatsby doc site
  .gitignore
  lerna.json
  package.json
  packages/design-system/src/components/ChoiceList/ChoiceList.tsx
  packages/design-system/src/components/DateField/DateField.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/FormControl/FormControl.tsx
  packages/design-system/src/components/MonthPicker/MonthPicker.tsx
  packages/design-system/src/components/TextField/TextField.tsx
  packages/design-system/src/components/__snapshots__/i18n.test.ts.snap
  packages/design-system/src/components/i18n.test.ts
  packages/design-system/src/components/i18n.ts
  packages/docs/README.md
  packages/docs/content/intro.mdx
  packages/docs/gatsby-config.ts
  packages/docs/gatsby-node.js
  packages/docs/package.json
  packages/docs/src/components/DocSiteFooter.tsx
  packages/docs/src/components/DocSiteHeader.tsx
  packages/docs/src/images/favicon.ico
  packages/docs/src/pages/404.tsx
  packages/docs/src/pages/index.tsx
  packages/docs/src/styles/components/footer.scss
  packages/docs/src/styles/components/header.scss
  packages/docs/src/styles/index.scss
  tsconfig.json
  yarn.lock
Labels: Status: Ready For Review

#1717 [BETA-FIX] Fix missing Header export
  packages/ds-healthcare-gov/src/components/Header/Header.tsx
Labels: Status: Ready For Review

#1723 [WNMGDS-1604] Simplify gathering of analytics content
  packages/design-system/src/components/Alert/Alert.tsx
  packages/design-system/src/components/Dialog/Dialog.test.jsx
  packages/design-system/src/components/Dialog/Dialog.tsx
  packages/design-system/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
  packages/design-system/src/components/Drawer/Drawer.tsx
  packages/design-system/src/components/HelpDrawer/HelpDrawer.test.tsx
  packages/design-system/src/components/HelpDrawer/HelpDrawer.tsx
  packages/design-system/src/components/HelpDrawer/__snapshots__/HelpDrawer.test.tsx.snap
  packages/design-system/src/components/analytics/events.test.ts
  packages/design-system/src/components/analytics/events.ts
  packages/design-system/src/components/analytics/index.ts
  packages/design-system/src/components/analytics/useAnalyticsContent.ts
Labels: Status: Ready For Review

#1733 [WNMGDS-1583] Gatsby footer
  packages/design-system-docs/package.json
  packages/design-system-scripts/package.json
  packages/design-system/package.json
  packages/docs/package.json
  packages/docs/src/components/DocSiteFooter.tsx
  packages/docs/src/components/DocSiteNav.tsx
  packages/docs/src/helpers/githubUrl.js
  packages/docs/src/pages/index.tsx
  packages/docs/src/styles/components/footer.scss
  packages/ds-healthcare-gov/package.json
  packages/ds-medicare-gov/package.json
  yarn.lock
Labels: Status: Ready For Review

#1740 [BETA-FIX] Remove bad export of type in ds-healthcare-gov
  packages/ds-healthcare-gov/src/types/index.d.ts
Labels: Status: Ready For Review

#1736 [WNMGDS-1247] Update screen reader readout
  packages/design-system/src/components/FilterChip/FilterChip.test.jsx
  packages/design-system/src/components/FilterChip/FilterChip.tsx
Labels: Status: Ready For Review

#1742 [BETA-FIX] Fix errant TS type in compiled esnext modules
  packages/ds-healthcare-gov/src/components/i18n.ts
Labels: Status: Ready For Review

#1750 Release 3.3.0
  packages/design-system-docs/package.json
  packages/design-system/package.json
  packages/ds-healthcare-gov/package.json
  packages/ds-medicare-gov/package.json
Labels: Status: Ready For Review

#1751 [WNMGDS-1595] info content migration
  packages/docs/content/1_getting-started/0_installation.mdx
  packages/docs/content/1_getting-started/1_using-sass-and-CSS.mdx
  packages/docs/content/1_getting-started/1_using-sass-and-css.mdx
  packages/docs/content/1_getting-started/2_using-components.mdx
  packages/docs/content/1_getting-started/3_theming.mdx
  packages/docs/content/1_getting-started/4_child-design-systems.mdx
  packages/docs/content/1_getting-started/5_examples.mdx
  packages/docs/content/1_getting-started/6_migrating-to-v2.mdx
  packages/docs/content/2_guidelines/0_accessibility.mdx
  packages/docs/content/2_guidelines/1_code-conventions.mdx
  packages/docs/content/2_guidelines/2_component-maturity.mdx
  packages/docs/content/2_guidelines/3_design-principles.mdx
  packages/docs/content/2_guidelines/4_forms.mdx
  packages/docs/content/2_guidelines/5_internationalization.mdx
  packages/docs/content/2_guidelines/6_responsive-design.mdx
  packages/docs/content/2_guidelines/7_browser-support.mdx
  packages/docs/content/2_guidelines/accessibility.mdx
  packages/docs/content/intro.mdx
  packages/docs/gatsby-node.js
  packages/docs/src/components/ContentRenderer.tsx
  packages/docs/src/components/DocSiteFooter.tsx
  packages/docs/src/components/DocSiteSidebar.tsx
  packages/docs/src/components/InfoPage.tsx
  packages/docs/src/helpers/casingUtils.ts
  packages/docs/src/helpers/githubUrl.js
  packages/docs/src/helpers/graphQLTypes.ts
  packages/docs/src/helpers/urlUtils.ts
  packages/docs/src/styles/components/syntax-highlighting.scss
  packages/docs/src/styles/index.scss
  yarn.lock
Labels: Status: Ready For Review

#1758 [WNMGDS-1580] Use i18n for icon components
  packages/design-system/src/components/Icons/AddIcon.tsx
  packages/design-system/src/components/Icons/AlertCircleIcon.tsx
  packages/design-system/src/components/Icons/ArrowIcon.tsx
  packages/design-system/src/components/Icons/ArrowsStacked.tsx
  packages/design-system/src/components/Icons/BuildingCircleIcon.tsx
  packages/design-system/src/components/Icons/CheckCircleIcon.tsx
  packages/design-system/src/components/Icons/CheckIcon.tsx
  packages/design-system/src/components/Icons/CloseIcon.tsx
  packages/design-system/src/components/Icons/CloseIconThin.tsx
  packages/design-system/src/components/Icons/DownloadIcon.tsx
  packages/design-system/src/components/Icons/ExternalLinkIcon.tsx
  packages/design-system/src/components/Icons/HhsLogo.tsx
  packages/design-system/src/components/Icons/ImageIcon.tsx
  packages/design-system/src/components/Icons/InfoCircleIcon.tsx
  packages/design-system/src/components/Icons/InfoCircleIconThin.tsx
  packages/design-system/src/components/Icons/LockCircleIcon.tsx
  packages/design-system/src/components/Icons/LockIcon.tsx
  packages/design-system/src/components/Icons/MenuIcon.tsx
  packages/design-system/src/components/Icons/MenuIconThin.tsx
  packages/design-system/src/components/Icons/NextIcon.tsx
  packages/design-system/src/components/Icons/RemoveIcon.tsx
  packages/design-system/src/components/Icons/StarIcon.tsx
  packages/design-system/src/components/Icons/UsaFlagIcon.tsx
  packages/design-system/src/components/Icons/UsaLogo.tsx
  packages/design-system/src/components/Icons/WarningIcon.tsx
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
Labels: Status: Ready For Review

#1759 [WNMGDS-1580] Use i18n for MonthPicker content
  packages/design-system/src/components/MonthPicker/MonthPicker.tsx
Labels: Status: Ready For Review

#1760 [WNMGDS-1580] Use i18n in Pagination and migrate tests to testing-library
  packages/design-system/src/components/Pagination/Pagination.test.tsx
  packages/design-system/src/components/Pagination/Pagination.tsx
  packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
Labels: Status: Ready For Review

#1761 [WNMGDS-1580] Use i18n for remaining components
  packages/design-system/src/components/Review/Review.tsx
  packages/design-system/src/components/SkipNav/SkipNav.tsx
  packages/design-system/src/components/Spinner/Spinner.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItemLabel.test.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItemLabel.tsx
  packages/design-system/src/components/VerticalNav/__snapshots__/VerticalNavItemLabel.test.tsx.snap
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
Labels: Status: Ready For Review

#1757 [WNMGDS-1580] Use i18n for components A-F
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/DateField/DateField.tsx
  packages/design-system/src/components/DateField/DateInput.tsx
  packages/design-system/src/components/Dialog/Dialog.tsx
  packages/design-system/src/components/Drawer/Drawer.tsx
  packages/design-system/src/components/FilterChip/FilterChip.test.jsx
  packages/design-system/src/components/FilterChip/FilterChip.tsx
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
Labels: Status: Ready For Review

#1756 [WNMGDS-1580] Add default Spanish content
  packages/design-system/src/components/Accordion/AccordionItem.tsx
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/DateField/DateField.tsx
  packages/design-system/src/components/DateField/DateInput.tsx
  packages/design-system/src/components/Dialog/Dialog.tsx
  packages/design-system/src/components/Drawer/Drawer.tsx
  packages/design-system/src/components/FilterChip/FilterChip.test.jsx
  packages/design-system/src/components/FilterChip/FilterChip.tsx
  packages/design-system/src/components/Icons/AddIcon.tsx
  packages/design-system/src/components/Icons/AlertCircleIcon.tsx
  packages/design-system/src/components/Icons/ArrowIcon.tsx
  packages/design-system/src/components/Icons/ArrowsStacked.tsx
  packages/design-system/src/components/Icons/BuildingCircleIcon.tsx
  packages/design-system/src/components/Icons/CheckCircleIcon.tsx
  packages/design-system/src/components/Icons/CheckIcon.tsx
  packages/design-system/src/components/Icons/CloseIcon.tsx
  packages/design-system/src/components/Icons/CloseIconThin.tsx
  packages/design-system/src/components/Icons/DownloadIcon.tsx
  packages/design-system/src/components/Icons/ExternalLinkIcon.tsx
  packages/design-system/src/components/Icons/HhsLogo.tsx
  packages/design-system/src/components/Icons/ImageIcon.tsx
  packages/design-system/src/components/Icons/InfoCircleIcon.tsx
  packages/design-system/src/components/Icons/InfoCircleIconThin.tsx
  packages/design-system/src/components/Icons/LockCircleIcon.tsx
  packages/design-system/src/components/Icons/LockIcon.tsx
  packages/design-system/src/components/Icons/MenuIcon.tsx
  packages/design-system/src/components/Icons/MenuIconThin.tsx
  packages/design-system/src/components/Icons/NextIcon.tsx
  packages/design-system/src/components/Icons/RemoveIcon.tsx
  packages/design-system/src/components/Icons/StarIcon.tsx
  packages/design-system/src/components/Icons/UsaFlagIcon.tsx
  packages/design-system/src/components/Icons/UsaLogo.tsx
  packages/design-system/src/components/Icons/WarningIcon.tsx
  packages/design-system/src/components/MonthPicker/MonthPicker.tsx
  packages/design-system/src/components/Pagination/Pagination.test.tsx
  packages/design-system/src/components/Pagination/Pagination.tsx
  packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/design-system/src/components/Review/Review.tsx
  packages/design-system/src/components/SkipNav/SkipNav.tsx
  packages/design-system/src/components/Spinner/Spinner.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItemLabel.test.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItemLabel.tsx
  packages/design-system/src/components/VerticalNav/__snapshots__/VerticalNavItemLabel.test.tsx.snap
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
Labels: Status: Ready For Review
