Repository CMSgov/design-system, pull requests merged in 2022-06, with the labels that each got.

#1875 [WNMGDS-1675] component content pt 3
  packages/design-system/src/components/Dialog/Dialog.stories.jsx
  packages/design-system/src/components/Icons/icons.stories.tsx
  packages/docs/content/5_components/icon.mdx
  packages/docs/content/5_components/idle-timeout.mdx
  packages/docs/content/5_components/masked-field.mdx
  packages/docs/content/5_components/modal-dialog.mdx
  packages/docs/content/5_components/month-picker.mdx
  packages/docs/content/5_components/pagination.mdx
  packages/docs/content/5_components/skip-nav.mdx
Labels: Status: Ready For Review

#1797 [WNMGDS-765] Remove duplicate SR content in UsaBanner
  packages/design-system/src/components/UsaBanner/UsaBanner.tsx
  packages/design-system/src/components/UsaBanner/__snapshots__/UsaBanner.test.jsx.snap
Labels: Status: Ready For Review

#1881 [WNMGDS-1712] icon props bugfix
  packages/design-system/src/components/Icons/StarIcon.tsx
  packages/design-system/src/components/Icons/SvgIcon.test.tsx
  packages/design-system/src/components/Icons/SvgIcon.tsx
  packages/design-system/src/components/Icons/__snapshots__/SvgIcon.test.tsx.snap
  packages/design-system/src/components/Icons/icons.stories.tsx
  packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/design-system/src/components/UsaBanner/__snapshots__/UsaBanner.test.jsx.snap
Labels: Status: Ready For Review

#1883 [NO-TICKET] manual dependency updates for security bumps
  packages/design-system-scripts/gulp/docs/extractReactData/reactDocgenHandler.js
  packages/design-system-scripts/gulp/docs/generatePages/processMarkdownPage.js
  packages/design-system-scripts/package.json
  yarn.lock
Labels: Status: Ready For Review

#1887 [WNMGDS-1713] Date field docs
  packages/design-system-docs/src/pages/components/DatePicker/DatePicker.example.jsx
  packages/design-system-docs/src/pages/components/DatePicker/_CalendarPickerDateField.docs.scss
  packages/design-system-docs/src/pages/components/MultiInputDateField/MultiInputDateField.example.jsx
  packages/design-system-docs/src/pages/components/MultiInputDateField/_MultiInputDateField.docs.scss
  packages/design-system-docs/src/pages/components/MultiInputDateField/multiinputdatefield.example.html
  packages/design-system-docs/src/pages/components/SingleInputDateField/SingleInputDateField.example.jsx
  packages/design-system-docs/src/pages/components/SingleInputDateField/_SingleInputDateField.docs.scss
  packages/design-system-docs/src/pages/components/SingleInputDateField/singleinputdatefield.example.html
  packages/design-system/src/components/DateField/index.ts
  packages/ds-healthcare-gov/docs/src/pages/components/DateField/_DateField.docs.scss
  packages/ds-healthcare-gov/docs/src/pages/components/DateField/datefield.example.html
  packages/ds-healthcare-gov/docs/src/pages/components/MultiInputDateField/_MultiInputDateField.docs.scss
  packages/ds-healthcare-gov/docs/src/pages/components/SingleInputDateField/_SingleInputDateField.docs.scss
Labels: Status: Ready For Review

#1889 [WNMGDS-1641] Implement styled custom controls for DayPicker
  .loki/reference/chrome_iphone7_Components_Icons_Available_Icons.png
  .loki/reference/chrome_iphone7_Components_MultiInputDateField_Controlled_Multi_Input_Date_Field.png
  .loki/reference/chrome_iphone7_Components_MultiInputDateField_Inverted_Multi_Input_Date_Field.png
  .loki/reference/chrome_iphone7_Components_MultiInputDateField_Multi_Input_Date_Field_Default.png
  .loki/reference/chrome_iphone7_Components_SingleInputDateField_Default.png
  .loki/reference/chrome_iphone7_Components_SingleInputDateField_With_Error.png
  .loki/reference/chrome_iphone7_Components_SingleInputDateField_With_Picker.png
  .loki/reference/chrome_iphone7_Components_Text_Field_Label_Masked_Field.png
  .loki/reference/chrome_laptop_Components_Icons_Available_Icons.png
  .loki/reference/chrome_laptop_Components_MultiInputDateField_Controlled_Multi_Input_Date_Field.png
  .loki/reference/chrome_laptop_Components_MultiInputDateField_Inverted_Multi_Input_Date_Field.png
  .loki/reference/chrome_laptop_Components_MultiInputDateField_Multi_Input_Date_Field_Default.png
  .loki/reference/chrome_laptop_Components_SingleInputDateField_Default.png
  .loki/reference/chrome_laptop_Components_SingleInputDateField_With_Error.png
  .loki/reference/chrome_laptop_Components_SingleInputDateField_With_Picker.png
  .loki/reference/chrome_laptop_Components_Text_Field_Label_Masked_Field.png
  packages/design-system-docs/src/pages/components/Icon/IconComponent.example.jsx
  packages/design-system/src/components/DateField/CustomDayPicker.tsx
  packages/design-system/src/components/DateField/CustomDayPickerCaption.tsx
  packages/design-system/src/components/DateField/SingleInputDateField.stories.jsx
  packages/design-system/src/components/DateField/SingleInputDateField.test.tsx
  packages/design-system/src/components/DateField/SingleInputDateField.tsx
  packages/design-system/src/components/DateField/__snapshots__/SingleInputDateField.test.tsx.snap
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/FormControl/FormControl.tsx
  packages/design-system/src/components/FormLabel/useFormLabel.tsx
  packages/design-system/src/components/Icons/icons.stories.tsx
  packages/design-system/src/components/Icons/index.ts
  packages/design-system/src/components/TextField/TextField.tsx
  packages/design-system/src/styles/components/_SingleInputDateField.scss
  packages/design-system/src/styles/components/_TextField.scss
  packages/design-system/src/styles/settings/variables/_forms.scss
Labels: Status: Ready For Review

#1901 [NO-TICKET] utilities unit tests
  packages/design-system-scripts/jest/unit.config.js
  packages/design-system/src/components/utilities/useClickOutsideHandler.test.tsx
  packages/design-system/src/components/utilities/usePressEscapeHandler.test.tsx
Labels: Status: Ready For Review

#1903 [NO-TICKET] Use trailing slashes for all internal links in Gatsby
  packages/docs/content/1_getting-started/1_using-sass-and-cSS.mdx
  packages/docs/content/1_getting-started/1_using-sass-and-css.mdx
  packages/docs/content/1_getting-started/3_theming.mdx
  packages/docs/content/2_guidelines/1_code-conventions.mdx
  packages/docs/content/2_guidelines/4_forms.mdx
  packages/docs/content/3_styles/3_spacing.mdx
  packages/docs/content/4_utilities/2_layout-grid.mdx
  packages/docs/content/4_utilities/display-visibility.mdx
  packages/docs/content/4_utilities/flexbox.mdx
  packages/docs/content/4_utilities/float.mdx
  packages/docs/content/4_utilities/font-size.mdx
  packages/docs/content/4_utilities/margin.mdx
  packages/docs/content/4_utilities/padding.mdx
  packages/docs/content/4_utilities/text-align.mdx
  packages/docs/content/5_components/autocomplete.mdx
  packages/docs/content/5_components/checkbox-and-radio.mdx
  packages/docs/content/5_components/dropdown.mdx
  packages/docs/content/5_components/idle-timeout.mdx
  packages/docs/content/5_components/modal-dialog.mdx
  packages/docs/content/5_components/spinner.mdx
  packages/docs/content/5_components/tabs.mdx
  packages/docs/content/5_components/text-field.mdx
  packages/docs/content/5_components/vertical-navigation.mdx
  packages/docs/content/6_patterns/documentation-page.mdx
  packages/docs/content/6_patterns/third-party-external-link.mdx
  packages/docs/content/intro.mdx
  packages/docs/src/helpers/urlUtils.ts
Labels: Status: Ready For Review

#1905 [WNMGDS-1698] Hide the instructions for the day picker visually
  packages/design-system/src/components/DateField/CustomDayPicker.tsx
  packages/design-system/src/styles/components/_SingleInputDateField.scss
Labels: Status: Ready For Review

#1919 [WNMGDS-1684] Add command to deploy branch demo to GitHub Pages
  README.md
  package.json
  scripts/deploy-demo.sh
Labels: Status: Ready For Review

#1928 [WNMGDS-1771] Fix locale link relying on deprecated `initialLanguage` prop
  packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.test.js
  packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.ts
  packages/ds-healthcare-gov/src/components/Header/localeLink.ts
Labels: Status: Ready For Review

#1932 [WNMGDS-1772] BUGFIX: medicare focus-dark was missing the correct color
  packages/design-system-tokens/src/themes/medicare.ts
  packages/ds-medicare-gov/src/styles/settings/variables/_medicare-theme.scss
Labels: Type: Bug, Release: Patch

#1934 [WNMGDS-1773] Fix long choice hint text wrapping the whole label in Safari
  packages/design-system/src/styles/components/_Choice.scss
Labels: Status: Ready For Review, Release: Patch

#1930 [No-ticket] Fix for node-sass deprecation warnings
  package.json
  packages/design-system-scripts/gulp/sass.js
  packages/design-system-scripts/package.json
  packages/design-system/src/styles/components/_Choice.scss
  packages/design-system/src/styles/components/_FilterChip.scss
  packages/design-system/src/styles/components/_Spinner.scss
  packages/design-system/src/styles/components/_StepList.scss
  packages/design-system/src/styles/components/_UsaBanner.scss
  packages/design-system/src/styles/settings/mixins/_layout.scss
  packages/design-system/src/styles/utilities/_grid.scss
  packages/docs/src/styles/components/footer.scss
  packages/ds-healthcare-gov/src/styles/components/_Inset.scss
  yarn.lock
Labels: Status: In JIRA, Type: Build Process

#1913 [EDUCATE-380] Add HCgov specific Accordion
  packages/design-system-docs/src/pages/components/Icon/IconComponent.example.jsx
  packages/design-system-tokens/src/themes/healthcare-components.ts
  packages/design-system/src/components/Accordion/AccordionItem.tsx
  packages/design-system/src/components/Accordion/__snapshots__/AccordionItem.test.tsx.snap
  packages/design-system/src/components/Icons/MinusCircleIcon.tsx
  packages/design-system/src/components/Icons/PlusCircleIcon.tsx
  packages/design-system/src/components/Icons/icons.stories.tsx
  packages/design-system/src/components/Icons/index.ts
  packages/design-system/src/styles/components/_SvgIcon.scss
  packages/ds-healthcare-gov/docs/src/pages/components/Accordion/Accordion.example.jsx
  packages/ds-healthcare-gov/docs/src/pages/components/Accordion/_Accordion.docs.scss
  packages/ds-healthcare-gov/docs/src/pages/components/Accordion/accordion.example.html
  packages/ds-healthcare-gov/src/components/Accordion/Accordion.stories.jsx
  packages/ds-healthcare-gov/src/components/Accordion/AccordionItem.tsx
  packages/ds-healthcare-gov/src/components/Accordion/index.tsx
  packages/ds-healthcare-gov/src/components/index.js
  packages/ds-healthcare-gov/src/styles/components/_Accordion.scss
  packages/ds-healthcare-gov/src/styles/components/_index.scss
  packages/ds-healthcare-gov/src/styles/settings/_healthcare-components-theme.scss
Labels: Status: Ready For Review

#1926 [WNMGDS-1720] css variable exporter
  .storybook/_core-components-scss-to-css.map.scss
  .storybook/_core-components-theme.css
  .storybook/_core-scss-to-css.map.scss
  .storybook/_core-theme.css
  .storybook/_healthcare-components-scss-to-css.map.scss
  .storybook/_healthcare-components-theme.css
  .storybook/_healthcare-scss-to-css.map.scss
  .storybook/_healthcare-theme.css
  .storybook/_medicare-components-scss-to-css.map.scss
  .storybook/_medicare-components-theme.css
  .storybook/_medicare-scss-to-css.map.scss
  .storybook/_medicare-theme.css
  packages/design-system-tokens/README.md
  packages/design-system-tokens/src/copy_themes.sh
  packages/design-system-tokens/src/index.ts
  packages/design-system-tokens/src/lib/exportCssVars.ts
  packages/design-system/src/styles/components/_Autocomplete.scss
  packages/design-system/src/styles/components/_Choice.scss
  packages/design-system/src/styles/components/_DateField.scss
  packages/design-system/src/styles/components/_Dropdown.scss
  packages/design-system/src/styles/components/_SkipNav.scss
  packages/design-system/src/styles/utilities/_grid.scss
  packages/docs/src/components/Layout.tsx
  packages/docs/src/styles/components/footer.scss
  packages/docs/src/styles/components/navigation.scss
  packages/docs/src/styles/index.scss
  packages/docs/src/styles/theme-variables/_core-components-scss-to-css.map.scss
  packages/docs/src/styles/theme-variables/_core-components-theme.css
  packages/docs/src/styles/theme-variables/_core-scss-to-css.map.scss
  packages/docs/src/styles/theme-variables/_core-theme.css
  packages/docs/src/styles/theme-variables/_healthcare-components-scss-to-css.map.scss
  packages/docs/src/styles/theme-variables/_healthcare-components-theme.css
  packages/docs/src/styles/theme-variables/_healthcare-scss-to-css.map.scss
  packages/docs/src/styles/theme-variables/_healthcare-theme.css
  packages/docs/src/styles/theme-variables/_medicare-components-scss-to-css.map.scss
  packages/docs/src/styles/theme-variables/_medicare-components-theme.css
  packages/docs/src/styles/theme-variables/_medicare-scss-to-css.map.scss
  packages/docs/src/styles/theme-variables/_medicare-theme.css
  packages/ds-medicare-gov/src/styles/components/_NavigationMenu.scss
Labels: Status: Ready For Review

#1917 [WNMGDS-1687] NewRelic monitoring for doc site
  .nvmrc
  packages/docs/gatsby-config.ts
  packages/docs/package.json
  yarn.lock
Labels: Status: Ready For Review

#1940 Release 3.6.0
  packages/design-system-docs/package.json
  packages/design-system-scripts/package.json
  packages/design-system/package.json
  packages/docs/package.json
  packages/ds-healthcare-gov/package.json
  packages/ds-medicare-gov/package.json
Labels: Status: Ready For Review
