Repository CMSgov/design-system, pull requests merged in 2023-11, with the labels that each got.

#2776 [WNMGDS-2545] Reorganize the font tokens
  .storybook/static/cmsgov-theme.css
  .storybook/static/core-theme.css
  .storybook/static/healthcare-theme.css
  .storybook/static/medicare-theme.css
  packages/design-system-tokens/src/themes/cmsgov-component.ts
  packages/design-system-tokens/src/themes/cmsgov.ts
  packages/design-system-tokens/src/themes/core-component.ts
  packages/design-system-tokens/src/themes/core.ts
  packages/design-system-tokens/src/themes/healthcare-component.ts
  packages/design-system-tokens/src/themes/healthcare.ts
  packages/design-system-tokens/src/themes/medicare-component.ts
  packages/design-system-tokens/src/themes/medicare.ts
  packages/design-system-tokens/src/tokens/animation.ts
  packages/design-system-tokens/src/tokens/color.ts
  packages/design-system-tokens/src/tokens/font.ts
  packages/design-system-tokens/src/tokens/index.ts
  packages/design-system-tokens/src/tokens/measure.ts
  packages/design-system-tokens/src/tokens/media.ts
  packages/design-system-tokens/src/tokens/radius.ts
  packages/design-system-tokens/src/tokens/spacer.ts
  packages/design-system-tokens/src/tokens/time.ts
  packages/design-system-tokens/src/tokens/zIndex.ts
  packages/design-system/src/styles/_base.scss
  packages/design-system/src/styles/components/_Label.scss
  packages/design-system/src/styles/core-theme.css
  packages/docs/src/components/content/ColorRamps.tsx
  packages/docs/src/helpers/themeTokens.ts
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/docs/static/themes/medicare-theme.css
  packages/ds-cms-gov/src/styles/cmsgov-theme.css
  packages/ds-healthcare-gov/src/styles/healthcare-theme.css
  packages/ds-medicare-gov/src/styles/_base.scss
  packages/ds-medicare-gov/src/styles/components/_Forms.scss
  packages/ds-medicare-gov/src/styles/components/_HelpDrawer.scss
  packages/ds-medicare-gov/src/styles/medicare-theme.css
Labels: Type: Breaking, Impacts: Core

#2772 [WNMGDS-2546] Add `ds-dropdown` web component
  .storybook/docs/WebComponentArgsTable.tsx
  .storybook/docs/WebComponentDocTemplate.mdx
  .storybook/docs/WebComponentEventsTable.tsx
  examples/cdn-web-components/index.html
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/design-system/src/components/web-components/__snapshots__/ds-dropdown.test.tsx.snap
  packages/design-system/src/components/web-components/ds-button.stories.tsx
  packages/design-system/src/components/web-components/ds-dropdown.stories.tsx
  packages/design-system/src/components/web-components/ds-dropdown.test.tsx
  packages/design-system/src/components/web-components/ds-dropdown.tsx
  packages/design-system/src/components/web-components/index.ts
  packages/design-system/src/components/web-components/preactement/define.ts
  packages/design-system/src/components/web-components/wrapperUtils.ts
  tests/browser/story-screenshots.test.ts
Labels: Impacts: Core, Type: Added

#2778 [WNMGDS-2534] Add docs for team to set up basic js frameworks + wc implementation
  packages/design-system/src/components/web-components/README.md
Labels: Type: Internal

#2780 [WNMGDS-2519] Deprecate textClassName from Label
  packages/design-system/src/components/Label/Label.tsx
Labels: Type: Breaking, Impacts: Core

#2782 [WNMGDS-2552] Add reference links to design artboards in Sketch cloud
  packages/docs/content/components/autocomplete.mdx
  packages/docs/content/components/checkbox.mdx
  packages/docs/content/components/drawer.mdx
  packages/docs/content/components/dropdown.mdx
  packages/docs/content/components/icon.mdx
  packages/docs/content/components/spinner.mdx
  packages/docs/content/components/usa-banner.mdx
  packages/docs/content/foundation/layout-grid/layout-grid.mdx
  packages/docs/content/foundation/spacing.mdx
  packages/docs/content/layouts/Healthcare/one-col-page-layout.mdx
  packages/docs/content/layouts/documentation-page.mdx
Labels: Impacts: Documentation, Type: Added

#2781 [WNMGDS-2550] Work around React/Google-Translate incompatibility in healthcare header
  packages/ds-healthcare-gov/src/components/Header/ActionMenu.tsx
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/ActionMenu.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/Header.test.tsx.snap
Labels: Type: Fixed, Impacts: Healthcare

#2785 [WNMGDS-2556] Fix the Dropdown not scrolling to the selected item when using pointer
  packages/design-system/src/components/Dropdown/Dropdown.test.interaction.ts
  packages/design-system/src/components/Dropdown/DropdownMenuOption.tsx
  packages/design-system/src/components/Dropdown/DropdownMenuSection.tsx
  tests/unit/setupTests.js
Labels: Type: Fixed, Impacts: Core

#2797 [WNMGDS-2557] Restore ability to disable autocompletes
  packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
Labels: Type: Fixed, Impacts: Core

#2798 [WNMGDS-1922] Update prop type definitions to support passthrough attributes
  packages/design-system/src/components/Badge/Badge.tsx
  packages/design-system/src/components/DateField/SingleInputDateField.tsx
  packages/design-system/src/components/Icons/SvgIcon.tsx
  packages/design-system/src/components/Tooltip/Tooltip.test.tsx
  packages/design-system/src/components/Tooltip/Tooltip.tsx
  packages/design-system/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
Labels: Type: Breaking, Impacts: Core

#2799 [WNMGDS-1922] Document pass-through props in Storybook dev docs
  .storybook/docs/DocumentationTemplate.mdx
  .storybook/docs/HtmlElementArgs.tsx
  .storybook/docs/WebComponentDocTemplate.mdx
  package.json
  packages/design-system/src/components/Badge/Badge.stories.tsx
  packages/design-system/src/components/Button/Button.stories.tsx
  packages/design-system/src/components/ChoiceList/Choice.stories.tsx
  packages/design-system/src/components/DateField/SingleInputDateField.stories.tsx
  packages/design-system/src/components/Dialog/Dialog.stories.tsx
  packages/design-system/src/components/Dropdown/Dropdown.stories.tsx
  packages/design-system/src/components/Icons/icons.stories.tsx
  packages/design-system/src/components/Label/Label.stories.tsx
  packages/design-system/src/components/Table/Table.stories.tsx
  packages/design-system/src/components/TextField/TextField.stories.tsx
  packages/design-system/src/components/Tooltip/Tooltip.stories.tsx
  packages/design-system/src/components/web-components/ds-badge.stories.tsx
  packages/design-system/src/components/web-components/ds-button.stories.tsx
  packages/design-system/src/components/web-components/ds-dropdown.stories.tsx
  yarn.lock
Labels: Impacts: Documentation, Type: Added

#2784 [NO-TICKET] Fix up text tokens and usage
  packages/design-system-tokens/src/themes/cmsgov-component.ts
  packages/design-system-tokens/src/themes/core-component.ts
  packages/design-system-tokens/src/themes/healthcare-component.ts
  packages/design-system-tokens/src/themes/medicare-component.ts
  packages/design-system/src/styles/_base.scss
Labels: Type: Breaking, Impacts: Core

#2805 [NO-TICKET] Adding a name property to the DropdownChangeObject
  packages/design-system/src/components/Dropdown/Dropdown.test.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
Labels: Impacts: Core, Type: Added

#2813 [NO TICKET] Include designer approval as requirement
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Type: Internal, Impacts: Documentation

#2818 [WNMGDS-2570] Remove redundant table role to fix axe-core error
  packages/design-system/src/components/PrivacySettingsDialog/__snapshots__/PrivacySettingsTable.test.jsx.snap
  packages/design-system/src/components/Table/Table.tsx
  packages/design-system/src/components/Table/__snapshots__/Table.test.tsx.snap
  tests/browser/stories.test.ts
Labels: Type: Fixed, Impacts: Core

#2819 [WNMGDS-2550] Work around React/Google-Translate issue in dropdown options
  packages/design-system/dist.zip
  packages/design-system/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/design-system/src/components/Dropdown/DropdownMenuOption.tsx
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#2824 [NO-TICKET] Fix alert body content flowing out of bounds
  packages/design-system/src/styles/components/_Alert.scss
Labels: Type: Fixed, Impacts: Core

#2814 [WNMGDS-2523] Feature branch for replacing `useFormLabel` with smaller hooks
  package.json
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/ChoiceList/Choice.stories.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.stories.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.tsx
  packages/design-system/src/components/DateField/MultiInputDateField.stories.tsx
  packages/design-system/src/components/DateField/MultiInputDateField.test.tsx
  packages/design-system/src/components/DateField/MultiInputDateField.tsx
  packages/design-system/src/components/DateField/SingleInputDateField.stories.tsx
  packages/design-system/src/components/DateField/SingleInputDateField.tsx
  packages/design-system/src/components/Dropdown/Dropdown.stories.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/FormLabel/index.ts
  packages/design-system/src/components/FormLabel/useFormLabel.tsx
  packages/design-system/src/components/Hint/useHint.tsx
  packages/design-system/src/components/InlineError/index.ts
  packages/design-system/src/components/InlineError/useInlineError.tsx
  packages/design-system/src/components/Label/Label.stories.tsx
  packages/design-system/src/components/Label/Label.test.tsx
  packages/design-system/src/components/Label/__snapshots__/Label.test.tsx.snap
  packages/design-system/src/components/Label/useLabelProps.ts
  packages/design-system/src/components/MonthPicker/MonthPicker.stories.tsx
  packages/design-system/src/components/MonthPicker/MonthPicker.tsx
  packages/design-system/src/components/TextField/Mask.test.tsx
  packages/design-system/src/components/TextField/TextField.stories.tsx
  packages/design-system/src/components/TextField/TextField.test.tsx
  packages/design-system/src/components/TextField/TextField.tsx
  packages/design-system/src/components/TextField/TextInput.test.tsx
  packages/design-system/src/components/TextField/TextInput.tsx
  packages/design-system/src/components/TextField/__snapshots__/TextInput.test.tsx.snap
  packages/design-system/src/components/flags.ts
  packages/design-system/src/components/utilities/cleanFieldProps.ts
  packages/design-system/src/components/utilities/describeField.ts
  packages/design-system/src/components/web-components/ds-dropdown.tsx
  packages/ds-healthcare-gov/src/components/index.ts
  packages/ds-healthcare-gov/src/components/web-components/index.ts
  tests/browser/snapshots/storybook-docs/Docs-Components-ChoiceList-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Dropdown-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-MonthPicker-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-MultiInputDateField-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-SingleInputDateField-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-TextField-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Breaking, Impacts: Core
