Repository CMSgov/design-system, pull requests merged in 2023-04, with the labels that each got.

#2452 [WNMGDS-2262] Improve side nav a11y
  packages/docs/src/components/layout/DocSiteNavigation.tsx
  packages/docs/src/styles/components/navigation.scss
  packages/docs/src/styles/components/themeSwitcher.scss
  packages/docs/src/styles/index.scss
Labels: Impacts: Documentation, Type: Changed

#2449 [WNMGDS-2112] Add accent colors to themes
  .storybook/static/cmsgov-theme.css
  .storybook/static/core-theme.css
  .storybook/static/healthcare-theme.css
  .storybook/static/medicare-theme.css
  packages/design-system-tokens/src/themes/cmsgov.ts
  packages/design-system-tokens/src/themes/core.ts
  packages/design-system-tokens/src/themes/healthcare.ts
  packages/design-system-tokens/src/themes/medicare.ts
  packages/design-system/src/styles/core-theme.css
  packages/design-system/src/styles/utilities/_background-color.scss
  packages/docs/content/foundation/theme-colors.mdx
  packages/docs/content/utilities/background-color.mdx
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/docs/static/themes/medicare-theme.css
  packages/ds-cms-gov/src/styles/cmsgov-theme.css
  packages/ds-healthcare-gov/src/styles/healthcare-theme.css
  packages/ds-medicare-gov/src/styles/medicare-theme.css
Labels: Impacts: Core, Type: Added

#2453 [WNMGDS-2226] Update privacy settings content
  packages/design-system/src/components/PrivacySettingsDialog/__snapshots__/PrivacySettingsTable.test.jsx.snap
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
  packages/ds-healthcare-gov/src/styles/components/_Footer.scss
  tests/browser/snapshots/components-privacysettingsdialog--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/components-privacysettingsdialog--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/components-privacysettingsdialog--default-cmsgov--chromium.png
  tests/browser/snapshots/components-privacysettingsdialog--default-cmsgov--firefox.png
  tests/browser/snapshots/components-privacysettingsdialog--default-cmsgov--webkit.png
  tests/browser/snapshots/components-privacysettingsdialog--default-core--Mobile-Chrome.png
  tests/browser/snapshots/components-privacysettingsdialog--default-core--chromium-forced-colors.png
  tests/browser/snapshots/components-privacysettingsdialog--default-core--chromium.png
  tests/browser/snapshots/components-privacysettingsdialog--default-core--firefox.png
  tests/browser/snapshots/components-privacysettingsdialog--default-core--webkit.png
  tests/browser/snapshots/components-privacysettingsdialog--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/components-privacysettingsdialog--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/components-privacysettingsdialog--default-healthcare--chromium.png
  tests/browser/snapshots/components-privacysettingsdialog--default-healthcare--firefox.png
  tests/browser/snapshots/components-privacysettingsdialog--default-healthcare--webkit.png
  tests/browser/snapshots/components-privacysettingsdialog--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/components-privacysettingsdialog--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-privacysettingsdialog--default-medicare--chromium.png
  tests/browser/snapshots/components-privacysettingsdialog--default-medicare--firefox.png
  tests/browser/snapshots/components-privacysettingsdialog--default-medicare--webkit.png
Labels: Impacts: Core, Type: Changed

#2459 [WNMGDS-2212] Many storybook stories updated for easier control via args.
  packages/design-system/src/components/Alert/Alert.stories.jsx
  packages/design-system/src/components/Autocomplete/Autocomplete.stories.jsx
  packages/design-system/src/components/Badge/Badge.stories.jsx
  packages/design-system/src/components/Button/Button.stories.jsx
  packages/design-system/src/components/ChoiceList/Choice.stories.jsx
  packages/design-system/src/components/ChoiceList/ChoiceList.stories.jsx
  packages/design-system/src/components/DateField/MultiInputDateField.stories.jsx
  packages/design-system/src/components/DateField/SingleInputDateField.stories.jsx
  packages/design-system/src/components/Drawer/Drawer.stories.jsx
  packages/design-system/src/components/Dropdown/Dropdown.stories.jsx
  packages/design-system/src/components/FormLabel/FormLabel.stories.jsx
  packages/design-system/src/components/HelpDrawer/HelpDrawer.stories.jsx
  packages/design-system/src/components/MonthPicker/MonthPicker.stories.jsx
  packages/design-system/src/components/SkipNav/SkipNav.stories.jsx
  packages/design-system/src/components/Spinner/Spinner.stories.jsx
  packages/design-system/src/components/TextField/TextField.stories.jsx
  packages/design-system/src/components/Tooltip/Tooltip.stories.jsx
  packages/design-system/src/components/VerticalNav/VerticalNav.stories.jsx
  tests/browser/snapshots/datefield--picker-interaction--cmsgov--webkit.png
Labels: Type: Internal, Impacts: Core

#2456 [WNMGDS-1828] Add version switcher to doc site
  packages/docs/src/components/layout/DocSiteNavigation.tsx
  packages/docs/src/components/layout/VersionSwitcher.tsx
  scripts/append-versions.ts
  scripts/bump-and-tag-release.sh
  scripts/bump-main.sh
  versions.json
Labels: Impacts: Documentation, Type: Added

#2457 [WNMGDS-2236] Initial redesign of hgov footer
  packages/ds-healthcare-gov/src/components/Footer/Footer.tsx
  packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.tsx
  packages/ds-healthcare-gov/src/components/Footer/LogosRow.tsx
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/InlineLinkLists.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/LogosRow.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Logo/Logo.tsx
  packages/ds-healthcare-gov/src/components/Logo/LogoEnSvg.test.tsx
  packages/ds-healthcare-gov/src/components/Logo/LogoEnSvg.tsx
  packages/ds-healthcare-gov/src/components/Logo/LogoEsSvg.test.jsx
  packages/ds-healthcare-gov/src/components/Logo/LogoEsSvg.tsx
  packages/ds-healthcare-gov/src/components/locale/en.json
  packages/ds-healthcare-gov/src/components/locale/es.json
  packages/ds-healthcare-gov/src/styles/components/_Footer.scss
  packages/ds-healthcare-gov/src/styles/components/_Logo.scss
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--chromium.png
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--firefox.png
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--webkit.png
Labels: Type: Breaking, Impacts: Healthcare

#2454 [WNMGDS-2082] Steplist aria-label Primary/Secondary sections changed to use aria-describedby
  packages/design-system/src/components/StepList/Step.test.jsx
  packages/design-system/src/components/StepList/Step.tsx
  packages/design-system/src/components/StepList/StepList.tsx
  packages/design-system/src/components/StepList/__snapshots__/Step.test.jsx.snap
  packages/design-system/src/components/StepList/__snapshots__/StepList.test.jsx.snap
Labels: Impacts: Core, Type: Changed

#2466 [NO-TICKET] Fix a11y tests + cmsgov button colors
  .storybook/static/cmsgov-theme.css
  packages/design-system-tokens/src/themes/cmsgov-component.ts
  packages/docs/static/themes/cmsgov-theme.css
  packages/ds-cms-gov/src/styles/cmsgov-theme.css
  tests/a11y/storybook.a11y.test.ts
  tests/browser/snapshots/button--click--cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/button--click--cmsgov--chromium.png
  tests/browser/snapshots/button--click--cmsgov--firefox.png
  tests/browser/snapshots/button--click--cmsgov--webkit.png
  tests/browser/snapshots/button--hover--cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/button--hover--cmsgov--chromium.png
  tests/browser/snapshots/button--hover--cmsgov--firefox.png
  tests/browser/snapshots/button--hover--cmsgov--webkit.png
  tests/browser/snapshots/components-button--all-anchor-buttons-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/components-button--all-anchor-buttons-cmsgov--chromium.png
  tests/browser/snapshots/components-button--all-anchor-buttons-cmsgov--firefox.png
  tests/browser/snapshots/components-button--all-anchor-buttons-cmsgov--webkit.png
  tests/browser/snapshots/components-button--all-buttons-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/components-button--all-buttons-cmsgov--chromium.png
  tests/browser/snapshots/components-button--all-buttons-cmsgov--firefox.png
  tests/browser/snapshots/components-button--all-buttons-cmsgov--webkit.png
  tests/browser/snapshots/tooltip--open-interactive--cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/tooltip--open-interactive--cmsgov--chromium.png
  tests/browser/snapshots/tooltip--open-interactive--cmsgov--firefox.png
  tests/browser/snapshots/tooltip--open-interactive--cmsgov--webkit.png
Labels: Type: Fixed, Impacts: CMSgov

#2468 [WNMGDS-2290] Upgrade `downshift` and convert `Autocomplete` to functional component
  packages/design-system/package.json
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  yarn.lock
Labels: Type: Internal, Impacts: Core

#2473 [NO-TICKET] Clean up Storybook build dir
  .storybook/main.js
  .storybook/webpack.config.js
Labels: Type: Internal, Impacts: Core

#2475 [WNMGDS-2050] Pagination page list fix
  packages/design-system/src/components/Pagination/Ellipses.tsx
  packages/design-system/src/components/Pagination/Page.tsx
  packages/design-system/src/components/Pagination/Pagination.test.tsx
  packages/design-system/src/components/Pagination/Pagination.tsx
  packages/design-system/src/components/Pagination/__snapshots__/Page.test.tsx.snap
  packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/design-system/src/styles/components/_Pagination.scss
Labels: Type: Fixed, Impacts: Core

#2480 [WIP] [WNMGDS-2275] Tokenize mgov form elements
  .storybook/static/medicare-theme.css
  packages/design-system-tokens/src/themes/medicare-component.ts
  packages/design-system/src/styles/components/_ChoiceList.scss
  packages/design-system/src/styles/components/_DateField.scss
  packages/design-system/src/styles/components/_FormLabel.scss
  packages/design-system/src/styles/components/_Mask.scss
  packages/design-system/src/styles/components/_TextField.scss
  packages/docs/static/themes/medicare-theme.css
  packages/ds-medicare-gov/src/styles/components/_ChoiceList.scss
  packages/ds-medicare-gov/src/styles/components/_Forms.scss
  packages/ds-medicare-gov/src/styles/components/index.scss
  packages/ds-medicare-gov/src/styles/medicare-theme.css
  tests/browser/snapshots/components-month-picker--default-month-picker-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-month-picker--disabled-month-picker-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-month-picker--inverse-disabled-month-picker-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-month-picker--inverse-month-picker-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-month-picker--inverse-selected-month-picker-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-month-picker--selected-month-picker-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-multiinputdatefield--controlled-multi-input-date-field-medicare--Mobile-Chrome.png
  tests/browser/snapshots/components-multiinputdatefield--controlled-multi-input-date-field-medicare--chromium.png
  tests/browser/snapshots/components-multiinputdatefield--controlled-multi-input-date-field-medicare--firefox.png
  tests/browser/snapshots/components-multiinputdatefield--controlled-multi-input-date-field-medicare--webkit.png
  tests/browser/snapshots/components-privacysettingsdialog--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/components-privacysettingsdialog--default-core--Mobile-Chrome.png
  tests/browser/snapshots/components-privacysettingsdialog--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/components-privacysettingsdialog--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/components-privacysettingsdialog--default-medicare--chromium.png
  tests/browser/snapshots/components-privacysettingsdialog--default-medicare--firefox.png
  tests/browser/snapshots/components-text-field--all-masked-fields-medicare--Mobile-Chrome.png
  tests/browser/snapshots/components-text-field--all-masked-fields-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-text-field--all-masked-fields-medicare--chromium.png
  tests/browser/snapshots/components-text-field--all-masked-fields-medicare--firefox.png
  tests/browser/snapshots/components-text-field--all-masked-fields-medicare--webkit.png
Labels: Impacts: Medicare, Type: Changed

#2482 [WNMGDS-1250] Added `DrawerManager` context provider and `useDrawerManager` hook to manage state of multiple drawers on a single page.
  packages/design-system/src/components/Drawer/DrawerManager.stories.jsx
  packages/design-system/src/components/Drawer/DrawerManager.test.tsx
  packages/design-system/src/components/Drawer/DrawerManager.tsx
  packages/design-system/src/components/Drawer/index.ts
  packages/docs/content/components/drawer.mdx
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-cmsgov--chromium.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-cmsgov--firefox.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-cmsgov--webkit.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-core--Mobile-Chrome.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-core--chromium-forced-colors.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-core--chromium.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-core--firefox.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-core--webkit.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-healthcare--chromium.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-healthcare--firefox.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-healthcare--webkit.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-medicare--chromium.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-medicare--firefox.png
  tests/browser/snapshots/components-drawermanager--drawer-manager-default-medicare--webkit.png
  tests/browser/snapshots/datefield--picker-interaction--cmsgov--webkit.png
  tests/browser/snapshots/datefield--picker-interaction--core--webkit.png
  tests/browser/snapshots/datefield--picker-interaction--healthcare--webkit.png
Labels: Impacts: Core, Type: Added
