Repository CMSgov/design-system, pull requests merged in 2023-12, with the labels that each got.

#2830 [WNMGDS-2584] Add a11y docs to checkbox page
  packages/docs/content/components/checkbox.mdx
Labels: Type: Internal, Impacts: Documentation

#2833 [WNMGDS-2578] Remove import for file we deleted in #2828
  packages/ds-medicare-gov/src/components/index.ts
Labels: Type: Breaking, Impacts: Core

#2829 [WNMGDS-2583] Add radio button a11y interaction docs
  packages/docs/content/components/dropdown.mdx
  packages/docs/content/components/radio.mdx
Labels: Type: Internal, Impacts: Documentation

#2832 [WNMGDS-2581] Add a11y docs to alerts page
  packages/docs/content/components/alert.mdx
Labels: Type: Internal, Impacts: Documentation

#2834 [WNMGDS-2582] Add a11y docs to button
  packages/docs/content/components/button.mdx
Labels: Type: Internal, Impacts: Documentation

#2841 [WNMGDS-2524] Stories for hint and error + passthrough props
  packages/design-system/src/components/Hint/Hint.stories.tsx
  packages/design-system/src/components/Hint/Hint.tsx
  packages/design-system/src/components/InlineError/InlineError.stories.tsx
  packages/design-system/src/components/InlineError/InlineError.tsx
  packages/design-system/src/components/Label/Label.stories.tsx
  packages/design-system/src/components/Label/Label.tsx
  packages/docs/content/components/label.mdx
  tests/browser/snapshots/components-label--inverse-label-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/components-label--inverse-label-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/components-label--inverse-label-cmsgov--chromium.png
  tests/browser/snapshots/components-label--inverse-label-cmsgov--firefox.png
  tests/browser/snapshots/components-label--inverse-label-cmsgov--webkit.png
  tests/browser/snapshots/components-label--inverse-label-core--Mobile-Chrome.png
  tests/browser/snapshots/components-label--inverse-label-core--chromium-forced-colors.png
  tests/browser/snapshots/components-label--inverse-label-core--chromium.png
  tests/browser/snapshots/components-label--inverse-label-core--firefox.png
  tests/browser/snapshots/components-label--inverse-label-core--webkit.png
  tests/browser/snapshots/components-label--inverse-label-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/components-label--inverse-label-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/components-label--inverse-label-healthcare--chromium.png
  tests/browser/snapshots/components-label--inverse-label-healthcare--firefox.png
  tests/browser/snapshots/components-label--inverse-label-healthcare--webkit.png
  tests/browser/snapshots/components-label--inverse-label-medicare--Mobile-Chrome.png
  tests/browser/snapshots/components-label--inverse-label-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-label--inverse-label-medicare--chromium.png
  tests/browser/snapshots/components-label--inverse-label-medicare--firefox.png
  tests/browser/snapshots/components-label--inverse-label-medicare--webkit.png
  tests/browser/snapshots/components-label--label-default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/components-label--label-default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/components-label--label-default-cmsgov--chromium.png
  tests/browser/snapshots/components-label--label-default-cmsgov--firefox.png
  tests/browser/snapshots/components-label--label-default-cmsgov--webkit.png
  tests/browser/snapshots/components-label--label-default-core--Mobile-Chrome.png
  tests/browser/snapshots/components-label--label-default-core--chromium-forced-colors.png
  tests/browser/snapshots/components-label--label-default-core--chromium.png
  tests/browser/snapshots/components-label--label-default-core--firefox.png
  tests/browser/snapshots/components-label--label-default-core--webkit.png
  tests/browser/snapshots/components-label--label-default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/components-label--label-default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/components-label--label-default-healthcare--chromium.png
  tests/browser/snapshots/components-label--label-default-healthcare--firefox.png
  tests/browser/snapshots/components-label--label-default-healthcare--webkit.png
  tests/browser/snapshots/components-label--label-default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/components-label--label-default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-label--label-default-medicare--chromium.png
  tests/browser/snapshots/components-label--label-default-medicare--firefox.png
  tests/browser/snapshots/components-label--label-default-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Components-Hint-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-InlineError-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/stories.test.ts
Labels: Impacts: Core, Type: Changed

#2843 [WNMGDS-2524] Create/update docs for label, hint, and inline error
  packages/design-system/src/components/Hint/Hint.tsx
  packages/design-system/src/components/InlineError/InlineError.tsx
  packages/design-system/src/components/Label/Label.tsx
  packages/docs/content/components/hint.mdx
  packages/docs/content/components/inline-error.mdx
  packages/docs/content/components/label.mdx
  packages/docs/content/patterns/Forms/validation.mdx
Labels: Impacts: Documentation, Type: Added

#2852 [NO-TICKET] Update autocomplete FCM screenshot
  tests/browser/snapshots/autocomplete--type--cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/autocomplete--type--core--chromium-forced-colors.png
  tests/browser/snapshots/autocomplete--type--healthcare--chromium-forced-colors.png
Labels: Type: Internal, Impacts: Core

#2850 [WNMGDS-2585] Implement a11y docs on drawer.
  packages/docs/content/components/drawer.mdx
Labels: Type: Internal, Impacts: Documentation

#2849 [WIP] [WNMGDS-2594] implement a11y docs on dropdown
  packages/docs/content/components/dropdown.mdx
Labels: Type: Internal, Impacts: Documentation

#2848 [NO-TICKET] Add hcm support for dropdown focus styles
  packages/design-system/src/styles/components/_Dropdown.scss
  tests/browser/snapshots/dropdown--open--cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/dropdown--open--core--chromium-forced-colors.png
  tests/browser/snapshots/dropdown--open--healthcare--chromium-forced-colors.png
  tests/browser/snapshots/dropdown--open--medicare--chromium-forced-colors.png
  tests/browser/snapshots/dropdown-optgroups--open--cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/dropdown-optgroups--open--core--chromium-forced-colors.png
  tests/browser/snapshots/dropdown-optgroups--open--healthcare--chromium-forced-colors.png
  tests/browser/snapshots/dropdown-optgroups--open--medicare--chromium-forced-colors.png
Labels: Type: Fixed, Impacts: Core
