Repository CMSgov/design-system, pull requests merged in 2023-06, with the labels that each got.

#2509 [WNMGDS-2345] Reorganize story files so they're easier to find
  .storybook/main.ts
  packages/design-system/src/components/reset/resetAll.stories.tsx
  packages/design-system/src/styles/reset-form-els.stories.tsx
  packages/design-system/src/styles/reset-lists.stories.tsx
  packages/design-system/src/styles/reset-typography.stories.tsx
  packages/design-system/src/styles/typography-body-text.stories.tsx
  packages/design-system/src/styles/typography-headings.stories.tsx
  packages/design-system/src/styles/utilities/flexbox.stories.tsx
  packages/design-system/src/styles/utilities/float.stories.tsx
  packages/design-system/src/styles/utilities/font-size.stories.tsx
  packages/design-system/src/styles/utilities/layout-grid.stories.tsx
  packages/design-system/src/styles/utilities/margin.stories.tsx
  packages/design-system/src/styles/utilities/padding.stories.tsx
  packages/design-system/src/styles/utilities/text-align.stories.tsx
  packages/design-system/src/styles/utilities/visibility.stories.tsx
  packages/docs/content/layouts/Healthcare/one-col-page-layout.stories.tsx
  packages/docs/content/layouts/documentation-page.stories.tsx
  tests/browser/snapshots/reset-overview--overview-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/reset-overview--overview-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/reset-overview--overview-cmsgov--chromium.png
  tests/browser/snapshots/reset-overview--overview-cmsgov--firefox.png
  tests/browser/snapshots/reset-overview--overview-cmsgov--webkit.png
  tests/browser/snapshots/reset-overview--overview-core--Mobile-Chrome.png
  tests/browser/snapshots/reset-overview--overview-core--chromium-forced-colors.png
  tests/browser/snapshots/reset-overview--overview-core--chromium.png
  tests/browser/snapshots/reset-overview--overview-core--firefox.png
  tests/browser/snapshots/reset-overview--overview-core--webkit.png
  tests/browser/snapshots/reset-overview--overview-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/reset-overview--overview-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/reset-overview--overview-healthcare--chromium.png
  tests/browser/snapshots/reset-overview--overview-healthcare--firefox.png
  tests/browser/snapshots/reset-overview--overview-healthcare--webkit.png
  tests/browser/snapshots/reset-overview--overview-medicare--Mobile-Chrome.png
  tests/browser/snapshots/reset-overview--overview-medicare--chromium-forced-colors.png
  tests/browser/snapshots/reset-overview--overview-medicare--chromium.png
  tests/browser/snapshots/reset-overview--overview-medicare--firefox.png
  tests/browser/snapshots/reset-overview--overview-medicare--webkit.png
Labels: Type: Internal, Impacts: Documentation

#2508 [WNMGDS-2338] Improve VoiceOver support for Dropdown
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/Dropdown/Dropdown.test.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/design-system/src/components/Dropdown/useHighlightStatusMessageFn.ts
  packages/design-system/src/components/Dropdown/utils.tsx
Labels: Type: Fixed, Impacts: Core

#2518 [WNMGDS-2366] Fix headings on blog pages and fine-tune spacing on doc pages
  packages/docs/src/components/layout/Layout.tsx
  packages/docs/src/components/layout/PageHeader.tsx
  packages/docs/src/styles/pages/layout.scss
Labels: Type: Fixed, Impacts: Documentation

#2513 [LHDM-1281] Modify a11y label rendering for Alert
  packages/design-system/src/components/Alert/Alert.tsx
Labels: Type: Fixed, Impacts: Core

#2524 [WNMGDS-2371] Wrap highlightitem args in if statement to prevent undefined
  packages/design-system/src/components/Dropdown/useHighlightStatusMessageFn.ts
Labels: Type: Fixed, Impacts: Core

#2521 [WNMGDS-2365] Update CSS Reset docs according to beta-testing feedback
  packages/docs/content/migration-guides/introducing-a-css-reset.mdx
  packages/docs/src/images/margin-collapse.png
Labels: Impacts: Documentation, Type: Changed

#2525 [WNMGDS-2373] Update ThirdPartyExternalLink to use anchor instead of button
  packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.test.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/__snapshots__/ThirdPartyExternalLink.test.tsx.snap
  packages/design-system/src/styles/components/_ThirdPartyExternalLink.scss
  packages/design-system/src/styles/index.scss
  tests/browser/snapshots/components-thirdpartyexternallink--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-cmsgov--chromium.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-cmsgov--firefox.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-cmsgov--webkit.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-core--Mobile-Chrome.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-core--chromium-forced-colors.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-core--chromium.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-core--firefox.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-core--webkit.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-healthcare--chromium.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-healthcare--firefox.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-healthcare--webkit.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-medicare--chromium.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-medicare--firefox.png
  tests/browser/snapshots/components-thirdpartyexternallink--default-medicare--webkit.png
Labels: Impacts: Core, Type: Added

#2531 [WNMGDS-2365] Move CSS reset migration guide to a permanent place
  packages/docs/content/foundation/base.mdx
  packages/docs/content/foundation/css-normalization.mdx
  packages/docs/content/foundation/layout-grid/layout-grid.mdx
  packages/docs/content/foundation/layout-grid/responsive-design.mdx
  packages/docs/content/foundation/spacing.mdx
  packages/docs/content/foundation/system-color-tokens.mdx
  packages/docs/content/foundation/theme-colors.mdx
  packages/docs/content/foundation/typography/body.mdx
  packages/docs/content/foundation/typography/content.mdx
  packages/docs/content/foundation/typography/headings.mdx
  packages/docs/content/foundation/typography/links.mdx
  packages/docs/content/foundation/typography/list.mdx
Labels: Impacts: Documentation, Type: Changed

#2537 [NO-TICKET] v7 updates for dev docs
  packages/docs/content/getting-started/for-developers.mdx
  scripts/build-cdn-indexes.ts
Labels: Impacts: Documentation, Type: Changed

#2540 [NO-TICKET] Fixed autocompletes clear input functionality in Storybook.
  packages/design-system/src/components/Autocomplete/Autocomplete.stories.tsx
Labels: Type: Fixed, Impacts: Documentation

#2547 [WNMGDS-2306] Add devices tested with to a11y page - part of assets migration
  packages/docs/content/guidelines/accessibility.mdx
Labels: Impacts: Documentation, Type: Added

#2550 [WNMGDS-2404] Update language in mgov footer to remove trademark language
  packages/ds-healthcare-gov/src/components/Footer/LogosRow.tsx
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/LogosRow.test.tsx.snap
  packages/ds-healthcare-gov/src/components/locale/en.json
  packages/ds-healthcare-gov/src/components/locale/es.json
Labels: Type: Fixed, Impacts: Medicare

#2551 [WNMGDS-2405] Remove `aria-hidden` from HHS logo
  packages/design-system/src/components/Icons/HhsLogo.tsx
Labels: Type: Fixed, Impacts: Core, Impacts: Medicare

#2548 [WNMGDS-2367] v7 blog post
  packages/docs/content/blog/release-7.0.mdx
  packages/docs/src/images/new-dropdown.png
  packages/docs/src/images/version-switcher.png
Labels: Impacts: Documentation, Type: Added

#2554 [WNMGDS-2408] Add some screen reader context for error messages
  packages/design-system/src/components/ChoiceList/__snapshots__/Choice.test.tsx.snap
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/design-system/src/components/InlineError/InlineError.tsx
  packages/design-system/src/components/InlineError/__snapshots__/InlineError.test.tsx.snap
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
Labels: Type: Fixed, Impacts: Core
