Repository CMSgov/design-system, pull requests merged in 2023-05, with the labels that each got.

#2485 [NO-TICKET] Fix package exports
  examples/create-react-app-typescript/package.json
  examples/create-react-app-typescript/src/index.tsx
  examples/create-react-app-typescript/src/styles/index.scss
  packages/design-system/package.json
  packages/ds-cms-gov/package.json
  packages/ds-healthcare-gov/package.json
  packages/ds-medicare-gov/package.json
Labels: Type: Fixed, Impacts: Core

#2483 [WNMGDS-2290] Switch from Downshift's old API to new and no longer clear Autocomplete input on blur
  packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/design-system/src/components/Autocomplete/createFilteredA11yStatusMessageFn.ts
  packages/design-system/src/components/Autocomplete/keepInputDownshiftStateReducer.ts
Labels: Type: Breaking, Impacts: Core

#2484 [WNMGDS-2282] Fix `labelId` leaking through `TextField` into the DOM
  packages/design-system/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
  packages/design-system/src/components/FormLabel/useFormLabel.tsx
  packages/design-system/src/components/TextField/TextField.test.tsx
Labels: Type: Fixed, Impacts: Core

#2489 [NO-TICKET] Clean up a selection of console warnings in unit tests
  packages/design-system/src/components/ChoiceList/ChoiceList.test.tsx
  packages/design-system/src/components/TextField/TextInput.test.tsx
  packages/design-system/src/components/TextField/__snapshots__/useLabelMask.test.tsx.snap
  packages/design-system/src/components/TextField/useLabelMask.test.tsx
  packages/ds-healthcare-gov/src/components/Header/Header.test.tsx
  packages/ds-healthcare-gov/src/components/Header/Header.tsx
Labels: Type: Internal, Impacts: Core

#2491 [WNMGDS-2329] Updated healthcare footer according to design changes
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/InlineLinkLists.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/PrivacySettingsLink.test.tsx.snap
  packages/ds-healthcare-gov/src/components/locale/en.json
  packages/ds-healthcare-gov/src/components/locale/es.json
  packages/ds-healthcare-gov/src/styles/components/_Footer.scss
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--chromium.png
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--firefox.png
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--webkit.png
Labels: Impacts: Healthcare, Type: Changed

#2486 [NO-TICKET] Clean out an unused form token after color changes made it obsolete
  .storybook/static/medicare-theme.css
  packages/design-system-tokens/src/themes/medicare-component.ts
  packages/docs/static/themes/medicare-theme.css
  packages/ds-medicare-gov/src/styles/medicare-theme.css
Labels: Type: Breaking, Impacts: Core

#2496 [WNMGDS-2322] Doc Site Search
  packages/docs/gatsby-config.ts
  packages/docs/package.json
  packages/docs/src/components/content/SearchForm.tsx
  packages/docs/src/components/icons/CmsLogo.tsx
  packages/docs/src/components/layout/DocSiteNavigation.tsx
  packages/docs/src/components/layout/HeaderFullWidth.tsx
  packages/docs/src/components/layout/Layout.tsx
  packages/docs/src/components/layout/PageHeader.tsx
  packages/docs/src/helpers/graphQLTypes.ts
  packages/docs/src/pages/search.tsx
  packages/docs/src/styles/components/pageHeader.scss
  packages/docs/src/styles/index.scss
  packages/docs/src/styles/pages/search.scss
  yarn.lock
Labels: Impacts: Documentation, Type: Added

#2505 [WNGMDS-2175] Convert abs font sizes to rel
  .storybook/static/cmsgov-theme.css
  .storybook/static/core-theme.css
  .storybook/static/healthcare-theme.css
  .storybook/static/medicare-theme.css
  packages/design-system-tokens/src/themes/cmsgov-component.ts
  packages/design-system-tokens/src/themes/core-component.ts
  packages/design-system-tokens/src/themes/healthcare-component.ts
  packages/design-system-tokens/src/themes/medicare-component.ts
  packages/design-system-tokens/src/themes/medicare.ts
  packages/design-system-tokens/src/tokens/font.ts
  packages/design-system/src/styles/_base.scss
  packages/design-system/src/styles/components/_Dialog.scss
  packages/design-system/src/styles/components/_UsaBanner.scss
  packages/design-system/src/styles/core-theme.css
  packages/docs/src/styles/components/colorMigrationTable.scss
  packages/docs/src/styles/pages/layout.scss
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/docs/static/themes/medicare-theme.css
  packages/ds-cms-gov/src/styles/cmsgov-theme.css
  packages/ds-healthcare-gov/src/styles/components/_Accordion.scss
  packages/ds-healthcare-gov/src/styles/healthcare-theme.css
  packages/ds-medicare-gov/src/styles/_base.scss
  packages/ds-medicare-gov/src/styles/components/_Dialog.scss
  packages/ds-medicare-gov/src/styles/components/_Icons.scss
  packages/ds-medicare-gov/src/styles/components/_SimpleFooter.scss
  packages/ds-medicare-gov/src/styles/medicare-theme.css
  tests/browser/snapshots/components-idle-timeout--view-dialog-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/components-idle-timeout--view-dialog-cmsgov--chromium.png
  tests/browser/snapshots/components-idle-timeout--view-dialog-cmsgov--firefox.png
  tests/browser/snapshots/components-idle-timeout--view-dialog-core--Mobile-Chrome.png
  tests/browser/snapshots/components-idle-timeout--view-dialog-core--chromium.png
  tests/browser/snapshots/components-idle-timeout--view-dialog-core--firefox.png
  tests/browser/snapshots/components-idle-timeout--view-dialog-core--webkit.png
  tests/browser/snapshots/components-idle-timeout--view-dialog-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/components-idle-timeout--view-dialog-healthcare--chromium.png
  tests/browser/snapshots/components-idle-timeout--view-dialog-healthcare--firefox.png
  tests/browser/snapshots/components-idle-timeout--view-dialog-healthcare--webkit.png
  tests/browser/snapshots/components-idle-timeout--view-dialog-medicare--Mobile-Chrome.png
  tests/browser/snapshots/components-idle-timeout--view-dialog-medicare--chromium.png
  tests/browser/snapshots/components-idle-timeout--view-dialog-medicare--firefox.png
  tests/browser/snapshots/components-privacysettingsdialog--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/components-privacysettingsdialog--default-cmsgov--chromium.png
  tests/browser/snapshots/components-privacysettingsdialog--default-cmsgov--firefox.png
  tests/browser/snapshots/components-privacysettingsdialog--default-core--Mobile-Chrome.png
  tests/browser/snapshots/components-privacysettingsdialog--default-core--chromium.png
  tests/browser/snapshots/components-privacysettingsdialog--default-core--firefox.png
  tests/browser/snapshots/components-privacysettingsdialog--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/components-privacysettingsdialog--default-healthcare--chromium.png
  tests/browser/snapshots/components-privacysettingsdialog--default-healthcare--firefox.png
  tests/browser/snapshots/components-privacysettingsdialog--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/mask--text-entry--cmsgov--webkit.png
Labels: Impacts: Core, Impacts: Healthcare, Impacts: Medicare, Impacts: CMSgov, Type: Changed

#2504 [WNMGDS-2343] Migrate HCgov logo details from styleguide.healthcare.gov
  packages/docs/content/components/logos/healthcare-logo.mdx
  packages/docs/src/images/HCgov-logo/10_Squeezed.png
  packages/docs/src/images/HCgov-logo/4_ColorBackground.png
  packages/docs/src/images/HCgov-logo/5_PhotoBackground.png
  packages/docs/src/images/HCgov-logo/6_Reversed.png
  packages/docs/src/images/HCgov-logo/7_Dropshadow.png
  packages/docs/src/images/HCgov-logo/8_DifferentColors.png
  packages/docs/src/images/HCgov-logo/9_Outlined.png
  packages/docs/src/images/HCgov-logo/BlackLogoTag.png
  packages/docs/src/images/HCgov-logo/GreyLogoTag.png
  packages/docs/src/images/HCgov-logo/favicon.ico
Labels: Impacts: Documentation, Type: Added

#2506 [WNMGDS-2293] UsaBanner now appears on mobile/tablet versions of the doc site.
  packages/docs/src/components/layout/DocSiteNavigation.tsx
Labels: Impacts: Documentation, Type: Changed
