Repository CMSgov/design-system, pull requests merged in 2023-08, with the labels that each got.

#2603 [WNMGDS-2286] Add the usabanner component to hgov global header
  packages/design-system/src/components/UsaBanner/UsaBanner.stories.tsx
  packages/design-system/src/components/UsaBanner/UsaBanner.tsx
  packages/design-system/src/components/UsaBanner/__snapshots__/UsaBanner.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Header/Header.tsx
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/Header.test.tsx.snap
  packages/ds-healthcare-gov/src/styles/components/_Header.scss
  tests/browser/snapshots/healthcare-header--logged-in-controlled-header-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/healthcare-header--logged-in-controlled-header-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/healthcare-header--logged-in-controlled-header-healthcare--chromium.png
  tests/browser/snapshots/healthcare-header--logged-in-controlled-header-healthcare--firefox.png
  tests/browser/snapshots/healthcare-header--logged-in-controlled-header-healthcare--webkit.png
  tests/browser/snapshots/healthcare-header--logged-in-header-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/healthcare-header--logged-in-header-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/healthcare-header--logged-in-header-healthcare--chromium.png
  tests/browser/snapshots/healthcare-header--logged-in-header-healthcare--firefox.png
  tests/browser/snapshots/healthcare-header--logged-in-header-healthcare--webkit.png
  tests/browser/snapshots/healthcare-header--logged-out-header-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/healthcare-header--logged-out-header-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/healthcare-header--logged-out-header-healthcare--chromium.png
  tests/browser/snapshots/healthcare-header--logged-out-header-healthcare--firefox.png
  tests/browser/snapshots/healthcare-header--logged-out-header-healthcare--webkit.png
  tests/browser/snapshots/healthcare-header--minimal-header-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/healthcare-header--minimal-header-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/healthcare-header--minimal-header-healthcare--chromium.png
  tests/browser/snapshots/healthcare-header--minimal-header-healthcare--firefox.png
  tests/browser/snapshots/healthcare-header--minimal-header-healthcare--webkit.png
Labels: Impacts: Healthcare, Type: Changed

#2609 [WNMGDS-2458] Fix `size` prop on Dropdown
  packages/design-system/src/components/Dropdown/Dropdown.test.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#2612 [LHDM-1932] Add ReactNode to tab type definition for TabPanel
  packages/design-system/src/components/Tabs/TabPanel.tsx
Labels: Impacts: Core, Type: Changed

#2614 [NO-TICKET] Story refinement (SkipNav, one-col-page layout)
  packages/design-system/src/components/SkipNav/SkipNav.stories.tsx
  packages/docs/content/layouts/Healthcare/one-col-page-layout.stories.tsx
Labels: Impacts: Documentation, Type: Changed

#2599 [WNMGDS-2427] Filter-dialog prototype for doc site theme and version switching
  packages/design-system/src/components/Dialog/Dialog.tsx
  packages/design-system/src/components/Drawer/Drawer.tsx
  packages/design-system/src/components/NativeDialog/NativeDialog.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/styles/components/_Dialog.scss
  packages/docs/src/components/layout/FilterDialog/CloseButton.tsx
  packages/docs/src/components/layout/FilterDialog/FilterDialog.test.tsx
  packages/docs/src/components/layout/FilterDialog/FilterDialog.tsx
  packages/docs/src/components/layout/FilterDialog/FilterDialogManager.tsx
  packages/docs/src/components/layout/FilterDialog/__snapshots__/FilterDialog.test.tsx.snap
  packages/docs/src/components/layout/FilterDialog/index.ts
  packages/docs/src/components/layout/Layout.tsx
  packages/docs/src/components/layout/SideNav/SideNav.tsx
  packages/docs/src/components/layout/SideNav/ThemeDialog.tsx
  packages/docs/src/components/layout/SideNav/ThemeVersionSection.tsx
  packages/docs/src/components/layout/SideNav/VersionDialog.tsx
  packages/docs/src/components/layout/SideNav/themeVersionData.ts
  packages/docs/src/components/layout/ThemeSwitcher.tsx
  packages/docs/src/components/layout/VersionSwitcher.tsx
  packages/docs/src/helpers/useTheme.ts
  packages/docs/src/styles/components/filterDialog.scss
  packages/docs/src/styles/components/navigation.scss
  packages/docs/src/styles/index.scss
Labels: Impacts: Documentation, Type: Added

#2616 [NO-TICKET] Put the USA banner in healthcare Header behind a feature flag
  packages/ds-healthcare-gov/src/components/Header/Header.tsx
Labels: Impacts: Healthcare, Type: Added

#2632 [WNMGDS-2479] Add support for both independent and grouped options at the same time in Dropdowns
  packages/design-system/src/components/Dropdown/Dropdown.stories.tsx
  packages/design-system/src/components/Dropdown/Dropdown.test.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/design-system/src/components/Dropdown/utils.tsx
  packages/design-system/src/styles/components/_Dropdown.scss
Labels: Type: Fixed, Impacts: Core

#2635 [NO-TICKET] Fix possibility of null reference in Dropdown
  packages/design-system/src/components/Dropdown/Dropdown.tsx
Labels: Type: Fixed, Impacts: Core

#2615 [WNMGDS-2472] Remove glossary link from mgov footer
  packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.tsx
  packages/ds-medicare-gov/src/styles/components/_SimpleFooter.scss
  tests/browser/snapshots/medicare-simplefooter--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/medicare-simplefooter--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/medicare-simplefooter--default-medicare--chromium.png
  tests/browser/snapshots/medicare-simplefooter--default-medicare--firefox.png
  tests/browser/snapshots/medicare-simplefooter--default-medicare--webkit.png
Labels: Type: Breaking, Impacts: Medicare

#2642 [NO-TICKET] Update heading props to be less restrictive
  packages/design-system/src/components/Alert/Alert.tsx
  packages/design-system/src/components/Drawer/Drawer.tsx
  packages/design-system/src/components/IdleTimeout/IdleTimeout.tsx
  packages/design-system/src/components/IdleTimeout/IdleTimeoutDialog.tsx
Labels: Impacts: Core, Type: Changed

#2646 [WNMGDS-2480] fix mgov footer layout
  packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.tsx
  packages/ds-medicare-gov/src/styles/components/_SimpleFooter.scss
  tests/browser/snapshots/medicare-simplefooter--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/medicare-simplefooter--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/medicare-simplefooter--default-medicare--chromium.png
  tests/browser/snapshots/medicare-simplefooter--default-medicare--firefox.png
  tests/browser/snapshots/medicare-simplefooter--default-medicare--webkit.png
Labels: Type: Fixed, Impacts: Medicare

#2662 [NO-TICKET] Correct typo on heading docs
  packages/docs/content/foundation/typography/headings.mdx
Labels: Type: Internal, dependencies
