Repository CMSgov/design-system, pull requests merged in 2023-03, with the labels that each got.

#2398 [WNMGDS-2214] Pagination bugfix for Safari 13, layout logic moved to styles.
  packages/design-system/src/components/Pagination/Pagination.test.tsx
  packages/design-system/src/components/Pagination/Pagination.tsx
  packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/design-system/src/styles/components/_Pagination.scss
  tests/browser/snapshots/components-pagination--default-core--chromium-forced-colors.png
  tests/browser/snapshots/components-pagination--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/components-pagination--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-pagination--hidden-navigation-core--chromium-forced-colors.png
  tests/browser/snapshots/components-pagination--hidden-navigation-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/components-pagination--hidden-navigation-medicare--chromium-forced-colors.png
Labels: Type: Fixed, Impacts: Core

#2394 [WNMGDS-2235] Updates to color ramps
  .storybook/static/cmsgov-theme.css
  packages/design-system-tokens/src/themes/cmsgov.ts
  packages/design-system-tokens/src/themes/core.ts
  packages/design-system-tokens/src/themes/healthcare.ts
  packages/design-system-tokens/src/themes/medicare.ts
  packages/docs/static/themes/cmsgov-theme.css
Labels: Type: Breaking, Impacts: Documentation, Impacts: Core, Impacts: Healthcare, Impacts: Medicare, Impacts: CMSgov

#2400 [NO-TICKET] Feedback on the Standardizing theme colors in v7
  packages/docs/content/migration-guides/standardize-theme-colors.mdx
  packages/docs/src/components/content/ColorRamps.tsx
Labels: Impacts: Documentation, Type: Changed

#2403 [WNMGDS-2222] Upgrade to TS 4.9 and stop referencing dist directly in medicare
  package.json
  packages/design-system-tokens/package.json
  packages/design-system/package.json
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/Button/Button.tsx
  packages/design-system/src/components/DateField/SingleInputDateField.tsx
  packages/design-system/src/components/Icons/AddIcon.tsx
  packages/design-system/src/components/Icons/AlertCircleIcon.tsx
  packages/design-system/src/components/Icons/ArrowIcon.tsx
  packages/design-system/src/components/Icons/ArrowsStackedIcon.tsx
  packages/design-system/src/components/Icons/BuildingCircleIcon.tsx
  packages/design-system/src/components/Icons/CalendarIcon.tsx
  packages/design-system/src/components/Icons/CheckCircleIcon.tsx
  packages/design-system/src/components/Icons/CheckIcon.tsx
  packages/design-system/src/components/Icons/CloseIcon.tsx
  packages/design-system/src/components/Icons/CloseIconThin.tsx
  packages/design-system/src/components/Icons/DownloadIcon.tsx
  packages/design-system/src/components/Icons/ExternalLinkIcon.tsx
  packages/design-system/src/components/Icons/HhsLogo.tsx
  packages/design-system/src/components/Icons/ImageIcon.tsx
  packages/design-system/src/components/Icons/InfoCircleIcon.tsx
  packages/design-system/src/components/Icons/InfoCircleIconThin.tsx
  packages/design-system/src/components/Icons/LockCircleIcon.tsx
  packages/design-system/src/components/Icons/LockIcon.tsx
  packages/design-system/src/components/Icons/MenuIcon.tsx
  packages/design-system/src/components/Icons/MenuIconThin.tsx
  packages/design-system/src/components/Icons/MinusCircleIcon.tsx
  packages/design-system/src/components/Icons/NextIcon.tsx
  packages/design-system/src/components/Icons/PdfIcon.tsx
  packages/design-system/src/components/Icons/PlusCircleIcon.tsx
  packages/design-system/src/components/Icons/RemoveIcon.tsx
  packages/design-system/src/components/Icons/StarIcon.tsx
  packages/design-system/src/components/Icons/SvgIcon.test.tsx
  packages/design-system/src/components/Icons/SvgIcon.tsx
  packages/design-system/src/components/Icons/UsaFlagIcon.tsx
  packages/design-system/src/components/Icons/UsaLogo.tsx
  packages/design-system/src/components/Icons/WarningIcon.tsx
  packages/design-system/src/components/Icons/WhiteHouseLogo.tsx
  packages/design-system/src/components/Icons/icons.stories.tsx
  packages/design-system/src/components/Icons/index.ts
  packages/design-system/src/components/InlineError/InlineError.tsx
  packages/design-system/src/components/Tabs/Tabs.tsx
  packages/docs/package.json
  packages/ds-medicare-gov/src/components/Icons/Caret.tsx
  packages/ds-medicare-gov/src/components/Icons/CheckShieldIcon.tsx
  packages/ds-medicare-gov/src/components/Icons/DrugsIcon.tsx
  packages/ds-medicare-gov/src/components/Icons/InfoCircleOutlineIcon.tsx
  packages/ds-medicare-gov/src/components/Icons/PharmacyIcon.tsx
  packages/ds-medicare-gov/src/components/Icons/PiggyBankIcon.tsx
  packages/ds-medicare-gov/src/components/Icons/RoundedStarEmptyIcon.tsx
  packages/ds-medicare-gov/src/components/Icons/RoundedStarFilledIcon.tsx
  packages/ds-medicare-gov/src/components/Icons/RoundedStarHalfIcon.tsx
  packages/ds-medicare-gov/src/components/Icons/RoundedStarIcon.tsx
  tsconfig.json
  yarn.lock
Labels: Impacts: Core, Type: Changed

#2408 [WNMGDS-2224] Rename and reorganize examples
  examples/README.md
  examples/cdn-html-css/README.md
  examples/cdn-html-css/index.html
  examples/cdn-html-css/logo.svg
  examples/cdn-html-css/style.css
  examples/cdn-preact/README.md
  examples/cdn-preact/copy.sh
  examples/cdn-react/README.md
  examples/cdn-react/index.html
  examples/cdn-react/style.css
  examples/cdn-web-components/README.md
  examples/cdn-web-components/copy.sh
  examples/create-react-app-typescript/README.md
  examples/preact-app/README.md
  examples/preact-react-app/README.md
  examples/react-app/README.md
Labels: Impacts: Documentation, Type: Changed

#2410 [WNMGDS-2224] Document Preact and web components
  packages/docs/content/getting-started/for-developers.mdx
  packages/docs/src/styles/components/tableOfContents.scss
Labels: Impacts: Documentation, Type: Changed

#2424 [WNMGDS-1025] Fix spanish link navigation
  packages/ds-healthcare-gov/src/components/Header/ActionMenu.tsx
  packages/ds-healthcare-gov/src/components/Header/Header.test.tsx
  packages/ds-healthcare-gov/src/components/Header/Header.tsx
  packages/ds-healthcare-gov/src/components/Header/MenuLinks.test.tsx
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/Header.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/defaultMenuLinks.test.js.snap
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/localeLink.test.js.snap
  packages/ds-healthcare-gov/src/components/Header/localeLink.ts
  packages/ds-healthcare-gov/src/components/locale/en.json
  packages/ds-healthcare-gov/src/components/locale/es.json
Labels: Type: Fixed, Status: In JIRA, Impacts: Healthcare

#2425 [WNMGDS-2238] Healthcare privacy settings modal button css cascading incorrectly.
  packages/ds-healthcare-gov/src/styles/components/_Footer.scss
Labels: Type: Fixed, Impacts: Healthcare

#2417 [WNMGDS-2246] Remove old unused focus styles
  .storybook/static/cmsgov-theme.css
  .storybook/static/core-theme.css
  .storybook/static/healthcare-theme.css
  .storybook/static/medicare-theme.css
  packages/design-system-tokens/src/themes/cmsgov.ts
  packages/design-system-tokens/src/themes/core.ts
  packages/design-system-tokens/src/themes/healthcare.ts
  packages/design-system-tokens/src/themes/medicare.ts
  packages/design-system/src/styles/core-theme.css
  packages/design-system/src/styles/utilities/_background-color.scss
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/docs/static/themes/medicare-theme.css
  packages/ds-cms-gov/src/styles/cmsgov-theme.css
  packages/ds-healthcare-gov/src/styles/healthcare-theme.css
  packages/ds-medicare-gov/src/styles/medicare-theme.css
Labels: Impacts: Core, Type: Changed

#2428 [WNMGDS-2249] Remove Mgov deprecated colors
  .storybook/static/medicare-theme.css
  packages/design-system-tokens/src/themes/medicare.ts
  packages/docs/content/migration-guides/standardize-theme-colors.mdx
  packages/docs/static/themes/medicare-theme.css
  packages/ds-medicare-gov/src/styles/medicare-theme.css
Labels: Type: Breaking, Impacts: Medicare

#2429 [WNMGDS-2250] Add primary util classes for bg color
  packages/design-system/src/styles/utilities/_background-color.scss
  packages/docs/content/utilities/background-color.mdx
Labels: Impacts: Core, Type: Added

#2433 [WNMGDS-2253] Updates to release note generation script
  package.json
  scripts/notes.ts
  themes.json
  yarn.lock
Labels: Type: Fixed, Impacts: Internal

#2437 [WNMGDS-2231] Update Button docs
  packages/docs/content/components/button.mdx
Labels: Impacts: Documentation, Status: In JIRA, Type: Added

#2438 [WNMGDS-2040] CDN Index build script
  package.json
  scripts/build-cdn-indexes.ts
Labels: Type: Internal, Impacts: Core

#2430 [WNMGDS-2252] Delete the medicare icons that have been deprecated for at least a year
  packages/ds-medicare-gov/src/components/Icons/Caret.tsx
  packages/ds-medicare-gov/src/components/Icons/Checkmark.tsx
  packages/ds-medicare-gov/src/components/Icons/CloseSymbol.tsx
  packages/ds-medicare-gov/src/components/Icons/HamburgerSymbol.tsx
  packages/ds-medicare-gov/src/components/Icons/No.tsx
  packages/ds-medicare-gov/src/components/Icons/index.ts
Labels: Type: Breaking, Impacts: Medicare

#2431 [WNMGDS-2241] Make external links screen reader accessible
  packages/design-system/src/components/Icons/ExternalLinkIcon.tsx
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
  packages/design-system/src/components/patterns/thirdPartyExternalLinks.stories.tsx
Labels: Type: Fixed, Impacts: Core

#2426 [WNMGDS-2248] Add inline-flex utility class
  packages/design-system/src/styles/utilities/_display-visibility.scss
  packages/docs/content/utilities/display.mdx
Labels: Impacts: Core, Type: Added
