Repository CMSgov/design-system, pull requests merged in 2023-02, with the labels that each got.

#2365 [WNMGDS-2206] Theme color page updates
  packages/docs/content/foundation/theme-colors.mdx
  packages/docs/content/utilities/background-color.mdx
  packages/docs/content/utilities/text/text-color.mdx
  packages/docs/src/components/content/ColorExampleList.tsx
  packages/docs/src/components/content/ColorExampleRow.tsx
  packages/docs/src/components/content/ColorRamps.tsx
  packages/docs/src/components/content/ColorSwatch.tsx
  packages/docs/src/components/content/ColorSwatchList.tsx
  packages/docs/src/components/content/ContentRenderer.tsx
  packages/docs/src/components/content/TextColorList.tsx
  packages/docs/src/styles/components/colorExampleRow.scss
  packages/docs/src/styles/components/colorRamps.scss
  packages/docs/src/styles/components/colorSwatch.scss
  packages/docs/src/styles/components/textColorList.scss
  packages/docs/src/styles/index.scss
Labels: Status: Ready For Review

#2374 [NO-TICKET] Remove unused flag for error icons
  packages/design-system/src/components/flags.ts
  packages/ds-healthcare-gov/src/components/index.ts
Labels: Impacts: Core

#2373 [WNMGDS-2161] Compact pagination
  packages/design-system/src/components/Pagination/Page.tsx
  packages/design-system/src/components/Pagination/Pagination.test.tsx
  packages/design-system/src/components/Pagination/Pagination.tsx
  packages/design-system/src/components/Pagination/__snapshots__/Page.test.tsx.snap
  packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
  packages/design-system/src/styles/components/_Pagination.scss
Labels: Type: Accessibility, Impacts: Core

#2377 [NO-TICKET] Remove unused SVG files in Medicare
  packages/ds-medicare-gov/src/components/Caret/Caret.svg
  packages/ds-medicare-gov/src/components/CautionCircle/caution-circle.svg
  packages/ds-medicare-gov/src/components/Checkmark/Checkmark.svg
  packages/ds-medicare-gov/src/components/CloseSymbol/CloseSymbol.svg
  packages/ds-medicare-gov/src/components/HamburgerSymbol/Hamburger.svg
  packages/ds-medicare-gov/src/components/HamburgerSymbol/HamburgerSymbol.svg
  packages/ds-medicare-gov/src/components/No/No.svg
Labels: Impacts: Medicare

#2382 [WNMGDS-2186] Normalize theme-level gray palettes
  .storybook/static/cmsgov-theme.css
  .storybook/static/core-theme.css
  .storybook/static/healthcare-theme.css
  .storybook/static/medicare-theme.css
  packages/design-system-tokens/src/themes/cmsgov-component.ts
  packages/design-system-tokens/src/themes/cmsgov.ts
  packages/design-system-tokens/src/themes/core-component.ts
  packages/design-system-tokens/src/themes/core.ts
  packages/design-system-tokens/src/themes/healthcare-component.ts
  packages/design-system-tokens/src/themes/healthcare.ts
  packages/design-system-tokens/src/themes/medicare-component.ts
  packages/design-system-tokens/src/themes/medicare.ts
  packages/design-system/src/styles/components/_SingleInputDateField.scss
  packages/design-system/src/styles/core-theme.css
  packages/docs/content/foundation/theme-colors.mdx
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/docs/static/themes/medicare-theme.css
  packages/ds-cms-gov/src/styles/cmsgov-theme.css
  packages/ds-healthcare-gov/src/styles/healthcare-theme.css
  packages/ds-medicare-gov/src/styles/medicare-theme.css
Labels: Breaking Change, Type: Visual Change, Impacts: Core, Impacts: Healthcare, Impacts: Medicare, Impacts: CMSgov
