Repository CMSgov/design-system, pull requests merged in 2023-07, with the labels that each got.

#2564 [WNMGDS-2416] Add background color to calendar dialog
  packages/design-system/src/styles/components/_SingleInputDateField.scss
Labels: Type: Fixed, Impacts: Core

#2566 [WNMGDS-2417] Fix `Dropdown` `className` prop not being applied to its container element
  packages/design-system/src/components/Dropdown/Dropdown.test.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#2567 [WNMGDS-2415] Refactor AccordionItem
  packages/design-system/src/components/Accordion/AccordionItem.test.tsx
  packages/design-system/src/components/Accordion/AccordionItem.tsx
  packages/ds-healthcare-gov/src/components/Accordion/Accordion.stories.tsx
Labels: Impacts: Core, Type: Changed

#2568 [WNMGDS-2418] Add `selectedId` prop to `Tabs` for controlled behavior
  packages/design-system/src/components/Tabs/Tabs.stories.tsx
  packages/design-system/src/components/Tabs/Tabs.test.tsx
  packages/design-system/src/components/Tabs/Tabs.tsx
  tests/browser/story-screenshots.test.ts
Labels: Impacts: Core, Type: Added

#2570 [WNMGDS-2419] Make Dropdown option checks less strict
  packages/design-system/src/components/Dropdown/Dropdown.stories.tsx
  packages/design-system/src/components/Dropdown/Dropdown.test.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  tests/browser/story-screenshots.test.ts
Labels: Type: Fixed, Impacts: Core

#2573 [WNMGDS-2420] Left align wrapping text in Accordion; side effect of reset CSS
  packages/design-system/src/styles/components/_Accordion.scss
Labels: Type: Fixed, Impacts: Core

#2563 [WNMGDS-2402] Migrate all prop tables from doc site
  package.json
  packages/design-system/src/components/ChoiceList/Choice.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.tsx
  packages/design-system/src/components/Table/Table.tsx
  packages/design-system/src/components/Table/TableBody.tsx
  packages/design-system/src/components/Table/TableCell.tsx
  packages/design-system/src/components/Tabs/Tabs.tsx
  packages/design-system/src/components/Tooltip/Tooltip.stories.tsx
  packages/design-system/src/components/Tooltip/Tooltip.tsx
  packages/docs/content/components/accordion.mdx
  packages/docs/content/components/checkbox.mdx
  packages/docs/content/components/date-field/date-picker.mdx
  packages/docs/content/components/drawer.mdx
  packages/docs/content/components/radio.mdx
  packages/docs/content/components/step-list.mdx
  packages/docs/content/components/table.mdx
  packages/docs/content/components/tabs.mdx
  packages/docs/content/components/tooltip.mdx
  packages/docs/content/components/vertical-navigation.mdx
  packages/docs/src/components/content/ContentRenderer.tsx
  packages/docs/src/components/content/PropTable.tsx
  packages/docs/src/components/content/PropTableHtmlElementRow.tsx
  packages/docs/src/components/content/ReactDocsLink.tsx
  packages/docs/src/components/content/ReactDocsLinks.tsx
  scripts/extractPropData.js
Labels: Impacts: Documentation, Type: Changed

#2575 [WNMGDS-2376] Fix and move `StepList` documentation
  packages/design-system/src/components/StepList/StepList.tsx
  packages/docs/content/components/step-list.mdx
Labels: Type: Fixed, Impacts: Documentation

#2576 [WNMGDS-2211] Vertically align pagination items
  packages/design-system/src/styles/components/_Pagination.scss
  tests/browser/snapshots/components-pagination--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/components-pagination--default-cmsgov--chromium.png
  tests/browser/snapshots/components-pagination--default-cmsgov--firefox.png
  tests/browser/snapshots/components-pagination--default-cmsgov--webkit.png
  tests/browser/snapshots/components-pagination--default-core--chromium-forced-colors.png
  tests/browser/snapshots/components-pagination--default-core--chromium.png
  tests/browser/snapshots/components-pagination--default-core--firefox.png
  tests/browser/snapshots/components-pagination--default-core--webkit.png
  tests/browser/snapshots/components-pagination--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/components-pagination--default-healthcare--chromium.png
  tests/browser/snapshots/components-pagination--default-healthcare--firefox.png
  tests/browser/snapshots/components-pagination--default-healthcare--webkit.png
  tests/browser/snapshots/components-pagination--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-pagination--default-medicare--chromium.png
  tests/browser/snapshots/components-pagination--default-medicare--firefox.png
  tests/browser/snapshots/components-pagination--default-medicare--webkit.png
  tests/browser/snapshots/components-pagination--hidden-navigation-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/components-pagination--hidden-navigation-cmsgov--chromium.png
  tests/browser/snapshots/components-pagination--hidden-navigation-cmsgov--firefox.png
  tests/browser/snapshots/components-pagination--hidden-navigation-cmsgov--webkit.png
  tests/browser/snapshots/components-pagination--hidden-navigation-core--chromium-forced-colors.png
  tests/browser/snapshots/components-pagination--hidden-navigation-core--chromium.png
  tests/browser/snapshots/components-pagination--hidden-navigation-core--firefox.png
  tests/browser/snapshots/components-pagination--hidden-navigation-core--webkit.png
  tests/browser/snapshots/components-pagination--hidden-navigation-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/components-pagination--hidden-navigation-healthcare--chromium.png
  tests/browser/snapshots/components-pagination--hidden-navigation-healthcare--firefox.png
  tests/browser/snapshots/components-pagination--hidden-navigation-healthcare--webkit.png
  tests/browser/snapshots/components-pagination--hidden-navigation-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-pagination--hidden-navigation-medicare--chromium.png
  tests/browser/snapshots/components-pagination--hidden-navigation-medicare--firefox.png
  tests/browser/snapshots/components-pagination--hidden-navigation-medicare--webkit.png
Labels: Type: Fixed, Impacts: Core

#2585 [WNMGDS-2432] Convert the FormLabel component to a functional component
  packages/design-system/src/components/FormLabel/FormLabel.tsx
Labels: Type: Internal, Impacts: Core

#2590 [WNMGDS-2441] Export all types related to the dropdown component
  packages/design-system/src/components/Dropdown/index.ts
Labels: Type: Fixed, Impacts: Core

#2591 [WNMGDS-2445] Make the `ds-cms-gov` package public and publishable
  package.json
  packages/ds-cms-gov/package.json
Labels: Impacts: CMSgov, Type: Changed

#2593 [WNMGDS-2451] Add ability for keyboard scroll in dropdown list
  packages/design-system/src/styles/components/_Dropdown.scss
Labels: Type: Fixed, Impacts: Core

#2598 [WNMGDS-2453] Add `type="button"` to dropdown toggle to prevent form submissions
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#2600 [WNMGDS-2421] Style autocomplete message options
  packages/design-system/src/styles/components/_Autocomplete.scss
Labels: Type: Fixed, Impacts: Core

#2602 [WNMGDS-2455] Reimplement hgov accordion story, fix default props for accordionitem
  packages/design-system/src/components/Accordion/AccordionItem.tsx
  packages/ds-healthcare-gov/src/components/Accordion/Accordion.stories.tsx
  packages/ds-healthcare-gov/src/styles/components/_Accordion.scss
Labels: Type: Fixed, Impacts: Healthcare

#2604 [NO-TICKET] Fix passthrough of `getA11yStatusMessage` on dropdowns
  packages/design-system/src/components/Dropdown/Dropdown.tsx
Labels: Type: Fixed, Impacts: Core
