Repository CMSgov/design-system, pull requests merged in 2023-10, with the labels that each got.

#2715 [WNMGDS-2498] Add web-component support to our Storybook
  .eslintignore
  .storybook/main.ts
  .storybook/preview.tsx
  packages/design-system/package.json
  packages/design-system/src/components/web-components/ds-alert.stories.tsx
  packages/design-system/src/components/web-components/ds-alert.ts
  packages/design-system/src/components/web-components/ds-badge.ts
  packages/design-system/src/components/web-components/ds-button.stories.tsx
  packages/design-system/src/components/web-components/ds-button.tsx
  packages/design-system/src/components/web-components/ds-usa-banner.ts
  packages/design-system/src/components/web-components/index.ts
  packages/design-system/src/components/web-components/preactement/LICENSE.md
  packages/design-system/src/components/web-components/preactement/README.md
  packages/design-system/src/components/web-components/preactement/define.ts
  packages/design-system/src/components/web-components/preactement/model.ts
  packages/design-system/src/components/web-components/preactement/parse.ts
  packages/design-system/src/components/web-components/preactement/shared/element.ts
  packages/design-system/src/components/web-components/preactement/shared/index.ts
  packages/design-system/src/components/web-components/preactement/shared/model.ts
  packages/design-system/src/components/web-components/preactement/shared/parse.ts
  tests/browser/story-screenshots.test.ts
Labels: Impacts: Core, Type: Added

#2725 [WNMGDS-2522] Remove the unused "success" text field
  .storybook/static/cmsgov-theme.css
  .storybook/static/core-theme.css
  .storybook/static/healthcare-theme.css
  .storybook/static/medicare-theme.css
  packages/design-system-tokens/src/themes/cmsgov-component.ts
  packages/design-system-tokens/src/themes/core-component.ts
  packages/design-system-tokens/src/themes/healthcare-component.ts
  packages/design-system-tokens/src/themes/medicare-component.ts
  packages/design-system/src/components/TextField/TextField.stories.tsx
  packages/design-system/src/styles/components/_TextField.scss
  packages/design-system/src/styles/core-theme.css
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/docs/static/themes/medicare-theme.css
  packages/ds-cms-gov/src/styles/cmsgov-theme.css
  packages/ds-healthcare-gov/src/styles/healthcare-theme.css
  packages/ds-medicare-gov/src/styles/medicare-theme.css
  tests/browser/snapshots/components-textfield--success-field-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/components-textfield--success-field-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/components-textfield--success-field-cmsgov--chromium.png
  tests/browser/snapshots/components-textfield--success-field-cmsgov--firefox.png
  tests/browser/snapshots/components-textfield--success-field-cmsgov--webkit.png
  tests/browser/snapshots/components-textfield--success-field-core--Mobile-Chrome.png
  tests/browser/snapshots/components-textfield--success-field-core--chromium-forced-colors.png
  tests/browser/snapshots/components-textfield--success-field-core--chromium.png
  tests/browser/snapshots/components-textfield--success-field-core--firefox.png
  tests/browser/snapshots/components-textfield--success-field-core--webkit.png
  tests/browser/snapshots/components-textfield--success-field-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/components-textfield--success-field-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/components-textfield--success-field-healthcare--chromium.png
  tests/browser/snapshots/components-textfield--success-field-healthcare--firefox.png
  tests/browser/snapshots/components-textfield--success-field-healthcare--webkit.png
  tests/browser/snapshots/components-textfield--success-field-medicare--Mobile-Chrome.png
  tests/browser/snapshots/components-textfield--success-field-medicare--chromium-forced-colors.png
  tests/browser/snapshots/components-textfield--success-field-medicare--chromium.png
  tests/browser/snapshots/components-textfield--success-field-medicare--firefox.png
  tests/browser/snapshots/components-textfield--success-field-medicare--webkit.png
Labels: Type: Breaking, Impacts: Core

#2726 [WNMGDS-2516] add presentational role to hgov logo
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/LogosRow.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/Header.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Logo/LogoEnSvg.tsx
  packages/ds-healthcare-gov/src/components/Logo/LogoEsSvg.tsx
  packages/ds-healthcare-gov/src/components/Logo/__snapshots__/Logo.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Logo/__snapshots__/LogoEnSvg.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Logo/__snapshots__/LogoEsSvg.test.jsx.snap
Labels: Type: Fixed, Impacts: Healthcare

#2727 [WNMGDS-2525] Add a `ds-usa-banner` story
  packages/design-system/src/components/UsaBanner/index.ts
  packages/design-system/src/components/web-components/__snapshots__/ds-usa-banner.test.tsx.snap
  packages/design-system/src/components/web-components/ds-usa-banner.stories.tsx
  packages/design-system/src/components/web-components/ds-usa-banner.test.tsx
  packages/design-system/src/components/web-components/ds-usa-banner.ts
  packages/design-system/src/components/web-components/ds-usa-banner.tsx
  tests/browser/story-screenshots.test.ts
Labels: Impacts: Documentation, Type: Added

#2734 [NO-TICKET] Ensure steplist bullet point receives same font across browsers
  packages/design-system/src/styles/components/_StepList.scss
  tests/browser/snapshots/components-steplist--step-list-example-cmsgov--firefox.png
  tests/browser/snapshots/components-steplist--step-list-example-core--firefox.png
  tests/browser/snapshots/components-steplist--step-list-example-healthcare--firefox.png
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--firefox.png
Labels: Type: Fixed, Impacts: Core

#2730 [LHDM-2086] Convert UsaBanner text content to template string usage
  packages/design-system/src/components/UsaBanner/UsaBanner.tsx
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/Header.test.tsx.snap
Labels: Type: Fixed, Impacts: Core, Impacts: Healthcare

#2743 [WNMGDS-2531] Fix dropdown tap-through
  packages/design-system/src/components/Dropdown/Dropdown.stories.tsx
  packages/design-system/src/components/Dropdown/DropdownMenu.tsx
Labels: Type: Fixed, Impacts: Core

#2748 [NO-TICKET] Allow the setting of an error message on the inverse ChoiceList story
  packages/design-system/src/components/ChoiceList/ChoiceList.stories.tsx
Labels: Type: Fixed, Impacts: Documentation

#2751 [NO-TICKET] Update CDN examples to use latest DS version
  examples/cdn-html-css/index.html
  examples/cdn-preact/README.md
  examples/cdn-preact/copy.sh
  examples/cdn-preact/index.html
  examples/cdn-react/index.html
  examples/cdn-web-components/README.md
  examples/cdn-web-components/copy.sh
  examples/cdn-web-components/index.html
Labels: Impacts: Documentation, Type: Changed

#2749 [WNMGDS-2529] Give the calendar button more context for screen readers
  packages/design-system/src/components/DateField/SingleInputDateField.test.tsx
  packages/design-system/src/components/DateField/SingleInputDateField.tsx
Labels: Type: Fixed, Impacts: Core

#2753 [WNMGDS-2525] Add an attributes table to storybook docs for web components
  .storybook/docs/DocumentationTemplate.mdx
  .storybook/docs/WebComponentArgsTable.tsx
  .storybook/docs/WebComponentDocTemplate.mdx
  .storybook/preview.tsx
  packages/design-system/src/components/web-components/ds-alert.stories.tsx
  packages/design-system/src/components/web-components/ds-button.stories.tsx
  packages/design-system/src/components/web-components/ds-usa-banner.stories.tsx
Labels: Impacts: Documentation, Type: Added

#2738 [WNMGDS-2521] Add custom event handling to web components
  packages/design-system/package.json
  packages/design-system/src/components/Alert/useAlertAnalytics.ts
  packages/design-system/src/components/web-components/__snapshots__/ds-alert.test.tsx.snap
  packages/design-system/src/components/web-components/__snapshots__/ds-usa-banner.test.tsx.snap
  packages/design-system/src/components/web-components/ds-alert.test.tsx
  packages/design-system/src/components/web-components/ds-alert.tsx
  packages/design-system/src/components/web-components/ds-button.stories.tsx
  packages/design-system/src/components/web-components/ds-button.test.tsx
  packages/design-system/src/components/web-components/ds-button.tsx
  packages/design-system/src/components/web-components/preactement/define.ts
  packages/design-system/src/components/web-components/preactement/model.ts
  packages/design-system/src/components/web-components/preactement/shared/model.ts
  yarn.lock
Labels: Impacts: Core, Type: Added

#2747 [WNMGDS-2539] Fix incompatibilities with React 18 types
  examples/create-react-app-typescript/src/components/App.tsx
  examples/create-react-app-typescript/src/components/Examples/AccordionExample.tsx
  examples/create-react-app-typescript/src/components/Examples/AlertExample.tsx
  examples/create-react-app-typescript/src/components/Examples/AutocompleteExample.tsx
  examples/create-react-app-typescript/src/components/Examples/BadgeExample.tsx
  examples/create-react-app-typescript/src/components/Examples/ButtonExample.tsx
  examples/create-react-app-typescript/src/components/Examples/ChoiceListExample.tsx
  examples/create-react-app-typescript/src/components/Examples/DateFieldExample.tsx
  examples/create-react-app-typescript/src/components/Examples/DropdownExample.tsx
  examples/create-react-app-typescript/src/components/Examples/FilterChipExample.tsx
  examples/create-react-app-typescript/src/components/Examples/HelpDrawerExample.tsx
  examples/create-react-app-typescript/src/components/Examples/LabelExample.tsx
  examples/create-react-app-typescript/src/components/Examples/MaskedFieldExample.tsx
  examples/create-react-app-typescript/src/components/Examples/ModalDialogExample.tsx
  examples/create-react-app-typescript/src/components/Examples/MonthPickerExample.tsx
  examples/create-react-app-typescript/src/components/Examples/PaginationExample.tsx
  examples/create-react-app-typescript/src/components/Examples/SpinnerExample.tsx
  examples/create-react-app-typescript/src/components/Examples/TableExample.tsx
  examples/create-react-app-typescript/src/components/Examples/TabsExample.tsx
  examples/create-react-app-typescript/src/components/Examples/TextFieldExample.tsx
  examples/create-react-app-typescript/src/components/Examples/TooltipExample.tsx
  examples/create-react-app-typescript/src/components/Examples/UsaBannerExample.tsx
  examples/create-react-app-typescript/src/components/Examples/VerticalNavigationExample.tsx
  examples/create-react-app-typescript/src/index.tsx
  packages/design-system/src/components/FilterChip/FilterChip.tsx
  packages/design-system/src/components/Table/Table.tsx
  packages/design-system/src/components/Table/TableBody.tsx
  packages/design-system/src/components/Table/TableCaption.tsx
  packages/design-system/src/components/Table/TableCell.tsx
  packages/design-system/src/components/Table/TableHead.tsx
  packages/design-system/src/components/Table/TableRow.tsx
Labels: Type: Fixed, Impacts: Core

#2752 [WNMGDS-2536] Fix css-variable tables being rendered inside storybook wrapper elements
  packages/docs/content/components/alert.mdx
Labels: Type: Fixed, Impacts: Documentation

#2762 [NO-TICKET] Add a "patch" script for automatically cherry-picking commits
  README.md
  package.json
  scripts/notes.ts
  scripts/patch.ts
  scripts/utils.ts
Labels: Type: Internal, Impacts: Core

#2766 [WNMGDS-2540] Fix dead links in docs
  packages/design-system/src/components/ChoiceList/Choice.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.tsx
  packages/design-system/src/components/DateField/MultiInputDateField.tsx
  packages/design-system/src/components/Dialog/Dialog.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/Hint/Hint.tsx
  packages/design-system/src/components/Label/Label.tsx
  packages/design-system/src/components/MonthPicker/MonthPicker.tsx
  packages/design-system/src/components/TextField/TextField.tsx
  packages/design-system/src/components/VerticalNav/VerticalNav.stories.tsx
  packages/design-system/src/components/VerticalNav/VerticalNav.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItem.tsx
  packages/docs/content/components/dropdown.mdx
  packages/docs/content/foundation/layout-grid/layout-grid.mdx
Labels: Type: Fixed, Impacts: Documentation

#2768 [WNMGDS-2535] Fix interaction tests run with Preact
  packages/design-system/src/components/Dropdown/Dropdown.test.interaction.ts
  packages/design-system/src/components/TextField/Mask.test.interaction.ts
  packages/design-system/src/components/Tooltip/Tooltip.test.interaction.ts
Labels: Type: Internal, Impacts: Core

#2769 [WNMGDS-2535] Make storybook use Preact by default
  .storybook/webpack.config.js
  package.json
Labels: Impacts: Documentation, Type: Changed

#2767 [WNMGDS-2542] Fix radio example showing on checkbox doc page
  packages/docs/content/components/checkbox.mdx
Labels: Type: Fixed, Impacts: Documentation
