Repository CMSgov/design-system, pull requests merged in 2024-02, with the labels that each got.

#2921 [NO-TICKET] Fix the visual regression in #2893
  packages/design-system/src/components/ChoiceList/Choice.tsx
Labels: Type: Internal, Impacts: Core

#2926 [WNMGDS-2511] Update hgov footer html
  packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.tsx
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/InlineLinkLists.test.tsx.snap
Labels: Type: Fixed, Impacts: Healthcare

#2928 [WNMGDS-2669] Remove unused and underused autocomplete and dropdown tokens
  packages/design-system-tokens/src/themes/cmsgov-component.ts
  packages/design-system-tokens/src/themes/core-component.ts
  packages/design-system-tokens/src/themes/healthcare-component.ts
  packages/design-system-tokens/src/themes/medicare-component.ts
  packages/design-system/src/styles/components/_Autocomplete.scss
  packages/design-system/src/styles/components/_Dropdown.scss
  packages/docs/content/components/autocomplete.mdx
  packages/docs/content/components/dropdown.mdx
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/docs/static/themes/medicare-theme.css
Labels: Type: Breaking, Impacts: Core

#2931 [WNMGDS-2670] Capitalize Vietnamese language resources link
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/InlineLinkLists.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/languages.ts
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--chromium.png
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--firefox.png
  tests/browser/snapshots/healthcare-footer--basic-footer-healthcare--webkit.png
Labels: Type: Fixed, Impacts: Healthcare

#2927 [WNMGDS-2669] Make token changes informed by Figma migration
  packages/design-system-tokens/src/themes/cmsgov-component.ts
  packages/design-system-tokens/src/themes/core-component.ts
  packages/design-system-tokens/src/themes/healthcare-component.ts
  packages/design-system-tokens/src/themes/medicare-component.ts
  packages/design-system/src/styles/components/_Alert.scss
  packages/design-system/src/styles/components/_Hint.scss
  packages/design-system/src/styles/components/_InlineError.scss
  packages/design-system/src/styles/components/_Label.scss
  packages/design-system/src/styles/components/_SvgIcon.scss
  packages/design-system/src/styles/components/_Table.scss
  packages/docs/content/components/icon.mdx
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/docs/static/themes/medicare-theme.css
  tests/browser/storybook-docs.test.ts
Labels: Type: Breaking, Impacts: Core

#2936 [WNMGDS-2650] Remove unnecessary display utils from docs layout
  packages/docs/src/components/layout/Layout.tsx
Labels: Type: Fixed, Impacts: Documentation

#2937 [WNMGDS-2350] Fix background color of docs vertical nav on hover
  packages/docs/src/components/layout/SideNav/SideNav.tsx
  packages/docs/src/styles/components/navigation.scss
Labels: Type: Fixed, Impacts: Documentation

#2939 [WNMGDS-2663] Add defaultProp for spinner aria-valuetext
  packages/design-system/src/components/Spinner/Spinner.tsx
  tests/browser/snapshots/storybook-docs/Docs-Components-Spinner-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Fixed, Impacts: Core

#2940 [WNMGDS-2669] Replace `currentColor` values in tokens
  packages/design-system-tokens/src/themes/cmsgov-component.ts
  packages/design-system-tokens/src/themes/core-component.ts
  packages/design-system-tokens/src/themes/healthcare-component.ts
  packages/design-system-tokens/src/themes/medicare-component.ts
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/docs/static/themes/medicare-theme.css
Labels: Type: Breaking, Impacts: Core

#2942 [NO-TICKET] Fix accordion heading styles getting clobbered by `ds-content` class
  packages/design-system/src/styles/_base.scss
  packages/design-system/src/styles/components/_Accordion.scss
Labels: Type: Fixed, Impacts: Core

#2947 [WNMGDS-2681] Fix instance of static id in Dialogs
  packages/design-system/src/components/Dialog/Dialog.tsx
  packages/design-system/src/components/Dialog/__snapshots__/Dialog.test.tsx.snap
  packages/design-system/src/components/ThirdPartyExternalLink/__snapshots__/ThirdPartyExternalLink.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/InlineLinkLists.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/PrivacySettingsLink.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#2945 [WNMGDS-2667] Separate color utils into their own module and add to them
  packages/design-system-tokens/src/lib/colorUtils.ts
  packages/design-system-tokens/src/lib/exportCssVars.ts
  packages/design-system-tokens/src/lib/exportCsv.ts
  packages/design-system-tokens/src/lib/exportScssVars.ts
  packages/design-system-tokens/src/lib/file.ts
  packages/design-system-tokens/src/themes/cmsgov-component.ts
  packages/design-system-tokens/src/themes/core-component.ts
  packages/design-system-tokens/src/themes/healthcare-component.ts
  packages/design-system-tokens/src/themes/medicare-component.ts
  packages/docs/src/components/content/ColorExampleRow.tsx
  packages/docs/src/components/designer-tools/AllThemesColorTable.tsx
Labels: Type: Internal, Impacts: Core

#2946 [WNMGDS-2667][WNMGDS-2668] Scripts for syncing tokens with Figma
  package.json
  packages/design-system-tokens/package.json
  packages/design-system-tokens/src/figma/FigmaApi.ts
  packages/design-system-tokens/src/figma/__snapshots__/translateTokensToFigma.test.ts.snap
  packages/design-system-tokens/src/figma/syncFigmaToTokens.ts
  packages/design-system-tokens/src/figma/syncTokensToFigma.ts
  packages/design-system-tokens/src/figma/test/test-get-response.ts
  packages/design-system-tokens/src/figma/test/tokens/System.Value.json
  packages/design-system-tokens/src/figma/test/tokens/Theme.cmsgov.json
  packages/design-system-tokens/src/figma/test/tokens/Theme.core.json
  packages/design-system-tokens/src/figma/tokenTypes.ts
  packages/design-system-tokens/src/figma/translateFigmaToTokens.test.ts
  packages/design-system-tokens/src/figma/translateFigmaToTokens.ts
  packages/design-system-tokens/src/figma/translateTokensToFigma.test.ts
  packages/design-system-tokens/src/figma/translateTokensToFigma.ts
  packages/design-system-tokens/src/lib/colorUtils.ts
  packages/design-system-tokens/src/tokens/primitives.json
Labels: Type: Internal, Impacts: Core

#2949 [WNMGDS-2673] Audit and update default props
  packages/design-system/src/components/Drawer/Drawer.tsx
  packages/design-system/src/components/Spinner/Spinner.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/__snapshots__/ThirdPartyExternalLink.test.tsx.snap
  tests/browser/snapshots/storybook-docs/Docs-Components-Spinner-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-ThirdPartyExternalLink-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Changed

#2954 [WNMGDS-2656] Make `case-it` a direct dependency
  packages/design-system/package.json
Labels: Type: Fixed, Impacts: Core
