Repository CMSgov/design-system, pull requests merged in 2024-06, with the labels that each got.

#3099 [WNMGDS-2779] Replace dropdown label with div
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/design-system/src/styles/components/_Dropdown.scss
Labels: Type: Fixed, Impacts: Core

#3103 [WNMGDS-2779] Update wc snaps, add component logic to fix wc test
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/web-components/ds-dropdown/__snapshots__/ds-dropdown.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#3101 [WNMGDS-2785] Add full support for font-family tokens
  packages/design-system-tokens/src/css/translate.ts
  packages/design-system-tokens/src/figma/translateFigmaToTokens.ts
  packages/design-system-tokens/src/figma/translateTokensToFigma.ts
  packages/design-system-tokens/src/lib/tokens.ts
  packages/design-system-tokens/src/tokens/System.Value.json
Labels: Impacts: Core, Type: Added

#3102 [NO-TICKET] Stop ignoring token files for Prettier cleanup
  .prettierignore
  packages/design-system-tokens/src/tokens/System.Value.json
  packages/design-system-tokens/src/tokens/Theme.cmsgov.json
  packages/design-system-tokens/src/tokens/Theme.core.json
  packages/design-system-tokens/src/tokens/Theme.healthcare.json
  packages/design-system-tokens/src/tokens/Theme.medicare.json
Labels: Impacts: Core, Type: Added

#3108 [NO-TICKET] Fix bug causing drawers to always trap focus
  packages/design-system/src/components/Drawer/Drawer.tsx
Labels: Type: Fixed, Impacts: Core

#3107 [WNMGDS-2785] Fix first batch of Figma/CSS differences
  package.json
  packages/design-system-tokens/src/css/translate.ts
  packages/design-system-tokens/src/figma/syncFigmaToTokens.ts
  packages/design-system-tokens/src/figma/translateFigmaToTokens.test.ts
  packages/design-system-tokens/src/figma/translateFigmaToTokens.ts
  packages/design-system-tokens/src/figma/translateTokensToFigma.ts
  packages/design-system-tokens/src/lib/tokens.ts
  packages/design-system-tokens/src/tokens/System.Value.json
  packages/design-system-tokens/src/tokens/Theme.cmsgov.json
  packages/design-system-tokens/src/tokens/Theme.core.json
  packages/design-system-tokens/src/tokens/Theme.healthcare.json
  packages/design-system-tokens/src/tokens/Theme.medicare.json
  packages/design-system/src/components/ChoiceList/ChoiceList.stories.tsx
  packages/design-system/src/styles/_base.scss
  packages/design-system/src/styles/_font.scss
  packages/design-system/src/styles/_reset.scss
  packages/design-system/src/styles/_set-for-deprecation.scss
  packages/design-system/src/styles/components/_Button.scss
  packages/design-system/src/styles/components/_ChoiceList.scss
  packages/design-system/src/styles/components/_Dialog.scss
  packages/design-system/src/styles/components/_Hint.scss
  packages/design-system/src/styles/utilities/_font-weight.scss
  packages/docs/content/foundation/typography/body.mdx
  packages/docs/content/foundation/typography/headings.mdx
  packages/docs/content/utilities/font/font-weight.mdx
  packages/ds-healthcare-gov/src/styles/components/_Inset.scss
  tests/browser/snapshots/stories/web-components-ds-hint--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-hint--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-hint--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-hint--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-hint--default-medicare--webkit.png
Labels: Type: Breaking, Impacts: Core

#3111 [WNMGDS-2785] Updated Accordion with Figma changes
  packages/design-system/src/styles/components/_Accordion.scss
  packages/ds-healthcare-gov/src/styles/components/_Accordion.scss
Labels: Type: Breaking, Impacts: Core

#3112 [WNMGDS-2785] Update USA Banner with Figma changes
  packages/design-system-tokens/src/tokens/Theme.cmsgov.json
  packages/design-system-tokens/src/tokens/Theme.core.json
  packages/design-system-tokens/src/tokens/Theme.healthcare.json
  packages/design-system-tokens/src/tokens/Theme.medicare.json
  packages/design-system/src/styles/components/_UsaBanner.scss
  tests/browser/snapshots/stories/components-usabanner--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-usabanner--default-medicare--chromium.png
  tests/browser/snapshots/stories/components-usabanner--default-medicare--firefox.png
  tests/browser/snapshots/stories/components-usabanner--default-medicare--webkit.png
Labels: Type: Breaking, Impacts: Core

#3121 [WNMGDS-2780] Implement stricter warnings when the `isOpen` prop isn't used
  packages/design-system/src/components/Dialog/Dialog.test.tsx
  packages/design-system/src/components/Dialog/Dialog.tsx
  packages/design-system/src/components/Drawer/Drawer.test.tsx
  packages/design-system/src/components/Drawer/Drawer.tsx
  packages/design-system/src/components/IdleTimeout/IdleTimeoutDialog.test.tsx
  packages/design-system/src/components/NativeDialog/NativeDialog.test.tsx
  packages/design-system/src/components/NativeDialog/NativeDialog.tsx
  packages/design-system/src/components/NativeDialog/useNativeDialogAnalytics.test.tsx
  packages/docs/src/components/layout/FilterDialog/FilterDialog.tsx
  tests/browser/snapshots/storybook-docs/Docs-Components-Dialog-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Medicare-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Changed

#3122 [NO-TICKET] Remove inversed prop from label-div
  packages/design-system/src/components/Dropdown/Dropdown.tsx
Labels: Type: Fixed, Impacts: Core

#3126 [NO-TICKET] Export the healthcare version of ThirdPartyExternalLink
  packages/ds-healthcare-gov/src/components/ThirdPartyExternalLink/index.ts
  packages/ds-healthcare-gov/src/components/index.ts
Labels: Type: Fixed, Impacts: Healthcare

#3097 [NO-TICKET] Delete Sketch plugin
  packages/design-system-tokens/sketch/cmsds-token-importer/.gitignore
  packages/design-system-tokens/sketch/cmsds-token-importer/README.md
  packages/design-system-tokens/sketch/cmsds-token-importer/assets/icon.png
  packages/design-system-tokens/sketch/cmsds-token-importer/cmsds-token-importer.sketchplugin/Contents/Resources/icon.png
  packages/design-system-tokens/sketch/cmsds-token-importer/cmsds-token-importer.sketchplugin/Contents/Sketch/json-token-importer.js
  packages/design-system-tokens/sketch/cmsds-token-importer/cmsds-token-importer.sketchplugin/Contents/Sketch/json-token-importer.js.map
  packages/design-system-tokens/sketch/cmsds-token-importer/cmsds-token-importer.sketchplugin/Contents/Sketch/manifest.json
  packages/design-system-tokens/sketch/cmsds-token-importer/package.json
  packages/design-system-tokens/sketch/cmsds-token-importer/sketch-assets/icons.sketch
  packages/design-system-tokens/sketch/cmsds-token-importer/sketchtool
  packages/design-system-tokens/sketch/cmsds-token-importer/src/color.js
  packages/design-system-tokens/sketch/cmsds-token-importer/src/json-token-importer.js
  packages/design-system-tokens/sketch/cmsds-token-importer/src/manifest.json
  packages/design-system-tokens/sketch/cmsds-token-importer/src/text.js
  packages/design-system-tokens/sketch/cmsds-token-importer/src/updateSharedStyleReferences.js
  packages/design-system-tokens/sketch/cmsds-token-importer/yarn.lock
Labels: Type: Internal, Impacts: Core

#3125 [NO-TICKET] Remove deprecated `analyticsEventTypeOverride` prop
  packages/design-system/src/components/Alert/Alert.tsx
  packages/design-system/src/components/Button/Button.tsx
  packages/design-system/src/components/Dialog/Dialog.tsx
  packages/design-system/src/components/HelpDrawer/HelpDrawer.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
  packages/design-system/src/components/analytics/types.ts
  tests/browser/snapshots/storybook-docs/Docs-Components-Button-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Dialog-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Medicare-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-components-Alert-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Breaking, Impacts: Core

#3051 [WNMGDS-2712] Update deprecated aria
  packages/design-system/src/components/Autocomplete/utils.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.test.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.tsx
  packages/design-system/src/components/ChoiceList/__snapshots__/ChoiceList.test.tsx.snap
  packages/design-system/src/components/CloseButton/CloseButton.tsx
  packages/design-system/src/components/Dialog/Dialog.test.tsx
  packages/design-system/src/components/Dialog/Dialog.tsx
  packages/design-system/src/components/Dialog/__snapshots__/Dialog.test.tsx.snap
  packages/design-system/src/components/Drawer/Drawer.stories.tsx
  packages/design-system/src/components/Drawer/Drawer.tsx
  packages/design-system/src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/HelpDrawer/__snapshots__/HelpDrawer.test.tsx.snap
  packages/design-system/src/components/IdleTimeout/IdleTimeout.test.tsx
  packages/design-system/src/components/NativeDialog/NativeDialog.tsx
  packages/design-system/src/components/NativeDialog/__snapshots__/NativeDialog.test.tsx.snap
  packages/design-system/src/components/ThirdPartyExternalLink/__snapshots__/ThirdPartyExternalLink.test.tsx.snap
  packages/design-system/src/components/web-components/ds-choice/__snapshots__/ds-choice-list.test.tsx.snap
  packages/design-system/src/components/web-components/ds-choice/ds-choice-list.test.tsx
  packages/design-system/src/styles/components/_Drawer.scss
  packages/docs/src/components/layout/FilterDialog/__snapshots__/FilterDialog.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#3128 [NO-TICKET] Update package script documentation in the README
  README.md
  package.json
Labels: Type: Internal, Impacts: Documentation

#3129 [WNMGDS-2800] Refactor alert so headingId is on heading node, not alert body
  packages/design-system/src/components/Alert/Alert.tsx
  packages/design-system/src/components/Alert/__snapshots__/Alert.test.tsx.snap
  packages/design-system/src/components/web-components/ds-alert/__snapshots__/ds-alert.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#3131 [WNMGDS-2797] Remove `ds-u-sans-serif` and `ds-u-serif` utility classes
  packages/design-system-tokens/src/css/__snapshots__/css-snapshots.test.ts.snap
  packages/design-system/src/styles/_set-for-deprecation.scss
  packages/design-system/src/styles/index.scss
  packages/design-system/src/styles/utilities/_font-family.scss
  packages/docs/content/utilities/font/font-family.mdx
  packages/docs/src/styles/pages/layout.scss
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/docs/static/themes/medicare-theme.css
Labels: Type: Breaking, Impacts: Core

#3133 [WNMGDS-2797] Remove the unused `--autocomplete*` and `--dropdown*` variables
  packages/design-system-tokens/src/tokens/Theme.cmsgov.json
  packages/design-system-tokens/src/tokens/Theme.core.json
  packages/design-system-tokens/src/tokens/Theme.healthcare.json
  packages/design-system-tokens/src/tokens/Theme.medicare.json
Labels: Type: Breaking, Impacts: Core

#3130 [NO-TICKET] Export the `useDialog` hook
  packages/design-system/src/components/Dialog/index.ts
Labels: Type: Fixed, Impacts: Core

#3135 [WNMGDS-2797] Use variable references in theme files
  packages/design-system-tokens/src/css/__snapshots__/css-snapshots.test.ts.snap
  packages/design-system-tokens/src/css/__snapshots__/translate.test.ts.snap
  packages/design-system-tokens/src/css/translate.ts
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/docs/static/themes/medicare-theme.css
Labels: Impacts: Core, Type: Changed

#3136 [WNMGDS-2801] `aria-live` and `aria-atomic` regions should always be present in DOM
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/design-system/src/components/InlineError/InlineError.tsx
  packages/design-system/src/components/InlineError/useInlineError.tsx
  packages/design-system/src/components/TextField/__snapshots__/TextField.test.tsx.snap
  packages/design-system/src/components/web-components/ds-choice/__snapshots__/ds-choice-list.test.tsx.snap
  packages/design-system/src/components/web-components/ds-dropdown/__snapshots__/ds-dropdown.test.tsx.snap
  tests/browser/snapshots/stories/components-icons--available-icons-cmsgov--Mobile-Chrome.png
Labels: Impacts: Core, Type: Changed

#3139 [NO-TICKET] Clean up analytics code in Storybook
  .storybook/preview.tsx
Labels: Type: Internal, Impacts: Core

#3137 [WNMGDS-2806] Apply Ed Alton's recommended updates
  packages/docs/content/patterns/Forms/error-validation.mdx
Labels: Type: Fixed, Impacts: Documentation

#3140 [WNMGDS-2811] Fix body scroll freeze persisting after dialog unmounts
  packages/design-system/src/components/Dialog/useBodyScrollPrevention.test.ts
  packages/design-system/src/components/Dialog/useBodyScrollPrevention.ts
Labels: Type: Fixed, Impacts: Core
