Repository CMSgov/design-system, pull requests merged in 2024-05, with the labels that each got.

#3064 [WNMGDS-2757] Upgrade `react-day-picker` library
  examples/astro/src/pages/react.astro
  examples/preact-app/webpack.config.js
  packages/design-system/package.json
  packages/design-system/src/components/DateField/CustomDayPicker.tsx
  packages/design-system/src/components/DateField/SingleInputDateField.tsx
  packages/design-system/src/styles/components/_SingleInputDateField.scss
  packages/docs/src/components/content/PublishDate.tsx
  tests/browser/snapshots/examples/astro-react/astro-react--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-react/astro-react--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-react/astro-react--chromium.png
  tests/browser/snapshots/examples/astro-react/astro-react--firefox.png
  tests/browser/snapshots/examples/astro-react/astro-react--webkit.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--cmsgov--chromium.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--cmsgov--firefox.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--cmsgov--webkit.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--core--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--core--chromium-forced-colors.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--core--chromium.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--core--firefox.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--core--webkit.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--healthcare--chromium.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--healthcare--firefox.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--healthcare--webkit.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--medicare--chromium.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--medicare--firefox.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--medicare--webkit.png
  yarn.lock
Labels: Type: Fixed, Impacts: Core

#3065 [WNMGDS-2766] Apply user-supplied ids to table elements
  packages/design-system/src/components/Table/Table.test.tsx
  packages/design-system/src/components/Table/Table.tsx
  packages/design-system/src/components/Table/__snapshots__/Table.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#3066 [WNMGDS-2765] Move `cmsds-migrate` script dependencies into `dependencies`
  examples/astro/src/components/react/HelpDrawerExample.tsx
  examples/astro/src/components/react/TabsExample.tsx
  packages/design-system/package.json
Labels: Type: Fixed, Impacts: Core

#3067 [WNMGDS-2762] Fix accordions interfering with keyboard strokes of child elements
  packages/design-system/src/components/Accordion/Accordion.test.tsx
  packages/design-system/src/components/Accordion/Accordion.tsx
Labels: Type: Fixed, Impacts: Core

#3070 [WNMGDS-2744] Add bundle generation for individual web components
  examples/astro/src/pages/web-components.astro
  packages/design-system/package.json
  packages/docs/content/getting-started/for-developers.mdx
  packages/ds-cms-gov/package.json
  packages/ds-medicare-gov/package.json
  scripts/build-cdn-indexes.ts
  webpack.config.js
Labels: Type: Breaking, Impacts: Core

#3071 [WNMGDS-2771] Add `ds-accordion` and `ds-accordion-item` web components
  examples/astro/src/pages/web-components.astro
  packages/design-system/src/components/Accordion/AccordionItem.tsx
  packages/design-system/src/components/Accordion/index.ts
  packages/design-system/src/components/web-components/ds-accordion/__snapshots__/ds-accordion-item.test.tsx.snap
  packages/design-system/src/components/web-components/ds-accordion/__snapshots__/ds-accordion.test.tsx.snap
  packages/design-system/src/components/web-components/ds-accordion/ds-accordion-item.stories.tsx
  packages/design-system/src/components/web-components/ds-accordion/ds-accordion-item.test.tsx
  packages/design-system/src/components/web-components/ds-accordion/ds-accordion-item.tsx
  packages/design-system/src/components/web-components/ds-accordion/ds-accordion.stories.tsx
  packages/design-system/src/components/web-components/ds-accordion/ds-accordion.test.tsx
  packages/design-system/src/components/web-components/ds-accordion/ds-accordion.tsx
  packages/design-system/src/components/web-components/ds-accordion/index.ts
  packages/design-system/src/components/web-components/index.ts
  packages/design-system/src/styles/_web-components.scss
  packages/design-system/src/styles/components/_Accordion.scss
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--firefox.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--webkit.png
  tests/browser/snapshots/stories/web-components-accordion--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-accordion--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-accordion--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-accordion--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-accordion--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-accordion--default-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-accordion--default-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-accordion--default-core--chromium.png
  tests/browser/snapshots/stories/web-components-accordion--default-core--firefox.png
  tests/browser/snapshots/stories/web-components-accordion--default-core--webkit.png
  tests/browser/snapshots/stories/web-components-accordion--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-accordion--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-accordion--default-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-accordion--default-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-accordion--default-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-accordion--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-accordion--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-accordion--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-accordion--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-accordion--default-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Pagination-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Review-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Medicare-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-Accordion-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-AccordionItem-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-components-Alert-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/stories.test.ts
  webpack.config.js
Labels: Impacts: Core, Type: Added

#3072 [WNMGDS-2744] Make the web components bundle split backwards compatible
  webpack.config.js
Labels: Impacts: Core, Type: Added

#3073 [NO-TICKET] Add live-analytics option to Storybook
  .storybook/preview.tsx
Labels: Type: Internal, Impacts: Documentation

#3076 [NO-TICKET] Small changes for analytics testing
  .storybook/preview.tsx
Labels: Type: Internal, Impacts: Documentation

#3075 [WNMGDS-2767] Add `ds-pagination` web component
  .storybook/docs/WebComponentArgsTable.tsx
  examples/astro/src/pages/web-components.astro
  packages/design-system/src/components/Pagination/Pagination.test.tsx
  packages/design-system/src/components/Pagination/Pagination.tsx
  packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  packages/design-system/src/components/Pagination/index.ts
  packages/design-system/src/components/web-components/ds-accordion/ds-accordion.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.tsx
  packages/design-system/src/components/web-components/ds-month-picker/ds-month-picker.tsx
  packages/design-system/src/components/web-components/ds-pagination/__snapshots__/ds-pagination.test.tsx.snap
  packages/design-system/src/components/web-components/ds-pagination/ds-pagination.stories.tsx
  packages/design-system/src/components/web-components/ds-pagination/ds-pagination.test.tsx
  packages/design-system/src/components/web-components/ds-pagination/ds-pagination.tsx
  packages/design-system/src/components/web-components/ds-pagination/index.ts
  packages/design-system/src/components/web-components/ds-skip-nav/ds-skip-nav.ts
  packages/design-system/src/components/web-components/ds-spinner/ds-spinner.tsx
  packages/design-system/src/components/web-components/preactement/define.ts
  packages/design-system/src/components/web-components/preactement/model.ts
  packages/design-system/src/components/web-components/preactement/shared/model.ts
  packages/design-system/src/components/web-components/preactement/shared/parse.ts
  packages/design-system/src/components/web-components/wrapperUtils.ts
  packages/design-system/src/styles/_web-components.scss
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--firefox.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--webkit.png
  tests/browser/snapshots/stories/web-components-pagination--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-pagination--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-pagination--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-pagination--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-pagination--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-pagination--default-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-pagination--default-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-pagination--default-core--chromium.png
  tests/browser/snapshots/stories/web-components-pagination--default-core--firefox.png
  tests/browser/snapshots/stories/web-components-pagination--default-core--webkit.png
  tests/browser/snapshots/stories/web-components-pagination--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-pagination--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-pagination--default-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-pagination--default-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-pagination--default-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-pagination--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-pagination--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-pagination--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-pagination--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-pagination--default-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Pagination-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Review-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Medicare-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-Pagination-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-components-Alert-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3078 [NO-TICKET] Update analytics docs page with recent changes
  packages/docs/content/components/analytics.mdx
Labels: Impacts: Documentation, Type: Added

#3077 [WNMGDS-2770] New blog post for 10.1
  packages/docs/content/blog/release-10.1.mdx
Labels: Impacts: Documentation, Type: Added

#3079 [NO-TICKET] Add documentation for web component slots
  .storybook/docs/WebComponentDocTemplate.mdx
  .storybook/docs/WebComponentEventsTable.tsx
  .storybook/docs/WebComponentSlotsTable.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice.stories.tsx
Labels: Impacts: Documentation, Type: Added

#3082 [NO-TICKET] Fix web component custom events missing the default `event.detail.target`
  packages/design-system/src/components/web-components/preactement/define.test.tsx
  packages/design-system/src/components/web-components/preactement/define.ts
Labels: Type: Fixed, Impacts: Core

#3081 [WNMGDS-2724] ds-choice-list web component
  examples/astro/src/pages/web-components.astro
  packages/design-system/src/components/web-components/ds-choice-list/__snapshots__/ds-choice-list.test.tsx.snap
  packages/design-system/src/components/web-components/ds-choice-list/ds-choice-list.stories.tsx
  packages/design-system/src/components/web-components/ds-choice-list/ds-choice-list.test.tsx
  packages/design-system/src/components/web-components/ds-choice-list/ds-choice-list.tsx
  packages/design-system/src/components/web-components/ds-choice-list/index.ts
  packages/design-system/src/components/web-components/index.ts
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--firefox.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--webkit.png
  tests/browser/snapshots/stories/web-components-choicelist--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-choicelist--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-choicelist--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-choicelist--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-choicelist--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-choicelist--default-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-choicelist--default-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-choicelist--default-core--chromium.png
  tests/browser/snapshots/stories/web-components-choicelist--default-core--firefox.png
  tests/browser/snapshots/stories/web-components-choicelist--default-core--webkit.png
  tests/browser/snapshots/stories/web-components-choicelist--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-choicelist--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-choicelist--default-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-choicelist--default-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-choicelist--default-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-choicelist--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-choicelist--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-choicelist--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-choicelist--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-choicelist--default-medicare--webkit.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-core--chromium.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-core--firefox.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-core--webkit.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-choicelist--html-choices-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ChoiceList-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3084 [NO-TICKET] Combine `ds-choice` and `ds-choice-list` into a single bundle
  examples/astro/src/pages/web-components.astro
  packages/design-system/src/components/web-components/ds-choice-list/index.ts
  packages/design-system/src/components/web-components/ds-choice/__snapshots__/ds-choice-list.test.tsx.snap
  packages/design-system/src/components/web-components/ds-choice/ds-choice-list.stories.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice-list.test.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice-list.tsx
  packages/design-system/src/components/web-components/ds-choice/index.ts
  packages/design-system/src/components/web-components/index.ts
Labels: Impacts: Core, Type: Changed

#3086 [NO-TICKET] Fix bad VRT snapshot file
  tests/browser/snapshots/stories/web-components-ds-skip-nav--default-medicare--webkit.png
Labels: Type: Internal, Impacts: Core

#3083 [WNMGDS-2716] Remove privacy settings dialog
  packages/design-system/src/components/PrivacySettingsDialog/PrivacySettingsDialog.stories.tsx
  packages/design-system/src/components/PrivacySettingsDialog/PrivacySettingsDialog.test.jsx
  packages/design-system/src/components/PrivacySettingsDialog/PrivacySettingsDialog.tsx
  packages/design-system/src/components/PrivacySettingsDialog/PrivacySettingsTable.test.jsx
  packages/design-system/src/components/PrivacySettingsDialog/PrivacySettingsTable.tsx
  packages/design-system/src/components/PrivacySettingsDialog/__snapshots__/PrivacySettingsTable.test.jsx.snap
  packages/design-system/src/components/PrivacySettingsDialog/index.ts
  packages/design-system/src/components/PrivacySettingsDialog/privacySettings.test.ts
  packages/design-system/src/components/PrivacySettingsDialog/privacySettings.ts
  packages/design-system/src/components/analytics/events.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/styles/components/_PrivacySettings.scss
  packages/design-system/src/styles/index.scss
  packages/docs/src/components/layout/DocSiteFooter.tsx
  packages/ds-healthcare-gov/src/components/Footer/PrivacySettingsLink.tsx
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/InlineLinkLists.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/PrivacySettingsLink.test.tsx.snap
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-core--chromium.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-core--firefox.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-core--webkit.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-healthcare--chromium.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-healthcare--firefox.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-healthcare--webkit.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-medicare--chromium.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-medicare--firefox.png
  tests/browser/snapshots/stories/components-privacysettingsdialog--default-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Components-PrivacySettingsDialog-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Breaking, Impacts: Core

#3089 [WNMGDS-2760] Web component pass-thru attributes
  .storybook/docs/HtmlElementArgs.tsx
  .storybook/docs/WebComponentAttrs.tsx
  .storybook/docs/WebComponentDocTemplate.mdx
  packages/design-system/src/components/StepList/StepLink.tsx
  packages/design-system/src/components/web-components/ds-alert/ds-alert.stories.tsx
  packages/design-system/src/components/web-components/ds-alert/ds-alert.tsx
  packages/design-system/src/components/web-components/ds-badge/ds-badge.stories.tsx
  packages/design-system/src/components/web-components/ds-button/ds-button.stories.tsx
  packages/design-system/src/components/web-components/ds-button/ds-button.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice-list.stories.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice-list.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice.stories.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.stories.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.tsx
  packages/design-system/src/components/web-components/ds-hint/ds-hint.stories.tsx
  packages/design-system/src/components/web-components/ds-inline-error/ds-inline-error.stories.tsx
  packages/design-system/src/components/web-components/ds-label/ds-label.stories.tsx
  packages/design-system/src/components/web-components/ds-month-picker/ds-month-picker.stories.tsx
  packages/design-system/src/components/web-components/ds-month-picker/ds-month-picker.tsx
  packages/design-system/src/components/web-components/ds-skip-nav/ds-skip-nav.stories.tsx
  packages/design-system/src/components/web-components/ds-spinner/ds-spinner.stories.tsx
  packages/design-system/src/components/web-components/shared-attributes/accessibility.ts
  packages/design-system/src/components/web-components/shared-attributes/analytics.ts
  packages/design-system/src/components/web-components/shared-attributes/form.ts
  tests/browser/snapshots/storybook-docs/Docs-Components-StepList-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Breaking, Impacts: Core

#3090 [NO-TICKET] Generate the top-level CDN index
  .gitignore
  scripts/build-cdn-indexes.ts
  scripts/versions.ts
Labels: Impacts: Documentation, Type: Changed

#3091 [WNMGDS-2775] Restore additional screen-reader context for calendar-picker days
  packages/design-system/src/components/DateField/CustomDayPicker.tsx
  packages/design-system/src/components/DateField/CustomDayPickerDayContent.tsx
Labels: Type: Fixed, Impacts: Core

#3094 [WNMGDS-2790] Fix the `MultiInputDateField` overwriting some props with defaults
  packages/design-system/src/components/DateField/MultiInputDateField.test.tsx
  packages/design-system/src/components/DateField/MultiInputDateField.tsx
Labels: Type: Fixed, Impacts: Core

#3095 [WNMGDS-2784] Change end to flex-end to quiet another teams console warn
  packages/design-system/src/styles/components/_UsaBanner.scss
Labels: Type: Fixed, Impacts: Core

#3096 [NO-TICKET] Add missing `Hint`-component export
  packages/design-system/src/components/index.ts
Labels: Type: Fixed, Impacts: Core

#3098 [WNMGDS-2786] Update doc site code to use new JSON tokens
  packages/design-system-tokens/src/css/css-snapshots.test.ts
  packages/design-system-tokens/src/css/index.ts
  packages/design-system-tokens/src/css/translate.test.ts
  packages/design-system-tokens/src/css/translate.ts
  packages/design-system-tokens/src/figma/syncFigmaToTokens.ts
  packages/design-system-tokens/src/figma/syncTokensToFigma.ts
  packages/design-system-tokens/src/figma/translateTokensToFigma.test.ts
  packages/design-system-tokens/src/lib/__snapshots__/readTokenFiles.test.ts.snap
  packages/design-system-tokens/src/lib/readTokenFiles.test.ts
  packages/design-system-tokens/src/lib/readTokenFiles.ts
  packages/design-system-tokens/src/lib/tokens.ts
  packages/docs/src/components/content/ColorExampleRow.tsx
  packages/docs/src/components/content/ColorRamps.tsx
  packages/docs/src/components/content/ColorSwatch.tsx
  packages/docs/src/components/content/ComponentThemeOptions.tsx
  packages/docs/src/components/content/TextColorList.tsx
  packages/docs/src/components/designer-tools/AllThemesColorTable.tsx
  packages/docs/src/helpers/themeTokens.ts
  packages/docs/src/pages/designer-tools/all-theme-colors.tsx
  packages/docs/src/styles/pages/layout.scss
Labels: Impacts: Documentation, Type: Changed
