Repository CMSgov/design-system, pull requests merged in 2024-07, with the labels that each got.

#3142 [WNMGDS-2808] Fix Firefox scrolling pages to the top when a dialog opens
  packages/design-system/src/styles/components/_Dialog.scss
Labels: Type: Fixed, Impacts: Core

#3143 [WNMGDS-2809] Fix "dropdown flash"
  packages/design-system/src/components/Dropdown/DropdownMenuOption.tsx
Labels: Type: Fixed, Impacts: Core

#2860 [LHDM-2201] Header/Footer Custom classes/IDs
  packages/design-system/src/styles/components/_Accordion.scss
  packages/ds-healthcare-gov/src/components/Footer/Footer.tsx
  packages/ds-healthcare-gov/src/components/Footer/LogosRow.tsx
  packages/ds-healthcare-gov/src/components/Header/Header.test.tsx
  packages/ds-healthcare-gov/src/components/Header/Header.tsx
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/defaultMenuLinks.test.js.snap
  packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.ts
  tests/browser/snapshots/storybook-docs/Docs-Healthcare-Footer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Healthcare-Header-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Healthcare, Type: Changed

#3145 [WNMGDS-2818] Prevent nested errors in choicelist
  packages/design-system/src/components/ChoiceList/Choice.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.tsx
  packages/design-system/src/components/ChoiceList/__snapshots__/Choice.test.tsx.snap
  packages/design-system/src/components/MonthPicker/MonthPicker.tsx
  packages/design-system/src/components/web-components/ds-choice/__snapshots__/ds-choice.test.tsx.snap
  packages/design-system/src/components/web-components/preactement/parse.test.ts
  tests/browser/snapshots/storybook-docs/Docs-Components-Choice-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-ChoiceList-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Breaking, Impacts: Core

#3146 [WNMGDS-2821] Fix generating error ids for individual Choices
  packages/design-system/src/components/ChoiceList/Choice.tsx
  packages/design-system/src/components/web-components/ds-choice/__snapshots__/ds-choice.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#3150 [NO-TICKET] Remove available icons from VRT to avoid flakiness
  tests/browser/snapshots/stories/components-icons--available-icons-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-icons--available-icons-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-icons--available-icons-cmsgov--chromium.png
  tests/browser/snapshots/stories/components-icons--available-icons-cmsgov--firefox.png
  tests/browser/snapshots/stories/components-icons--available-icons-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-icons--available-icons-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-icons--available-icons-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-icons--available-icons-core--chromium.png
  tests/browser/snapshots/stories/components-icons--available-icons-core--firefox.png
  tests/browser/snapshots/stories/components-icons--available-icons-core--webkit.png
  tests/browser/snapshots/stories/components-icons--available-icons-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-icons--available-icons-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-icons--available-icons-healthcare--chromium.png
  tests/browser/snapshots/stories/components-icons--available-icons-healthcare--firefox.png
  tests/browser/snapshots/stories/components-icons--available-icons-healthcare--webkit.png
  tests/browser/snapshots/stories/components-icons--available-icons-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-icons--available-icons-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-icons--available-icons-medicare--chromium.png
  tests/browser/snapshots/stories/components-icons--available-icons-medicare--firefox.png
  tests/browser/snapshots/stories/components-icons--available-icons-medicare--webkit.png
  tests/browser/stories.test.ts
Labels: Type: Internal, Impacts: Core

#3153 [WNMGDS-2645] Remove unused storybook styles, add support for font fallbacks
  .storybook/cmsTheme.ts
  .storybook/preview.tsx
Labels: Type: Fixed, dependencies

#3154 [WNMGDS-2828] Update avoid error message guidance.
  packages/docs/content/patterns/Forms/error-validation.mdx
Labels: Type: Fixed, Impacts: Documentation

#3156 [WNMGDS-2826] Update third party external link docs to include pdf guidance
  packages/docs/content/components/third-party-external-link.mdx
Labels: Impacts: Documentation, Type: Added

#3157 [WNMGDS-2807] Fix medicare component overrides and make handling of side effects consistent
  packages/ds-healthcare-gov/package.json
  packages/ds-healthcare-gov/src/components/Accordion/Accordion.stories.tsx
  packages/ds-healthcare-gov/src/components/Accordion/AccordionItem.tsx
  packages/ds-healthcare-gov/src/components/Accordion/index.tsx
  packages/ds-healthcare-gov/src/components/Footer/Footer.tsx
  packages/ds-healthcare-gov/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
  packages/ds-healthcare-gov/src/components/i18n.ts
  packages/ds-healthcare-gov/src/components/index.ts
  packages/ds-medicare-gov/package.json
  packages/ds-medicare-gov/src/components/Card/Card.tsx
  packages/ds-medicare-gov/src/components/Card/index.ts
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.jsx
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.stories.tsx
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawerToggle.jsx
  packages/ds-medicare-gov/src/components/HelpDrawer/index.ts
  packages/ds-medicare-gov/src/components/MedicaregovLogo/MedicaregovLogo.spec.tsx
  packages/ds-medicare-gov/src/components/MedicaregovLogo/MedicaregovLogo.tsx
  packages/ds-medicare-gov/src/components/MedicaregovLogo/index.ts
  packages/ds-medicare-gov/src/components/MedicaregovLogo/medicaregovLogo.stories.tsx
  packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.tsx
  packages/ds-medicare-gov/src/components/SimpleFooter/index.ts
  packages/ds-medicare-gov/src/components/Stars/Stars.tsx
  packages/ds-medicare-gov/src/components/Stars/index.ts
  packages/ds-medicare-gov/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
  packages/ds-medicare-gov/src/components/ThirdPartyExternalLink/index.ts
  packages/ds-medicare-gov/src/components/index.ts
Labels: Type: Fixed, Impacts: Medicare

#3158 [WNMGDS-2825] Fix release tagging
  README.md
  lerna.json
  package.json
  scripts/release.ts
  scripts/versions.ts
  yarn.lock
Labels: Type: Internal, Impacts: Core

#3169 [WNMGDS-2709] Implement open graph tags
  packages/docs/src/components/layout/Layout.tsx
Labels: Type: Internal, Impacts: Documentation

#3170 [NO-TICKET] Update the example `.env` file to use the new Figma file id
  packages/design-system-tokens/.env.example
Labels: Type: Internal, Impacts: Core

#3173 [WNMGDS-2836] Update Design Assets section of README
  README.md
Labels: Type: Internal, Impacts: Documentation

#3176 [NO-TICKET] Fix Gatsby static image paths for archives and demos
  package.json
  packages/docs/src/components/content/ContentRenderer.tsx
  scripts/deploy-demo.ts
  scripts/deployDemo.ts
Labels: Type: Fixed, Impacts: Documentation

#3183 [NO-TICKET] Fix the bug caused by the first fix to Gatsby image paths
  packages/docs/src/components/content/ContentRenderer.tsx
Labels: Type: Fixed, Impacts: Documentation

#3174 [WNMGDS-2853 ] Release 11.0 blog post
  packages/docs/content/blog/release-11.0.mdx
  packages/docs/src/images/sketch-to-figma.jpg
Labels: Impacts: Documentation, Type: Added
