Repository CMSgov/design-system, pull requests merged in 2024-12, with the labels that each got.

#3342 [WNMGDS-3057] Fix inconsistencies in review heading styles
  packages/design-system/src/styles/components/_Review.scss
  tests/browser/snapshots/examples/astro-cmsgov-web-components/astro-cmsgov-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-cmsgov-web-components/astro-cmsgov-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-cmsgov-web-components/astro-cmsgov-web-components--chromium.png
  tests/browser/snapshots/examples/astro-cmsgov-web-components/astro-cmsgov-web-components--firefox.png
  tests/browser/snapshots/examples/astro-cmsgov-web-components/astro-cmsgov-web-components--webkit.png
  tests/browser/snapshots/examples/astro-healthcare-web-components/astro-healthcare-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-healthcare-web-components/astro-healthcare-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-healthcare-web-components/astro-healthcare-web-components--chromium.png
  tests/browser/snapshots/examples/astro-healthcare-web-components/astro-healthcare-web-components--firefox.png
  tests/browser/snapshots/examples/astro-healthcare-web-components/astro-healthcare-web-components--webkit.png
  tests/browser/snapshots/examples/astro-medicare-web-components/astro-medicare-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-medicare-web-components/astro-medicare-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-medicare-web-components/astro-medicare-web-components--chromium.png
  tests/browser/snapshots/examples/astro-medicare-web-components/astro-medicare-web-components--firefox.png
  tests/browser/snapshots/examples/astro-medicare-web-components/astro-medicare-web-components--webkit.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--firefox.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--webkit.png
Labels: Type: Breaking, Impacts: Core

#3331 [WNMGDS-2992] Allow pass through props into TextField from ds-autocomplete
  packages/design-system/src/components/InlineError/useInlineError.tsx
  packages/design-system/src/components/web-components/ds-autocomplete/__snapshots__/ds-autocomplete.test.tsx.snap
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.stories.tsx
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.test.tsx
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.tsx
  packages/design-system/src/components/web-components/utils.ts
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-autocomplete-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Changed

#3335 [WNMGDS-3044] Adds custom playwright reporter to provide JSON summary of test result data
  tests/browser/__snapshots__/custom-reporter.test.ts.snap
  tests/browser/custom-reporter.test.ts
  tests/browser/custom-reporter.ts
  tests/browser/playwright.config.ts
  tests/unit/jest.config.js
Labels: Type: Internal, Type: Added

#3345 [NO-TICKET] Use isPossibleValue util function in more places and add spec
  packages/design-system/src/components/Dialog/Dialog.tsx
  packages/design-system/src/components/Tooltip/Tooltip.tsx
  packages/design-system/src/components/web-components/ds-modal-dialog/ds-modal-dialog.tsx
  packages/design-system/src/components/web-components/ds-tooltip/ds-tooltip.tsx
  packages/design-system/src/components/web-components/utils.test.ts
Labels: Impacts: Core, Type: Changed

#3351 [WNMGDS-3047] Adds test coverage when async data fetching with Autocomplete
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  packages/design-system/src/components/Autocomplete/Autocomplete.stories.tsx
  packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
  tests/browser/stories.test.ts
  yarn.lock
Labels: Impacts: Core, Type: Added

#3350 [WNMGDS-3143] Fix `analytics={false}` being passed in `ds-modal-dialog`
  packages/design-system/src/components/web-components/__tests__/analytics.ts
  packages/design-system/src/components/web-components/analytics.ts
  packages/design-system/src/components/web-components/ds-alert/ds-alert.test.tsx
  packages/design-system/src/components/web-components/ds-modal-dialog/__snapshots__/ds-modal-dialog.test.tsx.snap
  packages/design-system/src/components/web-components/ds-modal-dialog/ds-modal-dialog.test.tsx
  packages/design-system/src/components/web-components/ds-modal-dialog/ds-modal-dialog.tsx
Labels: Type: Fixed, Impacts: Core

#3353 [NO-TICKET] Change the failure threshold for VRT screenshots
  packages/design-system/src/components/Autocomplete/Autocomplete.test.interaction.ts
  packages/design-system/src/components/Button/Button.test.interaction.ts
  packages/design-system/src/components/DateField/SingleInputDateField.test.interaction.ts
  packages/design-system/src/components/Dialog/Dialog.test.interaction.ts
  packages/design-system/src/components/Drawer/Drawer.test.interaction.ts
  packages/design-system/src/components/Dropdown/Dropdown.test.interaction.ts
  packages/design-system/src/components/TextField/Mask.test.interaction.ts
  packages/design-system/src/components/TextField/TextField.test.interaction.ts
  packages/design-system/src/components/Tooltip/Tooltip.test.interaction.ts
  packages/design-system/src/components/web-components/ds-modal-dialog/ds-modal-dialog.test.interaction.ts
  tests/browser/examples.test.ts
  tests/browser/expectNoAxeViolations.ts
  tests/browser/expectScreenshot.ts
  tests/browser/interactionHelpers.ts
  tests/browser/stories.test.ts
Labels: Type: Internal, Impacts: Core

#3354 [WNMGDS-3126] Adds test coverage for fetching async data with `ds-autocomplete`
  packages/design-system/src/components/Autocomplete/Autocomplete.stories.tsx
  packages/design-system/src/components/Autocomplete/testMocks.tsx
  packages/design-system/src/components/web-components/ds-autocomplete/__snapshots__/ds-autocomplete.test.tsx.snap
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.stories.tsx
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.test.tsx
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-core--chromium.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-core--firefox.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-core--webkit.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--loading-message-medicare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-core--chromium.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-core--firefox.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-core--webkit.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-autocomplete--no-results-medicare--webkit.png
  tests/browser/stories.test.ts
Labels: Impacts: Core, Type: Added

#3356 [WNMGDS-2928] Standardize `inputRef` prop types
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/Button/Button.test.tsx
  packages/design-system/src/components/Button/Button.tsx
  packages/design-system/src/components/ChoiceList/Choice.test.tsx
  packages/design-system/src/components/ChoiceList/Choice.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.stories.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.tsx
  packages/design-system/src/components/DateField/SingleInputDateField.tsx
  packages/design-system/src/components/Dropdown/Dropdown.test.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/TextField/TextField.test.tsx
  packages/design-system/src/components/TextField/TextField.tsx
  packages/design-system/src/components/TextField/TextInput.test.tsx
  packages/design-system/src/components/TextField/TextInput.tsx
  tests/browser/snapshots/storybook-docs/Docs-Components-Autocomplete-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Choice-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Dropdown-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-SingleInputDateField-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-TextField-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Fixed, Impacts: Core

#3352 [WNMGDS-3127] Adds stories to document grouped-item functionality in `ds-autocomplete`
  packages/design-system/src/components/Autocomplete/Autocomplete.stories.tsx
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.stories.tsx
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.test.tsx
  tests/browser/stories.test.ts
Labels: Impacts: Core, Type: Added

#3357 [WNMGDS-3077] Fix wrong Storybook iframes loading on doc site
  packages/docs/src/components/content/ColorExampleList.tsx
  packages/docs/src/components/content/StorybookExample.tsx
  packages/docs/src/helpers/clientOnly.ts
  packages/docs/src/helpers/clientOnly.tsx
Labels: Type: Fixed, Impacts: Documentation

#3362 [WNMGDS-3147] Enable `--list` for playwright custom playwright reporter
  tests/browser/__snapshots__/custom-reporter.test.ts.snap
  tests/browser/custom-reporter.test.ts
  tests/browser/custom-reporter.ts
Labels: Type: Fixed, Type: Internal, Impacts: Core

#3361 [WNMGDS-2928] Follow up to improve the standardized `inputRef` types
  packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/Button/Button.test.tsx
  packages/design-system/src/components/Button/Button.tsx
  packages/design-system/src/components/ChoiceList/Choice.test.tsx
  packages/design-system/src/components/ChoiceList/Choice.tsx
  packages/design-system/src/components/Dropdown/Dropdown.test.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/TextField/TextField.test.tsx
  packages/design-system/src/components/TextField/TextField.tsx
  packages/design-system/src/components/TextField/TextInput.test.tsx
  packages/design-system/src/components/TextField/TextInput.tsx
  tests/browser/snapshots/storybook-docs/Docs-Components-Autocomplete-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Choice-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Dropdown-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-SingleInputDateField-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-TextField-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Fixed, Impacts: Core
