Repository CMSgov/design-system, pull requests merged in 2024-10, with the labels that each got.

#3250 [WNMDGS-2959] Added Lexend and Public Sans font files to CMSgov theme
  packages/ds-cms-gov/src/fonts/lexend/Lexend-SemiBold.woff2
  packages/ds-cms-gov/src/fonts/public-sans/PublicSans-Regular.woff2
Labels: Impacts: CMSgov, Type: Added

#3258 [NO-TICKET] Adds optional bundle analysis to the build command
  .gitignore
  README.md
  gulpfile.js
  package.json
  webpack.config.js
  yarn.lock
Labels: Type: Internal, Impacts: Core

#3256 [WMNGDS-2918] Adds ds-drawer web component.
  packages/design-system/src/components/Drawer/Drawer.tsx
  packages/design-system/src/components/web-components/ds-drawer/__snapshots__/ds-drawer.test.tsx.snap
  packages/design-system/src/components/web-components/ds-drawer/ds-drawer.stories.tsx
  packages/design-system/src/components/web-components/ds-drawer/ds-drawer.test.tsx
  packages/design-system/src/components/web-components/ds-drawer/ds-drawer.tsx
  packages/design-system/src/components/web-components/ds-drawer/index.ts
  packages/design-system/src/components/web-components/index.ts
  tests/browser/snapshots/stories/web-components-ds-drawer--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-core--chromium.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-core--firefox.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-core--webkit.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-drawer--default-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Medicare-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/stories.test.ts
Labels: Impacts: Core, Type: Added

#3262 [WNMGDS-2993] Simplify NPM distribution method for web components
  examples/astro/src/pages/web-components.astro
  packages/design-system/package.json
  packages/ds-cms-gov/package.json
  packages/ds-healthcare-gov/package.json
  packages/ds-medicare-gov/package.json
Labels: Type: Fixed, Impacts: Core

#3266 [NO-TICKET] Undo semibold deprecation
  packages/design-system/src/styles/_font.scss
  packages/design-system/src/styles/_set-for-deprecation.scss
  packages/design-system/src/styles/utilities/_font-weight.scss
  packages/docs/content/foundation/typography/body.mdx
  packages/docs/content/foundation/typography/headings.mdx
  packages/docs/content/utilities/font/font-weight.mdx
Labels: Type: Fixed, Impacts: Core

#3274 [WNMGDS-2934] Expand the `clean` command with `clean:builds` subcommand
  package.json
Labels: Type: Internal, Impacts: Core

#3264 [WNGDS-2978] Add customizable `arialabel` prop to `Tabs` component.
  packages/design-system/src/components/Tabs/Tabs.test.tsx
  packages/design-system/src/components/Tabs/Tabs.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tabs.stories.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tabs.test.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tabs.tsx
  tests/browser/snapshots/storybook-docs/Docs-Components-Tabs-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-tabs-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3270 [WNMGDS-2921] Implement Filter Chip Web Component
  examples/cdn-web-components/index.html
  packages/design-system/src/components/web-components/ds-filter-chip/__snapshots__/ds-filter-chip.test.tsx.snap
  packages/design-system/src/components/web-components/ds-filter-chip/ds-filter-chip.stories.tsx
  packages/design-system/src/components/web-components/ds-filter-chip/ds-filter-chip.test.tsx
  packages/design-system/src/components/web-components/ds-filter-chip/ds-filter-chip.tsx
  packages/design-system/src/components/web-components/ds-filter-chip/index.ts
  packages/design-system/src/components/web-components/index.ts
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--chromium.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--firefox.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--webkit.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-core--chromium.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-core--firefox.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-core--webkit.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-medicare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-core--chromium.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-core--firefox.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-core--webkit.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-filter-chip-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3281 [NO-TICKET] Resolves stylelint errors and updates snapshots
  .storybook/storybookStyles.scss
  tests/browser/snapshots/stories/components-badge--warning-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-choicelist--default-checkbox-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-dropdown--inverse-option-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-pagination--compact-navigation-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-pagination--hidden-navigation-cmsgov--webkit.png
  tests/browser/snapshots/stories/utilities-float--float-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-ds-filter-chip--multiple-chips-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-tab-panel--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-tab-panel--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-tab-panel--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-ds-tab-panel--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-ds-tab-panel--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-cmsgov--webkit.png
Labels: Type: Fixed, Impacts: Core

#3267 [WNMGDS-2999] Add a shared web components example template and new example project
  examples/README.md
  examples/_web-components-template.html
  examples/astro-themes/.gitignore
  examples/astro-themes/.vscode/extensions.json
  examples/astro-themes/.vscode/launch.json
  examples/astro-themes/README.md
  examples/astro-themes/package.json
  examples/astro-themes/public/favicon.svg
  examples/astro-themes/src/components/Layout.astro
  examples/astro-themes/src/components/WebComponentExamples.astro
  examples/astro-themes/src/env.d.ts
  examples/astro-themes/src/pages/cmsgov.astro
  examples/astro-themes/src/pages/core.astro
  examples/astro-themes/src/pages/healthcare.astro
  examples/astro-themes/src/pages/index.astro
  examples/astro-themes/src/pages/medicare.astro
  examples/astro-themes/tsconfig.json
  examples/astro/src/pages/web-components.astro
  examples/cdn-web-components/index.html
  package.json
  scripts/apply-example-templates.ts
  scripts/build-examples.ts
  scripts/deploy-demo.ts
  scripts/utils.ts
  tests/browser/examples.test.ts
  tests/browser/snapshots/examples/astro-cmsgov-web-components/astro-cmsgov-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-cmsgov-web-components/astro-cmsgov-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-cmsgov-web-components/astro-cmsgov-web-components--chromium.png
  tests/browser/snapshots/examples/astro-cmsgov-web-components/astro-cmsgov-web-components--firefox.png
  tests/browser/snapshots/examples/astro-cmsgov-web-components/astro-cmsgov-web-components--webkit.png
  tests/browser/snapshots/examples/astro-healthcare-web-components/astro-healthcare-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-healthcare-web-components/astro-healthcare-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-healthcare-web-components/astro-healthcare-web-components--chromium.png
  tests/browser/snapshots/examples/astro-healthcare-web-components/astro-healthcare-web-components--firefox.png
  tests/browser/snapshots/examples/astro-healthcare-web-components/astro-healthcare-web-components--webkit.png
  tests/browser/snapshots/examples/astro-medicare-web-components/astro-medicare-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-medicare-web-components/astro-medicare-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-medicare-web-components/astro-medicare-web-components--chromium.png
  tests/browser/snapshots/examples/astro-medicare-web-components/astro-medicare-web-components--firefox.png
  tests/browser/snapshots/examples/astro-medicare-web-components/astro-medicare-web-components--webkit.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--firefox.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--webkit.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--chromium.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--firefox.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--webkit.png
Labels: Impacts: Documentation, Type: Added

#3286 [WNMGDS-3007] Fix arrow behavior for disabled tabs
  packages/design-system/src/components/Tabs/Tabs.test.tsx
  packages/design-system/src/components/Tabs/Tabs.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tabs.test.tsx
Labels: Type: Fixed, Impacts: Core

#3293 [no-ticket] Updates snapshots
  tests/browser/snapshots/stories/components-drawermanager--drawer-manager-default-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-dropdown--disabled-core--firefox.png
  tests/browser/snapshots/stories/web-components-ds-tooltip--content-heading-as-attribute-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-tooltip--interactive-content-cmsgov--webkit.png
Labels: Type: Fixed, Impacts: Core

#3292 [WNMGDS-2932] Adds the optional hintClassName prop to the useHint interface.
  packages/design-system/src/components/DateField/MultiInputDateField.test.tsx
  packages/design-system/src/components/Hint/useHint.tsx
  packages/design-system/src/components/TextField/TextField.test.tsx
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.stories.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice-list.stories.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice.stories.tsx
  packages/design-system/src/components/web-components/ds-date-field/ds-date-field.stories.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.stories.tsx
  packages/design-system/src/components/web-components/ds-month-picker/ds-month-picker.stories.tsx
  packages/design-system/src/components/web-components/ds-text-field/ds-text-field.stories.tsx
  packages/design-system/src/components/web-components/ds-text-field/ds-text-field.test.tsx
  packages/design-system/src/components/web-components/shared-attributes/form.ts
  tests/browser/snapshots/storybook-docs/Docs-Components-Choice-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-ChoiceList-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Dropdown-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-MonthPicker-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-MultiInputDateField-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-SingleInputDateField-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-TextField-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-autocomplete-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-choice-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-choice-list-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-date-field-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-dropdown-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-month-picker-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-text-field-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Fixed, Impacts: Core

#3291 [WNMDGS-2972] Swap bold headers with semibold headers on CMSgov theme
  packages/design-system-tokens/src/css/__snapshots__/css-snapshots.test.ts.snap
  packages/design-system-tokens/src/tokens/Theme.cmsgov.json
  packages/design-system-tokens/src/tokens/Theme.core.json
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  tests/browser/snapshots/stories/utilities-text-align--text-align-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-tooltip--interactive-content-core--firefox.png
Labels: Impacts: CMSgov, Type: Changed

#3299 [WNMGDS-2613] Updates drawer guidance
  packages/docs/content/components/drawer.mdx
Labels: Impacts: Core, Type: Changed

#3300 [no-ticket] Updates snapshots for nightly tests
  tests/browser/snapshots/stories/utilities-text-align--text-align-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-tooltip--interactive-content-core--firefox.png
Labels: Type: Fixed, Impacts: Core

#3303 [WNMGDS-3025] Add markdown rendering to web component Storybook docs
  .storybook/docs/WebComponentArgsTable.tsx
  .storybook/docs/WebComponentAttrs.tsx
  .storybook/docs/WebComponentEventsTable.tsx
  packages/design-system/src/components/web-components/ds-accordion/ds-accordion-item.stories.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice.stories.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.stories.tsx
  packages/design-system/src/components/web-components/ds-pagination/ds-pagination.stories.tsx
  packages/design-system/src/components/web-components/shared-attributes/storybook.tsx
Labels: Type: Fixed, Impacts: Documentation
