Repository CMSgov/design-system, pull requests merged in 2024-08, with the labels that each got.

#3184 [NO-TICKET] Bump `gh-pages` from `3.2.3` to `6.1.1`
  package.json
  yarn.lock
Labels: Type: Internal, dependencies

#3186 [NO-TICKET] Fix broken links in `COMPONENT_MATURITY.md`
  COMPONENT_MATURITY.md
Labels: Type: Fixed, Impacts: Documentation

#3189 [WNMGDS-2835] Adds figma links to docs site
  packages/docs/content/components/accordion.mdx
  packages/docs/content/components/alert.mdx
  packages/docs/content/components/autocomplete.mdx
  packages/docs/content/components/badge.mdx
  packages/docs/content/components/button.mdx
  packages/docs/content/components/card.mdx
  packages/docs/content/components/checkbox.mdx
  packages/docs/content/components/date-field/date-picker.mdx
  packages/docs/content/components/date-field/multi-input-date-field.mdx
  packages/docs/content/components/date-field/single-input-date-field.mdx
  packages/docs/content/components/drawer.mdx
  packages/docs/content/components/dropdown.mdx
  packages/docs/content/components/filter-chip.mdx
  packages/docs/content/components/footer/healthcare-footer.mdx
  packages/docs/content/components/footer/medicare-footer.mdx
  packages/docs/content/components/header/healthcare-header.mdx
  packages/docs/content/components/header/medicare-header.mdx
  packages/docs/content/components/icon.mdx
  packages/docs/content/components/logos/healthcare-logo.mdx
  packages/docs/content/components/logos/hhs-logo.mdx
  packages/docs/content/components/logos/medicare-logo.mdx
  packages/docs/content/components/modal-dialog.mdx
  packages/docs/content/components/month-picker.mdx
  packages/docs/content/components/pagination.mdx
  packages/docs/content/components/radio.mdx
  packages/docs/content/components/review.mdx
  packages/docs/content/components/skip-nav.mdx
  packages/docs/content/components/spinner.mdx
  packages/docs/content/components/stars.mdx
  packages/docs/content/components/step-list.mdx
  packages/docs/content/components/table.mdx
  packages/docs/content/components/tabs.mdx
  packages/docs/content/components/text-field/text-field.mdx
  packages/docs/content/components/tooltip.mdx
  packages/docs/content/components/usa-banner.mdx
  packages/docs/content/components/vertical-navigation.mdx
  packages/docs/content/foundation/layout-grid/layout-grid.mdx
  packages/docs/content/foundation/spacing.mdx
  packages/docs/content/foundation/typography/body.mdx
  packages/docs/content/foundation/typography/headings.mdx
  packages/docs/content/foundation/typography/links.mdx
  packages/docs/content/foundation/typography/lists.mdx
  packages/docs/content/layouts/Healthcare/one-col-page-layout.mdx
  packages/docs/content/layouts/documentation-page.mdx
  packages/docs/content/patterns/Forms/error-validation.mdx
  packages/docs/content/utilities/text/measure.mdx
  packages/docs/src/components/layout/PageHeader.tsx
  packages/docs/src/components/page-templates/InfoPage.tsx
  packages/docs/src/helpers/graphQLTypes.ts
  packages/docs/src/helpers/urlUtils.ts
  packages/docs/static/images/figma-icon.png
  packages/docs/static/images/sketch-icon.png
Labels: Impacts: Documentation, Type: Changed

#2522 [NO-TICKET] Use the external link component in doc site
  packages/docs/src/components/content/ContentRenderer.tsx
Labels: Impacts: Documentation, Type: Changed

#3185 [WNMGDS-2855] Markdown and MDX broken link script
  .eslintignore
  .gitignore
  .prettierignore
  package.json
  scripts/check-markdown-links.ts
Labels: Type: Internal, Impacts: Documentation

#3196 [WNMGDS-2861] Adds PrintIcon component
  packages/design-system/src/components/Icons/PrintIcon.tsx
  packages/design-system/src/components/Icons/icons.stories.tsx
  packages/design-system/src/components/Icons/index.ts
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
Labels: Impacts: Core, Type: Added

#3203 [WNMGDS-2878] Render Doc Site stories for Modal Dialog and Drawer
  packages/docs/content/components/drawer.mdx
  packages/docs/content/components/modal-dialog.mdx
  packages/docs/src/components/content/StorybookExample.tsx
Labels: Type: Fixed, Impacts: Documentation

#3202 [WNMGDS-2861] Adds Email, Link, RSS & What's New Icon components
  packages/design-system/src/components/Icons/EmailIcon.tsx
  packages/design-system/src/components/Icons/LinkIcon.tsx
  packages/design-system/src/components/Icons/RssIcon.tsx
  packages/design-system/src/components/Icons/WhatsNewIcon.tsx
  packages/design-system/src/components/Icons/icons.stories.tsx
  packages/design-system/src/components/Icons/index.ts
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
Labels: Impacts: Core, Type: Added

#3205 [WNMGDS-2875] Fix Release script take 2
  scripts/bump-child-deps-utils.ts
  scripts/release.ts
  scripts/versions.ts
Labels: Type: Fixed, Impacts: Core

#3208 [WNMGDS-2884] Add `cmsds-migrate` script for v11 CSS changes
  packages/design-system/scripts/cmsds-migrate/configs/deprecated-css-v11.mjs
  packages/docs/content/blog/release-11.0.mdx
  packages/docs/src/styles/components/syntaxHighlighting.scss
Labels: Impacts: Core, Type: Added

#3210 [WNMGDS-2890] Fix `onAnalyticsEvent` attribute rendering to DOM through `HelpDrawer`
  packages/design-system/src/components/HelpDrawer/HelpDrawer.test.tsx
  packages/design-system/src/components/HelpDrawer/HelpDrawer.tsx
Labels: Type: Fixed, Impacts: Core

#3211 [NO-TICKET] Define a better return type for `defaultMenuLinks`
  packages/ds-healthcare-gov/src/components/Header/Header.tsx
  packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.ts
Labels: Type: Fixed, Impacts: Healthcare
