Repository CMSgov/design-system, pull requests merged in 2024-01, with the labels that each got.

#2862 [WNMGDS-2604] Fix content with stacking contexts bleeding through Healthcare header menu
  packages/design-system/src/components/NativeDialog/NativeDialog.tsx
  packages/ds-healthcare-gov/src/components/Header/ActionMenu.tsx
  packages/ds-healthcare-gov/src/components/Header/Header.tsx
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/Header.test.tsx.snap
  packages/ds-healthcare-gov/src/styles/components/_Header.scss
Labels: Type: Fixed, Impacts: Healthcare

#2867 [WNMGDS-2595] Fix 404s on docs site
  packages/docs/content/foundation/typography/content.mdx
  packages/docs/content/foundation/typography/lists.mdx
  packages/docs/content/layouts/Healthcare/one-col-page-layout.mdx
  packages/docs/content/utilities/flexbox.mdx
  packages/docs/gatsby-node.js
  packages/docs/redirects.json
Labels: Type: Fixed, Impacts: Documentation

#2859 [WNMGDS-2623] Add a label migration guide
  packages/docs/content/migration-guides/v9-label-updates.mdx
Labels: Impacts: Documentation, Type: Added

#2864 [NO-TICKET] Refactor Healthcare header
  packages/ds-healthcare-gov/src/components/Header/Header.tsx
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/localeLink.test.js.snap
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/loginLink.test.js.snap
  packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.ts
  packages/ds-healthcare-gov/src/components/Header/localeLink.test.js
  packages/ds-healthcare-gov/src/components/Header/localeLink.ts
  packages/ds-healthcare-gov/src/components/Header/loginLink.test.js
  packages/ds-healthcare-gov/src/components/Header/loginLink.ts
Labels: Type: Internal, Impacts: Core

#2866 [WNMGDS-2625] Remove `core-js` polyfills for IE
  packages/design-system/package.json
  packages/design-system/src/components/MonthPicker/MonthPicker.tsx
  packages/design-system/src/components/Tooltip/Tooltip.tsx
  yarn.lock
Labels: Impacts: Core, Type: Changed

#2863 [WNMGDS-2621] Enforce mutual exclusivity of the `mask` and `labelMask` props
  packages/design-system/src/components/TextField/TextField.stories.tsx
  packages/design-system/src/components/TextField/TextField.tsx
Labels: Type: Fixed, Impacts: Core

#2869 [WNMGDS-2628] Fix flash of unstyled TextField story
  packages/design-system/src/components/TextField/TextField.stories.tsx
Labels: Type: Fixed, Impacts: Documentation

#2857 [WNMGDS-2624] Use `p` tags for hints and errors
  packages/design-system/src/components/ChoiceList/__snapshots__/Choice.test.tsx.snap
  packages/design-system/src/components/ChoiceList/__snapshots__/ChoiceList.test.tsx.snap
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/design-system/src/components/Hint/Hint.tsx
  packages/design-system/src/components/InlineError/InlineError.tsx
  packages/design-system/src/components/InlineError/__snapshots__/InlineError.test.tsx.snap
  packages/design-system/src/components/Label/__snapshots__/Label.test.tsx.snap
  packages/design-system/src/components/MonthPicker/__snapshots__/MonthPicker.test.tsx.snap
  packages/design-system/src/styles/components/_Hint.scss
  packages/design-system/src/styles/components/_InlineError.scss
Labels: Impacts: Core, Type: Changed

#2873 [WNMGDS-2543] Add LTS policy
  packages/docs/content/guidelines/support-policies.mdx
  packages/docs/redirects.json
Labels: Type: Internal, Impacts: Documentation

#2870 [WNMGDS-2629] Fix bug in NativeDialog where ESC doesn't call exit handler
  packages/design-system/src/components/Dialog/Dialog.stories.tsx
  packages/design-system/src/components/NativeDialog/NativeDialog.tsx
Labels: Type: Fixed, Impacts: Core

#2876 [WNMGDS-2614] Remove Firefox focus styles added in #510
  packages/design-system/src/styles/components/_Dropdown.scss
Labels: Type: Fixed, Impacts: Core

#2868 [NO-TICKET] Update the `create-react-app-typescript` example project
  examples/create-react-app-typescript/package.json
  examples/create-react-app-typescript/src/components/App.tsx
  examples/create-react-app-typescript/src/components/Examples/MultiInputDateFieldExample.tsx
  examples/create-react-app-typescript/src/components/Examples/SingleInputDateFieldExample.tsx
Labels: Type: Internal, Impacts: Documentation

#2874 [NO-TICKET] Fix a dead link in the Spinner guidance
  packages/docs/content/components/spinner.mdx
Labels: Type: Fixed, Impacts: Documentation

#2880 [WNMGDS-2633] Add the missing `ds-u-color--gray-dark` util that we said existed
  packages/design-system/src/styles/utilities/_text-color.scss
Labels: Type: Fixed, Impacts: Core

#2882 [WNMGDS-2634] Update the visited link color for the cmsgov theme
  packages/design-system-tokens/src/themes/cmsgov.ts
Labels: Impacts: CMSgov, Type: Changed

#2887 [WNMGDS-2159] Open up some theme-colors page content to all themes
  packages/docs/content/foundation/theme-colors.mdx
Labels: Impacts: Documentation, Type: Changed

#2889 [WNMGDS-2439] Replace many config functions with single global `config` function
  .storybook/preview.tsx
  packages/design-system/src/components/Alert/Alert.test.tsx
  packages/design-system/src/components/Alert/useAlertAnalytics.ts
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/Button/Button.test.tsx
  packages/design-system/src/components/Button/useButtonAnalytics.ts
  packages/design-system/src/components/Dialog/Dialog.test.jsx
  packages/design-system/src/components/Dialog/useDialogAnalytics.ts
  packages/design-system/src/components/HelpDrawer/HelpDrawer.test.tsx
  packages/design-system/src/components/HelpDrawer/useHelpDrawerAnalytics.ts
  packages/design-system/src/components/InlineError/useInlineError.tsx
  packages/design-system/src/components/analytics/events.test.ts
  packages/design-system/src/components/analytics/events.ts
  packages/design-system/src/components/analytics/types.ts
  packages/design-system/src/components/config.ts
  packages/design-system/src/components/flags.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/web-components/ds-alert.test.tsx
  packages/design-system/src/components/web-components/ds-button.test.tsx
  packages/design-system/src/components/web-components/index.ts
  packages/docs/content/components/analytics.mdx
  packages/docs/content/components/config.mdx
  packages/docs/content/components/header/healthcare-header.mdx
  packages/docs/content/getting-started/for-developers.mdx
  packages/ds-healthcare-gov/src/components/Header/analytics.test.js
  packages/ds-healthcare-gov/src/components/Header/analytics.ts
  packages/ds-healthcare-gov/src/components/config.ts
  packages/ds-healthcare-gov/src/components/flags.ts
  packages/ds-healthcare-gov/src/components/index.ts
  packages/ds-healthcare-gov/src/components/web-components/index.ts
  tests/browser/snapshots/storybook-docs/Docs-Components-Button-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Dialog-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-components-Alert-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#2890 [WNMGDS-2555] Add `isOpen` to `Drawer` and `Dialog` to fix focus-management issue
  packages/design-system/src/components/Dialog/Dialog.stories.tsx
  packages/design-system/src/components/Dialog/Dialog.test.tsx
  packages/design-system/src/components/Dialog/Dialog.tsx
  packages/design-system/src/components/Dialog/__snapshots__/Dialog.test.tsx.snap
  packages/design-system/src/components/Dialog/useBodyScrollPrevention.ts
  packages/design-system/src/components/Drawer/Drawer.stories.tsx
  packages/design-system/src/components/Drawer/Drawer.test.tsx
  packages/design-system/src/components/Drawer/Drawer.tsx
  packages/design-system/src/components/Drawer/DrawerManager.stories.tsx
  packages/design-system/src/components/Drawer/DrawerManager.test.tsx
  packages/design-system/src/components/HelpDrawer/HelpDrawer.test.tsx
  packages/design-system/src/components/IdleTimeout/IdleTimeout.test.tsx
  packages/design-system/src/components/IdleTimeout/IdleTimeout.tsx
  packages/design-system/src/components/IdleTimeout/IdleTimeoutDialog.test.tsx
  packages/design-system/src/components/IdleTimeout/IdleTimeoutDialog.tsx
  packages/design-system/src/components/NativeDialog/NativeDialog.test.tsx
  packages/design-system/src/components/NativeDialog/NativeDialog.tsx
  packages/design-system/src/components/NativeDialog/__snapshots__/NativeDialog.test.tsx.snap
  packages/design-system/src/components/PrivacySettingsDialog/PrivacySettingsDialog.test.jsx
  packages/design-system/src/components/PrivacySettingsDialog/PrivacySettingsDialog.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.test.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/__snapshots__/ThirdPartyExternalLink.test.tsx.snap
  packages/docs/src/components/layout/FilterDialog/FilterDialog.test.tsx
  packages/docs/src/components/layout/FilterDialog/FilterDialog.tsx
  packages/docs/src/components/layout/SideNav/ThemeDialog.tsx
  packages/docs/src/components/layout/SideNav/ThemeVersionSection.tsx
  packages/docs/src/components/layout/SideNav/VersionDialog.tsx
  packages/ds-healthcare-gov/src/components/Footer/PrivacySettingsLink.tsx
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/InlineLinkLists.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/PrivacySettingsLink.test.tsx.snap
  tests/browser/snapshots/storybook-docs/Docs-Components-Dialog-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-DrawerManager-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-PrivacySettingsDialog-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Breaking, Impacts: Core

#2892 [NO-TICKET] Remove console.log, create eslint check for it
  .eslintrc.js
  packages/design-system-tokens/src/index.ts
  packages/design-system-tokens/src/lib/file.ts
  packages/design-system/src/components/MonthPicker/MonthPicker.tsx
Labels: Type: Fixed, Impacts: Core

#2894 [NO-TICKET] Uncheck that IdleTimeout has Spanish translations
  packages/docs/content/components/idle-timeout.mdx
Labels: Type: Fixed, Impacts: Documentation

#2896 [WNMGDS-2638] Publish the drawer manager feature
  packages/design-system/src/components/Drawer/DrawerManager.stories.tsx
  packages/design-system/src/components/Drawer/DrawerManager.test.tsx
  packages/design-system/src/components/Drawer/DrawerManager.tsx
  packages/design-system/src/components/Drawer/index.ts
  packages/docs/content/components/drawer.mdx
Labels: Impacts: Core, Type: Added

#2898 [WNMGDS-2639] Add new `useDialog` hook
  packages/design-system/src/components/Dialog/Dialog.stories.tsx
  packages/design-system/src/components/Dialog/useDialog.test.tsx
  packages/design-system/src/components/Dialog/useDialog.ts
  tests/browser/stories.test.ts
Labels: Impacts: Core, Type: Added

#2900 [NO-TICKET] Expand some `string` prop types in IdleTimeout to `ReactNode`
  packages/design-system/src/components/IdleTimeout/IdleTimeout.stories.tsx
  packages/design-system/src/components/IdleTimeout/IdleTimeout.tsx
  packages/design-system/src/components/IdleTimeout/IdleTimeoutDialog.tsx
  tests/browser/snapshots/storybook-docs/Docs-Components-IdleTimeout-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Changed

#2901 [NO-TICKET] Use only a single version of Storybook "doc blocks"
  packages/design-system/src/components/Drawer/Drawer.stories.tsx
  packages/design-system/src/components/PrivacySettingsDialog/PrivacySettingsDialog.stories.tsx
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.stories.tsx
  tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-PrivacySettingsDialog-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Medicare-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Fixed, Impacts: Documentation

#2904 [NO-TICKET] Fix error placement types
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/InlineError/useInlineError.tsx
  packages/design-system/src/components/config.ts
  packages/docs/content/components/config.mdx
Labels: Type: Internal, Impacts: Core

#2899 [WNMGDS-2632] Release 9.0 blog post
  packages/docs/content/blog/release-9.0.mdx
  packages/docs/content/migration-guides/v9-label-updates.mdx
  packages/docs/src/images/dialog-x-close.png
Labels: Impacts: Documentation, Type: Added

#2908 [WNMGDS-2658] Fix crash of privacy settings dialog in node environments
  packages/design-system/src/components/PrivacySettingsDialog/privacySettings.test.ts
  packages/design-system/src/components/PrivacySettingsDialog/privacySettings.ts
Labels: Type: Fixed, Impacts: Core
