Repository CMSgov/design-system, pull requests merged in 2024-11, with the labels that each got.

#3304 [WMNGDS-3022] Removes `ds-tab-panel` module
  packages/design-system/src/components/web-components/ds-tabs/ds-tab-panel.stories.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tab-panel.test.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tab-panel.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tab-panel.types.d.ts
  packages/design-system/src/components/web-components/ds-tabs/ds-tabs.stories.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tabs.test.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tabs.tsx
  packages/design-system/src/components/web-components/ds-tabs/index.tsx
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-tabs-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Fixed, Impacts: Core

#3296 [WNMGDS-3026] Add analytics support to web components
  .storybook/docs/WebComponentArgsTable.tsx
  .storybook/docs/WebComponentAttrs.tsx
  .storybook/docs/WebComponentEventsTable.tsx
  packages/design-system/src/components/web-components/analytics.ts
  packages/design-system/src/components/web-components/analyticsTesting.ts
  packages/design-system/src/components/web-components/ds-accordion/ds-accordion-item.stories.tsx
  packages/design-system/src/components/web-components/ds-alert/__snapshots__/ds-alert.test.tsx.snap
  packages/design-system/src/components/web-components/ds-alert/ds-alert.stories.tsx
  packages/design-system/src/components/web-components/ds-alert/ds-alert.test.tsx
  packages/design-system/src/components/web-components/ds-alert/ds-alert.tsx
  packages/design-system/src/components/web-components/ds-button/__snapshots__/ds-button.test.tsx.snap
  packages/design-system/src/components/web-components/ds-button/ds-button.stories.tsx
  packages/design-system/src/components/web-components/ds-button/ds-button.test.tsx
  packages/design-system/src/components/web-components/ds-button/ds-button.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice.stories.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.stories.tsx
  packages/design-system/src/components/web-components/ds-pagination/ds-pagination.stories.tsx
  packages/design-system/src/components/web-components/preactement/model.ts
  packages/design-system/src/components/web-components/preactement/shared/model.ts
  packages/design-system/src/components/web-components/shared-attributes/analytics.ts
  packages/design-system/src/components/web-components/shared-attributes/storybook.tsx
  packages/docs/content/components/analytics.mdx
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-accordion-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-accordion-item-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-alert-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-autocomplete-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-button-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-choice-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-choice-list-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-date-field-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-dropdown-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-hint-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-month-picker-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-pagination-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-review-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-step-list-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-tab-panel-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-tabs-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-text-field-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-tooltip-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3307 [WNMGDS-3037] Adds web component section to Accordion doc site page
  packages/docs/content/components/accordion.mdx
Labels: Impacts: Documentation, Type: Added

#3308 [WNMGDS-3027] Add Web Component Sections to doc site pages.
  packages/docs/content/components/autocomplete.mdx
  packages/docs/content/components/checkbox.mdx
  packages/docs/content/components/date-field/single-input-date-field.mdx
  packages/docs/content/components/drawer.mdx
  packages/docs/content/components/filter-chip.mdx
  packages/docs/content/components/radio.mdx
  packages/docs/content/components/step-list.mdx
  packages/docs/content/components/table.mdx
  packages/docs/content/components/tabs.mdx
  packages/docs/content/components/tooltip.mdx
  packages/docs/content/components/vertical-navigation.mdx
  packages/docs/src/components/content/ContentRenderer.tsx
  packages/docs/src/components/content/ReactDocsLinks.tsx
  packages/docs/src/components/content/StorybookDocLink.tsx
  packages/docs/src/components/content/StorybookDocLinks.tsx
Labels: Impacts: Documentation, Type: Added

#3312 [WNMGDS-2984] Update Pagination Styling for Medicare
  packages/design-system-tokens/src/css/__snapshots__/css-snapshots.test.ts.snap
  packages/design-system-tokens/src/tokens/Theme.cmsgov.json
  packages/design-system-tokens/src/tokens/Theme.core.json
  packages/design-system-tokens/src/tokens/Theme.healthcare.json
  packages/design-system-tokens/src/tokens/Theme.medicare.json
  packages/design-system/src/styles/components/_Pagination.scss
  tests/browser/snapshots/stories/components-pagination--compact-navigation-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-pagination--compact-navigation-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-pagination--compact-navigation-medicare--chromium.png
  tests/browser/snapshots/stories/components-pagination--compact-navigation-medicare--firefox.png
  tests/browser/snapshots/stories/components-pagination--compact-navigation-medicare--webkit.png
  tests/browser/snapshots/stories/components-pagination--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-pagination--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-pagination--default-medicare--chromium.png
  tests/browser/snapshots/stories/components-pagination--default-medicare--firefox.png
  tests/browser/snapshots/stories/components-pagination--default-medicare--webkit.png
  tests/browser/snapshots/stories/components-pagination--hidden-navigation-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-pagination--hidden-navigation-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-pagination--hidden-navigation-medicare--chromium.png
  tests/browser/snapshots/stories/components-pagination--hidden-navigation-medicare--firefox.png
  tests/browser/snapshots/stories/components-pagination--hidden-navigation-medicare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-pagination--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-pagination--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-pagination--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-pagination--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-pagination--default-medicare--webkit.png
Labels: Impacts: Medicare, Type: Changed

#3316 [WNMGDS-2930] Update mgov guidance on button.mdx
  packages/docs/content/components/button.mdx
Labels: Impacts: Documentation, Impacts: Medicare, Type: Changed

#3275 [WNMGDS-3009][WNMGDS-3010] Add Angular example project and fix Angular web component content issue
  .nvmrc
  examples/angular/.gitignore
  examples/angular/README.md
  examples/angular/angular.json
  examples/angular/package.json
  examples/angular/src/global_styles.css
  examples/angular/src/index.html
  examples/angular/src/main.html
  examples/angular/src/main.ts
  examples/angular/tsconfig.app.json
  examples/angular/tsconfig.json
  packages/design-system/src/components/web-components/preactement/__snapshots__/define.test.tsx.snap
  packages/design-system/src/components/web-components/preactement/define.test.tsx
  packages/design-system/src/components/web-components/preactement/define.ts
  packages/design-system/src/components/web-components/preactement/shared/model.ts
  yarn.lock
Labels: Type: Fixed, Impacts: Core

#3315 [WNMGDS-2750] Remove `aria-disabled` from `TabPanel` components
  packages/design-system/src/components/Tabs/TabPanel.test.tsx
  packages/design-system/src/components/Tabs/TabPanel.tsx
Labels: Type: Fixed, Impacts: Core

#3321 [WNMGDS-2916] Release v12 Blogpost
  packages/docs/content/blog/release-12.0.mdx
Labels: Impacts: Documentation, Type: Added

#3325 [WNMGDS-2941] Remove clickable card guidance from button component (mgov)
  packages/docs/content/components/button.mdx
Labels: Impacts: Documentation, Type: Changed

#3328 [no-ticket] Updates snapshots
  tests/browser/snapshots/stories/components-usabanner--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-usabanner--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-usabanner--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/components-usabanner--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/components-usabanner--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-usabanner--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-usabanner--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-usabanner--default-medicare--chromium.png
  tests/browser/snapshots/stories/components-usabanner--default-medicare--firefox.png
  tests/browser/snapshots/stories/components-usabanner--default-medicare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-usa-banner--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-usa-banner--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-usa-banner--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-ds-usa-banner--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-ds-usa-banner--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-usa-banner--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-usa-banner--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-usa-banner--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-usa-banner--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-usa-banner--default-medicare--webkit.png
Labels: Type: Fixed, Impacts: Core

#3329 [NO-TICKET] Updates PR Template to reflect new script that updates all browser tests
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
Labels: Impacts: Core, Type: Added

#3330 [NO-TICKET] Prevent double firing of exit event in Modal Dialog
  packages/design-system/src/components/NativeDialog/NativeDialog.tsx
Labels: Type: Fixed, Impacts: Core
