Repository CMSgov/design-system, pull requests merged in 2024-09, with the labels that each got.

#3213 [NO-TICKET] Revises release v11 blog post
  packages/docs/content/blog/release-11.0.mdx
Labels: Type: Fixed, Impacts: Documentation

#3217 [NO-TICKET] Exclude core design system from dependency update
  scripts/bump-child-deps-utils.ts
Labels: Type: Internal, Impacts: Core

#3216 [WNMGDS-2713] Add default value overrides to Storybook
  packages/design-system/src/components/Autocomplete/Autocomplete.stories.tsx
  packages/design-system/src/components/DateField/MultiInputDateField.stories.tsx
  packages/design-system/src/components/Dialog/Dialog.stories.tsx
  packages/design-system/src/components/Drawer/Drawer.stories.tsx
  packages/design-system/src/components/FilterChip/FilterChip.stories.tsx
  packages/design-system/src/components/Pagination/Pagination.stories.tsx
  packages/design-system/src/components/Review/Review.stories.tsx
  packages/design-system/src/components/SkipNav/SkipNav.stories.tsx
  tests/browser/snapshots/storybook-docs/Docs-Components-Autocomplete-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Dialog-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-FilterChip-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-MultiInputDateField-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Pagination-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Review-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-SkipNav-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Internal, Impacts: Core

#3199 [WNMGDS-2838] Update all themes to make inline tool tips black
  packages/design-system-tokens/src/css/__snapshots__/css-snapshots.test.ts.snap
  packages/design-system-tokens/src/tokens/Theme.cmsgov.json
  packages/design-system-tokens/src/tokens/Theme.core.json
  packages/design-system-tokens/src/tokens/Theme.healthcare.json
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/ds-medicare-gov/src/styles/components/_Tooltip.scss
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-cmsgov--chromium.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-cmsgov--firefox.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-core--chromium.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-core--firefox.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-core--webkit.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-healthcare--chromium.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-healthcare--firefox.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-healthcare--webkit.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-medicare--chromium.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-medicare--firefox.png
  tests/browser/snapshots/stories/components-tooltip--inline-trigger-medicare--webkit.png
Labels: Impacts: Core, Type: Changed

#3198 [WNMGDS-2864] Add utility actions pattern guidance page
  packages/docs/content/patterns/utility-actions.mdx
Labels: Impacts: Documentation, Type: Added

#3215 [WNMGDS-2872] Adds `ds-step-list` web component.
  packages/design-system/src/components/StepList/StepList.stories.tsx
  packages/design-system/src/components/web-components/ds-step-list/ds-step-list.stories.tsx
  packages/design-system/src/components/web-components/ds-step-list/ds-step-list.test.tsx
  packages/design-system/src/components/web-components/ds-step-list/ds-step-list.tsx
  packages/design-system/src/components/web-components/ds-step-list/index.ts
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-cmsgov--chromium.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-cmsgov--firefox.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-core--chromium.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-core--firefox.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-core--webkit.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-healthcare--chromium.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-healthcare--firefox.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-healthcare--webkit.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-medicare--chromium.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-medicare--firefox.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-medicare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-core--chromium.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-core--firefox.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-core--webkit.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-step-list--step-list-example-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-step-list-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3230 [WNMGDS-2935] Make Sass token file changes backwards compatible
  packages/design-system-tokens/src/css/translate.test.ts
  packages/design-system-tokens/src/css/translate.ts
Labels: Type: Fixed, Impacts: Core

#3232 [WNMGDS-2950] Reorder Sass token files to avoid Sass compiler errors
  packages/design-system-tokens/src/css/translate.test.ts
  packages/design-system-tokens/src/css/translate.ts
Labels: Type: Fixed, Impacts: Core

#3233 [WNMGDS-2912] Updates versions script and adds latest patch and release versions
  scripts/versions.ts
  versions.json
Labels: Type: Internal, Impacts: Core

#3243 [WNMGDS 2915] Remove doc site email icon
  packages/docs/content/not-in-sidebar/contact.mdx
  packages/docs/src/components/icons/EmailIcon.tsx
Labels: Impacts: Documentation, Type: Changed

#3234 [WNMGDS-2892] Adds `ds-tabs` web component.
  packages/design-system/src/components/web-components/ds-tabs/ds-tab-panel.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tabs.stories.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tabs.test.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tabs.tsx
  packages/design-system/src/components/web-components/ds-tabs/index.tsx
  packages/design-system/src/components/web-components/index.ts
  tests/browser/expectNoAxeViolations.ts
  tests/browser/snapshots/stories/web-components-ds-tabs--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-core--chromium.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-core--firefox.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-core--webkit.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-tabs--default-medicare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-core--chromium.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-core--firefox.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-core--webkit.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-tabs--disabled-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-tabs-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/stories.test.ts
Labels: Impacts: Core, Type: Added

#3246 [WNMDGS-2975] Change focus color from orchid to copper on CMSgov theme
  packages/design-system-tokens/src/css/__snapshots__/css-snapshots.test.ts.snap
  packages/design-system-tokens/src/tokens/System.Value.json
  packages/design-system-tokens/src/tokens/Theme.cmsgov.json
  packages/docs/static/themes/cmsgov-theme.css
  tests/browser/snapshots/stories-interaction/autocomplete--type--cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/autocomplete--type--cmsgov--chromium.png
  tests/browser/snapshots/stories-interaction/autocomplete--type--cmsgov--firefox.png
  tests/browser/snapshots/stories-interaction/autocomplete--type--cmsgov--webkit.png
  tests/browser/snapshots/stories-interaction/button--click--cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/button--click--cmsgov--chromium.png
  tests/browser/snapshots/stories-interaction/button--click--cmsgov--firefox.png
  tests/browser/snapshots/stories-interaction/button--click--cmsgov--webkit.png
  tests/browser/snapshots/stories-interaction/button--focus--cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/button--focus--cmsgov--chromium.png
  tests/browser/snapshots/stories-interaction/button--focus--cmsgov--firefox.png
  tests/browser/snapshots/stories-interaction/button--focus--cmsgov--webkit.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--cmsgov--chromium.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--cmsgov--firefox.png
  tests/browser/snapshots/stories-interaction/datefield--picker-interaction--cmsgov--webkit.png
  tests/browser/snapshots/stories-interaction/dropdown--open--cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/dropdown--open--cmsgov--chromium.png
  tests/browser/snapshots/stories-interaction/dropdown--open--cmsgov--firefox.png
  tests/browser/snapshots/stories-interaction/dropdown--open--cmsgov--webkit.png
  tests/browser/snapshots/stories-interaction/dropdown-optgroups--open--cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/dropdown-optgroups--open--cmsgov--chromium.png
  tests/browser/snapshots/stories-interaction/dropdown-optgroups--open--cmsgov--firefox.png
  tests/browser/snapshots/stories-interaction/dropdown-optgroups--open--cmsgov--webkit.png
  tests/browser/snapshots/stories-interaction/mask--text-entry--cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/mask--text-entry--cmsgov--chromium.png
  tests/browser/snapshots/stories-interaction/mask--text-entry--cmsgov--firefox.png
  tests/browser/snapshots/stories-interaction/mask--text-entry--cmsgov--webkit.png
  tests/browser/snapshots/stories-interaction/mask--text-entry-and-exit--cmsgov--webkit.png
  tests/browser/snapshots/stories-interaction/textbox--focus--cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/textbox--focus--cmsgov--chromium.png
  tests/browser/snapshots/stories-interaction/textbox--focus--cmsgov--firefox.png
  tests/browser/snapshots/stories-interaction/textbox--focus--cmsgov--webkit.png
Labels: Impacts: CMSgov, Type: Changed

#3253 [NO-TICKET] Maintain local state in web components when attributes change
  packages/design-system/package.json
  packages/design-system/src/components/web-components/ds-alert/__snapshots__/ds-alert.test.tsx.snap
  packages/design-system/src/components/web-components/ds-badge/__snapshots__/ds-badge.test.tsx.snap
  packages/design-system/src/components/web-components/ds-button/__snapshots__/ds-button.test.tsx.snap
  packages/design-system/src/components/web-components/ds-choice/__snapshots__/ds-choice.test.tsx.snap
  packages/design-system/src/components/web-components/ds-date-field/__snapshots__/ds-date-field.test.tsx.snap
  packages/design-system/src/components/web-components/ds-dropdown/__snapshots__/ds-dropdown.test.tsx.snap
  packages/design-system/src/components/web-components/ds-hint/__snapshots__/ds-hint.test.tsx.snap
  packages/design-system/src/components/web-components/ds-inline-error/__snapshots__/ds-inline-error.test.tsx.snap
  packages/design-system/src/components/web-components/ds-label/__snapshots__/ds-label.test.tsx.snap
  packages/design-system/src/components/web-components/ds-pagination/__snapshots__/ds-pagination.test.tsx.snap
  packages/design-system/src/components/web-components/ds-text-field/__snapshots__/ds-text-field.test.tsx.snap
  packages/design-system/src/components/web-components/preactement/define.test.tsx
  packages/design-system/src/components/web-components/preactement/define.ts
  packages/design-system/src/components/web-components/preactement/shared/model.ts
  yarn.lock
Labels: Type: Fixed, Impacts: Core
