Repository CMSgov/design-system, pull requests merged in 2024-03, with the labels that each got.

#2958 [WNMGDS- 2685] Privacy settings to no longer throw error when no cookie exists
  packages/design-system/src/components/PrivacySettingsDialog/privacySettings.ts
Labels: Type: Fixed, Impacts: Core

#2962 [WNMGDS-2675] Show accurate colors in theme-colors page
  packages/docs/src/components/content/ColorExampleList.tsx
  packages/docs/src/helpers/clientOnly.ts
Labels: Type: Fixed, Impacts: Documentation

#2961 [WNMGDS-2674] Add VRTs for remaining example
  examples/astro/package.json
  examples/astro/src/layouts/Layout.astro
  examples/astro/src/pages/index.astro
  examples/astro/src/pages/react.astro
  examples/preact-app/package.json
  examples/preact-react-app/package.json
  examples/react-app/package.json
  package.json
  tests/browser/examples.config.ts
  tests/browser/examples.test.ts
  tests/browser/snapshots/examples/astro-react/astro-react--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-react/astro-react--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-react/astro-react--chromium.png
  tests/browser/snapshots/examples/astro-react/astro-react--firefox.png
  tests/browser/snapshots/examples/astro-react/astro-react--webkit.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--firefox.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--webkit.png
  yarn.lock
Labels: Type: Internal, Impacts: Documentation

#2971 [WNMGDS-2686] remove aria-labelledby from accordion; not needed
  packages/design-system/src/components/Accordion/AccordionItem.test.tsx
  packages/design-system/src/components/Accordion/AccordionItem.tsx
  packages/design-system/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  packages/design-system/src/components/Accordion/__snapshots__/AccordionItem.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#2970 [WNMGDS-2696] remove live region attrs from Pagination
  packages/design-system/src/components/Pagination/Pagination.tsx
  packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#2957 [WNMGDS-2665] Configure browserslist
  package.json
  packages/docs/package.json
Labels: Impacts: Core, Type: Changed

#2951 [WNMGDS-2699] Remove title attr from vert nav label component, unhelpful attr.
  packages/design-system/src/components/Dropdown/DropdownMenuOption.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItem.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItemLabel.test.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItemLabel.tsx
  packages/design-system/src/components/VerticalNav/__snapshots__/VerticalNavItemLabel.test.tsx.snap
  packages/design-system/src/components/locale/en.json
  packages/design-system/src/components/locale/es.json
Labels: Type: Breaking, Impacts: Core

#2977 [WNMGDS-1859] Deprecate truncate utility class
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/design-system/src/styles/_set-for-deprecation.scss
  packages/design-system/src/styles/components/_Dropdown.scss
  packages/design-system/src/styles/utilities/_truncate.scss
  packages/docs/content/utilities/font/font-size.mdx
  packages/docs/content/utilities/text/text-truncation.mdx
Labels: Impacts: Core, Type: Changed

#2983 [WNMGDS-2704] Remove unused packages
  package.json
  packages/design-system-tokens/package.json
  packages/ds-healthcare-gov/package.json
  yarn.lock
Labels: Type: Internal, Impacts: Core

#2984 [NO-TICKET] Add a migration script for the old to new typography classes
  packages/design-system/scripts/cmsds-migrate/configs/deprecated-semantic-typography-classes.mjs
Labels: Impacts: Core, Type: Added

#2985 [NO-TICKET] Make new example package private
  examples/astro/package.json
  examples/preact-app/package.json
  examples/preact-react-app/package.json
  examples/react-app/package.json
Labels: Type: Internal, Impacts: Documentation

#2987 [NO-TICKET] Fix release script not bumping versions in private packages
  scripts/release.ts
Labels: Type: Internal, Impacts: Core

#2988 [NO-TICKET] Fix release tagging with private packages
  scripts/release.ts
Labels: Type: Internal, Impacts: Core

#2990 [WNMGDS-2705] Upgrade to TypeScript v5
  examples/astro/package.json
  package.json
  packages/design-system-tokens/package.json
  scripts/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: Impacts: Core, Type: Changed

#2992 [WNMGDS-2706] Update example VRT snapshots
  examples/cdn-web-components/index.html
  examples/preact-app/index.html
  examples/preact-app/src/scripts/index.js
  examples/preact-react-app/index.html
  examples/preact-react-app/src/scripts/index.js
  examples/react-app/index.html
  examples/react-app/src/scripts/index.js
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--firefox.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--webkit.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--chromium.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--firefox.png
  tests/browser/snapshots/examples/cdn-web-components/cdn-web-components--webkit.png
  tests/browser/snapshots/examples/react-app/react-app--Mobile-Chrome.png
  tests/browser/snapshots/examples/react-app/react-app--chromium-forced-colors.png
  tests/browser/snapshots/examples/react-app/react-app--chromium.png
  tests/browser/snapshots/examples/react-app/react-app--firefox.png
  tests/browser/snapshots/examples/react-app/react-app--webkit.png
Labels: Type: Fixed, Impacts: Documentation

#2995 [WNMGDS-2690] Drop unnecessary peer dependencies for docs package
  packages/docs/package.json
Labels: Type: Internal, Impacts: Documentation

#2997 [NO-TICKET] Fix headings on blog posts not getting any heading styles
  packages/docs/src/components/layout/Layout.tsx
  packages/docs/src/components/page-templates/BlogPage.tsx
Labels: Type: Fixed, Impacts: Documentation
