Repository CMSgov/design-system, pull requests merged in 2024-04, with the labels that each got.

#3006 [WNMGDS-2722] New browser testing wrapper script
  README.md
  package.json
  scripts/browser-tests.ts
  scripts/release.ts
  scripts/utils.ts
Labels: Type: Internal, Impacts: Core

#3007 [WNMGDS-2726] Update alert background colors to ensure sufficient color contrast
  packages/design-system-tokens/src/themes/cmsgov-component.ts
  packages/design-system-tokens/src/themes/cmsgov.ts
  packages/design-system-tokens/src/themes/core-component.ts
  packages/design-system-tokens/src/themes/core.ts
  packages/design-system-tokens/src/themes/healthcare-component.ts
  packages/design-system-tokens/src/themes/healthcare.ts
  packages/design-system-tokens/src/themes/medicare-component.ts
  packages/design-system-tokens/src/tokens/color.ts
  packages/design-system/src/components/Alert/Alert.stories.tsx
  packages/design-system/src/styles/components/_Alert.scss
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/docs/static/themes/medicare-theme.css
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--firefox.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--webkit.png
  tests/browser/snapshots/stories/components-alert--error-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-alert--error-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-alert--error-cmsgov--chromium.png
  tests/browser/snapshots/stories/components-alert--error-cmsgov--firefox.png
  tests/browser/snapshots/stories/components-alert--error-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-alert--error-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-alert--error-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-alert--error-core--chromium.png
  tests/browser/snapshots/stories/components-alert--error-core--firefox.png
  tests/browser/snapshots/stories/components-alert--error-core--webkit.png
  tests/browser/snapshots/stories/components-alert--error-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-alert--error-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-alert--error-healthcare--chromium.png
  tests/browser/snapshots/stories/components-alert--error-healthcare--firefox.png
  tests/browser/snapshots/stories/components-alert--error-healthcare--webkit.png
  tests/browser/snapshots/stories/components-alert--error-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-alert--error-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-alert--error-medicare--chromium.png
  tests/browser/snapshots/stories/components-alert--error-medicare--firefox.png
  tests/browser/snapshots/stories/components-alert--error-medicare--webkit.png
  tests/browser/snapshots/stories/components-alert--success-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-alert--success-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-alert--success-cmsgov--chromium.png
  tests/browser/snapshots/stories/components-alert--success-cmsgov--firefox.png
  tests/browser/snapshots/stories/components-alert--success-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-alert--success-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-alert--success-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-alert--success-core--chromium.png
  tests/browser/snapshots/stories/components-alert--success-core--firefox.png
  tests/browser/snapshots/stories/components-alert--success-core--webkit.png
  tests/browser/snapshots/stories/components-alert--success-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-alert--success-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-alert--success-healthcare--chromium.png
  tests/browser/snapshots/stories/components-alert--success-healthcare--firefox.png
  tests/browser/snapshots/stories/components-alert--success-healthcare--webkit.png
  tests/browser/snapshots/stories/components-alert--success-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-alert--success-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-alert--success-medicare--chromium.png
  tests/browser/snapshots/stories/components-alert--success-medicare--firefox.png
  tests/browser/snapshots/stories/components-alert--success-medicare--webkit.png
Labels: Type: Breaking, Impacts: Core

#3012 [NO-TICKET] Don't pass the browser tests when they fail!
  scripts/browser-tests.ts
  scripts/utils.ts
Labels: Type: Internal, Impacts: Core

#3010 [WNMGDS-2698] NPM cleanup
  .stylelintrc.js
  package.json
  packages/design-system-tokens/package.json
  packages/design-system/src/styles/_base.scss
  packages/design-system/src/styles/_mixins.scss
  packages/design-system/src/styles/_reset.scss
  packages/design-system/src/styles/_set-for-deprecation.scss
  packages/design-system/src/styles/components/_Accordion.scss
  packages/design-system/src/styles/components/_Alert.scss
  packages/design-system/src/styles/components/_Autocomplete.scss
  packages/design-system/src/styles/components/_Badge.scss
  packages/design-system/src/styles/components/_Button.scss
  packages/design-system/src/styles/components/_ChoiceList.scss
  packages/design-system/src/styles/components/_CloseButton.scss
  packages/design-system/src/styles/components/_Dialog.scss
  packages/design-system/src/styles/components/_Dropdown.scss
  packages/design-system/src/styles/components/_FilterChip.scss
  packages/design-system/src/styles/components/_Hint.scss
  packages/design-system/src/styles/components/_Label.scss
  packages/design-system/src/styles/components/_LabelMask.scss
  packages/design-system/src/styles/components/_Mask.scss
  packages/design-system/src/styles/components/_Pagination.scss
  packages/design-system/src/styles/components/_SingleInputDateField.scss
  packages/design-system/src/styles/components/_Spinner.scss
  packages/design-system/src/styles/components/_SvgIcon.scss
  packages/design-system/src/styles/components/_Tabs.scss
  packages/design-system/src/styles/components/_TextField.scss
  packages/design-system/src/styles/components/_Tooltip.scss
  packages/design-system/src/styles/components/_TooltipIcon.scss
  packages/design-system/src/styles/components/_UsaBanner.scss
  packages/design-system/src/styles/components/_VerticalNav.scss
  packages/design-system/src/styles/index.scss
  packages/docs/src/styles/components/colorRamps.scss
  packages/docs/src/styles/components/embeddedExamples.scss
  packages/docs/src/styles/components/filterDialog.scss
  packages/docs/src/styles/components/navigation.scss
  packages/docs/src/styles/components/responsiveExample.scss
  packages/docs/src/styles/components/spacingUtilityExampleList.scss
  packages/docs/src/styles/components/syntaxHighlighting.scss
  packages/docs/src/styles/index.scss
  packages/docs/src/styles/pages/contact.scss
  packages/docs/src/styles/pages/layout.scss
  packages/docs/src/styles/pages/search.scss
  packages/ds-healthcare-gov/src/styles/components/_Accordion.scss
  packages/ds-healthcare-gov/src/styles/components/_Footer.scss
  packages/ds-healthcare-gov/src/styles/components/_Header.scss
  packages/ds-medicare-gov/src/styles/_base.scss
  packages/ds-medicare-gov/src/styles/_fonts.scss
  packages/ds-medicare-gov/src/styles/components/_Card.scss
  packages/ds-medicare-gov/src/styles/components/_HelpDrawer.scss
  packages/ds-medicare-gov/src/styles/components/_SimpleFooter.scss
  packages/ds-medicare-gov/src/styles/components/_Tooltip.scss
  yarn.lock
Labels: Type: Internal, dependencies

#3018 [WNMGDS-2733] Add Release 10.0 blog post
  packages/docs/content/blog/release-10.0.mdx
Labels: Impacts: Documentation, Type: Added

#3021 [WNMGDS-2701] Remove truncate util class from repo
  packages/design-system/src/components/web-components/__snapshots__/ds-dropdown.test.tsx.snap
  packages/design-system/src/styles/_set-for-deprecation.scss
  packages/design-system/src/styles/index.scss
  packages/design-system/src/styles/utilities/_truncate.scss
Labels: Type: Breaking, Impacts: Core

#2996 [WNMGDS-2717] Reduce dialog polyfill to bare minimum
  packages/design-system/src/components/NativeDialog/NativeDialog.tsx
  packages/design-system/src/components/NativeDialog/polyfill/LICENSE
  packages/design-system/src/components/NativeDialog/polyfill/index.d.ts
  packages/design-system/src/components/NativeDialog/polyfill/index.js
  packages/design-system/src/components/NativeDialog/shim.ts
  packages/design-system/src/components/ThirdPartyExternalLink/__snapshots__/ThirdPartyExternalLink.test.tsx.snap
Labels: Impacts: Core, Type: Changed

#3019 [NO-TICKET] Organize web components into folders
  packages/design-system/package.json
  packages/design-system/src/components/web-components/__snapshots__/ds-button.test.tsx.snap
  packages/design-system/src/components/web-components/ds-alert/__snapshots__/ds-alert.test.tsx.snap
  packages/design-system/src/components/web-components/ds-alert/ds-alert.stories.tsx
  packages/design-system/src/components/web-components/ds-alert/ds-alert.test.tsx
  packages/design-system/src/components/web-components/ds-alert/ds-alert.tsx
  packages/design-system/src/components/web-components/ds-alert/index.ts
  packages/design-system/src/components/web-components/ds-badge/__snapshots__/ds-badge.test.tsx.snap
  packages/design-system/src/components/web-components/ds-badge/ds-badge.stories.tsx
  packages/design-system/src/components/web-components/ds-badge/ds-badge.test.tsx
  packages/design-system/src/components/web-components/ds-badge/ds-badge.ts
  packages/design-system/src/components/web-components/ds-badge/index.ts
  packages/design-system/src/components/web-components/ds-button/__snapshots__/ds-button.test.tsx.snap
  packages/design-system/src/components/web-components/ds-button/ds-button.stories.tsx
  packages/design-system/src/components/web-components/ds-button/ds-button.test.tsx
  packages/design-system/src/components/web-components/ds-button/ds-button.tsx
  packages/design-system/src/components/web-components/ds-button/index.ts
  packages/design-system/src/components/web-components/ds-dropdown/__snapshots__/ds-dropdown.test.tsx.snap
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.stories.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.test.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.tsx
  packages/design-system/src/components/web-components/ds-dropdown/index.ts
  packages/design-system/src/components/web-components/ds-usa-banner/__snapshots__/ds-usa-banner.test.tsx.snap
  packages/design-system/src/components/web-components/ds-usa-banner/ds-usa-banner.stories.tsx
  packages/design-system/src/components/web-components/ds-usa-banner/ds-usa-banner.test.tsx
  packages/design-system/src/components/web-components/ds-usa-banner/ds-usa-banner.tsx
  packages/design-system/src/components/web-components/ds-usa-banner/index.ts
  packages/ds-cms-gov/package.json
  packages/ds-medicare-gov/package.json
  tests/browser/snapshots/storybook-docs/Docs-Components-Choice-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-ChoiceList-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Pagination-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Review-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Tooltip-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Medicare-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-components-Alert-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-components-Badge-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Internal, Impacts: Core

#3023 [NO-TICKET] Fix changing themes in web component stories
  packages/design-system/src/components/web-components/ds-alert/ds-alert.stories.tsx
  packages/design-system/src/components/web-components/ds-badge/ds-badge.stories.tsx
  packages/design-system/src/components/web-components/ds-button/ds-button.stories.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.stories.tsx
  packages/design-system/src/components/web-components/ds-usa-banner/ds-usa-banner.stories.tsx
  packages/design-system/src/components/web-components/storybook.tsx
Labels: Impacts: Documentation, Type: Added

#3024 [WNMGDS-2729] Add `ds-inline-error` web component
  .storybook/docs/WebComponentArgsTable.tsx
  packages/design-system/src/components/InlineError/InlineError.tsx
  packages/design-system/src/components/web-components/ds-inline-error/__snapshots__/ds-inline-error.test.tsx.snap
  packages/design-system/src/components/web-components/ds-inline-error/ds-inline-error.stories.tsx
  packages/design-system/src/components/web-components/ds-inline-error/ds-inline-error.test.tsx
  packages/design-system/src/components/web-components/ds-inline-error/ds-inline-error.tsx
  packages/design-system/src/components/web-components/ds-inline-error/index.ts
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-InlineError-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3026 [WNMGDS-2728] Add `ds-hint` web component
  packages/design-system/src/components/web-components/ds-hint/__snapshots__/ds-hint.test.tsx.snap
  packages/design-system/src/components/web-components/ds-hint/ds-hint.stories.tsx
  packages/design-system/src/components/web-components/ds-hint/ds-hint.test.tsx
  packages/design-system/src/components/web-components/ds-hint/ds-hint.tsx
  packages/design-system/src/components/web-components/ds-hint/index.ts
  tests/browser/snapshots/stories/web-components-hint--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-hint--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-hint--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-hint--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-hint--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-hint--default-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-hint--default-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-hint--default-core--chromium.png
  tests/browser/snapshots/stories/web-components-hint--default-core--firefox.png
  tests/browser/snapshots/stories/web-components-hint--default-core--webkit.png
  tests/browser/snapshots/stories/web-components-hint--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-hint--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-hint--default-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-hint--default-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-hint--default-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-hint--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-hint--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-hint--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-hint--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-hint--default-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-Hint-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3027 [NO-TICKET] Don't require Choice props that are provided by the ChoiceList
  packages/design-system/src/components/ChoiceList/ChoiceList.tsx
  tests/browser/snapshots/storybook-docs/Docs-Components-ChoiceList-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Fixed, Impacts: Core

#2582 [LHDM-1818] Pass backdropClickExits to NativeDialog from Drawer
  packages/design-system/src/components/Drawer/Drawer.stories.tsx
  packages/design-system/src/components/Drawer/Drawer.tsx
  packages/design-system/src/components/HelpDrawer/HelpDrawer.stories.tsx
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.stories.tsx
Labels: Impacts: Core, Type: Added

#3029 [NO-TICKET] Fix doc-page pattern in Storybook
  packages/docs/content/layouts/documentation-page.stories.tsx
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-cmsgov--chromium.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-cmsgov--firefox.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-cmsgov--webkit.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-core--chromium.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-core--firefox.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-core--webkit.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-healthcare--chromium.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-healthcare--firefox.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-healthcare--webkit.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-medicare--chromium.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-medicare--firefox.png
  tests/browser/snapshots/stories/patterns-documentation-page--documentation-page-medicare--webkit.png
  tests/browser/stories.test.ts
Labels: Type: Fixed, Impacts: Documentation

#3033 [WNMGDS-2745] Fix dialogs inheriting font size from ancestors
  packages/design-system/src/styles/components/_Dialog.scss
  packages/design-system/src/styles/components/_Drawer.scss
Labels: Type: Fixed, Impacts: Core

#3034 [WNMGDS-2727] Add `ds-label` component
  packages/design-system/src/components/web-components/ds-label/__snapshots__/ds-label.test.tsx.snap
  packages/design-system/src/components/web-components/ds-label/ds-label.stories.tsx
  packages/design-system/src/components/web-components/ds-label/ds-label.test.tsx
  packages/design-system/src/components/web-components/ds-label/ds-label.tsx
  packages/design-system/src/components/web-components/ds-label/index.ts
  tests/browser/snapshots/stories/web-components-label--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-label--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-label--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-label--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-label--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-label--default-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-label--default-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-label--default-core--chromium.png
  tests/browser/snapshots/stories/web-components-label--default-core--firefox.png
  tests/browser/snapshots/stories/web-components-label--default-core--webkit.png
  tests/browser/snapshots/stories/web-components-label--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-label--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-label--default-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-label--default-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-label--default-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-label--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-label--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-label--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-label--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-label--default-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-Label-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3037 [NO-TICKET] Add warning in docs to skip v7
  packages/docs/content/blog/release-7.0.mdx
Labels: Impacts: Documentation, Type: Changed

#3038 [NO-TICKET] Add more documentation about our web components
  packages/docs/content/components/alert.mdx
  packages/docs/content/components/badge.mdx
  packages/docs/content/components/button.mdx
  packages/docs/content/components/dropdown.mdx
  packages/docs/content/components/overview.mdx
  packages/docs/content/components/usa-banner.mdx
Labels: Impacts: Documentation, Type: Added

#3043 [NO-TICKET]
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.test.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.tsx
Labels: Type: Fixed, Impacts: Core

#3044 [NO-TICKET] Add missing `inversed` attribute to `ds-dropdown`
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.stories.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.test.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.tsx
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-Dropdown-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Fixed, Impacts: Core

#3030 [WNMGDS-2740] Add local focus styles to USA banner
  packages/design-system/src/styles/_mixins.scss
  packages/design-system/src/styles/components/_UsaBanner.scss
Labels: Type: Fixed, Impacts: Core

#3008 [WNMGDS-2697] Update label guidance
  packages/docs/content/components/label.mdx
  packages/docs/content/patterns/Forms/forms.mdx
Labels: Impacts: Documentation, Type: Changed

#3039 [WNMGDS-2727] Link to Storybook in label, hint, and inline-error docs
  packages/docs/content/components/hint.mdx
  packages/docs/content/components/inline-error.mdx
  packages/docs/content/components/label.mdx
Labels: Impacts: Documentation, Type: Added

#3048 [WNMGDS-2759] Refactor local preactement code
  packages/design-system/src/components/web-components/preactement/define.ts
  packages/design-system/src/components/web-components/preactement/shared/element.ts
  packages/design-system/src/components/web-components/preactement/shared/model.ts
Labels: Type: Internal, Impacts: Core

#3050 [WNMGDS-2742] Create spinner web component.
  examples/astro/src/pages/web-components.astro
  packages/design-system/src/components/web-components/ds-spinner/__snapshots__/ds-spinner.test.tsx.snap
  packages/design-system/src/components/web-components/ds-spinner/ds-spinner.stories.tsx
  packages/design-system/src/components/web-components/ds-spinner/ds-spinner.test.tsx
  packages/design-system/src/components/web-components/ds-spinner/ds-spinner.tsx
  packages/design-system/src/components/web-components/ds-spinner/index.ts
  packages/design-system/src/components/web-components/index.ts
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--chromium.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--firefox.png
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--webkit.png
  tests/browser/snapshots/stories/web-components-spinner--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-spinner--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-spinner--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-spinner--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-spinner--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-spinner--default-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-spinner--default-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-spinner--default-core--chromium.png
  tests/browser/snapshots/stories/web-components-spinner--default-core--firefox.png
  tests/browser/snapshots/stories/web-components-spinner--default-core--webkit.png
  tests/browser/snapshots/stories/web-components-spinner--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-spinner--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-spinner--default-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-spinner--default-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-spinner--default-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-spinner--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-spinner--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-spinner--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-spinner--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-spinner--default-medicare--webkit.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-core--chromium.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-core--firefox.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-core--webkit.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-spinner--inverse-filled-spinner-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-Spinner-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3053 [WNMGDS-2759] Fix nesting web components in other web components and re-renders
  examples/astro/src/pages/web-components.astro
  packages/design-system/src/components/web-components/ds-alert/__snapshots__/ds-alert.test.tsx.snap
  packages/design-system/src/components/web-components/ds-badge/__snapshots__/ds-badge.test.tsx.snap
  packages/design-system/src/components/web-components/ds-button/__snapshots__/ds-button.test.tsx.snap
  packages/design-system/src/components/web-components/ds-choice/__snapshots__/ds-choice.test.tsx.snap
  packages/design-system/src/components/web-components/ds-choice/ds-choice.stories.tsx
  packages/design-system/src/components/web-components/ds-dropdown/__snapshots__/ds-dropdown.test.tsx.snap
  packages/design-system/src/components/web-components/ds-hint/__snapshots__/ds-hint.test.tsx.snap
  packages/design-system/src/components/web-components/ds-inline-error/__snapshots__/ds-inline-error.test.tsx.snap
  packages/design-system/src/components/web-components/ds-label/__snapshots__/ds-label.test.tsx.snap
  packages/design-system/src/components/web-components/ds-usa-banner/__snapshots__/ds-usa-banner.test.tsx.snap
  packages/design-system/src/components/web-components/preactement/define.test.tsx
  packages/design-system/src/components/web-components/preactement/define.ts
  packages/design-system/src/components/web-components/preactement/parse.test.ts
  packages/design-system/src/components/web-components/preactement/parse.ts
  packages/design-system/src/components/web-components/preactement/shared/model.ts
  packages/design-system/src/components/web-components/preactement/shared/parse.ts
  tests/browser/snapshots/stories/web-components-choice--checked-children-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-core--chromium.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-core--firefox.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-core--webkit.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-choice--checked-children-medicare--webkit.png
Labels: Type: Fixed, Impacts: Core

#3054 [WNMGDS-2714] Remove `ga_` prefixed properties from analytics events
  packages/design-system/src/components/Alert/__snapshots__/Alert.test.tsx.snap
  packages/design-system/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/design-system/src/components/Dialog/Dialog.test.tsx
  packages/design-system/src/components/HelpDrawer/__snapshots__/HelpDrawer.test.tsx.snap
  packages/design-system/src/components/analytics/events.test.ts
  packages/design-system/src/components/analytics/events.ts
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/ActionMenu.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/analytics.test.js.snap
Labels: Impacts: Core, Type: Changed

#3056 [WNMGDS-2743] Skip nav web component
  examples/astro/src/pages/web-components.astro
  packages/design-system/dist.zip
  packages/design-system/src/components/web-components/ds-skip-nav/ds-skip-nav.stories.tsx
  packages/design-system/src/components/web-components/ds-skip-nav/ds-skip-nav.test.tsx
  packages/design-system/src/components/web-components/ds-skip-nav/ds-skip-nav.ts
  packages/design-system/src/components/web-components/ds-skip-nav/index.ts
  packages/design-system/src/components/web-components/index.ts
  packages/design-system/src/components/web-components/preactement/define.ts
  tests/browser/snapshots/stories/web-components-skipnav--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-skipnav--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-skipnav--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-skipnav--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-skipnav--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-skipnav--default-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-skipnav--default-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-skipnav--default-core--chromium.png
  tests/browser/snapshots/stories/web-components-skipnav--default-core--firefox.png
  tests/browser/snapshots/stories/web-components-skipnav--default-core--webkit.png
  tests/browser/snapshots/stories/web-components-skipnav--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-skipnav--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-skipnav--default-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-skipnav--default-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-skipnav--default-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-skipnav--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-skipnav--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-skipnav--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-skipnav--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-skipnav--default-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-SkipNav-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3055 [WNMGDS-2714] Fix `Dialog` and `HelpDrawer` analytics firing too early
  packages/design-system/src/components/Dialog/Dialog.stories.tsx
  packages/design-system/src/components/Dialog/Dialog.test.tsx
  packages/design-system/src/components/Dialog/useDialogAnalytics.ts
  packages/design-system/src/components/HelpDrawer/HelpDrawer.stories.tsx
  packages/design-system/src/components/HelpDrawer/HelpDrawer.test.tsx
  packages/design-system/src/components/HelpDrawer/__snapshots__/HelpDrawer.test.tsx.snap
  packages/design-system/src/components/HelpDrawer/useHelpDrawerAnalytics.ts
  packages/design-system/src/components/NativeDialog/useNativeDialogAnalytics.test.tsx
  packages/design-system/src/components/NativeDialog/useNativeDialogAnalytics.ts
Labels: Type: Fixed, Impacts: Core

#3058 [WNMGDS-2714] Remove more GA properties from analytics events
  packages/design-system/src/components/Alert/__snapshots__/Alert.test.tsx.snap
  packages/design-system/src/components/Alert/useAlertAnalytics.ts
  packages/design-system/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/design-system/src/components/Button/useButtonAnalytics.ts
  packages/design-system/src/components/Dialog/Dialog.test.tsx
  packages/design-system/src/components/Dialog/useDialogAnalytics.ts
  packages/design-system/src/components/HelpDrawer/__snapshots__/HelpDrawer.test.tsx.snap
  packages/design-system/src/components/HelpDrawer/useHelpDrawerAnalytics.ts
  packages/design-system/src/components/analytics/events.test.ts
  packages/design-system/src/components/analytics/events.ts
  packages/design-system/src/components/analytics/types.ts
  packages/design-system/src/components/analytics/useAnalyticsContent.ts
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/ActionMenu.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Header/__snapshots__/analytics.test.js.snap
  packages/ds-healthcare-gov/src/components/Header/analytics.ts
  tests/browser/snapshots/storybook-docs/Docs-Components-Button-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Dialog-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Medicare-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-components-Alert-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Changed

#3059 [WNMGDS-2725] Add optional analytics tracking to `ThirdPartyExternalLink`
  .storybook/preview.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.test.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/__snapshots__/ThirdPartyExternalLink.test.tsx.snap
  packages/design-system/src/components/ThirdPartyExternalLink/useThirdPartyExternalLinkAnalytics.ts
  packages/design-system/src/components/analytics/events.ts
  packages/design-system/src/components/config.ts
  tests/browser/snapshots/storybook-docs/Docs-Components-ThirdPartyExternalLink-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3063 [WNMGDS-2715] Add analytics to healthcare footer links
  .storybook/preview.tsx
  packages/design-system/src/components/config.ts
  packages/ds-healthcare-gov/src/components/Footer/Footer.test.tsx
  packages/ds-healthcare-gov/src/components/Footer/Footer.tsx
  packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.test.tsx
  packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.tsx
  packages/ds-healthcare-gov/src/components/Footer/Logo.tsx
  packages/ds-healthcare-gov/src/components/Footer/LogosRow.test.tsx
  packages/ds-healthcare-gov/src/components/Footer/LogosRow.tsx
  packages/ds-healthcare-gov/src/components/Footer/PrivacySettingsLink.tsx
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/InlineLinkLists.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/__snapshots__/LogosRow.test.tsx.snap
  packages/ds-healthcare-gov/src/components/Footer/analytics.ts
Labels: Impacts: Healthcare, Type: Added
