Repository CMSgov/design-system, pull requests merged in 2025-05, with the labels that each got.

#3550 [WNMGDS-3290] Remove `react-helmet`
  package-lock.json
  packages/docs/gatsby-config.mjs
  packages/docs/package.json
  packages/docs/src/components/layout/DocSiteSeo.tsx
  packages/docs/src/components/layout/Layout.tsx
  packages/docs/src/components/page-templates/BlogPage.tsx
  packages/docs/src/components/page-templates/InfoPage.tsx
  packages/docs/src/pages/404.tsx
  packages/docs/src/pages/blog.tsx
  packages/docs/src/pages/contact.tsx
  packages/docs/src/pages/index.tsx
  packages/docs/src/pages/search.tsx
Labels: Impacts: Documentation, Type: Changed

#3552 [WNMGDS-3304] Removes default props from components
  packages/design-system/src/components/Alert/Alert.tsx
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/Button/Button.tsx
  packages/design-system/src/components/ChoiceList/Choice.tsx
  packages/design-system/src/components/Drawer/Drawer.tsx
  packages/design-system/src/components/Dropdown/Dropdown.test.tsx
  packages/design-system/src/components/Icons/SvgIcon.tsx
  packages/design-system/src/components/Label/Label.tsx
  packages/design-system/src/components/Pagination/Pagination.tsx
  packages/design-system/src/components/Review/Review.tsx
  packages/design-system/src/components/Spinner/Spinner.tsx
  packages/design-system/src/components/Table/Table.tsx
  packages/design-system/src/components/Table/TableCell.tsx
  packages/design-system/src/components/Tabs/TabPanel.tsx
  packages/design-system/src/components/TextField/TextField.tsx
  packages/design-system/src/components/Tooltip/Tooltip.tsx
  packages/design-system/src/components/VerticalNav/VerticalNav.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItem.tsx
  packages/design-system/src/components/web-components/ds-tooltip/ds-tooltip.tsx
  packages/docs/src/components/layout/FilterDialog/FilterDialog.tsx
  packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.tsx
  packages/ds-healthcare-gov/src/components/Header/Header.tsx
  packages/ds-healthcare-gov/src/components/Logo/LogoEnSvg.tsx
  packages/ds-healthcare-gov/src/components/Logo/LogoEsSvg.tsx
  tests/browser/snapshots/storybook-docs/Docs-Components-Autocomplete-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Button-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Icons-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Label-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Pagination-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Review-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Spinner-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Table-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-TextField-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Tooltip-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-VerticalNav-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Healthcare-Header-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Medicare-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-components-Alert-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Changed

#3561 [WNMGDS-3353] Remove two broken links on checkbox page
  packages/docs/content/components/checkbox.mdx
Labels: Type: Fixed, Impacts: Documentation

#3566 [WNMGDS-3350] Remove form components table
  packages/docs/content/components/checkbox.mdx
  packages/docs/content/components/date-field/date-picker.mdx
  packages/docs/content/components/date-field/multi-input-date-field.mdx
  packages/docs/content/components/date-field/single-input-date-field.mdx
  packages/docs/content/components/hint.mdx
  packages/docs/content/components/inline-error.mdx
  packages/docs/content/components/label.mdx
  packages/docs/content/components/month-picker.mdx
  packages/docs/content/components/radio.mdx
  packages/docs/content/components/text-field/masked-field.mdx
  packages/docs/content/components/text-field/text-field.mdx
  packages/docs/src/components/content/ComponentThemeOptions.tsx
  packages/docs/src/helpers/urlUtils.ts
Labels: Type: Fixed, Impacts: Documentation

#3571 [WNMGDS-3189] Fix `ds-autocomplete` storybook controls
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.stories.tsx
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.tsx
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-autocomplete-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Fixed, Impacts: Core

#3565 [WNMGDS-3357] Removed default props from child DS components
  packages/design-system/src/components/Accordion/AccordionItem.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
  packages/ds-healthcare-gov/src/components/Accordion/AccordionItem.tsx
  packages/ds-healthcare-gov/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.test.tsx
  packages/ds-healthcare-gov/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
  packages/ds-healthcare-gov/src/components/ThirdPartyExternalLink/__snapshots__/ThirdPartyExternalLink.test.tsx.snap
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.jsx
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.stories.tsx
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.tsx
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawerToggle.jsx
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawerToggle.tsx
  packages/ds-medicare-gov/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.test.tsx
  packages/ds-medicare-gov/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
  packages/ds-medicare-gov/src/components/ThirdPartyExternalLink/__snapshots__/ThirdPartyExternalLink.test.tsx.snap
Labels: Impacts: Healthcare, Impacts: Medicare, Type: Changed

#3573 [NO-TICKET] Update check for production to work on the server or client
  packages/docs/src/helpers/urlUtils.ts
Labels: Type: Fixed, Impacts: Documentation

#3572 [WNMGDS-3354] A11y guidance for radio and checkbox components
  packages/docs/content/components/checkbox.mdx
  packages/docs/content/components/radio.mdx
Labels: Impacts: Documentation, Type: Added

#3574 [WNMGDS-3369] Adds an alert icon without circle
  packages/design-system/src/components/Icons/AlertIcon.tsx
  packages/design-system/src/components/Icons/icons.stories.tsx
  packages/design-system/src/components/Icons/index.ts
Labels: Impacts: Core, Type: Added

#3587 [NO-TICKET] Fix bad check for window
  packages/docs/src/components/content/ComponentThemeOptions.tsx
  packages/docs/src/helpers/urlUtils.ts
Labels: Type: Fixed, Impacts: Documentation

#3589 [WNMGDS-3352] added a11y guidance idle timeout
  packages/docs/content/components/idle-timeout.mdx
Labels: Impacts: Documentation, Type: Added

#3562 [WNMGDS-3355] Fixed broken link on dropdown page
  packages/docs/content/components/dropdown.mdx
Labels: Type: Fixed, Impacts: Documentation

#3559 [WNMGDS-3344] Add Utag data object
  packages/docs/gatsby-ssr.tsx
  packages/docs/src/components/layout/Layout.tsx
  packages/docs/src/pages/404.tsx
Labels: Impacts: Documentation, Type: Added

#3556 [WNMGDS-3351] - add a11y guidance to all logos on docsite
  packages/docs/content/components/logos/healthcare-logo.mdx
  packages/docs/content/components/logos/hhs-logo.mdx
  packages/docs/content/components/logos/medicare-logo.mdx
Labels: Impacts: Documentation, Status: In JIRA, Type: Changed

#3579 [WNMGDS-3287] Added a "Color Contrast Guidance" component
  packages/docs/content/foundation/system-color-tokens.mdx
  packages/docs/content/foundation/theme-colors.mdx
  packages/docs/content/utilities/background-color.mdx
  packages/docs/content/utilities/text/text-color.mdx
  packages/docs/src/components/content/ColorContrastGuidelines.tsx
  packages/docs/src/components/content/ContentRenderer.tsx
  packages/docs/src/components/page-templates/BlogPage.tsx
  packages/docs/src/components/page-templates/InfoPage.tsx
  packages/docs/src/pages/404.tsx
  packages/docs/src/pages/contact.tsx
  packages/docs/src/pages/index.tsx
Labels: Impacts: Documentation, Type: Added

#3591 [NO-TICKET] Remove useRef and useEffect from Layout.tsx to correct analytics functioning
  packages/docs/src/components/layout/Layout.tsx
Labels: Type: Fixed, Impacts: Documentation

#3580 [WNMGDS-3309] Make stylesheet polling stop after 30 seconds
  packages/design-system/src/components/web-components/preactement/globalStyles.ts
Labels: Impacts: Core, Type: Changed

#3593 [NO-TICKET] Add in UTAG page view analytics
  packages/docs/src/components/layout/Layout.tsx
Labels: Type: Fixed, Impacts: Documentation

#3594 [WNMGDS-3375] Replicated autocomplete keyboard interaction bug
  packages/design-system/src/components/Autocomplete/Autocomplete.test.interaction.ts
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--cmsgov--chromium.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--cmsgov--firefox.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--cmsgov--webkit.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--core--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--core--chromium.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--core--firefox.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--core--webkit.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--healthcare--chromium.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--healthcare--firefox.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--healthcare--webkit.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--medicare--chromium.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--medicare--firefox.png
  tests/browser/snapshots/stories-interaction/autocomplete--keyboard--medicare--webkit.png
Labels: Type: Internal, Impacts: Core

#3596 [WNMGDS-3376] Updated `@react-stately` dependency
  package-lock.json
  packages/design-system/package.json
Labels: Type: Internal, dependencies

#3597 [WNMGDS-3360] Add `StatusIndicator` component to docs.
  packages/docs/src/components/layout/StatusIndicator.tsx
  packages/docs/src/helpers/graphQLTypes.ts
Labels: Impacts: Documentation, Type: Added

#3499 [WNMGDS-3052] Added pattern guidance for html tables.
  packages/docs/content/patterns/html-table.mdx
Labels: Impacts: Documentation, Type: Added

#3603 [WNMGDS-3368] Clarify storybook documentation around attributes that accept stringified JSON
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.stories.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice-list.stories.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.stories.tsx
  packages/design-system/src/components/web-components/ds-step-list/ds-step-list.stories.tsx
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-autocomplete-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-choice-list-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-dropdown-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-step-list-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Documentation, Type: Changed

#3617 [WNMGDS-2688] Update Astro Config so Tooltips render properly
  examples/astro-react-17/src/pages/index.astro
  examples/astro-react-18/astro.config.mjs
  examples/astro-react-18/src/pages/index.astro
Labels: Type: Fixed, Impacts: Core

#3619 [NO-TICKET] Update deps list so build works
  examples/astro-react-17/astro.config.mjs
  examples/astro-react-18/astro.config.mjs
  tests/browser/snapshots/examples/astro-react-17/astro-react-17--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-react-17/astro-react-17--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-react-17/astro-react-17--chromium.png
  tests/browser/snapshots/examples/astro-react-17/astro-react-17--firefox.png
  tests/browser/snapshots/examples/astro-react-17/astro-react-17--webkit.png
  tests/browser/snapshots/examples/astro-react-18/astro-react-18--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-react-18/astro-react-18--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-react-18/astro-react-18--chromium.png
  tests/browser/snapshots/examples/astro-react-18/astro-react-18--firefox.png
  tests/browser/snapshots/examples/astro-react-18/astro-react-18--webkit.png
Labels: Type: Fixed, Impacts: Core
