Repository CMSgov/design-system, pull requests merged in 2025-10, with the labels that each got.

#3781 [CMSDS-3467] Pass null into useRef initializers to align with react 19 types
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/Button/useButtonAnalytics.ts
  packages/design-system/src/components/ChoiceList/ChoiceList.tsx
  packages/design-system/src/components/DateField/SingleInputDateField.tsx
  packages/design-system/src/components/Dialog/Dialog.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/Dropdown/DropdownMenu.tsx
  packages/design-system/src/components/NativeDialog/useNativeDialogAnalytics.ts
  packages/design-system/src/components/Table/Table.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/useThirdPartyExternalLinkAnalytics.ts
  packages/design-system/src/components/Tooltip/useTooltipAnalytics.ts
  packages/design-system/src/components/analytics/useAnalyticsContent.ts
  packages/design-system/src/components/utilities/useAutoFocus.ts
  packages/design-system/src/components/utilities/usePrevious.ts
  packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.tsx
Labels: Impacts: Core, Type: Changed

#3782 [CMSDS-3467] Migrate `JSX.IntrinsicElements` to `React.JSX.IntrinsicElements` and add custom element support
  packages/design-system/src/components/Review/Review.tsx
  packages/design-system/src/components/utilities/findElementsOfType.ts
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice-list.tsx
  packages/design-system/src/components/web-components/ds-date-field/ds-date-field.tsx
  packages/design-system/src/components/web-components/ds-drawer/ds-drawer.tsx
  packages/design-system/src/components/web-components/ds-review/ds-review.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tabs.tsx
  packages/design-system/src/components/web-components/ds-third-party-external-link/ds-third-party-external-link.tsx
  packages/ds-medicare-gov/src/components/web-components/ds-simple-footer/ds-simple-footer.tsx
Labels: Impacts: CMSgov, Type: Changed

#3783 [CMSDS-3467] Coerce field values to string and add `coerceToString` utility
  packages/design-system/src/components/TextField/LabelMask.tsx
  packages/design-system/src/components/TextField/Mask.tsx
  packages/design-system/src/components/TextField/maskHelpers.test.ts
  packages/design-system/src/components/TextField/maskHelpers.ts
Labels: Impacts: Core, Type: Changed

#3784 [CMSDS-3467] Resolve remaining React 19 semantic errors in Table, IdleTimeout, Autocomplete, Tabs, and useDialog
  packages/design-system/src/components/Autocomplete/utils.tsx
  packages/design-system/src/components/Dialog/useDialog.ts
  packages/design-system/src/components/IdleTimeout/IdleTimeout.tsx
  packages/design-system/src/components/Table/TableHead.tsx
  packages/design-system/src/components/Table/TableRow.tsx
  packages/design-system/src/components/Tabs/Tabs.tsx
Labels: Impacts: Core, Type: Changed

#3780 [CMSDS-3444] Remove aria-invalid attribute if ChoiceList is a checkbox group.
  packages/design-system/src/components/ChoiceList/ChoiceList.test.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.tsx
  packages/design-system/src/components/InlineError/useInlineError.tsx
  packages/design-system/src/components/web-components/ds-choice/__snapshots__/ds-choice-list.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#3795 [CMSDS-3575] Add a11y guidance for the Calendar Picker component
  packages/docs/content/components/date-field/date-picker.mdx
Labels: Impacts: Documentation, Type: Changed

#3785 [CMDS-3467] Bump `@types/react` packages
  package-lock.json
  package.json
  packages/design-system/package.json
  packages/docs/package.json
  packages/ds-cms-gov/package.json
  packages/ds-healthcare-gov/package.json
  packages/ds-medicare-gov/package.json
Labels: Type: Internal, Impacts: Core

#3801 [NO-TICKET] Ensure `Card` is exported from Core
  examples/_shared/react/CardComponentExample.tsx
  examples/astro-react-18/src/pages/index.astro
  packages/design-system/src/components/Card/index.ts
  packages/design-system/src/components/index.ts
  packages/ds-medicare-gov/src/components/index.ts
Labels: Impacts: Core, Type: Changed

#3804 [NO-TICKET] Adds necessary snapshot updates for `astro-react-18` example application.
  tests/browser/snapshots/examples/astro-react-18/astro-react-18--Mobile-Chrome.png
  tests/browser/snapshots/examples/astro-react-18/astro-react-18--chromium-forced-colors.png
  tests/browser/snapshots/examples/astro-react-18/astro-react-18--chromium.png
  tests/browser/snapshots/examples/astro-react-18/astro-react-18--firefox.png
  tests/browser/snapshots/examples/astro-react-18/astro-react-18--webkit.png
Labels: Type: Internal, Impacts: Core

#3802 [CMSDS-3600] Remove Mgov `Card` component
  packages/ds-medicare-gov/src/components/Card/Card.spec.tsx
  packages/ds-medicare-gov/src/components/Card/Card.stories.tsx
  packages/ds-medicare-gov/src/components/Card/Card.tsx
  packages/ds-medicare-gov/src/components/Card/index.ts
  packages/ds-medicare-gov/src/components/index.ts
  tests/browser/snapshots/stories/medicare-card--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/medicare-card--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/medicare-card--default-medicare--chromium.png
  tests/browser/snapshots/stories/medicare-card--default-medicare--firefox.png
  tests/browser/snapshots/stories/medicare-card--default-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Medicare-Card-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Medicare, Type: Changed
