Repository CMSgov/design-system, pull requests merged in 2025-08, with the labels that each got.

#3672 [CMSDS-3409] Renamed components that have theme-specific overrides
  packages/design-system/scripts/cmsds-migrate/configs/[v15-medicare]-renamed-components.mjs
  packages/design-system/scripts/cmsds-migrate/configs/[v17-healthcare]-renamed-components.mjs
  packages/docs/content/blog/release-13.0.mdx
  packages/ds-healthcare-gov/src/components/Accordion/index.tsx
  packages/ds-healthcare-gov/src/components/HealthcaregovAccordion/HealthcaregovAccordion.stories.tsx
  packages/ds-healthcare-gov/src/components/HealthcaregovAccordion/HealthcaregovAccordionItem.tsx
  packages/ds-healthcare-gov/src/components/HealthcaregovAccordion/index.tsx
  packages/ds-healthcare-gov/src/components/HealthcaregovThirdPartyExternalLink/HealthcaregovThirdPartyExternalLink.test.tsx
  packages/ds-healthcare-gov/src/components/HealthcaregovThirdPartyExternalLink/HealthcaregovThirdPartyExternalLink.tsx
  packages/ds-healthcare-gov/src/components/HealthcaregovThirdPartyExternalLink/__snapshots__/HealthcaregovThirdPartyExternalLink.test.tsx.snap
  packages/ds-healthcare-gov/src/components/HealthcaregovThirdPartyExternalLink/index.ts
  packages/ds-healthcare-gov/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
  packages/ds-healthcare-gov/src/components/ThirdPartyExternalLink/index.ts
  packages/ds-healthcare-gov/src/components/index.ts
  packages/ds-medicare-gov/package.json
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.tsx
  packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawerToggle.tsx
  packages/ds-medicare-gov/src/components/HelpDrawer/index.ts
  packages/ds-medicare-gov/src/components/MedicaregovHelpDrawer/MedicaregovHelpDrawer.stories.tsx
  packages/ds-medicare-gov/src/components/MedicaregovHelpDrawer/MedicaregovHelpDrawer.tsx
  packages/ds-medicare-gov/src/components/MedicaregovHelpDrawer/MedicaregovHelpDrawerToggle.tsx
  packages/ds-medicare-gov/src/components/MedicaregovHelpDrawer/index.ts
  packages/ds-medicare-gov/src/components/MedicaregovThirdPartyExternalLink/MedicaregovThirdPartyExternalLink.test.tsx
  packages/ds-medicare-gov/src/components/MedicaregovThirdPartyExternalLink/MedicaregovThirdPartyExternalLink.tsx
  packages/ds-medicare-gov/src/components/MedicaregovThirdPartyExternalLink/__snapshots__/MedicaregovThirdPartyExternalLink.test.tsx.snap
  packages/ds-medicare-gov/src/components/MedicaregovThirdPartyExternalLink/index.ts
  packages/ds-medicare-gov/src/components/ThirdPartyExternalLink/index.ts
  packages/ds-medicare-gov/src/components/index.ts
  tests/browser/snapshots/stories-interaction/button--focus--medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Components-BoxQuotation-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Medicare-Dialog-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Medicare-MedicaregovHelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-tab-panel-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-components-BoxContent-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Breaking, Impacts: Healthcare, Impacts: Medicare

#3680 [CMSDS-3495] Added a11y testing guidance to badge.mdx
  packages/docs/content/components/badge.mdx
Labels: Type: Fixed, Impacts: Documentation

#3684 [CMSDS-3497] Added a11y guidance to multi-input date field.mdx
  packages/docs/content/components/date-field/multi-input-date-field.mdx
Labels: Impacts: Documentation, Type: Added

#3707 [CMSDS-3489] Refocus `Autocomplete` input after clearing search.
  packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.test.tsx
Labels: Impacts: Core, Type: Changed
