Repository CMSgov/design-system, pull requests merged in 2025-04, with the labels that each got.

#3501 [NO-TICKET] Deleting old bug report
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Type: Internal, Impacts: Documentation

#3504 [NO-TICKET] Updates versions json
  versions.json
Labels: Type: Fixed, Impacts: Core

#3494 [WNMGDS-3218] NoteBox guidance
  packages/design-system/src/components/NoteBox/NoteBox.test.tsx
  packages/design-system/src/components/NoteBox/NoteBoxQuotation.stories.tsx
  packages/design-system/src/components/NoteBox/NoteBoxQuotation.tsx
  packages/design-system/src/components/NoteBox/__snapshots__/NoteBox.test.tsx.snap
  packages/design-system/src/components/NoteBox/index.ts
  packages/docs/content/components/note-box.mdx
  packages/docs/src/styles/pages/layout.scss
  tests/browser/snapshots/stories/components-noteboxquotation--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-core--chromium.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-core--firefox.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-core--webkit.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-healthcare--chromium.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-healthcare--firefox.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-healthcare--webkit.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-medicare--chromium.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-medicare--firefox.png
  tests/browser/snapshots/stories/components-noteboxquotation--default-medicare--webkit.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-cmsgov--chromium.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-cmsgov--firefox.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-core--chromium.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-core--firefox.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-core--webkit.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-healthcare--chromium.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-healthcare--firefox.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-healthcare--webkit.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-medicare--chromium.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-medicare--firefox.png
  tests/browser/snapshots/stories/components-noteboxquotation--with-author-medicare--webkit.png
Labels: Impacts: Documentation, Type: Added

#3505 [NO-TICKET] Bug Report: Labels not repeated anymore
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Type: Internal, Impacts: Core

#3516 [WNMGDS-3315] Fixed `aria-invalid` property previously assigned to Dropdown Button
  packages/design-system/src/components/Dropdown/Dropdown.test.tsx
  packages/design-system/src/components/Dropdown/Dropdown.tsx
  packages/design-system/src/components/Dropdown/DropdownMenu.tsx
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/design-system/src/components/web-components/ds-dropdown/__snapshots__/ds-dropdown.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#3515 [WNMGDS-3272] Fixes broken example projects
  examples/astro-react-17/astro.config.mjs
  examples/astro-react-17/package.json
  examples/astro-react-18/package.json
  examples/astro-themes/package.json
  examples/astro/package.json
  examples/react-app/package.json
  examples/react-app/src/scripts/index.js
  package-lock.json
  package.json
Labels: Type: Fixed, dependencies

#3528 [WNMGDS-3210] Update vertical spacing guidance
  packages/docs/content/foundation/spacing.mdx
  packages/docs/src/components/content/ContentRenderer.tsx
  packages/docs/src/components/content/ThemeLabel.tsx
Labels: Impacts: Documentation, Type: Added

#3543 [wnmgds 3339] Fix `onChange` not firing for grouped items in `Autocomplete`
  packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
  packages/design-system/src/components/Autocomplete/Autocomplete.tsx
  packages/design-system/src/components/Autocomplete/utils.tsx
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.test.tsx
Labels: Type: Fixed, Impacts: Core

#3542 [WNMGDS-3336] Update `text-field` guidance
  packages/docs/content/components/text-field/text-field.mdx
Labels: Impacts: Documentation, Type: Added

#3549 [NO-TICKET] Update to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Impacts: Documentation, Type: Changed

#3546 [WNMGDS-3302] Refactor custom Playwright reporter to isolate test results by config group
  tests/browser/custom-reporter.test.ts
  tests/browser/custom-reporter.ts
  tests/browser/examples.config.ts
  tests/browser/interaction.config.ts
  tests/browser/playwright.config.ts
  tests/browser/storybook-docs.config.ts
Labels: Type: Internal, Impacts: Core

#3551 [WNMGDS-3345] Fixed broken links on single-input-field page
  packages/docs/content/components/date-field/date-picker.mdx
  packages/docs/content/components/date-field/multi-input-date-field.mdx
  packages/docs/content/components/date-field/single-input-date-field.mdx
Labels: Type: Fixed, Impacts: Documentation
