Repository CMSgov/design-system, pull requests merged in 2025-02, with the labels that each got.

#3423 [WNMGDS-3171] Adds Typography overview guidance to docs site
  packages/docs/content/foundation/typography/overview.mdx
Labels: Impacts: Documentation, Type: Added

#3358 [WNMGDS-3028] Updated Angular Example
  examples/angular/README.md
  examples/angular/angular.json
  examples/angular/package.json
  examples/angular/src/app/accordionItemWrapper/accordionItem.component.html
  examples/angular/src/app/accordionItemWrapper/accordionItem.component.ts
  examples/angular/src/app/accordionWrapper/accordion.component.html
  examples/angular/src/app/accordionWrapper/accordion.component.ts
  examples/angular/src/app/alertWrapper/alert.component.html
  examples/angular/src/app/alertWrapper/alert.component.ts
  examples/angular/src/app/app.component.html
  examples/angular/src/app/app.component.ts
  examples/angular/src/app/app.config.ts
  examples/angular/src/app/buttonWrapper/button.component.html
  examples/angular/src/app/buttonWrapper/button.component.ts
  examples/angular/src/app/drawerWrapper/drawer.component.html
  examples/angular/src/app/drawerWrapper/drawer.component.ts
  examples/angular/src/app/modalDialogWrapper/dialog.component.html
  examples/angular/src/app/modalDialogWrapper/dialog.component.ts
  examples/angular/src/app/reviewWrapper/review.component.html
  examples/angular/src/app/reviewWrapper/review.component.ts
  examples/angular/src/index.html
  examples/angular/src/main.html
  examples/angular/src/main.ts
  package-lock.json
Labels: Impacts: Documentation, Type: Changed

#3424 [WNMGDS-3205] Adds analytics tracking to theme & version dialogs
  packages/docs/src/components/layout/SideNav/ThemeDialog.tsx
  packages/docs/src/components/layout/SideNav/ThemeVersionSection.tsx
  packages/docs/src/components/layout/SideNav/VersionDialog.tsx
  packages/docs/src/helpers/analytics.ts
Labels: Impacts: Documentation, Type: Added

#3427 [NO-TICKET] Renames font size story
  packages/design-system/src/styles/utilities/font-size.stories.tsx
  tests/browser/snapshots/stories/utilities-font-size--font-size-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-cmsgov--chromium.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-cmsgov--firefox.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-cmsgov--webkit.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-core--chromium.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-core--firefox.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-core--webkit.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-healthcare--chromium.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-healthcare--firefox.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-healthcare--webkit.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-medicare--chromium.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-medicare--firefox.png
  tests/browser/snapshots/stories/utilities-font-size--font-size-medicare--webkit.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-cmsgov--chromium.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-cmsgov--firefox.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-cmsgov--webkit.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-core--chromium.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-core--webkit.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-healthcare--chromium.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-healthcare--webkit.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/utilities-font-size--responsive-medicare--webkit.png
Labels: Type: Fixed, Impacts: Documentation

#3425 [WNMGDS-2965] Fixed web component storybook link in button.md
  packages/docs/content/components/button.mdx
Labels: Type: Fixed, Impacts: Documentation

#3426 [WNMGDS-3167] Updates typography headings guidance
  packages/docs/.eslintrc.js
  packages/docs/content/foundation/typography/headings.mdx
  packages/docs/content/foundation/typography/overview.mdx
  packages/docs/src/components/content/ContentRenderer.tsx
  packages/docs/src/components/content/TypographyUsageTable.tsx
  packages/docs/src/styles/components/typographyUseageTable.scss
  packages/docs/src/styles/index.scss
Labels: Impacts: Documentation, Type: Changed

#3428 [NO-TICKET] Adds error handling for missing alias case in `sync:from-figma` script
  packages/design-system-tokens/src/figma/translateFigmaToTokens.ts
Labels: Type: Fixed, Impacts: Core

#3437 [WNMGDS-3173] Removes a stray Sketch reference on the `MaturityChecklist` component.
  packages/docs/src/components/content/MaturityChecklist/MaturityChecklist.tsx
Labels: Impacts: Documentation, Impacts: Core

#3436 [WNMGDS-3194] Adds new guidance and reordered sections for the drawer/help drawer page
  packages/docs/content/components/drawer.mdx
Labels: Impacts: Documentation, Type: Added

#3435 [WNMGDS-3245] Added accessibility and accessibility testing sections to month-picker
  packages/docs/content/components/month-picker.mdx
Labels: Impacts: Documentation, Type: Added

#3434 [WNMGDS-3247] Added accessibility and accessibility testing sections to tooltip page
  packages/docs/content/components/tooltip.mdx
Labels: Impacts: Documentation, Type: Added

#3431 [WNMGDS-3202] Button engagement analytics events
  packages/docs/.eslintrc.js
  packages/docs/src/components/content/ContentRenderer.tsx
  packages/docs/src/components/content/MaturityChecklist/MaturityChecklist.tsx
  packages/docs/src/components/content/PageFeedback.tsx
  packages/docs/src/components/content/SeeStorybookForGuidance.tsx
  packages/docs/src/components/content/StorybookDocLink.tsx
  packages/docs/src/components/content/Video.tsx
  packages/docs/src/components/layout/PageHeader.tsx
  packages/docs/src/components/layout/SideNav/SideNav.tsx
  packages/docs/src/components/layout/TableOfContents.tsx
  packages/docs/src/helpers/analytics.ts
  packages/docs/src/helpers/linkAnalytics.ts
Labels: Impacts: Documentation, Type: Added

#3438 [WNMGDS-3214] Fire analytics event on 404 page load
  packages/design-system/src/components/analytics/events.ts
  packages/docs/src/helpers/graphQLTypes.ts
  packages/docs/src/pages/404.tsx
Labels: Impacts: Documentation, Type: Added

#3451 [WNMGDS-3215] Allow for date entry format to switch between MM/DD and DD/MM per page language
  packages/design-system/src/components/DateField/DateInput.test.tsx
  packages/design-system/src/components/DateField/DateInput.tsx
  packages/design-system/src/components/DateField/MultiInputDateField.tsx
Labels: Type: Fixed, Impacts: Core

#3452 [WNMGDS-3186] Pulls in an accessibility fix for `react-aria`'s `<HiddenSelect />`
  packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/design-system/src/components/react-aria/index.js
  packages/design-system/src/components/web-components/ds-dropdown/__snapshots__/ds-dropdown.test.tsx.snap
Labels: Type: Fixed, Impacts: Core

#3440 [WNMGDS-3249] NavigationOpened analytics event
  packages/docs/src/helpers/analytics.ts
  packages/docs/src/helpers/navDataFormatUtils.ts
Labels: Impacts: Documentation, Type: Added

#3439 [WNMGDS-3244] Adds accessibility guidance to steplist page
  packages/docs/content/components/step-list.mdx
Labels: Impacts: Documentation, Type: Added

#3456 [WNMGDS-3227] Remove incorrect documentation for Dropdown
  packages/design-system/src/components/Dropdown/Dropdown.test.tsx
  packages/docs/content/components/dropdown.mdx
Labels: Type: Fixed, Impacts: Documentation
