Repository CMSgov/design-system, pull requests merged in 2025-09, with the labels that each got.

#3745 [CMSDS-3492] Adds `ds-third-party-external-link` web component
  examples/angular/src/app/app.component.html
  examples/angular/src/app/app.component.ts
  examples/angular/src/app/thirdPartyExternalLinkWrapper/thirdPartyExternalLink.component.html
  examples/angular/src/app/thirdPartyExternalLinkWrapper/thirdPartyExternalLink.component.ts
  packages/design-system/src/components/web-components/ds-third-party-external-link/__snapshots__/ds-third-party-external-link.test.tsx.snap
  packages/design-system/src/components/web-components/ds-third-party-external-link/ds-third-party-external-link.stories.tsx
  packages/design-system/src/components/web-components/ds-third-party-external-link/ds-third-party-external-link.test.tsx
  packages/design-system/src/components/web-components/ds-third-party-external-link/ds-third-party-external-link.tsx
  packages/design-system/src/components/web-components/ds-third-party-external-link/index.ts
  packages/design-system/src/components/web-components/index.ts
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-cmsgov--chromium.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-cmsgov--firefox.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-cmsgov--webkit.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-core--chromium.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-core--firefox.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-core--webkit.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-healthcare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-healthcare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-healthcare--webkit.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-medicare--chromium.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-medicare--firefox.png
  tests/browser/snapshots/stories/web-components-ds-third-party-external-link--default-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-third-party-external-link-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3763 [CMSDS-3547] Replace requiredLabel with hint on ChoiceList Story
  packages/design-system/src/components/ChoiceList/ChoiceList.stories.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.test.tsx
Labels: Type: Fixed, Impacts: Documentation

#3767 [CMSDS-3605] Update new relic browser app
  package-lock.json
  packages/docs/package.json
Labels: Impacts: Documentation, Type: Changed, dependencies

#3770 [NO-TICKET] Update two snapshots
  tests/browser/snapshots/stories/components-monthpicker--with-error-medicare--firefox.png
  tests/browser/snapshots/stories/foundations-typography-body-text--all-body-text-on-dark-healthcare--firefox.png
Labels: Type: Fixed, Impacts: Core

#3769 [CMSDS-3527] Only render "Learn more" link when learnMoreUrl is defined
  packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.test.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/__snapshots__/ThirdPartyExternalLink.test.tsx.snap
  packages/design-system/src/components/web-components/ds-third-party-external-link/__snapshots__/ds-third-party-external-link.test.tsx.snap
Labels: Type: Fixed, Impacts: Core
