Repository CMSgov/design-system, pull requests merged in 2025-03, with the labels that each got.

#3455 [WNMGDS-3246] Added a11y guidance to third part external link page
  packages/docs/content/components/third-party-external-link.mdx
Labels: Impacts: Documentation, Type: Added

#3458 [WNMGDS-3182] Updates two `@testing-library` dependencies
  package-lock.json
  package.json
  packages/design-system/src/components/Accordion/AccordionItem.test.tsx
  packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
  packages/design-system/src/components/ChoiceList/Choice.test.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.test.tsx
  packages/design-system/src/components/DateField/DateInput.test.tsx
  packages/design-system/src/components/DateField/MultiInputDateField.test.tsx
  packages/design-system/src/components/DateField/SingleInputDateField.test.tsx
  packages/design-system/src/components/Dialog/Dialog.test.tsx
  packages/design-system/src/components/Dialog/useBodyScrollPrevention.test.ts
  packages/design-system/src/components/Dialog/useDialog.test.tsx
  packages/design-system/src/components/Drawer/Drawer.test.tsx
  packages/design-system/src/components/Drawer/DrawerManager.test.tsx
  packages/design-system/src/components/Drawer/DrawerToggle.test.tsx
  packages/design-system/src/components/Dropdown/Dropdown.test.tsx
  packages/design-system/src/components/FilterChip/FilterChip.test.tsx
  packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.test.tsx
  packages/design-system/src/components/IdleTimeout/IdleTimeout.test.tsx
  packages/design-system/src/components/MonthPicker/MonthPicker.test.tsx
  packages/design-system/src/components/NativeDialog/shim.ts
  packages/design-system/src/components/Review/Review.test.tsx
  packages/design-system/src/components/SkipNav/SkipNav.test.tsx
  packages/design-system/src/components/Tabs/Tab.test.tsx
  packages/design-system/src/components/Tabs/Tabs.test.tsx
  packages/design-system/src/components/TextField/LabelMask.test.tsx
  packages/design-system/src/components/TextField/Mask.test.tsx
  packages/design-system/src/components/TextField/TextField.test.tsx
  packages/design-system/src/components/TextField/TextInput.test.tsx
  packages/design-system/src/components/TextField/useLabelMask.test.tsx
  packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.test.tsx
  packages/design-system/src/components/Tooltip/Tooltip.test.tsx
  packages/design-system/src/components/VerticalNav/VerticalNav.test.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItem.test.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItemLabel.test.tsx
  packages/design-system/src/components/utilities/useClickOutsideHandler.test.tsx
  packages/design-system/src/components/utilities/useCssDebugger.test.tsx
  packages/design-system/src/components/web-components/__tests__/rendering.tsx
  packages/design-system/src/components/web-components/ds-accordion/ds-accordion-item.test.tsx
  packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.test.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice-list.test.tsx
  packages/design-system/src/components/web-components/ds-choice/ds-choice.test.tsx
  packages/design-system/src/components/web-components/ds-date-field/ds-date-field.test.tsx
  packages/design-system/src/components/web-components/ds-drawer/ds-drawer.test.tsx
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.test.tsx
  packages/design-system/src/components/web-components/ds-filter-chip/ds-filter-chip.test.tsx
  packages/design-system/src/components/web-components/ds-modal-dialog/ds-modal-dialog.test.tsx
  packages/design-system/src/components/web-components/ds-month-picker/ds-month-picker.test.tsx
  packages/design-system/src/components/web-components/ds-skip-nav/ds-skip-nav.test.tsx
  packages/design-system/src/components/web-components/ds-tabs/ds-tabs.test.tsx
  packages/design-system/src/components/web-components/ds-text-field/ds-text-field.test.tsx
  packages/design-system/src/components/web-components/ds-tooltip/ds-tooltip.test.tsx
  packages/design-system/src/components/web-components/preactement/define.test.tsx
  packages/docs/.eslintrc.js
  packages/ds-healthcare-gov/src/components/Header/Header.test.tsx
  packages/ds-healthcare-gov/src/components/Header/MenuLinks.test.tsx
  packages/ds-medicare-gov/src/components/web-components/ds-simple-footer/ds-simple-footer.test.tsx
  tests/unit/jest.config.js
Labels: Type: Internal, dependencies

#3461 [WNMGDS-3219] Adds a11y testing guidance to USA banner documentation page.
  packages/docs/content/components/usa-banner.mdx
Labels: Impacts: Documentation, Impacts: Core

#3463 [NO-TICKET] Add subcomponents table for web components
  .storybook/docs/WebComponentArgsTable.tsx
  packages/design-system/src/components/web-components/ds-accordion/ds-accordion.stories.tsx
Labels: Impacts: Documentation, Type: Added

#3462 [WNMGDS-3261] Adds accessibility guidance for masked field inputs
  packages/docs/content/components/text-field/masked-field.mdx
Labels: Impacts: Documentation, Type: Added

#3466 [WNMGDS-3138] Make Medicare URLs language-aware in `SimpleFooter`
  packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.spec.tsx
  packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.tsx
Labels: Impacts: Medicare, Type: Added

#3470 [WNMGDS-3278] Add in search results position to search event
  packages/docs/src/pages/search.tsx
Labels: Type: Fixed, Impacts: Documentation

#3471 [WNMGDS-3277] Added in default analytics value for empty string searches
  packages/docs/src/components/content/SearchForm.tsx
Labels: Type: Fixed, Impacts: Documentation

#3469 [WNMGDS-3279] Link URL should point to link destination
  packages/docs/src/helpers/analytics.ts
Labels: Type: Fixed, Impacts: Documentation

#3468 [WNMGDS-3280] Make figma use the external link event
  packages/docs/src/components/content/ContentRenderer.tsx
  packages/docs/src/components/layout/PageHeader.tsx
Labels: Type: Fixed, Impacts: Documentation

#3474 [WNMGDS-3284] Fixes typo in `ds-dropdown` storybook docs
  packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.stories.tsx
Labels: Type: Fixed, Impacts: Documentation

#3477 [WNMGDS-3243] Upgraded Gatsby to v5
  package-lock.json
  package.json
  packages/design-system-tokens/package.json
  packages/docs/.eslintrc.js
  packages/docs/content/blog/release-7.0.mdx
  packages/docs/content/components/card.mdx
  packages/docs/content/components/footer/healthcare-footer.mdx
  packages/docs/content/components/footer/medicare-footer.mdx
  packages/docs/content/components/header/healthcare-header.mdx
  packages/docs/content/components/header/medicare-header.mdx
  packages/docs/content/components/inset.mdx
  packages/docs/content/components/logos/healthcare-logo.mdx
  packages/docs/content/components/logos/medicare-logo.mdx
  packages/docs/content/components/spinner.mdx
  packages/docs/content/components/stars.mdx
  packages/docs/content/components/usa-banner.mdx
  packages/docs/content/foundation/layout-grid/layout-grid.mdx
  packages/docs/content/foundation/system-color-tokens.mdx
  packages/docs/content/foundation/theme-colors.mdx
  packages/docs/content/foundation/typography/body.mdx
  packages/docs/content/layouts/Healthcare/one-col-page-layout.mdx
  packages/docs/content/layouts/overview.mdx
  packages/docs/content/migration-guides/migrating-to-new-buttons.mdx
  packages/docs/content/patterns/utility-actions.mdx
  packages/docs/content/utilities/background-color.mdx
  packages/docs/content/utilities/border/border-radius.mdx
  packages/docs/content/utilities/border/border.mdx
  packages/docs/content/utilities/display.mdx
  packages/docs/content/utilities/flexbox.mdx
  packages/docs/content/utilities/float.mdx
  packages/docs/content/utilities/overflow.mdx
  packages/docs/content/utilities/text/text-color.mdx
  packages/docs/content/utilities/text/word-break.mdx
  packages/docs/content/utilities/vertical-align.mdx
  packages/docs/content/utilities/visibility.mdx
  packages/docs/gatsby-config.mjs
  packages/docs/gatsby-node.js
  packages/docs/gatsby-node.mjs
  packages/docs/package.json
  packages/docs/src/components/content/ContentRenderer.tsx
  packages/docs/src/components/layout/SideNav/SideNav.tsx
  packages/docs/src/components/layout/TableOfContents.tsx
  packages/docs/src/components/page-templates/BlogPage.tsx
  packages/docs/src/components/page-templates/InfoPage.tsx
  packages/docs/src/helpers/avoidRefresh.ts
  packages/docs/src/helpers/graphQLTypes.ts
  packages/docs/src/helpers/useSendViewEvent.ts
  packages/docs/src/pages/404.tsx
  packages/docs/src/pages/blog.tsx
  packages/docs/src/pages/contact.tsx
  packages/docs/src/pages/index.tsx
  packages/docs/src/reusable-text-snippets/ColorContrastGuidelines.mdx
Labels: Type: Internal, Impacts: Documentation

#3301 NO-TICKET: Expose 'informational' as part of the AlertVariation type
  packages/design-system/src/components/Alert/Alert.tsx
Labels: Impacts: Core, Type: Added

#3489 [NO-TICKET] Include changes made to `package-lock.json` in the release script
  package-lock.json
  scripts/release.ts
Labels: Type: Internal, dependencies

#3490 [WNMGDS-2880] Add support for aria-describedby to ThirdPartyExernalLink
  packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
  tests/browser/snapshots/storybook-docs/Docs-Components-ThirdPartyExternalLink-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3491 [WNMGDS-3267] Adds a dedicated `backdropClickExits` story for `Drawer`.
  packages/design-system/src/components/Drawer/Drawer.stories.tsx
  packages/design-system/src/components/Drawer/Drawer.tsx
  tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/stories.test.ts
Labels: Impacts: Documentation, Type: Added

#3492 [WNMGDS-3300] Fixed broken default story for `ds-drawer` in Storybook
  packages/design-system/src/components/web-components/ds-drawer/ds-drawer.stories.tsx
Labels: Type: Fixed, Impacts: Documentation

#3495 [NO-TICKET] Add analytics handler to storybook links
  packages/docs/src/components/layout/PageHeader.tsx
Labels: Type: Fixed, Impacts: Documentation

#3493 [WNMGDS-3271] Added `backdrop-click-exits` attribute to `ds-drawer`
  packages/design-system/src/components/web-components/ds-drawer/ds-drawer.stories.tsx
  packages/design-system/src/components/web-components/ds-drawer/ds-drawer.tsx
  tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/stories.test.ts
Labels: Impacts: Core, Type: Added

#3497 [NO-TICKET] New form for bug reports
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Type: Internal, Impacts: Documentation

#3500 [No Ticket] Update snapshot for firefox
  tests/browser/snapshots/examples/astro-web-components/astro-web-components--firefox.png
Labels: Type: Internal, Impacts: Core
