Repository CMSgov/design-system, pull requests merged in 2025-06, with the labels that each got.

#3626 [WMNGDS-3373] Extend `VerticalNavItem` to conditionally render status icon
  packages/design-system/src/components/VerticalNav/StatusIcon.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItem.test.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItem.tsx
  packages/design-system/src/components/VerticalNav/__snapshots__/VerticalNavItem.test.tsx.snap
Labels: Impacts: Core, Type: Added

#3631 [WNMGDS-3416] Fix broken link to Typography page
  packages/docs/content/foundation/layout-grid/responsive-design.mdx
Labels: Type: Fixed, Impacts: Documentation

#3632 [WNMGDS-3414] Fix Textfield regex patterns
  packages/design-system/src/components/TextField/Mask.test.tsx
  packages/design-system/src/components/TextField/Mask.tsx
Labels: Type: Fixed, Impacts: Core

#3633 [WNMGDS-3412] Add Analytics Support to Tooltip
  .storybook/preview.tsx
  package-lock.json
  packages/design-system/src/components/Tooltip/Tooltip.test.tsx
  packages/design-system/src/components/Tooltip/Tooltip.tsx
  packages/design-system/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  packages/design-system/src/components/Tooltip/useTooltipAnalytics.ts
  packages/design-system/src/components/config.ts
  packages/docs/content/components/analytics.mdx
  tests/browser/snapshots/storybook-docs/Docs-Components-Tooltip-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3646 [NO-TICKET] The viewport does not need to be listed as an addon
  .storybook/main.ts
Labels: Type: Fixed, Impacts: Documentation

#3649 [WNMGDS-3388] Set required fields as required in Storybook
  packages/design-system/src/components/Accordion/AccordionItem.tsx
  packages/design-system/src/components/Alert/Alert.stories.tsx
  packages/design-system/src/components/Badge/Badge.stories.tsx
  packages/design-system/src/components/Button/Button.stories.tsx
  packages/design-system/src/components/ChoiceList/Choice.stories.tsx
  packages/design-system/src/components/ChoiceList/Choice.tsx
  packages/design-system/src/components/ChoiceList/ChoiceList.stories.tsx
  packages/design-system/src/components/Drawer/Drawer.stories.tsx
  packages/design-system/src/components/Dropdown/Dropdown.stories.tsx
  packages/design-system/src/components/HelpDrawer/HelpDrawer.stories.tsx
  packages/design-system/src/components/Label/Label.stories.tsx
  packages/design-system/src/components/Label/Label.tsx
  packages/design-system/src/components/Pagination/Pagination.stories.tsx
  packages/design-system/src/components/Table/TableCaption.tsx
  packages/design-system/src/components/Table/TableCell.tsx
  packages/design-system/src/components/Table/TableRow.tsx
  packages/design-system/src/components/TextField/TextField.stories.tsx
  packages/design-system/src/components/Tooltip/Tooltip.stories.tsx
  packages/design-system/src/components/VerticalNav/VerticalNavItem.tsx
  packages/ds-healthcare-gov/src/components/Header/DeConsumerMessage.tsx
  tests/browser/snapshots/stories-interaction/button--focus--medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Components-Button-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Choice-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-ChoiceList-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Dropdown-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Label-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Pagination-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-TextField-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-Components-Tooltip-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-components-Alert-Docs-prop-table-matches-snapshot-1.txt
  tests/browser/snapshots/storybook-docs/Docs-components-Badge-Docs-prop-table-matches-snapshot-1.txt
Labels: Type: Internal, Impacts: Documentation

#3653 [CMSDS-3466] Upgrade `react-docgen-typescript` to v2.4.0
  package-lock.json
  package.json
Labels: Impacts: Documentation, Type: Changed
