Repository CMSgov/design-system, pull requests merged in 2025-01, with the labels that each got.

#3359 [WNMGDS-3135] Calculates unit test code coverage
  package.json
  tests/unit/combineTestCoverage.ts
  tests/unit/coverageReporter.js
  tests/unit/jest.config.js
  tests/unit/testsReporter.js
  tests/unit/utils.js
  tests/unit/utils.test.ts
Labels: Type: Internal, Impacts: Core

#3365 [WNMGDS-3068] Upgrade Astro from 4.4.8 to 5.1.2
  examples/astro-themes/package.json
  examples/astro/package.json
  examples/cdn-web-components/index.html
  yarn.lock
Labels: Type: Changed, dependencies

#3366 [WNMGDS-2749] Update `Alert` to dynamically assign `role` based on `variation`
  packages/design-system/src/components/Alert/Alert.test.tsx
  packages/design-system/src/components/Alert/Alert.tsx
  packages/design-system/src/components/web-components/ds-alert/ds-alert.test.tsx
  tests/browser/snapshots/storybook-docs/Docs-components-Alert-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added

#3379 [NO-TICKET] Update the description of the design system package dist folder
  packages/design-system/README.md
Labels: Type: Fixed, Impacts: Documentation

#3380 [WNMGDS-3175] Remove outdated `humanize-react` library
  .storybook/docs/HtmlElementArgs.tsx
  .storybook/docs/WebComponentAttrs.tsx
  package.json
  packages/docs/package.json
  packages/docs/src/components/content/StorybookDocLinks.tsx
  packages/docs/src/helpers/humanizeList.tsx
  yarn.lock
Labels: Type: Internal, dependencies

#3369 [WNMGDS-3144] Alert Guidance updates
  packages/docs/content/components/alert.mdx
  packages/docs/src/components/content/SeeStorybookForGuidance.tsx
  packages/docs/static/themes/cmsgov-theme.css
  packages/docs/static/themes/core-theme.css
  packages/docs/static/themes/healthcare-theme.css
  packages/docs/static/themes/medicare-theme.css
  yarn.lock
Labels: Impacts: Documentation, Type: Changed

#3393 [NO-TICKET] Fix `hintClassName` being applied to DOM elements
  packages/design-system/src/components/utilities/cleanFieldProps.ts
Labels: Type: Fixed, Impacts: Core

#3391 [NO-TICKET] Use Shadow DOM in ds-button, ds-hint and ds-inline-error
  examples/_web-components-template.html
  examples/astro-themes/src/components/WebComponentExamples.astro
  examples/astro/src/pages/web-components.astro
  examples/cdn-web-components/index.html
  packages/design-system/src/components/web-components/ds-button/__snapshots__/ds-button.test.tsx.snap
  packages/design-system/src/components/web-components/ds-button/ds-button.stories.tsx
  packages/design-system/src/components/web-components/ds-button/ds-button.test.tsx
  packages/design-system/src/components/web-components/ds-button/ds-button.tsx
  packages/design-system/src/components/web-components/ds-hint/__snapshots__/ds-hint.test.tsx.snap
  packages/design-system/src/components/web-components/ds-hint/ds-hint.test.tsx
  packages/design-system/src/components/web-components/ds-hint/ds-hint.tsx
  packages/design-system/src/components/web-components/ds-inline-error/__snapshots__/ds-inline-error.test.tsx.snap
  packages/design-system/src/components/web-components/ds-inline-error/ds-inline-error.test.tsx
  packages/design-system/src/components/web-components/ds-inline-error/ds-inline-error.tsx
Labels: Impacts: Core, Type: Changed

#3394 [NO-TICKET] Preemptively fix CORS blocking stylesheet access in web component CDN example
  examples/cdn-web-components/index.html
Labels: Type: Fixed, Impacts: Documentation

#3396 [WNMGDS-3164] Add analytics tracking for documentation searches
  packages/docs/src/components/content/SearchForm.tsx
  packages/docs/src/helpers/analytics.ts
  packages/docs/src/pages/search.tsx
Labels: Impacts: Documentation, Type: Added

#3403 [WMNGDS-3172] Removes empty step list data snapshots
  packages/design-system/src/components/StepList/StepList.stories.tsx
  packages/design-system/src/components/StepList/__mocks__/stepListStepData.tsx
  packages/design-system/src/components/web-components/ds-step-list/ds-step-list.stories.tsx
  packages/design-system/src/components/web-components/ds-step-list/ds-step-list.test.tsx
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-cmsgov--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-cmsgov--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-cmsgov--chromium.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-cmsgov--firefox.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-cmsgov--webkit.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-core--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-core--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-core--chromium.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-core--firefox.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-core--webkit.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-healthcare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-healthcare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-healthcare--chromium.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-healthcare--firefox.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-healthcare--webkit.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-medicare--chromium.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-medicare--firefox.png
  tests/browser/snapshots/stories/components-steplist--step-list-step-data-medicare--webkit.png
Labels: Type: Fixed, Impacts: Documentation

#3402 [NO-TICKET] Fix dead links to old developer docs
  examples/cdn-html-css/README.md
  packages/docs/content/getting-started/child-design-systems.mdx
  packages/docs/content/migration-guides/migrating-to-v2.mdx
  packages/docs/content/not-in-sidebar/intro.mdx
  packages/ds-cms-gov/README.md
  packages/ds-healthcare-gov/README.md
  packages/ds-medicare-gov/README.md
Labels: Type: Fixed, Impacts: Documentation

#3395 [WNMGDS-3160] Updates docs site color guidance
  packages/docs/content/foundation/theme-colors.mdx
  packages/docs/src/components/content/ColorTable/ColorCard.tsx
  packages/docs/src/components/content/ColorTable/ColorTable.tsx
  packages/docs/src/components/content/ColorTable/index.ts
  packages/docs/src/components/content/ContentRenderer.tsx
  packages/docs/src/helpers/capitalize.ts
  packages/docs/src/helpers/themeTokens.ts
  packages/docs/src/styles/components/colorCard.scss
  packages/docs/src/styles/index.scss
Labels: Impacts: Documentation, Type: Changed

#3397 [WNMGDS-3175] Migrate yarn to npm
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .yarnrc
  COMPONENT_MATURITY.md
  README.md
  examples/angular/README.md
  examples/astro-themes/README.md
  examples/astro/README.md
  examples/preact-app/README.md
  examples/preact-app/index.html
  examples/preact-react-app/README.md
  examples/preact-react-app/index.html
  examples/react-app/README.md
  examples/react-app/index.html
  gulpfile.js
  package-lock.json
  package.json
  packages/design-system-tokens/README.md
  packages/design-system-tokens/package.json
  packages/design-system-tokens/src/figma/translateFigmaToTokens.ts
  packages/design-system/package.json
  packages/design-system/scripts/cmsds-migrate/README.md
  packages/docs/.eslintrc.js
  packages/docs/@types/@mdx-js/react/index.d.ts
  packages/docs/README.md
  packages/docs/content/blog/release-10.0.mdx
  packages/docs/gatsby-node.js
  packages/docs/package.json
  packages/docs/tsconfig.json
  packages/ds-cms-gov/package.json
  packages/ds-medicare-gov/README.md
  scripts/apply-example-templates.ts
  scripts/browser-tests.ts
  scripts/build-examples.ts
  scripts/deploy-demo.ts
  scripts/release.ts
  scripts/tsconfig.json
  tests/browser/examples.config.ts
  tests/browser/interaction.config.ts
  tests/browser/playwright.config.ts
  tests/browser/storybook-docs.config.ts
  tsconfig.json
  yarn.lock
Labels: Type: Internal, Impacts: Core

#3405 [WNMGDS-3166] Add eMedicare footer web-component
  packages/ds-medicare-gov/src/components/web-components/ds-simple-footer/__snapshots__/ds-simple-footer.test.tsx.snap
  packages/ds-medicare-gov/src/components/web-components/ds-simple-footer/ds-simple-footer.stories.tsx
  packages/ds-medicare-gov/src/components/web-components/ds-simple-footer/ds-simple-footer.test.tsx
  packages/ds-medicare-gov/src/components/web-components/ds-simple-footer/ds-simple-footer.tsx
  packages/ds-medicare-gov/src/components/web-components/ds-simple-footer/index.ts
  packages/ds-medicare-gov/src/components/web-components/index.ts
  tests/browser/snapshots/stories/medicare-web-components-ds-simple-footer--default-medicare--Mobile-Chrome.png
  tests/browser/snapshots/stories/medicare-web-components-ds-simple-footer--default-medicare--chromium-forced-colors.png
  tests/browser/snapshots/stories/medicare-web-components-ds-simple-footer--default-medicare--chromium.png
  tests/browser/snapshots/stories/medicare-web-components-ds-simple-footer--default-medicare--firefox.png
  tests/browser/snapshots/stories/medicare-web-components-ds-simple-footer--default-medicare--webkit.png
  tests/browser/snapshots/storybook-docs/Docs-Medicare-Web-Components-ds-simple-footer-Docs-prop-table-matches-snapshot-1.txt
  tests/unit/jest.config.js
  tsconfig.json
  webpack.config.js
Labels: Impacts: Core, Impacts: Medicare, Type: Added

#3418 [NO-TICKET] Add quote icon for consumption in Box Content component
  packages/design-system/src/components/Icons/QuotationMarkIcon.tsx
  packages/design-system/src/components/Icons/SvgIcon.tsx
  packages/design-system/src/components/Icons/icons.stories.tsx
  packages/design-system/src/components/Icons/index.ts
  tests/browser/snapshots/storybook-docs/Docs-Components-Icons-Docs-prop-table-matches-snapshot-1.txt
Labels: Impacts: Core, Type: Added
